### ISSUE TITLE
Module not found: Package path ./rsc is not exported from package 

### ISSUE THREAD

**Issue by walter-grace** [vercel/ai#1028]
### Description
From examples/next-ai-rsc

When downloading the code from Github repo and running pnpm install + pnpm dev. And run into an module error:
Failed to compile
./components/llm-stocks/stock-purchase.tsx:4:0
Module not found: Package path ./rsc is not exported from package C:\Users\nicoz\Downloads\ai-main\ai-main\node_modules\.pnpm\node_modules\ai (see exports field in C:\Users\nicoz\Downloads\ai-main\ai-main\node_modules\.pnpm\node_modules\ai\package.json)
  2 |
  3 | import { useId, useState } from 'react';
> 4 | import { useActions, useAIState, useUIState } from 'ai/rsc';
  5 | import { formatNumber } from '@/lib/utils';
  6 |
  7 | import type { AI } from '../../app/action';

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/llm-stocks/index.tsx 

![image](https://github.com/vercel/ai/assets/31444892/129e4c91-f95b-4e31-a77b-5af5939d851e)

**Comment by walter-grace** [comment]
added the folder source

**Comment by MaxLeiter** [comment]
Can you share more about your system? Your operating system and node version (`node -v`) would be helpful.

**Comment by oayandosu** [comment]
@MaxLeiter I'm having the same issue. pnpm, node v20.11.1

**Comment by walter-grace** [comment]
Same version for me : v20.11.0

**Comment by MaxLeiter** [comment]
Are you also on windows @oayandosu?

**Comment by oayandosu** [comment]
@MaxLeiter Mac Sonoma. Turborepo as well.

**Comment by oayandosu** [comment]
Had the same issue on Node 18.

**Comment by briann** [comment]
Hitting this issue on linux, yarn, node 21.6.2. Here's the build failure I encounter:
```
Type error: Cannot find module 'ai/rsc' or its corresponding type declarations.

> 1 | import { createAI } from 'ai/rsc';
```

If I run the following from my project root:
```bash
cp node_modules/ai/rsc/dist/rsc-types.d.ts node_modules/ai/rsc/dist/index.d.ts
```

Then the build completes fine. I see that we're specifying `rsc-types.d.ts` as the `types` value in `ai/package.json`'s exports block for `./rsc`, but perhaps some build tooling here doesn't respect this and is looking for `index.d.ts`?

**Comment by tmc** [comment]
Running `pnpm install ai@3.0.1` resolves this for me:

```shell
dependencies:
- ai 3.0.2
+ ai 3.0.1 (3.0.2 is available)
```

When I install 3.0.2:
```shell
dependencies:
- ai 3.0.1
+ ai 3.0.2 <- ../../packages/core
```

**Comment by briann** [comment]
I'm still able to repro on both `ai@3.0.1` and `ai@3.0.2`. 

I pushed up a branch (https://github.com/vercel/ai/pull/1043) which changes `rsc-types.ts` to `index.ts` and I'm able to use it locally to successfully import `ai/rsc`. It's a naive solution and I'm not sure if it's the right one, but putting it out there in case it helps.

**Comment by twxxk** [comment]
Same. When I copy next-ai-rsc to a different directory and run pnpm install ai@latest (3.0.2) and then pnpm dev, it works.

**Comment by leo-paz** [comment]
Happening for me too with `ai:3.0.2` node: `v18.18.0`

**Comment by sajadmh** [comment]
Experiencing the same issue when

`import { createAI, getMutableAIState, render } from 'ai/rsc';
`

Changing the import to this works:

`import { createAI, getMutableAIState, render } from 'ai/rsc/dist/rsc-types';
`

**Comment by IvanCoronado** [comment]
Adding `"moduleResolution": "bundler"` to your `tsconfig.json` fix the problem.

<img width="498" alt="image" src="https://github.com/vercel/ai/assets/13351933/d9ff45e2-d062-4f25-98c6-41e44d662885">

**Comment by joelhooks** [comment]
Same issue with node `v20.5.0` pnpm `8.7.0` in a turborepo

here's the repo https://github.com/badass-courses/course-builder

adding the above `moduleResolution: bundler` resolved the issue.

**Comment by bdcorps** [comment]
Getting this error when you switch `moduleResolution` from `node` to `bundler`
![CleanShot 2024-03-03 at 20 35 34@2x](https://github.com/vercel/ai/assets/6132555/1fecd257-eaf1-4eab-b694-26a4483b4fc8)

This is on `ai@3.0.4` and node `v20.10.0`

**Comment by nckre** [comment]
Had some issues in my own project which was based on the vercel chatbot. In addition to changing `moduleResolution` to `bundler`, had to remove `--turbo` flag from `dev` build to make it work.

**Comment by holdenmatt** [comment]
Hit the same issue on a fresh git clone of this repo.
Node v20.9.0, pnpm 8.12.0, macOS 12.3.1

For now, `pnpm install ai@3.0.1` fixed it for me

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete module-resolution and build failure for an existing exported AI SDK entry point, reproduced by several users, so it is a bug rather than a request for new functionality or documentation.

### Evidence
- A fresh clone of `examples/next-ai-rsc` fails to compile because the documented `ai/rsc` package path cannot be resolved from the package exports.
- Multiple users reproduced the failure across Windows, macOS, and Linux with different Node versions and package managers.
- Users identified package/configuration workarounds, including downgrading `ai`, adding `moduleResolution: "bundler"`, removing Turbopack, or renaming/copying the RSC declaration entry file.
