### ISSUE TITLE
docs/ai-rsc: missing information for a simple copy & paste

### ISSUE THREAD

**Issue by alonzuman** [vercel/ai#1045]
### Description

The ai-rsc page misses a few things that prevent simply copying and pasting the example code into a new repo:
- zod is missing (used right after) `pnpm install ai openai` -> `pnpm install ai openai zod`
- the imports are absolute `import { AI } from 'app/action'` -> `import { AI } from './action'`
- the setup of the root layout component drops the defaults you get when simply running npx create-next-app -y (like the Inter font, metadata etc')

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The issue requests corrections to documentation and its embedded example code so the AI RSC guide can be followed as written; it does not report a product behavior failure.

### Evidence
- The AI RSC documentation omits the required `zod` dependency from its install command.
- The documented import path is not directly usable when copied into a newly created repository.
- The root layout instructions replace defaults generated by `create-next-app`, reducing copy-and-paste usability.
