### ISSUE TITLE
Docs have multiple failing 404 links

### ISSUE THREAD

**Issue by conroywhitney** [vercel/ai#1058]
### Description

I hit a few 404s while browsing the docs so I ran Screaming Frog on the prod docs and it came up with:

* https://js.langchain.com/docs/api/callbacks/
* https://sdk.vercel.ai/docs/api-reference/anthropic-stream
* https://sdk.vercel.ai/docs/api-reference/cohere-stream
* https://sdk.vercel.ai/docs/api-reference/create-ai
* https://sdk.vercel.ai/docs/api-reference/docs/api-reference/use-completion
* https://sdk.vercel.ai/docs/api-reference/generative-ui/docs/concepts/prompt-engineering
* https://sdk.vercel.ai/docs/api-reference/google-generative-ai-stream
* https://sdk.vercel.ai/docs/api-reference/huggingface-stream
* https://sdk.vercel.ai/docs/api-reference/inkeep-stream
* https://sdk.vercel.ai/docs/api-reference/langchain-stream
* https://sdk.vercel.ai/docs/api-reference/mistral-stream
* https://sdk.vercel.ai/docs/api-reference/openai-stream
* https://sdk.vercel.ai/docs/api-reference/providers/js.langchain.com/docs
* https://sdk.vercel.ai/docs/api-reference/providers/lang-chain-stream
* https://sdk.vercel.ai/docs/api-reference/providers/use-chat
* https://sdk.vercel.ai/docs/api-reference/providers/use-completion
* https://sdk.vercel.ai/docs/api-reference/use-ai-state
* https://sdk.vercel.ai/docs/concepts/generative-ui

The main offenders are:

 * Needing to use the `/providers/` folder
 * Needing to use the `/generatve-ui/` folder
 
 But there are a few random 404s as well.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The issue requests correction of broken links and paths in the documentation, without describing a product or SDK behavior failure.

### Evidence
- The report lists multiple links in the production documentation that return HTTP 404 errors.
- It identifies incorrect or missing documentation paths involving `/providers/` and `/generative-ui/`.
