### ISSUE TITLE
404 page infinite redirect

### ISSUE THREAD

**Issue by conroywhitney** [vercel/ai#1060]
### Description

If you hit a 404 URL on the docs site (like https://sdk.vercel.ai/docs/foo/bar) you'll see that there's an infinite redirect which causes the browser to make about 100 requests per second (between all the assets, trackers, etc.)

Not sure if the docs have a custom 404 page? or if this is a Next/Vercel thing? Lemme know if I should post somewhere else.

![Screenshot 2024-03-02 at 4 56 26 PM](https://github.com/vercel/ai/assets/249891/f176d63b-6918-47e7-943d-e60b56f72ff2)

**Comment by lgrammel** [comment]
we have new docs now

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports concrete broken behavior on the existing documentation website, not a request to change documentation content.

### Evidence
- Visiting a nonexistent docs URL reportedly triggers an infinite redirect and roughly 100 requests per second.
- The attached network panel shows thousands of requests over about 45 seconds while the 404 page is open.
- The maintainer notes that the site now has new docs, suggesting the affected implementation was later replaced.
