### ISSUE TITLE
ai/rsc: Deploy with Vercel button broken

### ISSUE THREAD

**Issue by rikhuijzer** [vercel/ai#1092]
### Description

I just clicked through the Deploy with Vercel button at

https://github.com/vercel/ai/blob/9d51863453d22896e9244b43cf1c7c0138bdfeb9/examples/next-ai-rsc/README.md?plain=1#L27

and connected via GitLab. The build threw an error (see below for build logs) and the deployed site shows a `404: NOT_FOUND`/

### Code example

https://github.com/vercel/ai/blob/9d51863453d22896e9244b43cf1c7c0138bdfeb9/examples/next-ai-rsc/README.md?plain=1#L27

### Additional context

```
Running build in Washington, D.C., USA (East) – iad1
Cloning gitlab.com/<HIDDEN>
Previous build cache not available
Cloning completed: 1.551s
Running "vercel build"
Vercel CLI 33.5.3
Installing dependencies...
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "ai > solid-swr-store@0.10.7" has unmet peer dependency "solid-js@^1.2".
warning "ai > swrv@1.0.4" has unmet peer dependency "vue@>=3.2.26 < 4".
warning "ai > sswr@2.0.0" has unmet peer dependency "svelte@^4.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 32.68s.
Running "yarn run build"
yarn run v1.22.17
$ next build
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
   ▲ Next.js 14.1.1
   Creating an optimized production build ...
Compiler server unexpectedly exited with code: null and signal: SIGTERM
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
 ⚠ Using edge runtime on a page currently disables static generation for that page
   Generating static pages (0/3) ...

 ✓ Generating static pages (3/3) 
   Finalizing page optimization ...
   Collecting build traces ...
Route (app)                              Size     First Load JS
┌ ℇ /                                    5.35 kB         122 kB
└ ○ /_not-found                          886 B          85.4 kB
+ First Load JS shared by all            84.6 kB
  ├ chunks/726-38a3a50a14d8b6c1.js       29.1 kB
  ├ chunks/fd9d1056-8567c763e6940ab4.js  53.4 kB
  └ other shared chunks (total)          2.12 kB
○  (Static)        prerendered as static content
ℇ  (Edge Runtime)  server-rendered on demand using the Edge Runtime
Done in 46.53s.
Build Completed in /vercel/output [1m]
Deploying outputs...
Deployment completed
Uploading build cache [98.27 MB]...
Build cache uploaded: 2.841s
```

**Comment by rikhuijzer** [comment]
The error was fixed by running `npm update` and committing the `package-lock.json`. Still 404 though.

**Comment by rikhuijzer** [comment]
Ah fixed the 404 too. The problem was that the aforementioned deploy button doesn't automatically set the build system to `Next.js`. I manually set the "Framework preset" to "Next.js" and now the build succeeded.

So my problems are fixed, but I'll leave this issue open since the example doesn't work out of the box.

**Comment by conroywhitney** [comment]
@MaxLeiter @shuding -- is this related to https://github.com/vercel/ai/pull/1094? I'm getting a `next@14.1.2-canary.4` error hitting the deploy button (even with default framework set to Vercel). I tried re-deploying, as well as making random edits (to force a new deploy).

My solution was to clone the created github repo, run `pnpm i`, and [push the new `pnpm-lock.yaml`](https://github.com/conroywhitney/deploy-vercel-ai-ask-2228/commit/e2e80b6e03d30cc92a6f8d6d26f89391bbabada2)

### Deploy button
![Screenshot 2024-03-04 at 10 40 08 PM](https://github.com/vercel/ai/assets/249891/80eecd8b-e6de-4026-97c2-96854d271e65)

### Redeploying in Vercel
![Screenshot 2024-03-04 at 11 02 24 PM](https://github.com/vercel/ai/assets/249891/d869f863-8ba2-4a82-9d33-2be433edd59d)

### After updating `pnpm-lock.yaml`
![Screenshot 2024-03-04 at 11 15 13 PM](https://github.com/vercel/ai/assets/249891/0b753581-175f-40aa-8051-26992ed4abad)
![Screenshot 2024-03-04 at 11 15 48 PM](https://github.com/vercel/ai/assets/249891/8fb5a293-71d5-4240-aaa8-75eddd6330cf)

**Comment by conroywhitney** [comment]
🙌 fix'd

**Comment by conroywhitney** [comment]
@rikhuijzer -- weird. I wonder if there's some account settings difference...

What happens if you set `&framework=nextjs` in the "Deploy on Vercel" link? Could you try this one out?

https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fai%2Fblob%2Fmain%2Fexamples%2Fnext-ai-rsc&env=OPENAI_API_KEY&envDescription=OpenAI%20API%20Key&envLink=https%3A%2F%2Fplatform.openai.com%2Fapi-keys&framework=nextjs

**Comment by rikhuijzer** [comment]
I've tried Firefox and Edge both with a private GitLab repository and your new link. My "Framework Preset" is still "Other" after creating a new project when using that link resulting in a 404 page. The account was made new last week and is using email login. The account email is <MY_FIRST_NAME>.<MY_LAST_NAME>@gmail.com.

I guess if you make a new free account for yourself and the button works there, then all is good. Then maybe indeed my account has some incorrect setting somehow (even though I didn't change anything as far as I remember. I just pressed the deploy button).

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
This requests correction of a runnable example/template and its deployment setup rather than a change to AI SDK product behavior.

### Evidence
- The `examples/next-ai-rsc` Deploy with Vercel button produces a failed deployment or a deployed 404 page.
- Reporters found the generated project lacked a usable lockfile and selected the framework preset as “Other” instead of “Next.js.”
- The reporter explicitly states that the example does not work out of the box.
