### ISSUE TITLE
New model GigAI 

### ISSUE THREAD

**Issue by Turbo1337GS** [vercel/ai#1110]
### Feature Description

Look this https://gigasoft.com.pl/
I like this model! 

"It would be great if you added support for this model, it's new but good! The documentation is "poor" but it's on the website

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new model/provider support, which is a product capability enhancement.

### Evidence
- The issue explicitly asks to add support for the GigAI model.
- No existing AI SDK behavior is reported as broken or incorrect.
