### ISSUE TITLE
404 Error for Hugging Face Provider Documentation URL

### ISSUE THREAD

**Issue by CollComm** [vercel/ai#1115]
### Description

Title: 404 Error for Hugging Face Provider Documentation URL

---

**Description:**

Upon attempting to access the documentation for the Hugging Face provider at the following URL: https://sdk.vercel.ai/docs/guides/providers/hugging-face, a 404 error page is displayed instead of the expected content. This issue impedes access to vital information regarding the integration and utilization of the Hugging Face provider with the SDK.

**Steps to Reproduce:**
1. Navigate to the URL: https://sdk.vercel.ai/docs/guides/providers/hugging-face.
2. Observe the result.

**Expected Result:**

The expected result is to be directed to the documentation page for the Hugging Face provider, containing information on setup, configuration, and usage within the SDK.

**Actual Result:**

A 404 error page is displayed, indicating that the content at the specified URL cannot be found.

**Environment:**
- Browser: Google Chrome 122.0.6261.94
- Device: Laptop
- Operating System: macOS Sonoma

**Additional Information:**

- Date and Time when the issue was observed: March 6th, 2024. 
- [Webpage before](https://sdk.vercel.ai/docs/guides/providers/google)

**Suggested Next Steps:**

Investigation into the cause of the 404 error for the Hugging Face provider documentation URL is recommended. Potential steps could include verifying the URL structure, checking for recent changes to the documentation hierarchy, or ensuring that the content is correctly deployed and accessible.

---

**Attachments:**

<img width="449" alt="image" src="https://github.com/vercel/ai/assets/3196309/6acb5bf4-0b56-4d1d-a955-0d0ef3b912eb">

**Comment by CollComm** [comment]
See an duplicate issue. Closing to focus on the same topic.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the underlying report concerns missing documentation, this issue was identified and closed as duplicate bookkeeping, which falls under none.

### Evidence
- The reported Hugging Face documentation URL returns a 404 page.
- The sole comment states that this is a duplicate issue and is being closed to consolidate discussion elsewhere.
