### ISSUE TITLE
ai/rsc createStreamableUI().update replaces the whole UI node instead of the last appended node

### ISSUE THREAD

**Issue by marcoripa96** [vercel/ai#1129]
### Description

When reading the  the documentation of createStreamableUI I see the following:

- The `append `method is used to append a new UI node to the end of the old one. Once appended a new UI node, the previous UI node cannot be updated anymore.
- The `update` method is used to update the UI node. It takes a new UI node and replaces the old one.

From this I inferred the update method only updates the last appended node, but apparently it replaces the whole UI node.
I am not sure if this is a bug or if this is the intended behaviour. If it is the intended behaviour then how would I update only the last appended UI node?

Here's a [reproduction on codesandbox](https://codesandbox.io/p/devbox/elated-mayer-hqdjyq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltkcogu40007356kvyj1ynw1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltkcogu30002356krro1w2gu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltkcogu30004356k1hpty5e2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltkcogu40006356kgo0obk8p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltkcogu30002356krro1w2gu%2522%253A%257B%2522id%2522%253A%2522cltkcogu30002356krro1w2gu%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltkcogu40006356kgo0obk8p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltkcogu40005356khmavh4tq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltkcogu40006356kgo0obk8p%2522%252C%2522activeTabId%2522%253A%2522cltkcogu40005356khmavh4tq%2522%257D%252C%2522cltkcogu30004356k1hpty5e2%2522%253A%257B%2522id%2522%253A%2522cltkcogu30004356k1hpty5e2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltkcogu30003356k2bvi03t0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltkcogu30003356k2bvi03t0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

This happens on:

- `next`: 14.2.0-canary.2
- `ai`: 3.0.7

### Code example

```ts
import {
  createAI,
  createStreamableUI,
  getMutableAIState,
} from "ai/rsc";

async function submitUserMessage(userInput: string) {
  "use server";
  const aiState = getMutableAIState<typeof AI>();

  const ui = createStreamableUI(<div>Loading...</div>);

  (async () => {
    await sleep(1000);

    ui.update(<div>First message</div>);

    await sleep(1000);

    ui.append(<div>Second message</div>);

    await sleep(1000);

    ui.update(
      <div>
        Should update the last message, instead it replaces the whole ui node
      </div>,
    );

    ui.done();
  })();

  return {
    id: Date.now(),
    display: ui.value,
  };
}
```

**EDIT**
I found a way to achieve what I wanted following the example of nested UI presented here https://sdk.vercel.ai/docs/concepts/ai-rsc#nested-ui-streaming.

I would do something like this:

```ts

async function submitUserMessage(userInput: string) {
  "use server";
  const aiState = getMutableAIState<typeof AI>();

  const ui = createStreamableUI(<div>Loading...</div>);
  
  const textNode = createStreamableUI();
  
 ...
 ui.update(...);
 ui.append(...);
 
 ui.append(textNode.value);
 
 let content = [];
 
 for await (const token of generateTokens("some text")) {
     content.push(token);
     textNode.update(content.join(""));
 }
 
 textNode.done();

 ui.done();
 
 ...

  return {
    id: Date.now(),
    display: ui.value,
  };
}
```

It works, but it's a little verbose in my opinion, I think the dx could be improved, just like the first example I presented, or maybe there's actually just a better way than doing this. And also it's a bit counterintuitive since it's not really "nested" UI since the results "appends" a message, but maybe I am just thinking it in the wrong way.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests an API ergonomics enhancement for selectively updating appended UI, rather than demonstrating behavior that contradicts the documented contract.

### Evidence
- The documented `update` behavior replaces the existing UI node, matching the reported runtime behavior.
- The reporter found a working nested `createStreamableUI` approach.
- The remaining request is to make updating the most recently appended node less verbose and improve developer experience.
