### ISSUE TITLE
Next.js Pages Router's API documentation 

### ISSUE THREAD

**Issue by VedantRaut-sudo** [vercel/ai#1158]
### Description

![Screenshot 2024-03-15 102710](https://github.com/vercel/ai/assets/86559629/21343687-5dd7-489a-9ad8-cfba6fb6620e)
In your documentation specify the path (for example : page/api/chat.ts)

in app router you have specified but in page router there is not path mention and as a beginner it was difficult to many developer to understand .

**Comment by MaxLeiter** [comment]
We've released a brand new docs site with a new pages tutorial. You can access it here: https://sdk.vercel.ai/docs/getting-started/nextjs-pages-router

thanks for the feedback!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This requests clarification of written setup instructions and file placement in the documentation, without requiring a change to SDK behavior.

### Evidence
- The report asks the Pages Router API documentation to specify the example file path, such as `pages/api/chat.ts`.
- The reporter notes that the App Router documentation included a path while the Pages Router documentation did not.
- A maintainer responded that a new documentation site now includes a Pages Router tutorial.
