### ISSUE TITLE
Svelte support update useAssistant

### ISSUE THREAD

**Issue by dongumayagay** [vercel/ai#1161]
### Feature Description

update for svelte with useChat/useAssistant both the sdk and documentation

### Additional context

there is no useAssistant for svelte on the documentation and in the SDK

**Comment by dongumayagay** [comment]
![image](https://github.com/vercel/ai/assets/51516536/e94b27e2-e386-4f10-b6b2-ebc230160ecf)

**Comment by dongumayagay** [comment]
bump

**Comment by lgrammel** [comment]
Supported now (3.1.9): https://github.com/vercel/ai/releases/tag/ai%403.1.9

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The primary request is to add previously unavailable Svelte support for `useAssistant`; the documentation update is secondary to that new SDK capability.

### Evidence
- The description states that Svelte had no `useAssistant` implementation in either the SDK or documentation and requests adding it alongside `useChat`.
- The attached screenshot shows an empty Svelte tab for `experimental_useAssistant`.
- A maintainer later confirmed the capability was added in AI SDK 3.1.9.
