### ISSUE TITLE
forwardStream types and documentation

### ISSUE THREAD

**Issue by snikoletopoulos** [vercel/ai#1163]
### Description

There is a confusion for the `forwardStream` function
In code typescript has it's return type to be `Promise<any>`
In the documentation, it returns void, but I is used as if it returns a `Run` object(?)

### Additional context

![Screenshot 2024-03-15 at 3 27 55 PM](https://github.com/vercel/ai/assets/78855607/9bd819dd-9063-412a-aa50-f3ae27db32be)

![image](https://github.com/vercel/ai/assets/78855607/926ac32a-65c5-4b1d-acbc-7a8cbec703b2)

![image](https://github.com/vercel/ai/assets/78855607/8d73e1c8-bc3d-499d-9978-0460481218e4)

**Comment by lgrammel** [comment]
Good point, it returns `Run`.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1164

**Comment by snikoletopoulos** [comment]
Thank you! that was super fast!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The existing API declaration and documentation incorrectly describe the return type, creating a concrete type-level defect in current SDK behavior.

### Evidence
- `forwardStream` is documented as returning `void`, while its TypeScript declaration returns `Promise<any>`.
- The SDK documentation example awaits the result and accesses it as a Run object.
- A maintainer confirmed that `forwardStream` returns `Run` and linked the corrective PR #1164.
