### ISSUE TITLE
useAssistant not data stream

### ISSUE THREAD

**Issue by faye1225** [vercel/ai#1204]
### Feature Description

I hope to add stream processing for `thread.run.step.delta` events, and then return the data in `experimental_useAssistant`.

https://github.com/vercel/ai/blob/fac9a6ee7c3aca975f7dd9f2f40cda1b82a1f8f3/packages/core/streams/assistant-response.ts

like this:
```ts
...

 case 'thread.run.step.created': {
              controller.enqueue(
                textEncoder.encode(
                  formatStreamPart('data_message', {
                    id: value.data.id,
                    role: 'data',
                    data: [{ type: 'text', text: { value: '' } }]
                  })
                )
              )
              break
            }
            case 'thread.run.step.delta': {
              if (value.data.delta.step_details?.type !== 'tool_calls') break
              // @ts-ignore
              const valueCode =
                value.data.delta.step_details?.tool_calls[0].code_interpreter

              controller.enqueue(
                textEncoder.encode(formatStreamPart('data', [valueCode]))
              )

              break
            }




// in page
  const {
    status,
    messages,
    input,
    threadId,
    submitMessage,
    handleInputChange,
    data
  } = experimental_useAssistant()

```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new streaming and hook API capability, not a report that existing documented behavior is failing.

### Evidence
- The issue explicitly requests adding stream processing for `thread.run.step.delta` events.
- It asks for `experimental_useAssistant` to expose the streamed event payload through `data`, with suggested implementation code.
