### ISSUE TITLE
Build error: "AI cannot be used as a JSX component"

### ISSUE THREAD

**Issue by csdiehl** [vercel/ai#1232]
### Description

The project setup from the template project for using the AI SDK with server components, throws the following error on build: "AI cannot be used as a JSX component." This seems to contradict the documentation for this component, as it says it is a provider that can be used to wrap other components. I think it occurs because the type of `AI` is a Promise and not a React component.  

Here's a link to my [project repo](https://github.com/csdiehl/ai-data-assistant/tree/main) where the error can be reproduced. Specifically, it occurs in the [`layout.tsx` file](https://github.com/csdiehl/ai-data-assistant/blob/main/src/app/layout.tsx). I did not modify this file in any way from the template code provided in the documentation. 

Thanks!

### Action.tsx where AI is defined

```
// AI is a provider you wrap your application with so you can access AI and UI state in your components.
export const AI = createAI({
  actions: {
    submitUserMessage,
  },
  // Each state can be any shape of object, but for chat applications
  // it makes sense to have an array of messages. Or you may prefer something like { id: number, messages: Message[] }
  initialUIState,
  initialAIState,
})

```

### Layout.tsx Code

```
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { AI } from "./action"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
{/*TS error thrown on the following line*/}
        <AI>{children}</AI>
      </body>
    </html>
  )
}
```

**Comment by MaxLeiter** [comment]
What version of Next.js and typescript are you using? I recommend upgrading TypeScript

**Comment by csdiehl** [comment]
Hi @MaxLeiter thanks for the reply. I tried upgrading my Typescript to "^5.4.3" but that didn't resolve the error. I'm on Next 14.2.0-canary.22

**Comment by unstubbable** [comment]
If I remember correctly, the type of `AI` cannot be inferred correctly with the implicit return type of the action. For me, it helped to set an explicit return type, see https://github.com/unstubbable/ai-rsc-test/commit/ef44eb0.

**Comment by kevinschaich** [comment]
Same issue here, the suggestion to upgrade Next.js and Typescript worked for me:

```diff
dependencies:
- next 14.2.3
+ next 14.2.4

devDependencies:
- typescript 5.4.5
+ typescript 5.5.2
```

VSCode is happy with it now:

<img width="763" alt="image" src="https://github.com/vercel/ai/assets/9244728/6f96185f-dcd3-41ea-b53a-fe46044da05e">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete type-checking failure in existing AI SDK template behavior that contradicts the documented provider usage, even though the application can run when the error is ignored.

### Evidence
- Using the documented/template `<AI>{children}</AI>` pattern produced the TypeScript error “AI cannot be used as a JSX component.”
- The reporter reproduced it without modifying the template layout and noted that the inferred `AI` type appeared to be a Promise.
- Comments identify workarounds through explicit action return types or newer Next.js and TypeScript versions.
