### ISSUE TITLE
https://sdk.vercel.ai/docs/guides/providers/openai

### ISSUE THREAD

**Issue by James-Wuguoqing** [vercel/ai#1235]
### Description

<!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js"></script><script src="/_next/static/chunks/webpack.js" defer=""></script><script src="/_next/static/chunks/main.js" defer=""></script><script src="/_next/static/chunks/pages/_app.js" defer=""></script><script src="/_next/static/chunks/pages/_error.js" defer=""></script><script src="/_next/static/development/_buildManifest.js" defer=""></script><script src="/_next/static/development/_ssgManifest.js" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next"></div><script src="/_next/static/chunks/react-refresh.js"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"development","isFallback":false,"err":{"name":"Error","source":"edge-server","message":"Connection error.","stack":"Error: Connection error.\n at OpenAI.makeRequest (webpack-internal:///(rsc)/./node_modules/.pnpm/openai@4.29.2/node_modules/openai/core.mjs:322:19)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async POST (webpack-internal:///(rsc)/./app/api/completion/route.ts:20:22)\n at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:218:37)\n at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:157:26)\n at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:280:30)\n at async EdgeRouteModuleWrapper.handler (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:92:21)\n at async adapter (webpack-internal:///(rsc)/./node_modules/.pnpm/next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:176:16)\n at async runWithTaggedErrors (file://D:\\my-chatgpt\\my-ai-app\\node_modules\\.pnpm\\next@14.1.4_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\server\\web\\sandbox\\sandbox.js:99:24)\n at async DevServer.runEdgeFunction (file://D:\\my-chatgpt\\my-ai-app\\node_modules\\.pnpm\\next@14.1.4_react-dom@18.2.0_react@18.2.0\\node_modules\\next\\dist\\server\\next-server.js:1166:24)"},"gip":true,"scriptLoader":[]}</script></body></html>

### Additional context

why?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an unclear support request about an OpenAI connection failure rather than a substantiated AI SDK bug or a request to change documentation.

### Evidence
- The description pastes a Next.js/OpenAI `Connection error` response from a local application.
- No code example, reproduction steps, or evidence tying the failure to incorrect AI SDK behavior is provided.
- The only request is “why?”, making this primarily a troubleshooting question.
