### ISSUE TITLE
Enable streaming of text from Lanchain

### ISSUE THREAD

**Issue by rogerodipo** [vercel/ai#1236]
### Feature Description

Enable streaming of text from Lanchain in the render method rather than only directly from the llm.

**Comment by lgrammel** [comment]
Please check out our LangChain adapter: https://sdk.vercel.ai/providers/adapters/langchain

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The request is framed as adding a streaming capability or integration path, not fixing a documented failure. The adapter reference does not establish a concrete bug.

### Evidence
- The issue explicitly requests enabling text streaming from LangChain within the render method.
- No broken or contradictory existing behavior is reported.
- A maintainer points to the existing LangChain adapter as a possible solution.
