### ISSUE TITLE
Support seed for chat completions in render in ai/rsc

### ISSUE THREAD

**Issue by roguesherlock** [vercel/ai#1252]
### Feature Description

Hey I think it'd be nice add an option for `seed` to `render` function in `ai/rsc`. Let me know if you want me to create a pr for this. It should be quick one

https://platform.openai.com/docs/guides/text-generation/reproducible-outputs 

### Use Case

Being able to reproduce outputs for debugging purposes

**Comment by lgrammel** [comment]
`streamUI` (which superseeds `render`) has a `seed` setting: https://sdk.vercel.ai/docs/reference/ai-sdk-rsc/stream-ui

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for an API capability in `render`, not a report that existing behavior is broken. The capability is available through the newer `streamUI` API, but the original request remains an enhancement request.

### Evidence
- The issue requests adding a `seed` option to the `ai/rsc` `render` function for reproducible outputs.
- A maintainer notes that the superseding `streamUI` API already provides a `seed` setting.
