### ISSUE TITLE
Request to have token count in messages

### ISSUE THREAD

**Issue by faye1225** [vercel/ai#1259]
### Feature Description

I hope to include the number of tokens inherent to the API response when returning results. This way, I can better understand the consumption across different models.
- OpenAIStream,AnthropicStream,HuggingFaceStream...
- `return CompletionUsage {
    completion_tokens: number;
    prompt_tokens: number;
    total_tokens: number;
}`

This is relevant to the discussion, but there's still no good solution.
https://github.com/vercel/ai/issues/339
https://github.com/vercel/ai/issues/551

**Comment by MaxLeiter** [comment]
The utilities in the AI SDK core (3.0 release) include `usage` objects: https://sdk.vercel.ai/docs/reference/ai-sdk-core/generate-text#usage

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to add token-usage reporting as a new SDK capability, not a report of broken existing behavior.

### Evidence
- The issue requests token usage counts (`completion_tokens`, `prompt_tokens`, and `total_tokens`) in API responses across model stream utilities.
- A maintainer notes that AI SDK Core 3.0 includes `usage` objects, indicating the requested capability was subsequently provided.
