### ISSUE TITLE
Fireworks.AI RSC Function call does not work

### ISSUE THREAD

**Issue by fullstackwebdev** [vercel/ai#1273]
### Description

1. Download the repo and setup ./next-rsc
2. Setup your .env file to use fireworks
3. Modify action.tsx to use environmental variables below for openai

OPENAI_API_URL=https://api.fireworks.ai/inference/v1
OPENAI_API_KEY=
OPENAI_MODEL_NAME=accounts/fireworks/models/firefunction-v1

![Screenshot from 2024-04-04 00-34-39](https://github.com/vercel/ai/assets/10137946/09136891-bb62-4a7a-8bcd-d0b41cae74e8)

Somewhere in OpenAIStream(

https://github.com/vercel/ai/blob/b7732d764ff973b4b87019f1ad88fe3287ce6d6b/packages/core/streams/openai-stream.ts#L321-L404

It appears to be not picked up the tool/function

There is similar behavior for all other openai "compatible" apis, but fireworks.ai got the furthest.

**Comment by lgrammel** [comment]
Here's the same example, updated to the new `ai/core` functions: https://github.com/vercel/ai/pull/1212 - can you give it a try? (AI Core docs: https://sdk.vercel.ai/docs/ai-core

**Comment by fullstackwebdev** [comment]
Hi Thanks. I switched to your branch an updated the OpenAI code to use baseUrl

I tried firefunction-v1 and got this error message

![Screenshot from 2024-04-04 19-38-00](https://github.com/vercel/ai/assets/10137946/5655108a-3c56-4335-b271-69b682511a34)

```
}
Error:  [AI_TypeValidationError: Type validation failed: Value: {"id":"4311db86-63a2-4343-9cc2-ce15fb916907","object":"chat.completion.chunk","created":1712284976,"model":"accounts/fireworks/models/firefunction-v1","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"id":null,"type":"function","function":{"arguments":"}"}}]},"finish_reason":null}],"usage":null}.
Error message: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "choices",
      0,
      "delta",
      "tool_calls",
      0,
      "id"
    ],
    "message": "Expected string, received null"
  }
]] {
  name: 'AI_TypeValidationError',
  cause:  [ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "choices",
      0,
      "delta",
      "tool_calls",
      0,
      "id"
    ],
    "message": "Expected string, received null"
  }
]] {
  issues: [
  {
  code: 'invalid_type',
  expected: 'string',
  received: 'null',
  path: [ 'choices', 0, 'delta', 'tool_calls', 0, 'id' ],
  message: 'Expected string, received null'
}
],
  addIssue: [Function],
  addIssues: [Function],
  name: 'ZodError'
},
  value: {
  id: '4311db86-63a2-4343-9cc2-ce15fb916907',
  object: 'chat.completion.chunk',
  created: 1712284976,
  model: 'accounts/fireworks/models/firefunction-v1',
  choices: [
  {
  index: 0,
  delta: {
  tool_calls: [
  { index: 0, id: null, type: 'function', function: { arguments: '}' } }
]
},
  finish_reason: null
}
],
  usage: null
}
}
```


I went back and tried Mixtral 8x7b instruct nitro on openrouter.org, and this time, this actually got closer!

![Screenshot from 2024-04-04 19-53-05](https://github.com/vercel/ai/assets/10137946/55a38f42-09d0-473a-a531-1805396a37d8)

**Comment by lgrammel** [comment]
The errors indicate that the model is not strong enough to generate JSON that matches the schema.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a provider/model compatibility and troubleshooting report. The available discussion does not establish broken promised AI SDK behavior or request a defined SDK enhancement.

### Evidence
- Fireworks tool-call streaming fails validation because its response contains `tool_calls[0].id: null` where the OpenAI schema expects a string.
- The reporter is using Fireworks and OpenRouter through the OpenAI-compatible API configuration rather than a dedicated supported provider.
- The maintainer attributes the failures to model-generated output not matching the required JSON schema, rather than an AI SDK defect.
