### ISSUE TITLE
Local GGML model support

### ISSUE THREAD

**Issue by metatwin** [vercel/ai#130]
I would like to request local GGML model support for this package. It would be great if users can deploy models locally using the GGML-v3 model. Thanks so much for the great package.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new model/deployment capability, so it is a feature request despite the unresolved scope.

### Evidence
- The reporter explicitly requests support for locally deployed GGML-v3 models.
- No existing behavior is described as broken or contrary to documentation.
- The maintainer asks whether the request targets the playground or package, but no clarification is provided.
