### ISSUE TITLE
3.0.20 breaks experimental_onFunctionCall in useChat

### ISSUE THREAD

**Issue by MrOrz** [vercel/ai#1351]
## Steps to reproduce
1. Follow quickstart https://sdk.vercel.ai/docs/getting-started
2. Follow "Defining functions" and "Handling Function Calls on the Client" in OpenAI functions doc https://sdk.vercel.ai/docs/guides/providers/openai-functions#handling-function-calls-on-the-client , which implements `functionCallHandler` on client code to process the function call from LLM.

The repository that can reproduce the issue:  https://github.com/MrOrz/vercel-ai-function-bug/

## Expected result
This screenshot is made by pinning ai SDK at version `3.0.19`:
![image](https://github.com/vercel/ai/assets/108608/a6194efb-0f3b-40cf-8afe-c10321c40082)
1. console prints function call argument, indicating that the `functionCallHandler` is invoked correctly
2. function return value is added to `messages` and chat API is invoked again, as expected

## Actual result
This is the result of `3.0.20` and `3.0.22`:
![image](https://github.com/vercel/ai/assets/108608/72f98a47-ddc8-4ea1-8f8c-e1d3d6839de6)
Note that console prints nothing -- `functionCallHandler` is probably not called at all

### Code example

 https://github.com/MrOrz/vercel-ai-function-bug/

### Additional context

https://github.com/vercel/ai/issues/1316 indicates that there is a breaking change in 3.0.20. But it is more related to custom parsing of `StreamingTextResponse`. Does not mention that 3.0.20 also breaks `experimental_onFunctionCall`.

**Comment by lgrammel** [comment]
I have just tested the openai function call example incl. client side execution ( https://github.com/vercel/ai/tree/main/examples/next-openai/app/function-calling ) and it works as expected. I'll check out your repository to see if I can find out what's different.

**Comment by lgrammel** [comment]
@johnson-liang thanks. No need for a PR, we're in the process of updating our docs, so your changes would get lost.

**Comment by lgrammel** [comment]
With the recently added `useChat` / `streamText` tool calling revamp (see https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling ), `experimental_onFunctionCall` has become deprecated.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete regression in existing `useChat` function-calling behavior. Its later deprecation does not change the original report from a bug into a feature or documentation request.

### Evidence
- The reporter provides a reproducible regression: client-side `experimental_onFunctionCall` works in AI SDK 3.0.19 but is not invoked in 3.0.20 or 3.0.22.
- Expected follow-up message handling and API invocation no longer occur after the function call.
- A maintainer supplied a workaround and said they would investigate automatic support, corroborating the behavior gap.
