### ISSUE TITLE
httpAgent for experimental AI core provider packages

### ISSUE THREAD

**Issue by xyhStruggler** [vercel/ai#1360]
### Feature Description

In the OpenAI SDK, there is an 'httpAgent' client option to handle the HTTP(S) connections.
There is no such option in '@ai-sdk/openai'.
It will be great if you can provide this feature to change the HTTP agent. Thank you so much!

**Comment by gtoxlili** [comment]
have you solved this problem?

**Comment by xyhStruggler** [comment]
> have you solved this problem?

yep, I built a proxy server myself and redirect the HTTP request through that server

**Comment by lgrammel** [comment]
what is the use case?

we currently support setting headers if needed.

**Comment by xyhStruggler** [comment]
> what is the use case?
> 
> we currently support setting headers if needed.

For developers based in China, we have to use VPN to access OpenAI API Services. Need the httpAgent to set the proxy.

**Comment by qingtian1771** [comment]
How about this? thanks!

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1955

**Comment by kaifengwang-sbi-dalian** [comment]
Hi @xyhStruggler !
Could you please give some more details about the proxy server that you built before, I may face the same issue but have no idea about it, Thanks a lot ! BTW, I'm a developer based from China, I don't know how to ceate httpAgent to set the proxy!

**Comment by xyhStruggler** [comment]
> Hi @xyhStruggler ! Could you please give some more details about the proxy server that you built before, I may face the same issue but have no idea about it, Thanks a lot ! BTW, I'm a developer based from China, I don't know how to ceate httpAgent to set the proxy which you mentioned, thanks again ！

I went deep into the AI SDK code, found where they post the API, and changed it to send to a local address. Then I build the proxy server which is a simple nodejs server to receive the API requests and send to OpenAI API with httpAgent and proxy.
I do not recommend this because it only works for dev environment and Igrammel has already upgraded the AI SDK to support headers so you can add custom settings into the API request. Another option is to switch to Azure OpenAI API since they provide global access (that's what I did).

**Comment by kaifengwang-sbi-dalian** [comment]
Hi @xyhStruggler , Thank you for your reply，base on company policy, I can't sign up Azure OpenAI account for now, so I try to custom the http proxy from headers, but I can't find a right way to change the request proxy, do you know how to change the http proxy from headers ？thanks a lot.

**Comment by xyhStruggler** [comment]
@kaifengwang-sbi-dalian I haven't had a chance to try that but I'm pretty sure they put some examples that you can follow.

**Comment by kaifengwang-sbi-dalian** [comment]
> @kaifengwang-sbi-dalian I haven't had a chance to try that but I'm pretty sure they put some examples that you can follow.

got it, thanks .

**Comment by cloudcarver** [comment]
For those who're still struggling with the proxy issue, here is the answer:

1. Install `undici`
```shell
pnpm i undici
```

2. use a custom fetch
```javascript
// api/chat/route.js

import { fetch, ProxyAgent } from 'undici';

const dispatcher = new ProxyAgent('<proxy URL>')

const groq = createGroq({
  apiKey: "<my API key>",
  fetch: async (req, options) => {
    let res =  await fetch(req, {
      ...options, dispatcher
    });
    return res;
  }
})

```
The only compromise to make is to use `.js` to ignore the type issue. 

I also tried `node-fetch`, its API for handling the stream response is not compatible with the native `fetch`. `undici` works just fine here.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The issue requests a new provider configuration capability rather than reporting a failure of documented existing behavior.

### Evidence
- The OpenAI provider lacked an `httpAgent` option for configuring HTTP(S) connections through a proxy.
- The requested use case is routing OpenAI API traffic through a VPN/proxy, particularly for developers in China.
- A maintainer linked PR #1955, and a later comment demonstrated a custom `fetch` with Undici's `ProxyAgent` as a workaround.
