### ISSUE TITLE
@ai-sdk/anthropic@0.0.1 / @ai-sdk/open-ai@0.0.1 missing dist/ folders

### ISSUE THREAD

**Issue by connorblack** [vercel/ai#1366]
### Description

![CleanShot 2024-04-16 at 14 18 59@2x](https://github.com/vercel/ai/assets/1903789/dc0e9a86-869c-4147-92ce-c506307e0583)
<img width="845" alt="Screenshot 2024-04-16 at 2 19 38 PM" src="https://github.com/vercel/ai/assets/1903789/42d07737-b5e2-49e8-b99b-9f1f94c9a5fc">

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1367

**Comment by lgrammel** [comment]
I've released `v0.0.2` versions of the affected packages.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The initial package releases were missing required build artifacts, making this a concrete packaging failure that was subsequently fixed.

### Evidence
- The published @ai-sdk/anthropic@0.0.1 and @ai-sdk/openai@0.0.1 packages contained only LICENSE, README.md, and package.json; their dist folders were absent.
- A maintainer linked a corrective pull request and released v0.0.2 versions of the affected packages.
