### ISSUE TITLE
Assistant API v2 breaking changes

### ISSUE THREAD

**Issue by tomatac** [vercel/ai#1380]
### Description

Is the current Vercel API compatible to Assistant API v2?
Are there any breaking changes?
I have some issues with some assistants that were working, now responding like: “It looks like there aren’t any documents uploaded to search for information about …”. 
I know that v2 is new but it looks like Assistant API v1 is obsolete.
I could not even setup a version 1 Assistant API on OpenAI anymore. If I try to use the "Switch to v1" button, everything gets grayed out.
Also, it looks like the version 1 assistants were automatically converted to version 2. 

### Additional context

I use useAssistant and AssistantResponse.
The system worked few days ago.
Now is now responding with responses like this: “It looks like there aren’t any documents uploaded to search for information about …”.

**Comment by lgrammel** [comment]
I tested the `useAssistant` with the OpenAI SDK `v4.38.0` and it was behaving as expected.

Can you share more details where the AI SDK part is failing?

It could be that there are issues with your assistants independent of the AI SDK. You can find out by e.g. using them in the OpenAI playground.

**Comment by tomatac** [comment]
I use the Assistant file search function and the Assistant is behaving like there is no Vectors Store and Files associated with the Assistant and is responding with something like: “It looks like there aren’t any documents uploaded to search for information about …”.
It is a also bit strange that every thread creates a new vector store of size zero and it references this new created vector store.
So, i was not sure if we need to pass the vector_store_ids like in this example:
{
  "id": "asst_abc123",
  "object": "assistant",
  "created_at": 1698984975,
  "name": "Math Tutor",
  "description": null,
  "model": "gpt-4-turbo",
  "instructions": "You are a personal math tutor. When asked a question, write and run Python code to answer the question.",
  "tools": [
    {
      "type": "code_interpreter"
    },
    {
      "type": "file_search"
    }
  ],
  "tool_resources": {
    "file_search": {
      "vector_store_ids": ["vs_abc"]
    },
    "code_interpreter": {
      "file_ids": ["file-123", "file-456"]
    }
  }
}
Ref: https://platform.openai.com/docs/assistants/migration/what-has-changed

**Comment by wau** [comment]
have you figured it if its a bug from vercel ai sdk or we are using the chatgpt api wrong? also having the same problem

**Comment by wau** [comment]
@tomatac just figured it out and now my assistant is able to retrieve information from uploaded knowledge base, 
what to do:
`pnpm update openai`

this is my current version: `"openai": "^4.38.2",`

enable file search when creating the thread and passing the vector Id from your files:

```
// Create a thread if needed
  const threadId = input.threadId ?? input.data.threadId ?? (await openai.beta.threads.create({
    tool_resources: {
      "file_search": {
        "vector_store_ids": ["vs_tk7jWu0h6vjAdp7X2P1Y43gH"]
      }
    }
  })).id;
```
  
  enabling file search when running the response stream:
  
```
  const runStream = openai.beta.threads.runs.stream(threadId, {
        assistant_id:
          input.data.assistantId ??
          (() => {
            throw new Error('ASSISTANT_ID is not set');
          })(),
          tools: [{type: "file_search"}],
      });
```

everything is working fine now and the assistant is able to retrieve information from files :)

**Comment by tomatac** [comment]
@wau, updating openai library fixed the issue. I did some testing and I think that was also something wrong related to the OpenAI web UI that was not working right, because when I was getting the assistant properties using the API they were different from what was displayed in the UI and the assistants were created using the UI.

**Comment by burn2delete** [comment]
@wau could you please let us know which files you updated to include the file_search tool? I am trying to implement this within the [Next.JS AI Chatbot](https://github.com/vercel/ai-chatbot) template.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support/configuration question caused by the OpenAI dependency or UI, not a confirmed defect or requested change in the Vercel AI SDK.

### Evidence
- The maintainer tested `useAssistant` with OpenAI SDK v4.38.0 and could not reproduce an AI SDK failure.
- The reporter confirmed that updating the `openai` package fixed the issue and also suspected inconsistent behavior in OpenAI's web UI.
- Later comments provide configuration guidance and ask for implementation help with a template.
