### ISSUE TITLE
Ability to access request headers/metadata

### ISSUE THREAD

**Issue by MaxLeiter** [vercel/ai#1388]
### Feature Description

Many providers provide request ids (e.g. `x-request-id`) in their headers. It'd be great if this could be accessed after a model call.

### Use Case

o11y/debugging

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for a new API capability to expose provider response metadata, so it is a feature request.

### Evidence
- The issue requests access to provider response headers or metadata after a model call.
- The stated use case is retrieving request IDs for observability and debugging.
- No existing documented behavior is described as broken.
