### ISSUE TITLE
Super weird bug (not updating) only on Vercel / deployed code

### ISSUE THREAD

**Issue by bernaferrari** [vercel/ai#1438]
### Description

The following code works on local (dev + build), but fails on Vercel. I don't know why and it is super hard to debug vercel. I'm actually facing another bug, but I simplified into this to show something is definitely not working well. Is there anything I'm doing wrong here?

Expected:

https://github.com/vercel/ai/assets/351125/c6d0d916-eae2-4b36-9ef6-f08c502f65db

Deployed (vercel.app thing):

https://github.com/vercel/ai/assets/351125/7db14957-c631-4a1a-93b3-e487645b1a8b

action.ts
```ts
export async function validateCode2() {
  "use server";

  // const aiState = getMutableAIState();

  const status = createStreamableValue("in_progress");
  const ui = createStreamableUI(
    <div className="flex flex-col items-center justify-center gap-3 p-6 text-zinc-500">
      <div className="animate-spin">
        <Loader2 className="animate-spin w-4 h-4 my-2 text-primary" />
      </div>
      <div className="text-sm text-zinc-500">
        Please wait while we fulfill your order.
      </div>
    </div>
  );

  (async () => {
    await new Promise((resolve) => setTimeout(resolve, 2000));

    ui.done(
      <div className="flex flex-col items-center text-center justify-center gap-3 p-4 text-emerald-700">
        <CheckIcon />
        <div>Payment Succeeded</div>
        <div className="text-sm text-zinc-600">
          Thanks for your purchase! You will receive an email confirmation
          shortly.
        </div>
      </div>
    );

    // aiState.done({
    //   ...aiState.get(),
    //   messages: [
    //     ...aiState.get().messages.slice(0, -1),
    //     {
    //       role: "assistant",
    //       content: "The purchase has completed successfully.",
    //     },
    //   ],
    // });

    status.done("completed");
  })();

  return {
    status: status.value,
    display: ui.value,
  };
}

export const AI = createAI<AIState, UIState>({
  actions: {
    validateCode2,
  }
});
```

test2/page.tsx
```ts
import React from "react";
import { AI } from "@/lib/v2/actions";
import Test2 from "./methods";

export default function Page() {
  return (
    <AI>
      <Test2 />
    </AI>
  );
}
```

test2/methods.tsx
```ts
"use client";

import { readStreamableValue, useActions } from "ai/rsc";
import React, { useState } from "react";

export default function Page() {
  const { validateCode2 } = useActions();
  const [currentStatus, setCurrentStatus] = useState("");
  const [display, setDisplay] = useState(null);

  return (
    <div className="flex flex-col gap-4 w-full">
      <button
        onClick={async () => {
          const { status, display } = await validateCode2("arrrr");
          for await (const statusFromStream of readStreamableValue(status)) {
            console.log("statusFromStream", statusFromStream);
            setCurrentStatus(statusFromStream as string);
            setDisplay(display);
          }
          console.log("hello???");
          console.log("done");
        }}
      >
        Validate
      </button>
      {currentStatus && <div>{currentStatus}</div>}
      {display && <div>{display}</div>}
    </div>
  );
}
```

**Comment by lgrammel** [comment]
Can you try adding `export const dynamic = 'force-dynamic'`?

https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config

**Comment by bernaferrari** [comment]
Yes, it works. Weird gemini demo didn't need that. Now I have another error, but I won't open an issue because it is frustating to reproduce:
- make the function (like above) have a single streamable value, and done() in the middle. Keep processing.
- then redirect to a different page.
The server will keep loading for a while, but LLM calls will take 27 seconds instead of 2 seconds. Super weird. Have you seen anything like this? Only happens on Vercel. Locally works super well.

I think I'll drop ai and just use two POST requests for this, when it finishes one I return and start the other without awaiting. How would you do this?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a configuration and support question. The confirmed fix uses Next.js route settings, while the remaining concern lacks a reproducible report tying it to broken AI SDK behavior.

### Evidence
- The reported streaming issue occurred only in the Vercel deployment and was resolved by adding Next.js route configuration `export const dynamic = 'force-dynamic'`.
- The reporter confirmed the suggested configuration worked.
- The follow-up describes an unreproduced deployment-performance problem and asks for implementation advice rather than establishing an AI SDK defect.
