### ISSUE TITLE
[AI Core] Abort signal causes `BodyStreamBuffer was aborted`

### ISSUE THREAD

**Issue by johannschopplich** [vercel/ai#1445]
### Description

I'm migrating some function from the impeccable `modelfusion` from @lgrammel to the new Vercel AI Core. So cool that the work of ModelFusion does continue under a new umbrella! Much appreciated.

However, using the new Vercel AI Core functions, I can't use an `abortSignal`. It seems like even in `try/catch`, somewhere down the road inside the library there is an unhandled stream error, which leads to a Promise rejection outside of my try/catch methods.

The error reads (in Chrome):
```
DOMException: BodyStreamBuffer was aborted
```

### Code example

```ts
import { experimental_streamText } from 'ai';
import { openai } from '@ai-sdk/openai'

try {
  const { textStream } = await experimental_streamText({
    model: openai.chat('gpt-4-turbo'),
    prompt: 'Invent a new holiday and describe its traditions.',
    abortSignal: AbortSignal.timeout(2000)
  });

  for await (const text of textStream) {
    console.log(text)
  }
} catch (error) {
  // This will never be reached, because there is an unhandled Promise 
  // rejection in the stream
  console.error(error?.name)
}
```

### Additional context

- Latest Vercel AI Core

**Comment by lgrammel** [comment]
Thanks for the kind words!

Fix: https://github.com/vercel/ai/pull/1451

**Comment by anneclairelh** [comment]
@lgrammel, I am experimenting an almost identical error when using the `streamObject` method instead of the `streamText`. Has a similar fix been done on `streamObject` yet ? I'm happy to create a new ticker with more details if needed. Thanks a lot in advance!

**Comment by lgrammel** [comment]
@anneclairelh can you provide code that i can use for reproduction?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a reproducible failure in existing abort-signal handling that causes an unexpected unhandled stream rejection, and the maintainer confirmed it required a fix.

### Evidence
- Using `abortSignal` with `experimental_streamText` causes an unhandled `DOMException: BodyStreamBuffer was aborted`.
- The rejection occurs outside the provided `try/catch`, preventing expected error handling.
- A maintainer linked a pull request explicitly described as a fix.
