### ISSUE TITLE
Pages Router AI SDK 404 error

### ISSUE THREAD

**Issue by BensenHsu** [vercel/ai#1448]
### Description

Hi @lgrammel,

Quoted from the documentation of the Vercel AI SDK: `You can use the pages/ directory for the frontend while using an app/ directory Route Handler for handling your LLM responses with streaming.`. URL: https://sdk.vercel.ai/docs/guides/frameworks/nextjs-pages

But I only got `404 Not Found` error by creating API in `/app/api/chat/router.ts` and call it in `/pages/chat/index.ts`. Please enlighten me.

### Code example

**/app/api/chat/router.ts**:
```
import { OpenAIStream, StreamingTextResponse } from 'ai';
import OpenAI from 'openai';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});
 
export const dynamic = 'force-dynamic';
 
export default async function handler(req: Request, res: Response) {
  const { messages } = await req.json();

  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages,
  });
 
  const stream = OpenAIStream(response);

  return new StreamingTextResponse(stream);
}
```

**/pages/chat/index.ts**:
```
import { useChat } from 'ai/react';
 
export const dynamic = 'force-dynamic';
 
export default function IndexPage() {
  const { messages, handleSubmit, input, handleInputChange } = useChat({ api: '/api/chat'});
 
  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor="input">Prompt</label>
      <input
        name="prompt"
        value={input}
        onChange={handleInputChange}
        id="input"
      />
      <button type="submit">Submit</button>
      {messages.map((message, i) => (
        <div key={i}>{message.content}</div>
      ))}
    </form>
  );
}
```

**Comment by lgrammel** [comment]
The route file needs to be called `route.ts` (not `router.ts`). Can you check the filename?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a usage/configuration mistake resolved through support, not broken SDK behavior or a requested documentation/product change.

### Evidence
- The API handler was named `/app/api/chat/router.ts` instead of the required `/app/api/chat/route.ts`.
- A maintainer identified the filename mistake, and the reporter confirmed that renaming it resolved the 404.
