### ISSUE TITLE
Allow Unchecked Schema for Tool Calls and object generations. Make Zod optional.

### ISSUE THREAD

**Issue by Necmttn** [vercel/ai#1474]
### Feature Description

For the AI core api would like to be able to generate tool calls based on the `JSON Schema` instead of `Zod Schema`

### Use Case

In [@craftgen](https://github.com/craftgen/craftgen) We are generating the json schema for the nodes/tools on the fly  a.k.a user generated. 

### Additional context

@lgrammel  have implemented this before for [modelfusion](https://github.com/lgrammel/modelfusion) 🤘

https://github.com/vercel/modelfusion/blob/9d99703dc7b60836992bf661cfc9698c8ee5976c/examples/basic/src/model-function/generate-object-unchecked-json-schema-example.ts#L2

Let me know if you guys need help.

**Comment by lgrammel** [comment]
Duplicates https://github.com/vercel/ai/issues/1062

**Comment by lgrammel** [comment]
implemented in #2386

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
Although the original report requests JSON Schema support without Zod, the maintainer classified this issue as a duplicate, making it primarily a duplicate bookkeeping item.

### Evidence
- Maintainer identified the request as a duplicate of issue #1062.
- A later maintainer comment states the capability was implemented in PR #2386.
