### ISSUE TITLE
`createStreamableValue()` in `initialUIState` causes infinite loading

### ISSUE THREAD

**Issue by ndrsfel** [vercel/ai#1477]
### Description

Hey all, using 

```javascript
const initialUIState: {
  isGenerating: StreamableValue<boolean>;
  itineraryComponent: React.ReactNode;
} = {
  isGenerating: createStreamableValue(false).value,
  itineraryComponent: null,
};
```
from the [stream-object](https://github.com/vercel/ai/blob/f3c3ea08f3a0e741ae80d3555d7f55979773707a/examples/next-ai-rsc/app/stream-object/generate-itinerary.tsx#L66) example leads to an infinite loading state in the browser waiting for GET request with URL `ws://localhost:3000/_next/webpack-hmr` to be finished loading.

The backend console log states
> The streamable UI has been slow to update. This may be a bug or a performance issue or you forgot to call `.done()`. 

Indeed, setting `isGenerating` to `false` as default value in the above example fixes the problem. However, streaming the generating state to the client-side is not working any more.

Anyone able to reproduce?

### Code example

```javascript
const initialUIState: {
  isGenerating: StreamableValue<boolean>;
  itineraryComponent: React.ReactNode;
} = {
  isGenerating: createStreamableValue(false).value,
  itineraryComponent: null,
};
```
from the [stream-object](https://github.com/vercel/ai/blob/f3c3ea08f3a0e741ae80d3555d7f55979773707a/examples/next-ai-rsc/app/stream-object/generate-itinerary.tsx#L66) example

### Additional context

My versions
```
Next.js 14.2.3
Node    20.11.0
ai      3.1.0
@ai-sdk/openai 0.0.9
```

**Comment by shuding** [comment]
Hey! Any `createStreamableValue` values need to be __closed__ at some point. For your use case I'd recommend doing this:

```js
const isGenerating = createStreamableValue(false)
isGenerating.done()

const initialUIState: {
  isGenerating: StreamableValue<boolean>;
  itineraryComponent: React.ReactNode;
} = {
  isGenerating: isGenerating.value,
  itineraryComponent: null,
};
```

In the future we can simplify this to the currying style like:

```js
createStreamableValue(false).done().value
```

**Comment by shuding** [comment]
https://github.com/vercel/ai/pull/1479 will be helpful here.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The SDK behavior is explained as requiring streamable values to be closed; the concrete problem is incorrect sample code in a repository example that omits `.done()`.

### Evidence
- The linked `stream-object` example initializes `initialUIState` with an open `createStreamableValue(false).value`, resulting in infinite loading.
- A maintainer clarified that every streamable value must be closed with `.done()` and provided corrected sample code.
- The maintainer linked PR #1479 as helpful for addressing the example.
