### ISSUE TITLE
streamObject works on local machines, but not when deployed to vercel (pro user)

### ISSUE THREAD

**Issue by threefoldo** [vercel/ai#1519]
### Description

Follow the code here: 
https://sdk.vercel.ai/examples/next-app/basics/streaming-object-generation

The app runs well on local machine, but no reponse and timedout after 15 seconds. Even though I changed the timeout, there is no server errors, but the execution is still terminated after 15 seconds and there is no output in the client components.

### Code example

'use server';

import { streamObject } from 'ai';
import { openai } from '@ai-sdk/openai';
import { createStreamableValue } from 'ai/rsc';
import { z } from 'zod';

export async function generate(input: string) {
  'use server';

  const stream = createStreamableValue();

  (async () => {
    const { partialObjectStream } = await streamObject({
      model: openai('gpt-4-turbo'),
      system: 'You generate three notifications for a messages app.',
      prompt: input,
      schema: z.object({
        notifications: z.array(
          z.object({
            name: z.string().describe('Name of a fictional person.'),
            message: z.string().describe('Do not use emojis or links.'),
            minutesAgo: z.number(),
          }),
        ),
      }),
    });

    for await (const partialObject of partialObjectStream) {
      stream.update(partialObject);
    }

    stream.done();
  })();

  return { object: stream.value };
}

### Additional context

same issue: https://github.com/orgs/vercel/discussions/6751

**Comment by lgrammel** [comment]
@threefoldo can you check if this solves the issue for you? https://sdk.vercel.ai/docs/troubleshooting/common-issues/streaming-not-working-in-production

**Comment by threefoldo** [comment]
Thanks for the advice. I add the code at the beginning of the page.tsx file, but it doesn't work.
```
"use client";

export const dynamic = 'force-dynamic';
```

The client component:
```
 // app/your-route/page.js

export const dynamic = 'force-dynamic';

import { someStreamingFunction } from './someStreamingFunction';

async function YourComponent() {
  const data = await someStreamingFunction();

  return (
    <div>
      {/* Your component JSX */}
    </div>
  );
}

export default YourComponent;
```

The server action:
```
// app/your-route/someStreamingFunction.js

export async function someStreamingFunction() {
  'use server';

  // Your server-side streaming logic here
  // ...

  return data;
}
```

 Do I need to wrap the server action in a POST API?

**Comment by lgrammel** [comment]
@threefoldo do you have a github repo with a reproduction that you could share?

**Comment by lionelrudaz** [comment]
I'm running into a similar situation, but not with streamObject, with streamText and when the tool generates the UI.

I have the following error:

```
7023-4c5b21469a654b50.js:1 TypeError: Cannot destructure property 'children' of 'e' as it is null.
    at l (4168-9753ef37215827ad.js:1:12099)
    at rE (fd9d1056-3a3acf3c4e3d999c.js:1:40344)
    at l$ (fd9d1056-3a3acf3c4e3d999c.js:1:59319)
    at iZ (fd9d1056-3a3acf3c4e3d999c.js:1:117682)
    at ia (fd9d1056-3a3acf3c4e3d999c.js:1:95165)
    at fd9d1056-3a3acf3c4e3d999c.js:1:94987
    at il (fd9d1056-3a3acf3c4e3d999c.js:1:94994)
    at oJ (fd9d1056-3a3acf3c4e3d999c.js:1:92350)
    at oZ (fd9d1056-3a3acf3c4e3d999c.js:1:91769)
    at MessagePort.T (7023-4c5b21469a654b50.js:1:84042)
﻿```

Here's a video showing the issue. It's reproduced on Preview and Production environments.

https://github.com/vercel/ai/assets/592678/53d65dd4-4db2-43eb-8b50-1591324e8171

I've checked and it looks like the component that's supposed to be injected into <BotCard> is null. But it works perfectly on local machine. 

I've added this in my page.tsx file:

```
export const dynamic = 'force-dynamic';
export const maxDuration = 60;
```

Doesn't work.

I've tried to add <></> as a default value of children for <BotCard>, doesn't work. I've tried to add a paragraph in addition to my component in <BotCard>, doesn't work. 

I've updated the `ai` library to 3.1.3 as well.

I have no idea what's wrong, it's really frustrating. Maybe this is connected to your problem, I don't know. If not, then I'll open a separate issue.

My actions.tsx file:

```
import 'server-only';

import {
  createAI,
  createStreamableUI,
  getMutableAIState,
  getAIState,
  createStreamableValue
} from 'ai/rsc';

import { openai } from '@ai-sdk/openai';
import WINE_MATCHING_PROMPT from 'lib/prompts/wineMatchExplanationAndSearch';
import { nanoid } from '../utils';
import { BotCard, BotMessage, SpinnerMessage, UserMessage } from '@/components/llm/Messages';
import WineSearchResultsCarrousel from '@/components/wine/WineSearchResultsCarrousel';
import { streamText } from 'ai';
import { searchWinesFilterSchema } from '@/interfaces/zodSchemas/searchWinesFilters';
import { searchWines } from 'app/actions/wines';
import { saveMatch } from 'app/actions/matches';

async function submitUserMessage(content: string) {
  'use server';
  //await rateLimit() // Rate limit the function to avoid abuse

  const aiState = getMutableAIState();

  aiState.update({
    ...aiState.get(),
    messages: [
      ...aiState.get().messages,
      {
        id: nanoid(),
        role: 'user',
        content: `${aiState.get().interactions.join('\n\n')}\n\n${content}`
      }
    ]
  })

  const matchId = aiState.get().matchId;

  const history = aiState.get().messages.map(message => ({
    role: message.role,
    content: message.content
  }))

  let textContent = ''
  let searchWinesArgs;
  let foundWines;

  const textStream = createStreamableValue('')
  const spinnerStream = createStreamableUI(<SpinnerMessage />)
  const messageStream = createStreamableUI(null)
  const uiStream = createStreamableUI()

  ;(async () => {
    try {
      const result = await streamText({
        //model: google.generativeAI('models/gemini-1.0-pro-001'),
        model: openai.chat("gpt-4-turbo"),
        temperature: 0,
        tools: {
          searchWines: {
            description: 'Search for wines with color, price range, grapes, country, region and appellation.',
            parameters: searchWinesFilterSchema,
            execute: async (args) => {
              console.log("Execute search wines", args);
              const streamResults = createStreamableValue<string>()
              const wines = await searchWines(args);
              foundWines = wines;
              uiStream.append(<WineSearchResultsCarrousel wines={wines} args={args} matchId={matchId} />)

              streamResults.done(JSON.stringify(wines))

              return wines;
            }
          },
        },
        system: WINE_MATCHING_PROMPT,
        messages: [...history]
      })

      spinnerStream.done(null)

      for await (const delta of result.fullStream) {
        const { type } = delta

        if (type === 'text-delta') {
          const { textDelta } = delta

          textContent += textDelta
          messageStream.update(<BotMessage>{textContent}</BotMessage>)
        } else if (type === 'tool-call') {
          console.log('Tool call:', delta)

          const { toolName, args } = delta

          if (toolName === 'searchWines') {
            console.log("Tool call search for wines", args);
            searchWinesArgs = args;

            uiStream.update(
              <BotCard>
                <WineSearchResultsCarrousel wines={[]} args={args} matchId={matchId} />
              </BotCard>
            )

            console.log('Search wines: completed');
          }
        }
      }

      console.log('AI done, update the message history', textContent, foundWines);
      const newMessages: Message[] = [];
      newMessages.push({
        id: nanoid(),
        role: 'assistant',
        content: textContent
      })

      if (searchWinesArgs) {
        newMessages.push({
          id: nanoid(),
          role: 'assistant',
          content:
            "Voilà le vin qui me paraît parfait pour toi.",
          display: {
            name: 'searchWines',
            props: {
              args: searchWinesArgs,
              wines: foundWines
            }
          }
        })
      }

      aiState.done({
        ...aiState.get(),
        interactions: [],
        messages: [
          ...aiState.get().messages,
          ...newMessages
        ]
      })

      uiStream.done()
      textStream.done()
      messageStream.done()
    } catch (e) {
      console.error(e)

      const error = new Error(
        'The AI got rate limited, please try again later.'
      )
      uiStream.error(error)
      textStream.error(error)
      messageStream.error(error)
      aiState.done({})
    }
  })()

  return {
    id: nanoid(),
    attachments: uiStream.value,
    spinner: spinnerStream.value,
    display: messageStream.value
  }
}

export type Message = {
  role: 'user' | 'assistant' | 'system' | 'function' | 'data' | 'tool'
  content: string
  id?: string
  name?: string
  display?: {
    name: string
    props: Record<string, any>
  }
}

export type AIState = {
  matchId: string
  interactions?: string[]
  messages: Message[]
}

export type UIState = {
  id: string
  display: React.ReactNode
  spinner?: React.ReactNode
  attachments?: React.ReactNode
}[]

export const AI = createAI<AIState, UIState>({
  actions: {
    submitUserMessage,
    // requestCode,
    // validateCode,
    // describeImage
  },
  initialUIState: [],
  initialAIState: { matchId: nanoid(), interactions: [], messages: [] },
  onGetUIState: async () => {
    'use server'

    const aiState = getAIState();

    if (aiState) {
      const uiState = getUIStateFromAIState(aiState)
      return uiState
    }
  },
  onSetAIState: async ({ state, done }) => {
    'use server'
    
    if (done) {
      
      const { matchId, messages } = state;
      const title = messages[0].content
      await saveMatch(matchId, title, messages);
    }
  }
})

export const getUIStateFromAIState = (aiState: AIState) => {
  return aiState.messages
    .filter(message => message.role !== 'system')
    .map((message, index) => ({
      id: `${message.id}`,
      content: message.content,
      display:
        message.role === 'assistant' ? (
          message.display?.name === 'searchWines' ? (
            <BotCard>
              <WineSearchResultsCarrousel wines={message.display.props.wines} args={message.display.props.args} matchId={aiState.matchId} />
            </BotCard>
          ) : message.display?.name === 'showSeatPicker' ? (
            <BotCard>
              <br />
            </BotCard>
          ) : (
            <BotMessage>{message.content}</BotMessage>
          )
        ) : message.role === 'user' ? (
          <UserMessage firstMessage={index===0}>{message.content}</UserMessage>
        ) : (
          <BotMessage>{message.content}</BotMessage>
        )
    }))
}
```

Let me know if this is helpful.

**Comment by lionelrudaz** [comment]
Solved the issue by adding "use client" to the component that's rendered in Generative UI and moving 

```
export const dynamic = 'force-dynamic';
export const maxDuration = 60;
```

To the very top of my page.tsx file.

I hope this helps.

**Comment by threefoldo** [comment]
I have added the two export directives and update "ai" to 3.1.3, but the streaming still doesn't work. It works perfect on local machine, but not on vercel.

Here is the code:
```
// page.tsx

"use client";

export const dynamic = 'force-dynamic';
export const maxDuration = 60;

...

const generateContent = async (user_prompt) => {
    console.log('generate lesson plan:\n', user_prompt);
    const { object } = await generate(user_prompt);
    for await (const partialObject of readStreamableValue(object)) {
      if (partialObject) {
        setContent((prev) => ({ ...prev, ...partialObject }));
      }
    }
  };

...

<OutputForm isLoading={isLoading} content={content} setContent={setContent} />

// action.tsx

'use server';

...

export default async function generate(prompt: string) {
  'use server';

  const system_prompt = prompts['system_template'];

  const stream = createStreamableValue();

  (async () => {
    const { partialObjectStream } = await streamObject({
        model: openai('gpt-4-turbo'),
        system: system_prompt,
        prompt: prompt,
        schema: z.object({
            standards: z.string().optional(),
        }),
    });

    for await (const partialObject of partialObjectStream) {
      stream.update(partialObject);
    }

    stream.done();
  })();

  return { object: stream.value };
}

```

**Comment by threefoldo** [comment]
> @threefoldo do you have a github repo with a reproduction that you could share?

I have posted the code below. If that doesn't solve the problem, I will try to create a new repo.

**Comment by threefoldo** [comment]
I tried this code, it's the same problem, streaming works on local env, but not on vercel.

with this line at the very top of the page.tsx:
```
export const dynamic = 'force-dynamic';
```

https://sdk.vercel.ai/examples/next-app/basics/streaming-object-generation#server

**Comment by valstu** [comment]
Facing the same problem, was getting 504 from the server action. Now I added following lines
```
export const dynamic = 'force-dynamic';
export const maxDuration = 300;
```
I don't 504 anymore but the streaming won't work, I just get the final response when it is done by LLM (GPT-4 in this case).

**Comment by valstu** [comment]
Okay, adding this to `layout.tsx`
```
export const dynamic = 'force-dynamic'
```
Seemed to work for me.

**Comment by threefoldo** [comment]
> Okay, adding this to `layout.tsx`
> 
> ```ts
> export const dynamic = 'force-dynamic'
> ```
> 
> Seemed to work for me.

That works for me, too, thank you very much.

**Comment by reveurguy** [comment]
I was getting the same issue with `streamText` and `createStreamableValue, readStreamableValue`.

Adding this solved the streaming not working on production issue:
`export const dynamic = 'force-dynamic'`
`export const maxDuration = 60;`

I added the above lines to `/layout.tsx` file.

But I am facing another issue, the generation is getting timed out after 10seconds. The output starts generating, and after a while it stops when the task is timed out.

I am using this code:
https://sdk.vercel.ai/examples/next-app/basics/streaming-text-generation


This is the log from vercel deployment:

<img width="643" alt="Screenshot 2024-05-20 at 1 07 05 PM" src="https://github.com/vercel/ai/assets/59417546/bbcd4087-db57-44c6-b4dd-5349eb4cd3d5">

This is the error on the frontend side:

<img width="450" alt="Screenshot 2024-05-20 at 1 07 59 PM" src="https://github.com/vercel/ai/assets/59417546/bd3f9724-cd79-4523-937a-2d4c604864f1">


Any idea how to solve this?

**Comment by lamepic** [comment]
Faced the same timeout Issue, but adding :
`
export const maxDuration = 60;
`
`
export const dynamic = 'force-dynamic'
`

to both `/layout.tsx` and `/page.tsx` seem to fix it for me.

**Comment by lamepic** [comment]
Faced the same timeout Issue, but adding :
export const maxDuration = 60;
export const dynamic = 'force-dynamic'

to both /layout.tsx and /page.tsx seem to fix it for me.

**Comment by lamepic** [comment]
> I was getting the same issue with `streamText` and `createStreamableValue, readStreamableValue`.
> 
> Adding this solved the streaming not working on production issue: `export const dynamic = 'force-dynamic'` `export const maxDuration = 60;`
> 
> I added the above lines to `/layout.tsx` file.
> 
> But I am facing another issue, the generation is getting timed out after 10seconds. The output starts generating, and after a while it stops when the task is timed out.
> 
> I am using this code: https://sdk.vercel.ai/examples/next-app/basics/streaming-text-generation
> 
> This is the log from vercel deployment:
> 
> <img alt="Screenshot 2024-05-20 at 1 07 05 PM" width="643" src="https://private-user-images.githubusercontent.com/59417546/331982535-bbcd4087-db57-44c6-b4dd-5349eb4cd3d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjkyNzUsIm5iZiI6MTcxNzI2ODk3NSwicGF0aCI6Ii81OTQxNzU0Ni8zMzE5ODI1MzUtYmJjZDQwODctZGI1Ny00NGM2LWI0ZGQtNTM0OWViNGNkM2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE5MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMWI2NjYwODBmN2Y4ZDVlMGU3YzkyYzZkYjVhMTVkYzk3YzY2MTA5MzJjMDgwYWQxYTBjYmNlODgyM2Q0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xsgxrJ8dRlCleF-tTcmsB8OFOmYxcdRNlWkm3R1cnjM">
> This is the error on the frontend side:
> 
> <img alt="Screenshot 2024-05-20 at 1 07 59 PM" width="450" src="https://private-user-images.githubusercontent.com/59417546/331982804-bd3f9724-cd79-4523-937a-2d4c604864f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNjkyNzUsIm5iZiI6MTcxNzI2ODk3NSwicGF0aCI6Ii81OTQxNzU0Ni8zMzE5ODI4MDQtYmQzZjk3MjQtY2Q3OS00NTIzLTkzN2EtMmQ0YzYwNDg2NGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE5MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNWQwMTliYzc4ZWEwNmU2YWU1M2Q0MzE2NDM0OThkOTg5OGQ3ODI5MjAxYWMwZGJiZDFjMjc5ZTEyNGZjMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iw8_VQ8QWx57aFobOwZ9z7lZbCe2gCsIWdZp24V4E8A">
> Any idea how to solve this?


Faced the same timeout Issue, but adding :
export const maxDuration = 60;
export const dynamic = 'force-dynamic'

to both /layout.tsx and /page.tsx seem to fix it for me.

**Comment by olegakbarov** [comment]
If you self-host and user rocket loader from Cloudflare try disabling it.
