### ISSUE TITLE
fail type inference at createStreamableValue

### ISSUE THREAD

**Issue by toy-crane** [vercel/ai#1526]
### Description

follow this example at vercel AI example
https://sdk.vercel.ai/examples/next-app/basics/streaming-object-generation#server
createStreamableValue doesnt inferred although using `stream.update(partialObject);`

### Code example

```
'use server';

import { streamObject } from 'ai';
import { openai } from '@ai-sdk/openai';
import { createStreamableValue } from 'ai/rsc';
import { z } from 'zod';

export async function generate(input: string) {
  'use server';

  const stream = createStreamableValue();

  (async () => {
    const { partialObjectStream } = await streamObject({
      model: openai('gpt-4-turbo'),
      system: 'You generate three notifications for a messages app.',
      prompt: input,
      schema: z.object({
        notifications: z.array(
          z.object({
            name: z.string().describe('Name of a fictional person.'),
            message: z.string().describe('Do not use emojis or links.'),
            minutesAgo: z.number(),
          }),
        ),
      }),
    });

    for await (const partialObject of partialObjectStream) {
      stream.update(partialObject);
    }

    stream.done();
  })();

  return { object: stream.value };
}
```
### Additional context

how can I fix this problem?
are there anyone have same problem??

**Comment by lgrammel** [comment]
Can you provide the full error message?

**Comment by toy-crane** [comment]
```
(property) value: StreamableValue<any, any>
The value of the streamable. This can be returned from a Server Action and received by the client. To read the streamed values, use the readStreamableValue or useStreamableValue APIs.
```
there are no errors
The value is not just inferred instead of any.

**Comment by shuding** [comment]
Yeah `createStreamableValue()` can't infer its data type if data is set later with a `.update()` in a new clousure. I'm not sure if that's possible with TypeScript ([example](https://www.typescriptlang.org/play/?#code/DYUwLgBAzgUDDcAKAhlAngOwMYUQSggF4A+CAbxgmiIgEYYBfPfOK6GAeg4gD0B+IA)).

Only `createStreamableValue<T>()` and `createStreamableValue(data)` have the data type.

Let me know if you have other questions!

**Comment by yashkelhe** [comment]
I am encountering an issue when trying to import createStreamableValue from the ai/rsc module in my project. The export createStreamableValue does not exist in the module, as confirmed by the error and my console logs.

Export createStreamableValue doesn't exist in target module
  3 | import { streamText } from "ai";
  4 | // import { createStreamableValue } from "ai/rsc";
> 5 | import { createStreamableValue } from "ai/rsc";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  6 | import { createGoogleGenerativeAI } from "@ai-sdk/google";
  7 | import { generateEmbedding } from "@/lib/gemini";
  8 | import { db } from "@/server/db";

The export createStreamableValue was not found in module [project]/node_modules/ai/rsc/dist/rsc-client.mjs [app-client] (ecmascript) <exports>.
Did you mean to import readStreamableValue?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.



After logging the module exports, I found the following functions are available in ai/rsc: 
Module {
  readStreamableValue: [Function: readStreamableValue],
  useAIState: [Function: useAIState],
  useActions: [Function: useActions],
  useStreamableValue: [Function: useStreamableValue],
  useSyncUIState: [Function: useSyncUIState],
  useUIState: [Function: useUIState],
}


can anyone tell me how i can resolve this issue

**Comment by mirhadiseyidli** [comment]
> I am encountering an issue when trying to import createStreamableValue from the ai/rsc module in my project. The export createStreamableValue does not exist in the module, as confirmed by the error and my console logs.
> 
> Export createStreamableValue doesn't exist in target module 3 | import { streamText } from "ai"; 4 | // import { createStreamableValue } from "ai/rsc";
> 
> > 5 | import { createStreamableValue } from "ai/rsc";
> > | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > 6 | import { createGoogleGenerativeAI } from "@ai-sdk/google";
> > 7 | import { generateEmbedding } from "@/lib/gemini";
> > 8 | import { db } from "@/server/db";
> 
> The export createStreamableValue was not found in module [project]/node_modules/ai/rsc/dist/rsc-client.mjs [app-client] (ecmascript) . Did you mean to import readStreamableValue? All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
> 
> After logging the module exports, I found the following functions are available in ai/rsc: Module { readStreamableValue: [Function: readStreamableValue], useAIState: [Function: useAIState], useActions: [Function: useActions], useStreamableValue: [Function: useStreamableValue], useSyncUIState: [Function: useSyncUIState], useUIState: [Function: useUIState], }
> 
> can anyone tell me how i can resolve this issue

hey @yashkelhe, I know it's been a while but have you found a solution to this? I'm getting the same error

**Comment by OptivusSaswat** [comment]
> > I am encountering an issue when trying to import createStreamableValue from the ai/rsc module in my project. The export createStreamableValue does not exist in the module, as confirmed by the error and my console logs.
> > Export createStreamableValue doesn't exist in target module 3 | import { streamText } from "ai"; 4 | // import { createStreamableValue } from "ai/rsc";
> > > 5 | import { createStreamableValue } from "ai/rsc";
> > > | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > 6 | import { createGoogleGenerativeAI } from "@ai-sdk/google";
> > > 7 | import { generateEmbedding } from "@/lib/gemini";
> > > 8 | import { db } from "@/server/db";
> > 
> > 
> > The export createStreamableValue was not found in module [project]/node_modules/ai/rsc/dist/rsc-client.mjs [app-client] (ecmascript) . Did you mean to import readStreamableValue? All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
> > After logging the module exports, I found the following functions are available in ai/rsc: Module { readStreamableValue: [Function: readStreamableValue], useAIState: [Function: useAIState], useActions: [Function: useActions], useStreamableValue: [Function: useStreamableValue], useSyncUIState: [Function: useSyncUIState], useUIState: [Function: useUIState], }
> > can anyone tell me how i can resolve this issue
> 
> hey [@yashkelhe](https://github.com/yashkelhe), I know it's been a while but have you found a solution to this? I'm getting the same error

hey @mirhadiseyidli I went through Vercel AI SDK official docs. As 2025 in order to use createStreamableValue you need to install the   Vercel AI SDK's react server components package separately which in v4 was getting installed by default. So just run `bun install @ai-sdk/rsc` and that should solve the issue. Note* if you are using npm just replace "bun" with "npm"

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage and TypeScript inference question rather than a failure of promised SDK behavior or a concrete request to change the API.

### Evidence
- The reporter confirms there is no runtime or TypeScript error; the returned value is typed as `StreamableValue<any, any>`.
- A maintainer explains that TypeScript cannot infer the type from a later `.update()` in another closure and recommends `createStreamableValue<T>()` or passing initial data.
- Later comments concern a separate import/setup problem resolved by installing `@ai-sdk/rsc`.
