### ISSUE TITLE
Client side not working Next:JS

### ISSUE THREAD

**Issue by thareekanvarm** [vercel/ai#1538]
### Description

Hi ,

I am using latest vercel ai . but the main issue is like when im upgrading this vercel ai app function call is not working from client side .its only working on server side . im using somany function call which is depended with some cookies .how can i make it works on client side ?

im using nextJS

### Code example

const {
    messages,
    input,
    handleInputChange,
    setMessages,
    append,
    handleSubmit,
    reload,
    isLoading,
    stop,
  } = useChat({
    api: "/api/chat",
    experimental_onFunctionCall: functionCalls,
    initialMessages: initialMessages,
  });

### Additional context

dependencies:
- ai 2.2.34
+ ai 3.0.35
- openai 4.27.0
+ openai 4.39.0

**Comment by lgrammel** [comment]
Why do you have 2 versions of the AI SDK in your dependencies? Ideally it would be the same version on both ends, e.g. `3.1.3`. With the latest AI SDK, you can find an example here:

https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot

**Comment by lgrammel** [comment]
Can you share your route code? In general, it is not recommended to call OpenAI from the client, because you would expose your OpenAI key to anybody using your application.

**Comment by thareekanvarm** [comment]
import {
  OpenAIStream,
  StreamingTextResponse,
  Tool,
  ToolCallPayload,
  StreamData,
} from "ai";
import { functionCalls } from "functions";
import OpenAI from "openai";

const endpoint = `https://${process.env.AZURE_OPENAI_API_INSTANCE_NAME}.openai.azure.com`;

export const aiConfig = {
  apiKey: process.env.AZURE_OPENAI_API_KEY,
  baseURL: `${endpoint}/openai/deployments/${process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME}`,
  defaultQuery: { "api-version": process.env.AZURE_OPENAI_API_VERSION },
  defaultHeaders: { "api-key": process.env.AZURE_OPENAI_API_KEY },
};

const openai = new OpenAI(aiConfig);

export const config = {
  runtime: "edge",
};

export const dynamic = "force-dynamic";

`export default async function POST(req) {
  const { messages }: { messages: any[] } = await req.json();

  // Set the number of messages to send  const maxNumMessagesToSend = 20;
  // Get the last `numMessagesToSend` messages  const lastMessages = messages.slice(-maxNumMessagesToSend);

  console.log(messages);

  const response = await openai.chat.completions.create({
    model: process.env.AZURE_OPENAI_API_MODEL_NAME,
    stream: true,
    //@ts-ignore
    messages: [...messages],
    temperature: 0.3,
    n: 1,
    // max_tokens: 1000,
    // function_call: "auto",
    // functions,
    tools: functions,
    tool_choice: "auto",
  });

  const data = new StreamData();
  const stream = OpenAIStream(response, {
    experimental_onToolCall: async (
      call: ToolCallPayload,
      appendToolCallMessage
    ) => {
      for (const toolCall of call.tools) {
        // Note: this is a very simple example of a tool call handler
        // that only supports a single tool call function.
        console.log(toolCall);

        const newMessages = appendToolCallMessage({
          tool_call_id: toolCall.id,
          function_name: toolCall.func.name,
          tool_call_result: await functionCalls(messages, toolCall),
        });

        // const newMessages = await functionCalls(messages, toolCall);

        return openai.chat.completions.create({
          messages: [...messages, ...newMessages],
          model: process.env.AZURE_OPENAI_API_MODEL_NAME,
          stream: true,
          tools: functions,
          tool_choice: "auto",
        });
      }
    },
    onCompletion(completion) {
      console.log("completion", completion);
    },
    onFinal(completion) {
      data.close();
    },
  });

  data.append({
    text: "Hello, how are you?",
  });

  return new StreamingTextResponse(stream);
}

const functions: any = [{
    type: "function",
    function: {
      name: "get_product_my_offers_in_market",
      description:
        "Retrieve the user's offers in the market for a specific product.",
      parameters: {
        type: "object",
        properties: {
          ean: {
            type: "string",
            description: "The ean code of the product.",
          },
          state: {
            type: "string",
            enum: ["new", "used", "refurbished"],
            description:
              "Allows the user to get data only for a specific state or list of states, or all states.",
          },
          price: {
            type: "string",
            description: "Total price of the product",
          },
        },
        required: ["ean", "price", "state"],
      },
    },
  },]
`

**Comment by thareekanvarm** [comment]
really i dont want to use " experimental_onToolCall " on server side .. i want to use that on client side . can u help me on that .because im using some cookies

**Comment by thareekanvarm** [comment]
![image](https://github.com/vercel/ai/assets/117096530/83e6fd36-bd33-4cfd-b6f5-ea303488a324)

if i remove "experimental_onToolCall" from server side this is the message im getting .

**Comment by thareekanvarm** [comment]
thanks for ur response 

This was my issue 

https://sdk.vercel.ai/docs/troubleshooting/common-issues/client-side-function-calls-not-invoked

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a configuration/support question resolved by existing troubleshooting guidance, not a confirmed failure of promised SDK behavior.

### Evidence
- The reporter asks how to configure client-side function calls after upgrading from AI SDK 2.2.34 to 3.0.35.
- A maintainer requests missing route code and explains that direct client-side OpenAI calls are not recommended.
- The reporter ultimately identifies the relevant troubleshooting guide for client-side function calls, without establishing an SDK defect.
