### ISSUE TITLE
Google Vertex AI provider

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#1542]
### Feature Description

I would like there to be an example of using ai/rsc streamUI with vertex ai.

### Use Case

The situation arises if I am not allowed to use google ai, but instead must use VertexAI,

**Comment by lgrammel** [comment]
There is currently no vertex provider. You could implement a Google Vertex provider using the custom provider approach: https://sdk.vercel.ai/providers/community-providers/custom-providers

**Comment by coolxeo** [comment]
Any plans implementing that?

**Comment by lgrammel** [comment]
https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex

**Comment by coolxeo** [comment]
thanks @lgrammel this is great!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
Although initially phrased as a request for an example, the underlying need was new Google Vertex AI provider support, which was subsequently implemented.

### Evidence
- The requested Vertex AI integration did not exist at the time; the maintainer stated, “There is currently no vertex provider.”
- The reporter followed up by asking whether there were plans to implement it.
- A maintainer later linked the Vertex AI provider implementation PR and provider documentation.
