### ISSUE TITLE
"You uploaded an unsupported image" when trying to streamText with image data

### ISSUE THREAD

**Issue by lucasishuman** [vercel/ai#1544]
### Description

When I attempt to stream a text response from OpenAI and image data is present in the outgoing messages, I get an error. (see below for code sample)

Model is `gpt-4-turbo`

I'm confident it is a valid image format and under size limit.

I see the same behavior whether the image content is a URL or base64 encoded string.

Error:

```
web-app:dev:  ⨯ Error [AI_APICallError]: You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp'].
web-app:dev:     at eval (webpack-internal:///(rsc)/../../node_modules/@ai-sdk/provider-utils/dist/index.mjs:324:14)
web-app:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web-app:dev:     at async postToApi (webpack-internal:///(rsc)/../../node_modules/@ai-sdk/provider-utils/dist/index.mjs:231:28)
web-app:dev:     at async OpenAIChatLanguageModel.doStream (webpack-internal:///(rsc)/../../node_modules/@ai-sdk/openai/dist/index.mjs:277:50)
web-app:dev:     at async _retryWithExponentialBackoff (webpack-internal:///(rsc)/../../node_modules/ai/dist/index.mjs:369:12)
web-app:dev:     at async streamText (webpack-internal:///(rsc)/../../node_modules/ai/dist/index.mjs:1432:45)
web-app:dev:     at async POST (webpack-internal:///(rsc)/./src/app/api/chat/route.ts:40:20)
web-app:dev:     at async eval (webpack-internal:///(rsc)/../../node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:238:37)
web-app:dev:     at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/../../node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:153:26)
web-app:dev:     at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/../../node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:300:30)
```

I'm using:
* next: 14.2.3 (app router)
* ai: 3.1.3
* @ai-sdk/openai: 0.0.10

### Code example

Example user messages with image data included

```js
const messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "What’s in this image?"
            },
            {
                "type": "image",
                "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgEASABIAAD/2wCEA..."
            }
        ]
    }
]
```

```js
const messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "What’s in this image?"
            },
            {
                "type": "image",
                "image": "https://static01.nyt.com/images/2024/05/12/business/12Roose-AIFriends..."
            }
        ]
    }
]
```

Local API route

```js
import { StreamingTextResponse, streamText } from 'ai';
import { openai } from '@ai-sdk/openai';

export const runtime = 'edge';

export async function POST(req: Request) {
  const {
    messages,
    model = 'gpt-4-turbo',
  } = await req.json();

  const result = await streamText({
    messages,
    model: openai(model),
  });

  return new StreamingTextResponse(result.toAIStream());
}
```

Server returns error

```
web-app:dev:  ⨯ Error [AI_APICallError]: You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp'].
web-app:dev:     at eval (webpack-internal:///(rsc)/../../node_modules/@ai-sdk/provider-utils/dist/index.mjs:324:14)
web-app:dev:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web-app:dev:     at async postToApi (webpack-internal:///(rsc)/../../node_modules/@ai-sdk/provider-utils/dist/index.mjs:231:28)
web-app:dev:     at async OpenAIChatLanguageModel.doStream (webpack-internal:///(rsc)/../../node_modules/@ai-sdk/openai/dist/index.mjs:277:50)
web-app:dev:     at async _retryWithExponentialBackoff (webpack-internal:///(rsc)/../../node_modules/ai/dist/index.mjs:369:12)
web-app:dev:     at async streamText (webpack-internal:///(rsc)/../../node_modules/ai/dist/index.mjs:1432:45)
web-app:dev:     at async POST (webpack-internal:///(rsc)/./src/app/api/chat/route.ts:40:20)
web-app:dev:     at async eval (webpack-internal:///(rsc)/../../node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:238:37)
web-app:dev:     at async AppRouteRouteModule.execute (webpack-internal:///(rsc)/../../node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:153:26)
web-app:dev:     at async AppRouteRouteModule.handle (webpack-internal:///(rsc)/../../node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:300:30)
```

**Comment by lgrammel** [comment]
The error comes from the OpenAI API. Can you test whether you also receive it when using the OpenAI fetch API directly?

**Comment by lucasishuman** [comment]
When I use the OpenAI SDK directly (as shown below) - I get a valid response from OpenAI.

**Note** - I need to change the `message` > `content` > `image` props to match OpenAI's message schema - **maybe there is an issue mapping AI SDK image props to OpenAI image props in the AI SDK?**

Using
`"openai": "4.44.0"`

Sent message (using OpenAI message schema)

```js
    const messages = [
    {
      role: 'user',
      content: [
        {
          type: 'text',
          text: 'What is in this image',
        },
        {
          type: 'image_url',
          image_url: {
            url: 'https://static01.nyt.com/images/2024/05/12/.....',
          },
        },
      ],
    }
];
```

Route handler

```js
import OpenAI from "openai";

export async function POST(req: Request) {
  const { messages } = await req.json();

  const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
  });

  const response = await openai.chat.completions.create({
    model = 'gpt-4-turbo',
    messages,
  });

  console.log(response.choices[0]);
}
```

I feel like I must be missing something very obvious if no one else sees this behavior - but I also don't see an example in the AI SDK for messages with image content.

My `OPENAI_API_KEY` is in my env file and is valid.

**Comment by lucasishuman** [comment]
Maybe worth also noting is that client-side I am using the `useChat` hook, manually constructing the user message with image data/URL shown in original post, and then using `append` to send it to my app API.

**Comment by lucasishuman** [comment]
This is related to #1555 because when I remove the `data:image/jpeg;base64,` from the beginning of my base64 encoded image data string, I get a valid response.

However, when I pass a URL I still get an error.

So part of the fix may be just a matter of providing better documentation for messages with image content, but there's still something funky when sending an image URL.

**Comment by lucasishuman** [comment]
You can use any valid image URL to test, such as...

```js
const result = await streamText({
    messages: [{
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "What’s in this image?"
            },
            {
                "type": "image",
                "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
    }],
    model: openai('gpt-4-turbo'),
  });


```

**Comment by lgrammel** [comment]
@lucasishuman try using a URL

```ts
image: new URL('https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg')
```

See [examples/ai-core/src/generate-text/openai-multimodal-url.ts](https://github.com/vercel/ai/blob/main/examples/ai-core/src/generate-text/openai-multimodal-url.ts) for a full example

**Comment by lucasishuman** [comment]
@lgrammel - Great, thanks. That was the missing info I needed.

I feel like adding the image data and image URL examples to the AI SDK docs would be helpful.

You can close this issue.

**Comment by OrkhanGG** [comment]
I get the error "UnsupportedFunctionalityError [AI_UnsupportedFunctionalityError]: 'URL image parts' functionality not supported." when I use the following code:

`content: [
    { type: 'text', text: 'Describe the image in detail.' },
    {
        type: 'image',
        image: new URL(
            'https://github.com/vercel/ai/blob/main/examples/ai-core/data/comic-cat.png?raw=true',
        ),
    },
],
`

However, the same issue does not occur when I use base64; it works fine. Does anyone know why? I am using the Gemini 1.5 Pro model.

**Comment by lgrammel** [comment]
@OrkhanGG not all models support image urls (i think only openai does at this point). we'll add support for it, feel free to file a bug for the model provider / image urls.

**Comment by BenjDrury** [comment]
Having a similar issue.

When I use the /v1/chat/completions api as such:

{
    "model": "gpt-4o",
    "messages": [{
        "role": "user",
        "content": [{
            "type": "text",
            "text":"These are frames from a video that I want to upload. Generate a compelling description that I can upload along with the video."
            }, {
                "type": "image_url",
                "image_url": {
                    "url": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD//gAPTGF2Y..."
                    }
           }],
       }]
 }  
                    
 I get this back:

{
    "error": {
        "message": "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp'].",
        "type": "invalid_request_error",
        "param": null,
        "code": "image_parse_error"
    }
}

But only for some of the frames. I can take each of the base64 string I generate from a video and can look at them in a broswer with this: data:image/jpeg;base64,.... they are all valid and the same format, yet some arent accepted by openai

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The reported OpenAI failure was caused by undocumented or unclear input formatting rather than broken SDK behavior; the reporter’s requested outcome was improved documentation for base64 and URL image messages.

### Evidence
- Maintainer clarified that remote images must be passed as `image: new URL(...)`, with an existing runnable example.
- Reporter confirmed that using `URL` resolved the problem and said the missing information should be added to the AI SDK documentation.
- The later Gemini URL-support report was identified as provider-specific and directed to a separate issue.
