### ISSUE TITLE
`experimental_onToolCall` callback is not triggered but the `tool_calls` correctly streamed

### ISSUE THREAD

**Issue by younes101020** [vercel/ai#1548]
### Description

I've defined tools with only one function and i want to handle the function client side, everything works great except for the `experimental_onToolCall` which is not triggered when the function is called but the message streamed the `tool_calls` correctly note that it's the role `assistant` who streams it instead of `tool`.

### Code example

```
// When tool is streamed this callback is not triggered

const toolCallHandler: ToolCallHandler = async (chatMessages, toolCalls) => {
    console.log(toolCalls, "toolcalls");
    for (const tool of toolCalls) {
      if (tool.type === "function") {
        const { name, arguments: args } = tool.function;
        if (name === "write_ad") {
          // Parsing here does not always work since it seems that some characters in generated code aren't escaped properly.
          const parsedFunctionCallArguments: { code: string } =
            JSON.parse(args);
          const result = parsedFunctionCallArguments.code;
          console.log(result)
        }
      }
    }
  };

  const {
    messages,
    append,
    isLoading,
    handleSubmit: handleChatSubmit,
    input,
    handleInputChange,
  } = useChat({
    api: "/api/upload_gpt4v",
    experimental_onToolCall: toolCallHandler,
    body: {
      img: preview,
    },
    onFinish: () => setLoad(false),
  });

// But the tool is correctly streamed
...
      <ul>
        {messages!
          .filter((m) => m.role === "assistant" || m.role === "tool")
          .map((m, index) => (
            <li key={index}>
              {"assistant: "}
              {m.content}
            </li>
          ))}
        {isLoading && <Skeleton className="h-8 w-[60%]" />}
      </ul>
...
```
### Additional context

used model: gpt-4-turbo

**Comment by younes101020** [comment]
if anyone encounters the same error as me here's what might help you: https://sdk.vercel.ai/docs/troubleshooting/common-issues/client-side-function-calls-not-invoked

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes a concrete failure of an existing callback while the corresponding tool-call data is successfully streamed, so it is best classified as a bug.

### Evidence
- The reporter states that `useChat` receives and streams the `tool_calls`, but its existing `experimental_onToolCall` callback is never invoked.
- The behavior occurs with a defined client-side tool handler using `gpt-4-turbo`.
- A follow-up links to troubleshooting guidance, but does not reframe the report as a documentation request.
