### ISSUE TITLE
Ability to set defaultHeaders with OpenRouter

### ISSUE THREAD

**Issue by gouku** [vercel/ai#1576]
### Feature Description

It's possible to set extra headers with `openai` official sdk:

```ts
import OpenAI from "openai"

const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: $OPENROUTER_API_KEY,
  defaultHeaders: {
    "HTTP-Referer": $YOUR_SITE_URL, // Optional, for including your app on openrouter.ai rankings.
    "X-Title": $YOUR_SITE_NAME, // Optional. Shows in rankings on openrouter.ai.
  },
})
```

but it's not possible with `@ai-sdk/openai`:

```ts
import { OpenAI } from '@ai-sdk/openai'

const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: $OPENROUTER_API_KEY,
  defaultHeaders: {
    "HTTP-Referer": $YOUR_SITE_URL, // Optional, for including your app on openrouter.ai rankings.
    "X-Title": $YOUR_SITE_NAME, // Optional. Shows in rankings on openrouter.ai.
  }  
})
```

Got the following error:

```
Object literal may only specify known properties, and 'defaultHeaders' does not exist in type '{ baseURL?: string | undefined; baseUrl?: string | undefined; apiKey?: string | undefined; organization?: string | undefined; }'.ts(2353)
```

**Comment by lgrammel** [comment]
You can set custom headers using the `headers` setting.

```ts
import { createOpenAI } from '@ai-sdk/openai';

const openai = createOpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
  headers: {
    'X-My-Header': 'something',
  },
});
```

See also: https://sdk.vercel.ai/providers/ai-sdk-providers/openai

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question resolved by the existing `headers` configuration, not a product defect or request for a missing capability.

### Evidence
- The reporter asks for OpenAI SDK-style `defaultHeaders` support after receiving a TypeScript error for that unrecognized option.
- A maintainer explains that custom headers are already supported through the `headers` setting on `createOpenAI` and provides working code and documentation.
