### ISSUE TITLE
Make streaming work with langchain agents

### ISSUE THREAD

**Issue by Royal-lobster** [vercel/ai#158]
Is it possible to make streaming work with agents ? I am looking for a solution to stream intermediate steps and answer so users can see the tool selection process from UI along with streaming answer at end. 

This is the code i am using on backend

```ts
//...imports
export const runtime = "edge";

export const POST = async (req: Request) => {
  const { prompt, debugOptions } = generateInputSchema.parse(await req.json());
  const patchedOptions = { ...config.defaultDebugOptions, ...debugOptions };
  const { stream, handlers } = LangChainStream();

  const model = new ChatOpenAI({
    temperature: 0,
    openAIApiKey: env.OPENAI_API_KEY,
    modelName: "gpt-4-0613",
    callbackManager: CallbackManager.fromHandlers(handlers),
    streaming: true,
  });

  const tools = getTools(patchedOptions);

  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: "openai-functions",
    maxIterations: 10,
    returnIntermediateSteps: true,
  });

  await executor.call({ input: prompt }).finally(() => {
    handlers.handleChainEnd();
  });
  
  return new StreamingTextResponse(stream);
};

```

The stream for this is only giving full final answer at the end instead of letter by letter for me with useCompletion hook.

**Comment by CarlosZiegler** [comment]
Hey, I think this is the same topic as : #80

**Comment by Royal-lobster** [comment]
> Hey, I think this is the same topic as : #80

Oh true, but i think this one is on more integration with langchain agents. i can see the the demo from https://github.com/vercel-labs/ai/issues/80#issuecomment-1593984202 also facing the same issue as mine under functions which is giving out blocking answer at the end instead of streaming effect

**Comment by CarlosZiegler** [comment]
Yeap, I opened a PR to integrate axios but was closed, here is the explanation:

https://github.com/vercel-labs/ai/pull/140

**Comment by Royal-lobster** [comment]
> Yeap, I opened a PR to integrate axios but was closed, here is the explanation:
> 
> #140

I see ! Hopefully we get the update soon. will be waiting for it until then

**Comment by Zakinator123** [comment]
This PR probably solves your issue: #154

**Comment by e-roy** [comment]
I was able to get streaming working for langchain agents [here](https://github.com/e-roy/openai-functions-with-langchain/blob/main/src/app/api/news-langchain/route.ts)

**Comment by Adebesin-Cell** [comment]
> I was able to get streaming working for langchain agents [here](https://github.com/e-roy/openai-functions-with-langchain/blob/main/src/app/api/news-langchain/route.ts)

I ran the code but it doesn't work. I tesetd both routes ``news-langchain`` and ``news-openai``.

<img width="1437" alt="Screen Shot 2023-06-20 at 7 19 00 AM" src="https://github.com/vercel-labs/ai/assets/66301634/e327b339-db44-4d02-b2c8-54b451d9da15">

**Comment by e-roy** [comment]
@Adebesin-Cell that's odd, I don't see an error for no api key, the only thing I can think of is maybe it's timing out for you?

I deployed to vercel to test [https://openai-functions-with-langchain.vercel.app/](https://openai-functions-with-langchain.vercel.app/) and it seems to work fine with entering "latest on spacex" for an input.

my code could probably improve a bit, I was more focused on getting it to work

**Comment by AuYuHui2** [comment]
I have encountered the same problem, how can I solve it

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily an integration/support question about configuring LangChain agents and streaming. The available discussion does not establish that existing documented AI SDK behavior is broken.

### Evidence
- The reporter asks whether streaming LangChain agent intermediate steps and the final answer is possible.
- Their current code returns only the complete final answer instead of token-by-token output.
- Comments point to related PRs and external implementations, but no maintainer confirms an AI SDK defect.
