### ISSUE TITLE
chunkToText in OpenAIStream is mishandling tool_calls

### ISSUE THREAD

**Issue by doowb** [vercel/ai#1608]
### Description

When using the `experimental_onToolCall` callback with `OpenAIStream`, I am consistently receiving a JSON parsing error.
I tracked it down to how the [chunkToText](https://github.com/vercel/ai/blob/163fb6633cf05cc3861ceee8b9cc6a06ea842cab/packages/core/streams/openai-stream.ts#L359-L368) function is handling the `finish_reason`.

The `else if` highlighted above is `true` when the `finish_reason` is `'stop'`, which is what is being returned for `tool_calls`. The JSON value is incorrect and the `tool_calls` array is not being closed properly.

### Code example

```ts
import OpenAI from 'openai';
import { OpenAIStream, StreamingTextResponse } from 'ai';

// some request handler function
const handler = async () => {
  const openai = new OpenAI();
  const options = {
    messages: [/* some messages */],
    tools: [/* some tools */]
  };
  
  const response = await openai.chat.completions.create(options);
  const stream = OpenAIStream(response, {
    experimental_onToolCall: async (payload, append) => {
      console.log(payload);
      return 'Thinking...';
    }
  });
  
  return new StreamingTextResponse(stream);
}; 
```

### Additional context

I tried setting a `type` variable when the response string is being created for either the `function_call` or the `tool_calls`, then I used that in the `else if` expressions to determine how the response string should be closed and that worked.

Are you excepting PRs for this?

**Comment by lgrammel** [comment]
Thanks for investigating. It's hard to tell for me how involved and risky the fix is without seeing it. That code area is fairly complex.

Please note that the `OpenAIStream` approach with `onToolCall` is outdated and we recommend using AI SDK Core now:
https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling

**Comment by doowb** [comment]
Thanks for the quick response. I noticed in the docs that `OpenAIStream` isn't mentioned as much, so I started looking for what replaced it. I was hoping for a similar decoupling of making the request to the "provider" and parsing the stream.

I'm going to close this, but if I make a fix, I'll submit a PR.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing `OpenAIStream` tool-call parsing behavior, despite the API now being outdated and the issue being closed by the reporter.

### Evidence
- Using `experimental_onToolCall` with `OpenAIStream` consistently produces a JSON parsing error.
- The report traces the failure to `chunkToText` incorrectly handling `finish_reason: "stop"`, leaving the `tool_calls` array improperly closed.
- The maintainer notes that this API is outdated but does not dispute the reported failure.
