### ISSUE TITLE
LangChainAdapter does not support `StringOutParser`

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [vercel/ai#1662]
### Description

return new StreamingTextResponse(LangChainAdapter.toAIStream(stream))

Unable to support

### Code example

```
  const documentChain = await createStuffDocumentsChain({
      llm,
      prompt: questionAnsweringPrompt,
      outputParser: new StringOutputParser()
    });
 const stream = await documentChain.stream({
      context: documents,
    })
// error!
    return new StreamingTextResponse(LangChainAdapter.toAIStream(stream))```


### Additional context

_No response_

**Comment by htxqteam1** [comment]
having somewhat of the same issue. im using retriever chain to stream back but LangChainAdapter.toAIStream() but Type 'ReadableStreamDefaultReader<{ context: Document<Record<string, any>>[]; answer: string; } & { [key: string]: unknown; }>' is not assignable to type 'ReadableStreamDefaultReader<LangChainAIMessageChunk>'.
        Property 'content' is missing in type '{ context: Document<Record<string, any>>[]; answer: string; } & { [key: string]: unknown; }' but required in type 'LangChainAIMessageChunk'.
        
code: 
// Invoke the chain and stream response back
    s = await retrieverChain.stream({
      chat_history: latestKBufferWindow,
      input: currentMessageContent,
      case_id: caseId,
    });
  }

  const aiStream = LangChainAdapter.toAIStream(s);

  return new StreamingTextResponse(aiStream);

**Comment by donholly** [comment]
Same issue: 

![image](https://github.com/vercel/ai/assets/291077/e4b28d97-4b8d-416b-94fa-3c4b2a68475f)


```
  const questionAnsweringPrompt = ChatPromptTemplate.fromMessages([
    ['system', SYSTEM_TEMPLATE],
    new MessagesPlaceholder('messages')
  ])

  const documentChain = await createStuffDocumentsChain({
    llm,
    prompt: questionAnsweringPrompt
  })

  const stream = await documentChain.stream({
    messages: [new HumanMessage(query)],
    context: docs
  })

  const aiStream = LangChainAdapter.toAIStream(stream)
```

error: 

```
Argument of type 'IterableReadableStream<string>' is not assignable to parameter of type 'ReadableStream<LangChainAIMessageChunk>'.
  The types returned by 'getReader()' are incompatible between these types.
    Type 'ReadableStreamDefaultReader<string>' is not assignable to type 'ReadableStreamDefaultReader<LangChainAIMessageChunk>'.
      Type 'string' is not assignable to type 'LangChainAIMessageChunk'.ts(2345)
```

**Comment by lgrammel** [comment]
You type seems to be a raw string stream. Can you try passing it into `StreamingTextResponse` like this:

```
return new StreamingTextResponse(readableStream);
```

If you use `useChat` on the client, you can enable `streamMode: 'text'`.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1826

**Comment by lgrammel** [comment]
Supported in `v3.1.26+`: https://sdk.vercel.ai/docs/reference/stream-helpers/langchain-adapter#convert-stringoutputparser-stream

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete unsupported/failing adapter behavior in the existing API, subsequently fixed by adding StringOutputParser stream support.

### Evidence
- LangChainAdapter.toAIStream rejected LangChain streams produced by StringOutputParser because it only accepted LangChainAIMessageChunk streams.
- Multiple reporters reproduced TypeScript incompatibility errors when passing string or retriever-chain streams to the adapter.
- A maintainer linked the implementing PR and confirmed support was added in v3.1.26+.
