### ISSUE TITLE
Prompt gets added as first message in messages array and looses its attention

### ISSUE THREAD

**Issue by themataleao** [vercel/ai#1682]
### Description

Give the model a prompt through the `system` prop in `streamUI` for example, you speak only English.

Post 10 messages.

Switch the language to French.

The AI will often still speak English to you even though its set to french.

The problem is inherently given if the system prompt is the first message in the array sent to the API, the AI will lose its attention to the things earlier in the conversation. Instead, the system prompt should be the last message in the array.

### Code example

```
  const result = await streamUI({
    model: openai('gpt-3.5-turbo'),
    initial: <SpinnerMessage />,
    system: "You are a chatbot and you only speak English to the user"})
```

I am able to resolve the issue with the new `streamUI` function if I add my prompt as the last message, which is sent to the API.

```
  const result = await streamUI({
    model: openai('gpt-3.5-turbo'),
    initial: <SpinnerMessage />,
    system: `You will get your instructions in the last message received`,
    messages: [
      ...aiState.get().messages.map((message: any) => ({
        role: message.role,
        content: message.content,
        name: message.name
      })),{
        role: 'system',
        content: `You are a chatbot and you only speak French to the user`
      }
    ],
```

### Additional context

Attention is all you need

**Comment by lgrammel** [comment]
I think switching the system prompt half-way through a conversation is an edge case. You already addressed it through your last system prompt (which could also be an injected user message btw.).

Given that the recommend default is to have the system prompt first, and your situation is an edge case with a workaround, I'll close this issue.

**Comment by themataleao** [comment]
Thanks for the quick response @lgrammel 

Yeah I have checked the ai/rsc package and apparently, you are injecting the system prompt as a `user` message:

```
    case 'prompt': {
      languageModelMessages.push({
        role: 'user',
        content: [{ type: 'text', text: prompt.prompt }],
      });
      break;
    }
```

Do you know why it is recommended to have the system prompt first? As written it seems to me to lose attention if the message array gets too long. It could even get cropped if we go above the max_tokens for an API request.

Closing is fine for me.

**Comment by lgrammel** [comment]
a) no we are not, this is the prompt and not the system message
b) it's recommend to have the system prompt first because that's how the language models are trained. they get lots of examples where the system prompt (inside special tokens) comes at the beginning.

**Comment by themataleao** [comment]
Okay, thanks for the response and the feedback.

I will try my best to bend it towards my needs then :) I haven't tried with tools calling yet.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a change to intentional prompt-ordering behavior for an edge case, rather than reporting a violation of documented or promised SDK behavior.

### Evidence
- The reporter proposes changing `streamUI` so the system prompt is placed last rather than first to improve instruction adherence in long conversations.
- The maintainer states that placing the system prompt first is intentional and recommended based on model training, not broken SDK behavior.
- The described mid-conversation prompt change is characterized as an edge case with an available workaround.
