### ISSUE TITLE
useStreamableValue with streamable object alternates between undefined  and data

### ISSUE THREAD

**Issue by sullyo** [vercel/ai#1721]
### Description

When using the streamable object api with `useStreamableValue` the data streams in, it streams "undefined" a few times before completing

![image](https://github.com/vercel/ai/assets/13056592/d0f48937-13be-4a77-9455-757c5bcc964a)

This only happens if the component hasn't rendered before. 

### Code example
```
import { useStreamableValue } from "ai/rsc";

export function TablePreview({ tableData }: TablePreview) {
  const [data, error, pending] = useStreamableValue<PartialEntity>(tableData);
  console.log(tableData)
  return (
  <div>JSON.stringify(data)</div>
);
```

**Comment by lgrammel** [comment]
Potential fix: https://github.com/lgrammel/rsc-streamable/commit/1ab3f0c5c3deb7e0751e4d4dfe58a9b8278a8962

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete incorrect behavior in an existing streaming API, supported by a reproduction and proposed fix.

### Evidence
- `useStreamableValue` intermittently returns `undefined` while an object is streaming, despite object data being available before and afterward.
- The failure occurs when the component has not rendered previously.
- A reproduction repository and a potential fix were provided in the comments.
