### ISSUE TITLE
createStreamableUI example in the doc is not working 

### ISSUE THREAD

**Issue by defless** [vercel/ai#1816]
### Description

Since yesterday, the example associated with `createStreamableUI` (https://sdk.vercel.ai/examples/next-app/tools/render-interface-during-tool-call) is not working

**Comment by jeremyphilemon** [comment]
@defless Thanks for reporting! Can you share more details on what's not working? I tried running the example and it seems to be working fine.

I suspect you maybe didn't update the following placeholder inside the weather component?

```tsx
const data = await fetch(
  `https://api.example.com/weather?city=${city}&unit=${unit}`,
);
```

**Comment by defless** [comment]
I meant the whole page (https://sdk.vercel.ai/examples/next-app/tools/render-interface-during-tool-call) was returning a 500 error, not the example code in the page. 

But it's now working perfectly fine ! Thank you for your answer tho 👌

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a transient documentation-site availability report that resolved itself, not a current SDK bug or a request to change documentation or examples.

### Evidence
- Reporter clarified that the documentation page itself temporarily returned HTTP 500; the example code was not failing.
- Reporter later confirmed the page was working perfectly again.
- No ongoing failure or requested documentation/product change remains.
