### ISSUE TITLE
ai/rsc throwing uncatchable error with Vertex AI SDK.

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#1828]
### Description
The program crashes when the stop reason is a safety issue.  Also, when using streamUI there doesn't seem to be a way to handle the finishedReason nor usage. 

Using streamUI, setup a chatbot. Then ask it to "tell me a joke about a clown" or something like that. It triggers the safety issue, but I cannot seem to catch and handle it. The `getToolCallsFromParts` is the call causing the crash issue.

### Additional context

Unhandled Runtime Error
Error: Cannot read properties of undefined (reading 'flatMap')

Call Stack
getToolCallsFromParts
(rsc)\node_modules\.pnpm\@ai-sdk+google-vertex@0.0.5_zod@3.23.8\node_modules\@ai-sdk\google-vertex\dist\index.mjs (487:0)
Object.transform
(rsc)\node_modules\.pnpm\@ai-sdk+google-vertex@0.0.5_zod@3.23.8\node_modules\@ai-sdk\google-vertex\dist\index.mjs (413:0)
invokePromiseCallback
node:internal/webstreams/util (180:10)
Object.<anonymous>
node:internal/webstreams/util (185:23)
transformStreamDefaultControllerPerformTransform
node:internal/webstreams/transformstream (517:37)
transformStreamDefaultSinkWriteAlgorithm
node:internal/webstreams/transformstream (563:10)
<unknown>
node:internal/webstreams/transformstream (368:16)
writableStreamDefaultControllerProcessWrite
node:internal/webstreams/writablestream (1117:5)
writableStreamDefaultControllerAdvanceQueueIfNeeded
node:internal/webstreams/writablestream (1232:5)
writableStreamDefaultControllerWrite
node:internal/webstreams/writablestream (1106:3)
writableStreamDefaultWriterWrite
node:internal/webstreams/writablestream (996:3)
[kChunk]
node:internal/webstreams/readablestream (1562:31)
readableStreamFulfillReadRequest
node:internal/webstreams/readablestream (2095:24)
readableStreamDefaultControllerEnqueue
node:internal/webstreams/readablestream (2286:5)
ReadableStreamDefaultController.enqueue
node:internal/webstreams/readablestream (1055:5)
Object.pull
(rsc)\node_modules\.pnpm\@ai-sdk+provider-utils@0.0.11_zod@3.23.8\node_modules\@ai-sdk\provider-utils\dist\index.mjs (16:0)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1833

**Comment by lgrammel** [comment]
fixed in `@ai-sdk/google-vertex@0.0.6`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete runtime failure in the existing Google Vertex provider behavior, subsequently acknowledged and fixed by a maintainer.

### Evidence
- A Vertex AI safety stop caused `getToolCallsFromParts` to read `flatMap` from an undefined value and crash.
- The reporter described the error as uncatchable during `streamUI` use.
- A maintainer linked PR #1833 and confirmed the problem was fixed in `@ai-sdk/google-vertex@0.0.6`.
