### ISSUE TITLE
Sveltekit: Responses are not streaming

### ISSUE THREAD

**Issue by chanmathew** [vercel/ai#1891]
### Description

When using useChat in the UI and streamText in the +server.ts endpoint as shown in the Svelte example in the docs:
https://sdk.vercel.ai/docs/getting-started/svelte

The responses that come back are not streaming, instead it waits for the full response before the messages appear.

Please see here for repo:
https://stackblitz.com/edit/vercel-ai-sdk-sveltekit-non-streaming?file=src%2Froutes%2Fapi%2Fchat%2F%2Bserver.ts

**Comment by lgrammel** [comment]
It is working for me locally. Can you confirm with a local setup? This could be a stackblitz issue.

**Comment by chanmathew** [comment]
Closing this as it seems to be some weird edge case with Stackblitz / Cloudflare tunnels. Feel free to open if anyone else runs into this.

**Comment by wonyx** [comment]
The issue has been closed already,
I had same issue with cloudflared on my machine.
so, I tried to put a 'content-type': 'text/event-stream' header in the response header, and it worked.

Something like this:
```typescript
const result = streamText({
    model: ollama('phi4'),
    messages,
});

return result.toDataStreamResponse({
    headers: {
        'Transfer-Encoding': 'chunked',
        'Content-Type': 'text/event-stream',
        Connection: 'keep-alive',
    },
});
```

REF: https://github.com/cloudflare/cloudflared/issues/199#issuecomment-1648210459

**Comment by paulGeoghegan** [comment]
I'm actually having issues with this as well. User messages are sent and if I use generate text then it creates a response but wont display it in the front end but if I try to stream it doesn't even seem to create a result at all.
I'm checking and even though I'm doing:
```
import { streamTextOllama, ollama } from 'ai-sdk-ollama';
import { streamText, type UIMessage, convertToModelMessages } from 'ai';

export async function POST({ request }) {
	try {
		const { messages }: { messages: UIMessage[] } = await request.json();
		console.log('Received messages:', messages);
		const result = streamText({
			model: ollama('gemma3:27b'),
			messages: convertToModelMessages(messages)
		});
		return result.toUIMessageStreamResponse();
	} catch (error) {
		console.error('Error in chat POST handler:', error);
		return new Response(JSON.stringify({ error: String(error) }), { status: 500 });
	}
}
```
On my front end I'm calling it like:
```
			chat.sendMessage({ text: messageText });
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The available evidence does not establish broken AI SDK behavior; the confirmed problem is tied to external proxy/hosting environments, while the remaining report is a support-style troubleshooting case.

### Evidence
- The reporter confirmed streaming works when running directly on localhost.
- The failure was isolated to StackBlitz and Cloudflare Tunnel behavior, and the reporter closed the issue as an external edge case.
- A later workaround adds SSE-related response headers for cloudflared; another later comment reports a separate, insufficiently diagnosed setup problem.
