### ISSUE TITLE
Support parallel_tool_calls parameter for OpenAI models

### ISSUE THREAD

**Issue by mfclarke-cnx** [vercel/ai#1893]
### Feature Description

Currently the `streamUI` helper doesn't support multiple parallel tool calls. A quick workaround until this is supported would be to allow OpenAI's `parallel_tool_calls` parameter to be set to false (see https://platform.openai.com/docs/guides/function-calling/parallel-function-calling ).

### Use Case

Making sure the user can't accidentally cause an app to throw an error by getting the model to make multiple parallel tool calls.

**Comment by camwest** [comment]
Hmm what happens if the model tries to call multiple tools in parallel? Does the generate function just run once for the first tool then throw?

**Comment by camwest** [comment]
https://github.com/vercel/ai/blob/f7002ad2c5aa58ce6ed83e8d31fe22f71ebdb7d7/packages/openai/src/openai-chat-language-model.ts#L282

it looks like the underlying model implementation supports multiple tool calls.

**Comment by camwest** [comment]
https://github.com/vercel/ai/blob/f7002ad2c5aa58ce6ed83e8d31fe22f71ebdb7d7/packages/core/rsc/stream-ui/stream-ui.tsx#L301

[A](https://github.com/vercel/ai/blob/f7002ad2c5aa58ce6ed83e8d31fe22f71ebdb7d7/packages/core/rsc/stream-ui/stream-ui.tsx#L187)

Looks like streamUI should also. My understanding is it just pulls on the stream until it's done, the tool-call chunk gets pushed down for every toolCall in the response from OpenAI

**Comment by mfclarke-cnx** [comment]
Thanks for looking into this @camwest. I created an issue for what goes wrong #1894 . Basically the stream gets closed before all the tool calls have been processed. But - perhaps I'm not setting things up the right way?

**Comment by camwest** [comment]
> Thanks for looking into this @camwest. I created an issue for what goes wrong #1894 . Basically the stream gets closed before all the tool calls have been processed. But - perhaps I'm not setting things up the right way?

No the error makes sense. Thanks for sharing.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/1937

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/releases/tag/%40ai-sdk%2Fopenai%400.0.28

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This issue primarily requests a new OpenAI provider configuration parameter as a workaround; the concrete stream-handling failure was tracked separately.

### Evidence
- The title and description request exposing OpenAI's `parallel_tool_calls` parameter so it can be set to `false`.
- The underlying `streamUI` failure with multiple parallel calls was separated into issue #1894.
- A linked pull request and OpenAI provider release indicate the requested provider option was subsequently implemented.
