### ISSUE TITLE
Streamable object crashes on client side after 2s of streaming in production only

### ISSUE THREAD

**Issue by aaronvg** [vercel/ai#1910]
### Description

Check out this sample project, and click on the RAG example: https://github.com/BoundaryML/baml-examples/tree/main/nextjs-starter . Locally it works completely fine, but after deploying to vercel, clicking on the "answer question" button to start streaming will crash with a client-side error after 2 secs of streaming, saying that it can't construct a URL.

All you need is an OPENAI_API_KEY to test.

**Comment by aaronvg** [comment]
tried with 14.2.0, and now with nextjs15, same crash.

**Comment by aaronvg** [comment]
I found the issue -- when rendering a Link with a partial string response (while it's streaming), the url is invalid. I now only render links when the stream is complete.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was an application-level handling issue involving partial streamed data, not a confirmed AI SDK bug or feature request.

### Evidence
- The reporter traced the crash to rendering a Next.js Link with an incomplete URL while the string was still streaming.
- Waiting until the stream completed before rendering links resolved the problem.
- No broken AI SDK behavior or requested product change remained after the clarification.
