### ISSUE TITLE
Nuxt - Streaming Issue with the example "Nuxt OpenAI Starter" on Vercel

### ISSUE THREAD

**Issue by JuBertoo** [vercel/ai#196]
I've deployed the example "Nuxt OpenAI Starter" on Vercel and I'm encountering a streaming problem. Instead of sending data progressively, the system waits for the server's response to be complete before displaying any data. 
This issue doesn't occur when I run it locally.

https://nuxt-openai-vert.vercel.app/

Could this be related to Vercel's configuration? Any help is appreciated.

**Comment by jaredpalmer** [comment]
Nuxt doesn't support streaming at the moment. You can track the issue here: https://github.com/unjs/nitro/issues/1327

**Comment by Hebilicious** [comment]
@jaredpalmer This should currently be working with node runtimes, but support for (edge) streaming landed with h3 1.7.0, here's a working example with cloudflare pages :  

https://github.com/Hebilicious/vercel-sdk-ai/blob/cloudflare-official/examples/nuxt-openai/server/api/chat.ts

(I haven't tried it on vercel-edge but this should work too)

Note that this custom `sendStream` utility will be provided by the framework soon. 

@JuBertoo update your code to do something like this : 

```ts
export default defineEventHandler(async (event: any) => {
  // Extract the `prompt` from the body of the request
  const { messages } = await readBody(event)

  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: messages.map((message: any) => ({
      content: message.content,
      role: message.role
    }))
  })

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)
  // Respond with the stream
  return sendStream(event, stream)
})

function sendStream(event: H3Event, stream: ReadableStream) {
  // Mark to prevent h3 handling response
  event._handled = true

  // Workers (unenv)
  // @ts-expect-error _data will be there.
  event.node.res._data = stream

  // Node.js
  if (event.node.res.socket) {
    stream.pipeTo(
      new WritableStream({
        write(chunk) {
          event.node.res.write(chunk)
        },
        close() {
          event.node.res.end()
        }
      })
    )
  }
}
```

**Comment by JuBertoo** [comment]
Thank you for your response, Hebilicious, but it still doesn't work... I have installed the dependency 'h3': '^1.7.0' and updated the code. It may not be compatible with Vercel's Edge Functions.

`// ./api/chat.ts
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream } from 'ai'
import type { H3Event } from 'h3'

// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  // eslint-disable-next-line react-hooks/rules-of-hooks
  apiKey: useRuntimeConfig().openaiApiKey
})
const openai = new OpenAIApi(config)

export default defineEventHandler(async (event: any) => {
  // Extract the `prompt` from the body of the request
  const { messages } = await readBody(event)

  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: messages.map((message: any) => ({
      content: message.content,
      role: message.role
    }))
  })

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)
  // Respond with the stream
  return sendStream(event, stream)

  function sendStream(event: H3Event, stream: ReadableStream) {
    // Mark to prevent h3 handling response
    event._handled = true
  
    // Workers (unenv)
    event.node.res._data = stream
  
    // Node.js
    if (event.node.res.socket) {
      stream.pipeTo(
        new WritableStream({
          write(chunk) {
            event.node.res.write(chunk)
          },
          close() {
            event.node.res.end()
          }
        })
      )
    }
  }
})
`

**Comment by Hebilicious** [comment]
> Thank you for your response, @Hebilicious , but it still doesn't work... I have installed the dependency 'h3': '^1.7.0' and updated the code. It may not be compatible with Vercel's Edge Functions.
> 
> ``` // ./api/chat.ts
> import { Configuration, OpenAIApi } from 'openai-edge';
> import { OpenAIStream } from 'ai';
> import type { H3Event } from 'h3';
> 
> // Create an OpenAI API client (that's edge friendly!)
> const config = new Configuration({
>   // eslint-disable-next-line react-hooks/rules-of-hooks
>   apiKey: useRuntimeConfig().openaiApiKey,
> });
> const openai = new OpenAIApi(config);
> 
> export default defineEventHandler(async (event: any) => {
>   // Extract the `prompt` from the body of the request
>   const { messages } = await readBody(event);
> 
>   // Ask OpenAI for a streaming chat completion given the prompt
>   const response = await openai.createChatCompletion({
>     model: 'gpt-3.5-turbo',
>     stream: true,
>     messages: messages.map((message: any) => ({
>       content: message.content,
>       role: message.role,
>     })),
>   });
> 
>   // Convert the response into a friendly text-stream
>   const stream = OpenAIStream(response);
>   // Respond with the stream
>   return sendStream(event, stream);
> 
>   function sendStream(event: H3Event, stream: ReadableStream) {
>     // Mark to prevent h3 handling response
>     event._handled = true;
> 
>     // Workers (unenv)
>     event.node.res._data = stream;
> 
>     // Node.js
>     if (event.node.res.socket) {
>       stream.pipeTo(
>         new WritableStream({
>           write(chunk) {
>             event.node.res.write(chunk);
>           },
>           close() {
>             event.node.res.end();
>           },
>         })
>       );
>     }
>   }
> });
> ```

I assume that since it runs on cloudflare it should run on vercel edge, I will try to deploy an example.

**Comment by dosstx** [comment]
@Hebilicious Any update on whether you got it working on Vercel edge?

**Comment by Hebilicious** [comment]
> @Hebilicious Any update on whether you got it working on Vercel edge?

I've been able to deploy with the CLI without any issues, altough I'm not a vercel user so I'm not sure if that's with edge function ?

https://nuxt-openai-vercel-hebilicious.vercel.app/

Nuxt config
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  nitro: {
    preset: 'vercel-edge'
  },
  alias: {
    'node:util': path.resolve(
      __dirname,
      'node_modules/unenv/runtime/node/util/index.cjs'
    ),
    'node:net': path.resolve(
      __dirname,
      'node_modules/unenv/runtime/node/net/index.cjs'
    )
  },
  runtimeConfig: {
    openaiApiKey: ''
  }
})
```

Server API 

```ts
// ./api/chat.ts
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream } from 'ai'
import type { H3Event } from 'h3'

let openai: OpenAIApi

export default defineEventHandler(async (event: any) => {
  if (!openai) {
    let apiKey = useRuntimeConfig().openaiApiKey as string
    const config = new Configuration({ apiKey })
    openai = new OpenAIApi(config)
  }

  // Extract the `prompt` from the body of the request
  const { messages } = await readBody(event)

  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: messages.map((message: any) => ({
      content: message.content,
      role: message.role
    }))
  })

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response)
  // Respond with the stream
  return sendStream(event, stream)
})

function sendStream(event: H3Event, stream: ReadableStream) {
  // Mark to prevent h3 handling response
  event._handled = true

  // Workers (unenv)
  // @ts-expect-error _data will be there.
  event.node.res._data = stream

  // Node.js
  if (event.node.res.socket) {
    stream.pipeTo(
      new WritableStream({
        write(chunk) {
          event.node.res.write(chunk)
        },
        close() {
          event.node.res.end()
        }
      })
    )
  }
}

```

**Comment by MaxLeiter** [comment]
@Hebilicious those seem like two good suggestions. Would you mind contributing a pull request?

**Comment by Giancarlo-Ma** [comment]
how can i intercept the streaming content to save it to db on cf worker

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Examples**  
Confidence: **High**

### Rationale
The problem was traced to the Nuxt starter’s configuration and server implementation, and the proposed repository change was to correct the runnable example and its accompanying README guidance.

### Evidence
- The deployed Nuxt OpenAI Starter buffered the full response instead of streaming, while local development streamed correctly.
- A contributor demonstrated that streaming works on Vercel Edge with updated Nuxt/Nitro configuration and a custom `sendStream` implementation.
- Maintainers agreed that updating the example and documenting Edge Function caveats were appropriate and requested a pull request.
