### ISSUE TITLE
Continue generation and regeneration

### ISSUE THREAD

**Issue by Distortedlogic** [vercel/ai#198]
a way to continue generation when the response is over max tokens.

right now a dev can call `complete` directly to regenerate. but a function for this with a boolean on the request body for is regeneration or not, would be a nice QOL feature

**Comment by shuding** [comment]
Kinda related to https://github.com/vercel-labs/ai/issues/167#issuecomment-1604790534.

**Comment by jeremyphilemon** [comment]
#2164 adds support for requesting a generation without adding another user message while using `handleSubmit`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new continuation/regeneration capabilities and improved API ergonomics, not a report of broken existing behavior.

### Evidence
- Requests a new way to continue generation after reaching the maximum token limit.
- Proposes a regeneration helper with a request-body boolean to distinguish regeneration.
- A comment notes that #2164 adds support for generation without adding another user message.
