### ISSUE TITLE
Getting Not Found error for Google provider integration

### ISSUE THREAD

**Issue by retired-Hurt** [vercel/ai#2028]
### Description

While trying to integrate with the google generative AI provider, getting an error of "Not Found" while running the code. Below is the stack. This is with all default settings. 

`Error: Not Found

Source
eval
node_modules/.pnpm/@ai-sdk+provider-utils@0.0.15_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs (381:1)
async postToApi
node_modules/.pnpm/@ai-sdk+provider-utils@0.0.15_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs (304:1)
async GoogleGenerativeAILanguageModel.doStream
node_modules/.pnpm/@ai-sdk+google@0.0.22_zod@3.23.8/node_modules/@ai-sdk/google/dist/index.mjs (275:48)
async _retryWithExponentialBackoff
../core/util/retry-with-exponential-backoff.ts (36:12)
async streamUI
../stream-ui/stream-ui.tsx (256:18)
lib/chat/actions.tsx (60:18) @ async $$ACTION_0

  58 |   let AIModel = google('gemini-1.5-flash');
  59 |
> 60 |   const result = await streamUI({
     |                  ^
  61 |     model: AIModel,
  62 |     initial: <SpinnerMessage />,
  63 |     system: 'You are a general purpose assistant and you can help users with any query'`

### Code example

import 'server-only'

import {
  createAI,
  createStreamableUI,
  getMutableAIState,
  getAIState,
  streamUI,
  createStreamableValue
} from 'ai/rsc'

import { google } from '@ai-sdk/google';

import { BotMessage } from '@/components/stocks'

import { nanoid } from '@/lib/utils'
import { saveChat } from '@/app/actions'
import { SpinnerMessage, UserMessage } from '@/components/stocks/message'
import { Chat, Message, Session } from '@/lib/types'
import { auth } from '@/auth'

async function submitUserMessage(content: string) {
  'use server'

  const session = (await auth()) as Session
  const aiState = getMutableAIState<typeof AI>()

  aiState.update({
    ...aiState.get(),
    messages: [
      ...aiState.get().messages,
      {
        id: nanoid(),
        role: 'user',
        content
      }
    ]
  })

  let textStream: undefined | ReturnType<typeof createStreamableValue<string>>
  let textNode: undefined | React.ReactNode

  let AIModel = google('gemini-1.5-flash');

  const result = await streamUI({
    model: AIModel,
    initial: <SpinnerMessage />,
    system: 'You are a general purpose assistant and you can help users with any query',

    // Besides that, you can also chat with users and do some calculations if needed.`,
    messages: [
      ...aiState.get().messages.map((message: any) => ({
        role: message.role,
        content: message.content,
        name: message.name
      }))
    ],
    text: ({ content, done, delta }) => {
      if (!textStream) {
        textStream = createStreamableValue('')
        textNode = <BotMessage content={textStream.value} />
      }

      if (done) {
        textStream.done()
        aiState.done({
          ...aiState.get(),
          messages: [
            ...aiState.get().messages,
            {
              id: nanoid(),
              role: 'assistant',
              content
            }
          ]
        })

      } else {
        textStream.update(delta)
      }

      return textNode
    },
  })

  return {
    id: nanoid(),
    display: result.value
  }
}

export type AIState = {
  chatId: string
  messages: Message[]
}

export type UIState = {
  id: string
  display: React.ReactNode
}[]

export const AI = createAI<AIState, UIState>({
  actions: {
    submitUserMessage,
    // confirmPurchase
  },
  initialUIState: [],
  initialAIState: { chatId: nanoid(), messages: [] },
  onGetUIState: async () => {
    'use server'

    const session = await auth()

    if (session && session.user) {
      const aiState = getAIState().Chat;

      if (aiState) {
        const uiState = getUIStateFromAIState(aiState)
        return uiState
      }
    } else {
      return
    }
  },
  onSetAIState: async ({ state }) => {
    'use server'

    const session = await auth()

    if (session && session.user) {
      const { chatId, messages } = state

      const createdAt = new Date()
      const userId = session.user.id as string
      const path = `/chat/${chatId}`

      const firstMessageContent = messages[0].content as string
      const title = firstMessageContent.substring(0, 100)

      const chat: Chat = {
        id: chatId,
        title,
        userId,
        createdAt,
        messages,
        path
      }

      await saveChat(chat)
    } else {
      return
    }
  }
})

export const getUIStateFromAIState = (aiState: Chat) => {
  return aiState.messages
    .filter(message => message.role !== 'system')
    .map((message, index) => ({
      id: `${aiState.chatId}-${index}`,
      display:
        message.role === 'user' ? (
          <UserMessage>{message.content as string}</UserMessage>
        ) : message.role === 'assistant' &&
          typeof message.content === 'string' ? (
          <BotMessage content={message.content} />
        ) : null
    }))
}

**Comment by lgrammel** [comment]
The models need a `models/` prefix. Please try `models/gemini-1.5-flash-latest` as the model.

**Comment by retired-Hurt** [comment]
This helped. Thanks

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was a configuration/support issue caused by an incorrect model identifier, not a demonstrated SDK defect or request to change documentation, examples, or functionality.

### Evidence
- The request used `google('gemini-1.5-flash')`, which lacked the required `models/` prefix.
- A maintainer recommended `models/gemini-1.5-flash-latest`.
- The reporter confirmed that the corrected model identifier resolved the error.
