### ISSUE TITLE
Support streaming partial object chunks

### ISSUE THREAD

**Issue by AaronFriel** [vercel/ai#2036]
### Feature Description

Support sending a stream of JSON-patch like events with `streamObject` to enable more efficient end-to-end workflows and complex scenarios involving eliding some content from the response sent to the client or streaming partial strings as deltas.

This would build on #1883 to support a stream of patches.

### Use Case

The `streamObject` API currently streams whole objects - this is great for rendering UI elements where we want the **whole object** to be provided to the client as UI; however for agent workloads we may want to elide or transform the object in flight and efficiently transmit, e.g., updates to a single string value.

For example, we might define a tool with a shape like so:

```ts
const rating = z.object({
  rating: z.string(),
  score: z.number().int().min(0).max(100),
});

const response = z.object({
  moderation: z.object({
    harm: rating.describe("physical or psychological harm"),
    // ...
  }).describe(`\
for each category by key, rate whether the user's text matches the category from "not very likely" to "very likely" \
then give it a score. the score is your subjective evaluation of how likely it is that the user intended \
to convey the category evaluated, on a scale of 0 (meaning not at all) to 100 (absolutely certain, 100%)`
  response: z.string().describe("your reply to the user"),
  // ...
});
```

We may want to combine this with a `createStreamableValue` or even perform this `streamObject` call inside a readable stream constructor which emits only the deltas of each value for efficiency. That is, instead of streaming:

```
{}
{"moderation":{}}
{"moderation":{"harm": ...}}
// ...
{"moderation":{"harm":...},"response":"hello"}
{"moderation":{"harm":...},"response":"hello, world"}
```

_Edited 2024-06-21:_

We might like to reduce these to patches, perhaps eliding certain paths or transforming the object entirely, so that the transformed stream is O(n) in the size of the input stream or what is added to the server:

```
{"kind":"partial","path":["response",null],value:"hello"}
{"kind":"partial","path":["response",null],value:", "}
{"kind":"partial","path":["response",null],value:"world"}
```

As the response grows in length, this reduces the bandwidth and computational work on the client to linear from quadratic. This quadratically reduces the bandwidth of sending large strings (such as a long `response` above) and makes it easy to act on updates to the `moderation` key efficiently and incrementally, only acting *on* the moderation value updates and making decisions on values in the object being completed or updated, as opposed to inspecting each partial object and maintaining a diff by hand:

```ts
'use server';

import { openai } from '@ai-sdk/openai';
import { streamObject } from 'ai';
import { createStreamableValue } from 'ai/rsc';

// What the LLM returns:
export interface ToolResponse {
  response: string;
  moderation: {
    [key: string]: {
      rating: string;
      score: number;
    }
  }
}

// What the client receives:
export interface RecipeResponse {
  response: string;
  error: string;
}

export async function generateRecipe() {
  const response = createStreamableValue();

  streamObject({
    model: openai('gpt-4-turbo'),
    schema: responseSchema,
    prompt: `Generate a lasagna recipe that's to die for`,
  }).then(async ({ patchStream, abortController }) => {
    
    let moderated = false;
    for await (const patch of patchStream) {
      // the ts-pattern library enables nicer pattern matching on these values
      // for example's sake, we don't rely on any libraries

      // a moderation score:
      if (patch.path[0] === "moderation" && patch.path.length === 3 && patch.kind === 'complete') {
        if (patch.value.score >= 75) {
          moderated = true;
        } else if (patch.value.score >= 25) {
          logger.warn(`moderation value ${patch.path[1]} above normal`);
        }
      }

      if (patch.path[0] === "moderation" && patch.kind === 'complete') {
        if (moderated) {
          abortController.abort();
          response.update({"kind":"complete","path":["error",null],"value":"moderated content detected"});
          return;
        }
        
      }
      
      if (patch.path[0] === "response" && patch.kind === "partial") {
        // efficient updates, we only transmit updates to the `response` field:
        response.update(patch);
      }
    }

  });

  return {
    response: response,
  }
}
```

```ts
'use client';

import React from 'react';
import { useState } from 'react';
import { readStreamableValue, applyPatch } from 'ai/rsc';
import { generateRecipe, RecipeResponse } from '@/actions';

export default function Page() {
  const [recipeState, setRecipeState] = useState<DeepPartial<RecipeResponse> | undefined>();

  return (
    <div>
      <button
        onClick={async () => {
          const { response, error } = await generateRecipe();

          for await (const chunk of readStreamableValue(status)) {
            // applyState mutates the object efficiently in place, 
            // though this could be changed to act like a persistent data structure
            setRecipeState((state) => applyPatch(state, chunk));
          }
        }}
      >
        Ask
      </button>
      <p>{response}</p>
      {error && <p>{error}</p>}
    </div>
  );
}
```

### Additional context

The streaming JSON parser implemented in #1883 supports this use case by generating a stream of "parse events". Parse events match this type:

```
interface ParseEvent<any> = {
  kind: 'partial' | 'complete' | 'value',
  path: [...(string | number), null], 
        // the null value helps in pattern matching as a terminal path
  value: any,
}
```

Where as the object is incrementally parsed, for every value updated one or more events may be emitted:
* Number, boolean, and null values are only ever emitted with kind `complete`, after the entire value is parsed
* String value parsing emit `partial` events as chunks are read, and a `complete` event when the entire value is available
* Array and object values emit `complete` events when the entire value is parsed (the closing `}` or `]`)
* The root, outermost object emits a `value` event - this could be emitted as `complete` however it has been useful to use a unique kind for "an entire value"

**Comment by AaronFriel** [comment]
@lgrammel I would very much like to move some of our tooling over to the AI SDK to leverage the provider API adapters and ecosystem here, but this issue would be a blocker for us to do so.

It is _straightforward_ to update #1883 to also emit patch events, but before I do so:

1. Do you have any qualms with the current `PatchEvent` type? I'm not sold on 'partial', 'complete', 'value' myself, and open to suggestions.
2. Do you have any qualms with adding patch events to `streamObject` as above?

**Comment by lgrammel** [comment]
Is this needed when we can just send a text stream, as with to with `.textStream()`?

**Comment by AaronFriel** [comment]
I'm not sure I follow the question, it seems like a non-sequitur.

> useObject already uses that for efficient data transfer.

I'm not sure what this means - I don't think we agree on efficient here. The `streamObject` stream of partial objects is another example of accidentally quadratic behavior:
* Until #1883 lands, the server uses O(n^2) time to compute streaming objects.
* The client receives O(n^2) bytes instead of O(n), as `streamObject` streams whole objects.
* The client must parse that text, for another O(n^2) in bytes parsed by `JSON.parse`
* The UI framework and/or client state rendering must expend cycles comparing objects to "see what's different", which adds another O(n^2) compute

`useObject` also uses `parsePartialJson` and `isDeepEqual` - expensive operations that grow quadratically in the size of the text and object compared, respectively:

https://github.com/vercel/ai/blob/c70729f2c1fae84975ab13d35940aab7f8b791d1/packages/react/src/use-object.ts#L100-L109

**Comment by AaronFriel** [comment]
| Task                                | Complexity<br>(today) |                                                                                   Compute<br>(goal)                                                                                  |
|-------------------------------------|:---------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| Server parsing stream (time)        | O(n^2)                | O(n)<br>(#1883)                                                                                                                                                                      |
| Server transfer (bandwidth)         | O(n^2)                | O(n)<br>(#2036)                                                                                                                                                                      |
| Client parsing object stream (time) | O(n^2)                | O(n)<br>(Future PR to update `use-object`)                                                                                                                                           |
| Client diffing objects              | O(n^2)                | O(n)<br>(Future PR to export [`applyUpdate`](https://github.com/AaronFriel/fn-stream/blob/a208bf2f5dd686cf4e6e4f5c78d8e45e445daa7f/packages/fn-stream/.friel.scratch.ts#L16-L34)) |

**Comment by lgrammel** [comment]
You analysis is incorrect. We do not send O(n^2), we send O(n) with `textStream`

**Comment by AaronFriel** [comment]
It is if we send back a stream of objects derived from `streamObject`, no?

**Comment by lgrammel** [comment]
No we don't, we send back text delta because of exactly your considerations: 

https://github.com/vercel/ai/blob/main/packages/core/core/generate-object/stream-object.test.ts#L233

That being said, I absolutely want to integrate your streaming parser to get server and client side processing to O(n).

**Comment by AaronFriel** [comment]
I think we're talking past one another: this issue is about enabling `streamObject` to return a stream of patches from a tool/function API or chat completion that returns JSON.

The motivating code in the issue shows this, with the server side using patches to produce a text stream with O(n) complexity *derived from* an object stream, with complex logic (such as moderation) performed efficiently during the decoding of the object stream.

The text stream API is not relevant to this issue, as we need to perform transformation and agentic work on the server, which then results in an arbitrary stream to the client which itself could be a text stream, patch stream, etc.

In fact in our production use case, we operate on the patches to then generate a *differently shaped* set of patches that drive client behavior. Were we to adopt the AI SDK today, we would reintroduce the O(n^2) factors in the table above because we would need to send a stream of objects to the client, instead of a stream of patches.

**Comment by lgrammel** [comment]
Fair. I would need to see the details for the llm use cases. I thought about it and arrived at the conclusion that a text stream is sufficient and simpler than a patch stream, because we are linearly appending at the end.

My suggestion would be to start with the streaming parser first and then look at concrete examples where a patch stream is needed and a text stream is not sufficient.

**Comment by AaronFriel** [comment]
> I thought about it and arrived at the conclusion that a text stream is sufficient and simpler than a patch stream, because we are linearly appending at the end.

That's makes sense if you're sending text, or using `useStreamableValue` with server actions, with one streamable value "per value" that is rendered on the client. But as server actions are not cancellable (#1122) and as the complexity of the objects (or derived objects) grows, the quadratic factors impact usability. And as we are working with fairly large responses (100s to 1000s of tokens) of objects, repeated JSON parsing of the text stream ends up incurs significant latency on the client and causes unnecessary work by the framework to update UI elements as state drives React component updates.

> My suggestion

We're already shipping an application, and we have concrete examples I cannot share. Operating on patches has been fundamental to our approach on both client and server to drive down latency. I've updated the example in the issue to show how operating on patches enables trivial to modify the object stream and send a stream of patches to the client which constitute a _different_ object than the `streamObject` tool.

If `streamObject` returned a patch stream, we would be able to adopt the AI SDK, but as it stands it looks like we'll not be able to do so.

**Comment by AaronFriel** [comment]
@lgrammel I will just say, it would be a huge bummer for me to contribute the streaming in #1883 and not allow clients to make use of the capabilities in the AI SDK.

Seems like just a huge miss. I feel like I haven't been persuasive, but if you think it's not worth doing this, I may want to retract #1883.

**Comment by lgrammel** [comment]
@AaronFriel sure, please go ahead. i feel to pressured into accepting your solution and would prefer to explore alternatives, in particular since i don't want to be limited to exposing it as a separate module.

**Comment by AaronFriel** [comment]
I don't think there is an alternative to drive down the cost of compute, but welcome any new developments in streaming protocols here.

**Comment by psai-terwin** [comment]
@lgrammel @AaronFriel 

This discussion is interesting to me because I don't think we should throw the baby out with the bathwater so to speak. I don't think this needs to be an either / or discussion. We should be able to make this an optional way to do streaming if you want this method. It doesn't need to be the default. It just needs to be an option.

I'm also very disappointed that you can't cancel server actions (a next.js / react problem I guess) so we're looking at alternatives but getting super fast parsing / streaming and cost savings seems like something we would want here.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to expand `streamObject` with structured partial-object patch streaming for new workflows and performance improvements. It does not establish that the current API violates documented behavior.

### Evidence
- The issue explicitly requests adding a JSON-patch-like event stream to `streamObject`.
- Current whole-object streaming is described as unsuitable for server-side transformation, moderation, and incremental processing use cases.
- The proposed `patchStream`, patch event types, and `applyPatch` API are new optional capabilities rather than fixes to promised behavior.
- Comments clarify that existing text-delta streaming works as intended but does not address the requested structured patch-processing workflow.
