### ISSUE TITLE
Extend Vue Library with `useAssistant` support

### ISSUE THREAD

**Issue by Kunoacc** [vercel/ai#2040]
### Feature Description

Pumped to contribute by adding the `useAssistant` hook to Vue.js as a composable.

**Comment by lgrammel** [comment]
Shipped in https://github.com/vercel/ai/pull/2245

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to expand the Vue integration with a new composable, not a report of broken existing behavior.

### Evidence
- The issue explicitly proposes adding the existing `useAssistant` capability to the Vue library as a new composable.
- The maintainer comment states that the requested capability was shipped in PR #2245.
