### ISSUE TITLE
InvalidToolArgumentsError unhandled by useChat, leading to infinite loop

### ISSUE THREAD

**Issue by BrianHung** [vercel/ai#2042]
### Description

InvalidToolArgumentsError is unhandled by useChat, leading to an infinite loop of triggerRequest. This is extremely bad as credits can be fully drained easily this way.

The trace is as follows.

Tool arguments are returned and parsed by `parseToolCall` within `streamText`.

https://github.com/vercel/ai/blob/0565cd72934bc22bfc8f7a866abef97c643e6f86/packages/core/core/generate-text/run-tools-transformation.ts#L74-L77

When arguments are malformed, an `InvalidToolArgumentsError` is thrown.

https://github.com/vercel/ai/blob/0565cd72934bc22bfc8f7a866abef97c643e6f86/packages/core/core/generate-text/tool-call.ts#L74-L78

This error is then serialized and streamed back to the client.

https://github.com/vercel/ai/blob/0565cd72934bc22bfc8f7a866abef97c643e6f86/packages/core/core/generate-text/run-tools-transformation.ts#L119-L122

This error is received by `useChat` and is unhandled by `parseComplexResponse`.

https://github.com/vercel/ai/blob/0565cd72934bc22bfc8f7a866abef97c643e6f86/packages/ui-utils/src/parse-complex-response.ts#L34C23-L34C43

Because it is unhandled, `processChatStream` proceeds as normal and no new messages are emitted, leading to `triggerRequest` being called again.

https://github.com/vercel/ai/blob/0565cd72934bc22bfc8f7a866abef97c643e6f86/packages/react/src/use-chat.ts#L292-L349

### Additional context

I have a tool call defined as

```ts
showBarChart: {
	description:
		'Make a bar plot in matplotlib. The bars are positioned at x. Their dimensions are given by height. Always include the data parameter as a list of JSON objects.',
	parameters: z.object({
		data: z.array(z.record(z.number())).describe('JSON list for which to generate grouped bars'),
		axisKey: z.string().describe('The key to use for the x-axis.'),
		title: z.string().optional().describe('Set a title for the plot.'),
		yLabel: z.string().optional().describe('Set the label for the y-axis.'),
	}),
},
```

For some reason, gpt-4o doesn't return anything for data when it's defined as an array of records with variable keys. However, setting it to have defined keys does return valid data.

```ts
showBarChart: {
	description:
		'Make a bar plot in matplotlib. The bars are positioned at x. Their dimensions are given by height. Always include the data parameter as a list of JSON objects.',
	parameters: z.object({
		data: z
			.array(z.object({ x: z.number(), height: z.number() }))
			.describe('JSON list for which to generate grouped bars'),
		axisKey: z.string().describe('The key to use for the x-axis.'),
		title: z.string().optional().describe('Set a title for the plot.'),
		yLabel: z.string().optional().describe('Set the label for the y-axis.'),
	}),
},
```

**Comment by BrianHung** [comment]
A possible solution might be to enqueue a toolCall message and the error message, so that `useChat` gets an updated `messages` list which prevents `triggerRequest` from being called again.

```ts
          } catch (error) {
            controller.enqueue // tool call finished with an arguments parsing error
            toolResultsStreamController!.enqueue({
              type: 'error',
              error,
            });
          }
```

https://github.com/vercel/ai/blob/0565cd72934bc22bfc8f7a866abef97c643e6f86/packages/core/core/generate-text/run-tools-transformation.ts#L118-L123

**Comment by BrianHung** [comment]
If I am reading [this](https://community.openai.com/t/gpt-4-turbo-is-not-respecting-required-while-gpt-4-turbo-preview-is/712931/2) right

> Unfortunately function-calling is not guaranteed to follow the schema, and there can be differences in quality from model to model.

The arguments returned may not always follow the zod schema that was given.

**Comment by BrianHung** [comment]
For my use case, I was able to avoid an argument parsing error by being more precise with the tool and parameter descriptions.

```ts
showBarChart: {
	description:
		'Make a bar plot in matplotlib. The bars are positioned at x. Their dimensions are given by height. Always include the data parameter as a list of JSON objects.',
	parameters: z.object({
		axisKey: z.string().describe('The key to use for the x-axis.'),
		data: z
			.array(z.record(z.union([z.string(), z.number()])))
			.describe(
				'List of JSON objects for which to generate grouped bars. JSON objects must always contain axisKey as a field.'
			),
		title: z.string().optional().describe('Set a title for the plot.'),
		yLabel: z.string().optional().describe('Set the label for the y-axis.'),
	}),
},
```

**Comment by lgrammel** [comment]
Reproduced.

**Comment by lgrammel** [comment]
Cause:
- when the last message in `useChat` is an assistant message with completed tool calls,
- and `streamText` only returns an `error` event,
- then the checks fail and an infinite loop with the last assistant message is started.

**Comment by lgrammel** [comment]
WIP PR: https://github.com/vercel/ai/pull/2052

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing `useChat` error handling that causes unintended repeated requests and an infinite loop.

### Evidence
- `InvalidToolArgumentsError` is streamed to `useChat` but not handled by `parseComplexResponse`.
- The unhandled error causes `triggerRequest` to repeat indefinitely, potentially draining API credits.
- A maintainer reproduced the issue, identified the infinite-loop condition, and linked a work-in-progress fix.
