### ISSUE TITLE
Anthropic user content inside tool result

### ISSUE THREAD

**Issue by sintanial** [vercel/ai#2047]
### Title: 
Error with Consecutive User Role Messages After Tool Role Messages in Anthropic API

### Description:
When attempting to place a user role message immediately after a tool role message using the Anthropic API, an error is encountered:

```
AI_APICallError: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row.
```

This issue seems to be caused by the Anthropic API's requirement for roles to alternate strictly between "user" and "assistant". The current behavior does not support having a user role message following a tool role message without an intermediate assistant message.

### Steps to Reproduce:
1. Make an API call using the Anthropic API.
2. Structure the messages in the following order:
   - Tool role 'tool-call' message
   - User role with 'tool-result' message
   - User role with text
3. Execute the API call.

### Expected Behavior:
The API should accept the message structure, possibly by automatically incorporating the user message content within the tool result content or by providing a mechanism to handle such sequences without causing an error.

### Suggested Solution:
Replace this line https://github.com/vercel/ai/blob/main/packages/anthropic/src/convert-to-anthropic-messages-prompt.ts#L74 to this code:
```typescript
if (messages.length > 0 && messages[messages.length-1].role == "user" && messages[messages.length-1].content.find(part => part.type == "tool_result")) {
         messages[messages.length-1].content = messages[messages.length-1].content.concat(anthropicContent);
} else {
         messages.push({role: "user", content: anthropicContent});
}
```

**Comment by EvanFabry** [comment]
I'm currently trying to work around this issue (preferably without patching the AI SDK but could resort to that).

It seems unfortunate that AnthropicMessage and related types aren't directly exported by AI SDK. Do you have thoughts on whether those should be exported given the incompatibility with [LanguageModelV1Message](https://github.com/vercel/ai/blob/534f170ed5d156a3c5ad2ac6fd2fe58c622de14a/packages/provider/src/language-model/v1/language-model-v1-prompt.ts#L12-L31)?

**Comment by EvanFabry** [comment]
Thank you, @sintanial! This worked for me.

@lgrammel- this was super useful. Might be worth taking a look at :)

**Comment by lgrammel** [comment]
Your "solutions" will lead to to unexpected inputs to the Anthropic API and therefore potentially bad results. There are reasons why they enforce their structure: it's because their models are trained on it. Other providers have similar restrictions for similar reasons.

**Comment by sintanial** [comment]
In my case, i make 'ai web crawler', and this is my message seuqence:

```
[
  {
    "role": "system",
    "content": "<ROLE>You are an intelligent web browser capable of navigating web pages.</ROLE> ...."
  },
  {
    "role": "user",
    "content": "<PAGE_HTML>Some html of current page</PAGE_HTML>"
  },
  {
    "role": "assistant",
    "content": [
      {
        "type": "tool-call",
        "toolCallId": "call_2Rc2wCK6PIP2WpeHddb7R3n3",
        "toolName": "click",
        "args": {
          "explanation": "Accept all cookies to proceed with navigation.",
        }
      }
    ]
  },
  {
    "role": "tool",
    "content": [
      {
        "type": "tool-result",
        "toolCallId": "call_2Rc2wCK6PIP2WpeHddb7R3n3",
        "toolName": "click",
        "result": "Click completed successfully"
      }
    ]
  },
  {
    "role": "user",
    "content": "<PAGE_HTML>Some HTML here after click</PAGE_HTML>"
  }
]
```

As you can see, i put role 'user' just after role 'tool'. For my case it was necessary, because every time after every browser action i must to show LLM content of the current page. OpenAI and Claude allow this case and proper handle it

**Comment by lgrammel** [comment]
I see - so you want to provide additional information to the LLM when the user clicks accept. Have you considered the following:

```
[
  {
    "role": "system",
    "content": "<ROLE>You are an intelligent web browser capable of navigating web pages.</ROLE> ...."
  },
  {
    "role": "user",
    "content": "<PAGE_HTML>Some html of current page</PAGE_HTML>"
  },
  {
    "role": "assistant",
    "content": [
      {
        "type": "tool-call",
        "toolCallId": "call_2Rc2wCK6PIP2WpeHddb7R3n3",
        "toolName": "click",
        "args": {
          "explanation": "Accept all cookies to proceed with navigation.",
        }
      }
    ]
  },
  {
    "role": "tool",
    "content": [
      {
        "type": "tool-result",
        "toolCallId": "call_2Rc2wCK6PIP2WpeHddb7R3n3",
        "toolName": "click",
        "result": "<PAGE_HTML>Some HTML here after click</PAGE_HTML>"
      }
    ]
  }
]
```

**Comment by lgrammel** [comment]
That idea aside, this raises an important issue. It might be better to simplify the messages API for the Vercel AI SDK into `user` and `assistant` messages, deprecating `tool` messages.

**Comment by sintanial** [comment]
> I see - so you want to provide additional information to the LLM when the user clicks accept. Have you considered the following:
> 
> ```
> [
>   {
>     "role": "system",
>     "content": "<ROLE>You are an intelligent web browser capable of navigating web pages.</ROLE> ...."
>   },
>   {
>     "role": "user",
>     "content": "<PAGE_HTML>Some html of current page</PAGE_HTML>"
>   },
>   {
>     "role": "assistant",
>     "content": [
>       {
>         "type": "tool-call",
>         "toolCallId": "call_2Rc2wCK6PIP2WpeHddb7R3n3",
>         "toolName": "click",
>         "args": {
>           "explanation": "Accept all cookies to proceed with navigation.",
>         }
>       }
>     ]
>   },
>   {
>     "role": "tool",
>     "content": [
>       {
>         "type": "tool-result",
>         "toolCallId": "call_2Rc2wCK6PIP2WpeHddb7R3n3",
>         "toolName": "click",
>         "result": "<PAGE_HTML>Some HTML here after click</PAGE_HTML>"
>       }
>     ]
>   }
> ]
> ```

Yep, your version is good. But it has a little problem if the function must return some result (for example, collect something). Yes, you can concatenate all results and HTML page content, but a better approach for me is to separate it. I think this library should support all the flexibility of providers (Anthropic, OpenAI, etc.).




> That idea aside, this raises an important issue. It might be better to simplify the messages API for the Vercel AI SDK into `user` and `assistant` messages, deprecating `tool` messages.

It's a good idea! Makes sense! Also, it's much more intuitive because the tool is called on the assistant side and the tool results must be on the user side. The Anthropic version of organizing this functionality is quite good.

**Comment by nikshepsvn** [comment]
Can we get this fixed? Blocks very basic Anthropic usage without the patch

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2067

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The Anthropic provider’s message conversion produces an invalid role sequence for an existing tool-use workflow, causing API calls to fail. This is a concrete provider integration defect.

### Evidence
- A valid SDK sequence of assistant tool call, tool result, then user text is converted into consecutive Anthropic `user` messages, causing an `AI_APICallError`.
- Multiple users confirmed that merging the following user content into the tool-result message resolves the failure.
- A maintainer linked PR #2067 in response to the report.
