### ISSUE TITLE
Incorrect `args` format in `tool-call` messages when calling functions with no parameters

### ISSUE THREAD

**Issue by zvictor** [vercel/ai#2103]
# Description

While [porting gemini-chatbot to the Anthropic's provider](https://github.com/zvictor/anthropic-chatbot), I faced an error regarding tool/function calling with no parameters.

Functions that have no parameters lead to `tool-call` messages in which `"args": ""` instead of `"args": "{}"`.
Example:
```json
{
  "type": "tool-call",
  "toolCallType": "function",
  "toolCallId": "toolu_01RFn8zb3tbVnyiJ2FjhPqxb",
  "toolName": "showHotels",
  "args": ""
}
```

AI SDK does not accept that, leading to a `AI_JSONParseError: JSON parsing failed: Text: .`:

https://github.com/vercel/ai/blob/55a23687bebca255def82eaead9676e363d552c2/packages/core/core/generate-text/tool-call.ts#L68-L71

# Code example

### Source definition of the `showHotels` function:
```ts
import { tool } from 'ai'

tool({
  description: 'Show the UI to choose a hotel for the trip.',
  parameters: z.object({})
})
```

The code is located at [lib/chat/tools/showHotels.tsx:14](https://github.com/zvictor/anthropic-chatbot/blob/e89e79eb59ec4c39fe947ab921c3e02262a0940e/lib/chat/tools/showHotels.tsx#L14-L17), which is then imported at [lib/chat/actions.tsx:220](https://github.com/zvictor/anthropic-chatbot/blob/e89e79eb59ec4c39fe947ab921c3e02262a0940e/lib/chat/actions.tsx#L220-L222).

### JSON definition of the `showHotels` function:
```json
{
  "type": "function",
  "name": "showHotels",
  "description": "Show the UI to choose a hotel for the trip.",
  "parameters": {
    "type": "object",
    "properties": {},
    "additionalProperties": false,
    "$schema": "http://json-schema.org/draft-07/schema#"
  }
}
```

### Tool call:
```json
{
  "type": "tool-call",
  "toolCallType": "function",
  "toolCallId": "toolu_01RFn8zb3tbVnyiJ2FjhPqxb",
  "toolName": "showHotels",
  "args": ""
}
```

### Parse error:
```haskell
AI_JSONParseError: JSON parsing failed: Text: .
Error message: Unexpected end of JSON input
    at safeParseJSON (webpack-internal:///(rsc)/./node_modules/.pnpm/@ai-sdk+provider-utils@0.0.16_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:271:109)
    at parseToolCall (webpack-internal:///(rsc)/./node_modules/.pnpm/ai@3.2.7_openai@4.52.0_react@18.3.1_solid-js@1.8.17_svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:1184:92)
    ...
```

# Adicional context

If you change the parameters definition to something like `z.object({ city: z.string() }`, it works.

**Comment by lgrammel** [comment]
Can you provide the tool definition in typescript / AI SDK code? 

The following example works for me:
```ts
import { anthropic } from '@ai-sdk/anthropic';
import { generateText, tool } from 'ai';
import dotenv from 'dotenv';
import { z } from 'zod';

dotenv.config();

async function main() {
  const result = await generateText({
    model: anthropic('claude-3-opus-20240229'),
    maxTokens: 512,
    tools: {
      showBerlinCityAttractions: tool({
        description: 'Show Berlin city attractions',
        parameters: z.object({}),
        execute: async () => {
          console.log('Showing city attractions');
        },
      }),
    },
    prompt: 'Show Berlin city attractions',
  });

  console.log(JSON.stringify(result, null, 2));
}

main().catch(console.error);

**Comment by zvictor** [comment]
> Can you provide the tool definition in typescript / AI SDK code?

```ts
import { tool } from 'ai'

tool({
  description: 'Show the UI to choose a hotel for the trip.',
  parameters: z.object({})
})
```

It's located at [lib/chat/tools/showHotels.tsx:14](https://github.com/zvictor/anthropic-chatbot/blob/e89e79eb59ec4c39fe947ab921c3e02262a0940e/lib/chat/tools/showHotels.tsx#L14-L17), which is then imported at [lib/chat/actions.tsx:220](https://github.com/zvictor/anthropic-chatbot/blob/e89e79eb59ec4c39fe947ab921c3e02262a0940e/lib/chat/actions.tsx#L220-L222).

If you change the parameters definition to something like `z.object({ city: z.string() }`, it works.

**Comment by zvictor** [comment]
> The following example works for me

Yes, it works for me as well! But that's only when using `generateText`. If you go for `streamText` instead, it will throw the error:

```haskell
Delta {"type":"error","error":{"name":"AI_InvalidToolArgumentsError","message":"Invalid arguments for tool showBerlinCityAttractions: JSON parsing failed: Text: .\nError message: Unexpected end of JSON input","cause":{"name":"AI_JSONParseError","message":"JSON parsing failed: Text: .\nError message: Unexpected end of JSON input","cause":{},"stack":"AI_JSONParseError: JSON parsing failed: Text: .\nError message: Unexpected end of JSON input\n    at safeParseJSON (file:///node_modules/.pnpm/@ai-sdk+provider-utils@0.0.16_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:241:63)\n    at parseToolCall (file:///node_modules/.pnpm/ai@3.2.7_openai@4.52.0_react@18.3.1_solid-js@1.8.17_svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:1114:23)\n    at Object.transform (file:///node_modules/.pnpm/ai@3.2.7_openai@4.52.0_react@18.3.1_solid-js@1.8.17_svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:1313:30)\n    at invokePromiseCallback (node:internal/webstreams/util:180:10)\n    at Object.transformAlgorithm (node:internal/webstreams/util:185:23)\n    at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:526:37)\n    at transformStreamDefaultSinkWriteAlgorithm (node:internal/webstreams/transformstream:572:10)\n    at node:internal/webstreams/transformstream:377:16\n    at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1127:5)\n    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1242:5)","valueText":""},"stack":"AI_InvalidToolArgumentsError: Invalid arguments for tool showBerlinCityAttractions: JSON parsing failed: Text: .\nError message: Unexpected end of JSON input\n    at parseToolCall (file:///node_modules/.pnpm/ai@3.2.7_openai@4.52.0_react@18.3.1_solid-js@1.8.17_svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:1119:11)\n    at Object.transform (file:///node_modules/.pnpm/ai@3.2.7_openai@4.52.0_react@18.3.1_solid-js@1.8.17_svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:1313:30)\n    at invokePromiseCallback (node:internal/webstreams/util:180:10)\n    at Object.transformAlgorithm (node:internal/webstreams/util:185:23)\n    at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:526:37)\n    at transformStreamDefaultSinkWriteAlgorithm (node:internal/webstreams/transformstream:572:10)\n    at node:internal/webstreams/transformstream:377:16\n    at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1127:5)\n    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1242:5)\n    at writableStreamDefaultControllerWrite (node:internal/webstreams/writablestream:1116:3)","toolName":"showBerlinCityAttractions","toolArgs":""}}
Delta {"type":"finish","finishReason":"tool-calls","usage":{"promptTokens":346,"completionTokens":42,"totalTokens":388}}
```

Try this:

```js
import { anthropic } from '@ai-sdk/anthropic'
import { streamText, tool } from 'ai'
import dotenv from 'dotenv'
import { z } from 'zod'

dotenv.config()

async function main() {
  const result = await streamText({
    model: anthropic('claude-3-haiku-20240307'),
    maxTokens: 512,
    tools: {
      showBerlinCityAttractions: tool({
        description: 'Show Berlin city attractions',
        parameters: z.object({}),
        execute: async () => {
          console.log('Showing city attractions')
        }
      })
    },
    prompt: 'Show Berlin city attractions'
  })

  for await (const delta of result.fullStream) {
    console.log(`Delta`, JSON.stringify(delta))
  }
}

main().catch(console.error)
```

**Comment by mnalley95** [comment]
> bumping this as I'm also experiencing an error when I try to use an empty object via zod for a tool's parameters. when I define a parameter for the tool, everything works as expected.
> 
> 
> 
> URL type parameters are also no longer working:
> 
> ![image](https://github.com/vercel/ai/assets/44619264/9c3babf0-65a1-4609-bbbc-6eea79e00c49)
> 
> ![image](https://github.com/vercel/ai/assets/44619264/92d8f72e-f564-48a6-980b-6c08c5b9e2f9)
> 
> 
> 
> ### Additional Context
> 
> I'm using the Google Generative API provider and I haven't made any changes over the past 2 days. Everything was stable until earlier today for me. Btw - i'm using `generateText`

Getting exact same error as you using GoogleGenerativeAI, url type, and `streamText`. Was also working fine 2-3 days ago, then was getting the exact same error today.

**Comment by sumitstranger** [comment]
are you able to fix it?

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3073

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing tool-calling behavior: valid no-parameter tools produce empty, invalid JSON arguments during streaming and fail unexpectedly.

### Evidence
- `streamText` emits an empty string for the arguments of a parameterless Anthropic tool, then attempts to parse it as JSON and throws `AI_InvalidToolArgumentsError` / `AI_JSONParseError`.
- The reporter provided a reproducible `z.object({})` tool definition and confirmed the same tool works with `generateText` but fails with `streamText`.
- Other users reported similar failures, including behavior that had worked days earlier, and a maintainer linked a corrective pull request (#3073).
