### ISSUE TITLE
useObject hook's isLoading and stop functionality not working as expected during streaming

### ISSUE THREAD

**Issue by coji** [vercel/ai#2122]
### Description

When using the `useObject` hook from the Vercel AI SDK with Next.js and OpenAI, two main issues are encountered:

1. The `isLoading` state becomes `false` prematurely, as soon as the first chunk of the stream is received, instead of remaining `true` until the entire object is received.
2. The `stop` function only works before the streaming starts. Once the streaming begins, it's not possible to stop the ongoing stream.

These issues make it difficult to properly indicate the loading state and prevent users from interrupting an ongoing stream.

To reproduce this issue:

1. Clone the Vercel AI SDK repository.
2. Navigate to the `examples/next-openai` directory.
3. Install dependencies and run the example application.
4. Replace the content of `app/page.tsx` with the code provided in the "Code Example" section below.
5. Run the application and click the "Generate notifications" button.
6. Observe that the `isLoading` state becomes `false` as soon as the first notification appears, even though more notifications are still being generated.
7. Try clicking the "STOP" button after notifications start appearing. Note that it has no effect on the ongoing stream.

Expected behavior:
- The `isLoading` state should remain `true` until the entire object has been received and parsed.
- The `stop` function should be able to interrupt the stream at any point during the streaming process.

Actual behavior:
- `isLoading` becomes `false` as soon as the first chunk of the stream is received.
- `stop` only works before the streaming starts. Once streaming begins, it has no effect.

### Code example

```tsx:app/use-object/page.tsx
"use client";

import { experimental_useObject as useObject } from "ai/react";
import { notificationSchema } from "../api/use-object/schema";

export default function Page() {
  const { submit, isLoading, object, stop } = useObject({
    api: "/api/use-object",
    schema: notificationSchema,
  });

  return (
    <div className="flex flex-col items-center min-h-screen p-4 m-4">
      <button
        className="px-4 py-2 mt-4 text-white bg-blue-500 rounded-md disabled:bg-blue-200"
        onClick={async () => {
          submit("Messages during finals week.");
        }}
        disabled={isLoading}
      >
        Generate notifications
      </button>

      {isLoading && (
        <div className="mt-4 text-gray-500">
          <div>Loading...</div>
          <button
            type="button"
            className="px-4 py-2 border-blue-500 border rounded-md text-blue-500  mt-4"
            onClick={() => stop()}
          >
            STOP
          </button>
        </div>
      )}

      <div className="flex flex-col gap-4 mt-4">
        {object?.notifications?.map((notification, index) => (
          <div
            className="flex items-start gap-4 p-4 bg-gray-100 rounded-md dark:bg-gray-800"
            key={index}
          >
            <div className="flex-1 space-y-1">
              <div className="flex items-center justify-between">
                <p className="font-medium dark:text-white">
                  {notification?.name}
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  {notification?.minutesAgo}
                  {notification?.minutesAgo != null ? " minutes ago" : ""}
                </p>
              </div>
              <p className="text-gray-700 dark:text-gray-300">
                {notification?.message}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
```

### Additional context

This issue was reproduced by modifying the `next-openai` example from the Vercel AI SDK repository. The problem is consistent with the behavior observed in this modified example application.

Environment:
- Nodejs: v20.13.0
- Vercel AI SDK versions:
  - @ai-sdk/openai: 0.0.34
  - @ai-sdk/react: 0.0.12
  - ai: 3.2.12
- React version: 18.3.1
- Next.js version: 14.2.4
- AI Provider: OpenAI

This issue impacts the user experience as it's currently not possible to accurately represent the loading state or allow users to interrupt an ongoing stream once it has started. In the context of generating multiple notifications, users cannot see when the generation is complete, nor can they stop the generation process if they are satisfied with the current results.

I have recorded a video demonstrating this behavior:

https://github.com/vercel/ai/assets/9904/d11cf085-a709-4629-86bc-380a6c272819

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2126

**Comment by coji** [comment]
Thanks for the fix. I've noticed a minor follow-up issue: `isLoading` remains `true` after calling `stop()`.

New issue: https://github.com/vercel/ai/issues/2130

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Existing `useObject` state and cancellation APIs behave incorrectly during streaming, with concrete reproduction steps, expected behavior, and actual behavior.

### Evidence
- The report gives reproducible cases where `useObject` sets `isLoading` to `false` after the first streamed chunk rather than after stream completion.
- It also reports that the existing `stop()` function cannot interrupt a stream once streaming has begun.
- A maintainer linked pull request #2126 as a fix; a separate follow-up bug was filed for loading state after stopping.
