### ISSUE TITLE
Invalid request call with empty zod schema tool parameter

### ISSUE THREAD

**Issue by agusmoles** [vercel/ai#2171]
### Description

Im getting this issue when trying to set an empty parameters object with `streamUI`

![image](https://github.com/vercel/ai/assets/28370654/dab147ad-71cd-4f50-b2da-60b05fc6f17e)

I cannot pass an empty zod object schema to the `parameters` attribute of the tools. I tried `z.object({})` (which worked before somehow, with previous versions I think), `z.record(z.never())` and none works.

What actually fixes it (but its wrong from the logic perspective), is:

```ts
parameters: z.object({
          noParam: z.number(),
        })
```

### Code example

```ts
 const result = await streamUI({
    model: google("models/gemini-1.5-flash-latest"),
    presencePenalty: 0.7, // avoid repetition of already said things in the prompt
    maxRetries: 0,
    system: `....`,
    messages: [...history.get(), { role: "user", content: input }],
    text: ({ content, done }) => {
      if (done) {
        history.done((messages: ServerMessage[]) => [
          ...messages,
          { role: "assistant", content },
        ]);
      }

      return content;
    },
    tools: {
     toolFunc: {
        description: "...",
        parameters: z.record(z.never()), // this fails
        generate: async () => {
          history.done((messages: ServerMessage[]) => [
            ...messages,
            {
              role: "assistant",
              content: '...',
            },
          ]);

          return (
            <>
              { // something ... }
            </>
          );
        },
      },
    },
  })
```

### Additional context

Package versions:

```
    "ai": "^3.2.16",
    "@ai-sdk/google": "^0.0.24",
    "zod": "^3.23.8"
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3073

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure of existing tool parameter handling: parameterless tools cannot use an empty Zod schema and cause the request to fail.

### Evidence
- `streamUI` throws an "invalid argument" runtime error when a tool uses an empty Zod parameter schema.
- The reporter states `z.object({})` had worked in earlier versions, suggesting a regression.
- Adding an artificial required property avoids the error, but changes the tool's intended semantics.
- A maintainer linked PR #3073, indicating a code-level fix.
