### ISSUE TITLE
Context Caching (for Gemini)

### ISSUE THREAD

**Issue by Legit4K** [vercel/ai#2181]
### Feature Description

"In a typical AI workflow, you might pass the same input tokens over and over to a model. Using the Gemini API context caching feature, you can pass some content to the model once, cache the input tokens, and then refer to the cached tokens for subsequent requests. At certain volumes, using cached tokens is lower cost than passing in the same corpus of tokens repeatedly.

When you cache a set of tokens, you can choose how long you want the cache to exist before the tokens are automatically deleted. This caching duration is called the time to live (TTL). If not set, the TTL defaults to 1 hour. The cost for caching depends on the input token size and how long you want the tokens to persist."

### Use Case

"Context caching is particularly well suited to scenarios where a substantial initial context is referenced repeatedly by shorter requests. Consider using context caching for use cases such as:

- Chatbots with extensive system instructions
- Repetitive analysis of lengthy video files
- Recurring queries against large documents
- Frequent code repository analysis or bug fixing"

### Additional context

Both the native Gemini API and Vertex API released this for stable versions of Gemini 1.5 Flash and 1.5 Pro

would be really helpful if I can create and work with the caches directly within the AI SDK

https://ai.google.dev/gemini-api/docs/caching

**Comment by NirmalManoj** [comment]
+1 to this. Please provide a timeline for implementing this, @vercel team.

**Comment by lgrammel** [comment]
Would it be sufficient for you to be able to set the `cachedContent` name?

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2261

**Comment by kosukekurimoto** [comment]
Hello, is there any plan to add Context Caching to the Vertex provider as well?

**Comment by cooliopas** [comment]
Hi. Is there a specific reason why Context Caching (using Gemini) is only available on ai-sdk/google but is not available on @ai-sdk/google-vertex ?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request to add context-caching support and expand provider capabilities, with no concrete failure of existing documented behavior.

### Evidence
- The issue requests the ability to create and use Gemini context caches directly through the AI SDK.
- The description presents context caching as newly available functionality in the Gemini and Vertex APIs, not as broken existing SDK behavior.
- Later comments ask for the same capability in the Google Vertex provider.
