### ISSUE TITLE
Provider APIs (`doStream`, et al.) are not usable outside of AI SDK

### ISSUE THREAD

**Issue by AaronFriel** [vercel/ai#2196]
### Description

The Provider APIs `doStream` and `doGenerate` are publicly exported, but not genuinely usable without extracting functionality from the AI SDK that is not exported.

These APIs take a `prompt` parameter defined here:

https://github.com/vercel/ai/blob/3db90c3d44b5e4de6c7414bd6a970d166356ba94/packages/provider/src/language-model/v1/language-model-v1-prompt.ts#L1-L12

As the comment observes, "This is not a user-facing prompt." Indeed. Generating valid instances of this type from `CoreMessage` is performed in multiple steps using non-public functions. Here in `streamText`, the `getValidatedPrompt` and `convertToLanguageModelPrompt` functions are private to the core package:

https://github.com/vercel/ai/blob/3db90c3d44b5e4de6c7414bd6a970d166356ba94/packages/core/core/generate-text/stream-text.ts#L146-L159

Likewise in the definitions for `generateText`, `generateObject`, `streamObject`, and `streamUI`.

### Code example

n/a

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **Medium**

### Rationale
This requests an API expansion or ergonomics improvement by exposing the prompt-conversion functionality needed for direct provider API use. It does not identify a documented promise that the current behavior violates.

### Evidence
- `doStream` and `doGenerate` accept a non-user-facing provider prompt type.
- Converting `CoreMessage` values into that prompt relies on private `getValidatedPrompt` and `convertToLanguageModelPrompt` functions.
- The issue seeks publicly usable access to provider-level APIs outside the AI SDK core flow.
