### ISSUE TITLE
Error in implementing in nodejs 

### ISSUE THREAD

**Issue by KrishnaCodez** [vercel/ai#2213]
### Description

Hi Vercel,

I'm trying to implement AI  in my Node.js application, i copy paste the code that is available doc but I'm encountering an error. I'd appreciate some assistance in troubleshooting.

The error message I'm getting is:- 

### Code example

node_modules/@ai-sdk/ui-utils/node_modules/@ai-sdk/provider-utils/dist/index.d.ts(134,5): error TS2502: 'fetch' is referenced directly or indirectly in its own type annotation.
[0] node_modules/@ai-sdk/ui-utils/node_modules/@ai-sdk/provider-utils/dist/index.d.ts(149,5): error TS2502: 'fetch' is referenced directly or indirectly in its own type annotation.  
[0] node_modules/ai/dist/index.d.ts(8,33): error TS2307: Cannot find module 'openai/lib/AssistantStream' or its corresponding type declarations.
[0] node_modules/ai/dist/index.d.ts(9,21): error TS2307: Cannot find module 'openai/resources/beta/threads/runs/runs' or its corresponding type declarations.

### Additional context

node version v20.14.0

**Comment by MaxLeiter** [comment]
Can you please share your typescript version as well? Updating it may resolve this

**Comment by KrishnaCodez** [comment]
my ts version is     "typescript": "^5.1.6"  

and 

tsconfig.json  file :- 
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "sourceMap": true,
    "outDir": "dist",
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*.ts", "src/index.ts"]
}

**Comment by lgrammel** [comment]
Can you share a github repository with a minimal reproduction? I can't reproduce the issue

**Comment by lgrammel** [comment]
@KrishnaCodez i tried your example, but i can't run yarn or another package manager successfully bc it fails to find `@repo/eslint-config`

**Comment by KrishnaCodez** [comment]
@lgrammel i republished repo this it the [link ](https://github.com/CROSS-PLATFORM-AI/ai.git)

**Comment by guywaldman** [comment]
Encountered the same issue.
@lgrammel Seems that the Vercel AI SDK takes a peer dependency on types from [openai](https://www.npmjs.com/package/openai) even for things that don't require OAI integration (`AssistantStream` from [src/lib/AssistantStream.ts](https://github.com/openai/openai-node/blob/master/src/lib/AssistantStream.ts) and `Run` from [src/resources/beta/threads/runs/runs.ts](https://github.com/openai/openai-node/blob/master/src/resources/beta/threads/runs/runs.ts). I believe there was some regression that was introduced with peer deps.

**Comment by KrishnaCodez** [comment]
For me updating ts config file solved my problem. here's what i updated: 

// apps/backend/tsconfig.json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2022",
    "sourceMap": true,
    "outDir": "dist",
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*.ts", "src/index.ts"]
}

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete TypeScript compilation failure in existing AI SDK declarations, including an apparent unintended dependency on OpenAI types for non-OpenAI usage.

### Evidence
- TypeScript compilation fails in AI SDK declaration files with TS2502 and missing `openai` type-module errors.
- The failure persisted when using the Google provider, where OpenAI integration should not be required.
- Another user reproduced the missing OpenAI types and resolved it only by explicitly installing the latest `openai` dependency, suggesting a peer-dependency regression.
