### ISSUE TITLE
Vercel AI SDK Incompatibility with Latest Perplexity API Updates

### ISSUE THREAD

**Issue by judewang** [vercel/ai#2274]
### Description

Recent internal changes in the Perplexity API have caused the integration with the Vercel AI SDK to malfunction.

- The parameters `logprobs` and `top_logprobs` in the SDK configuration are conflicting with the Perplexity API’s validation mechanism.
- The following error message is encountered: `{"error":{"message":"Neither or both of logprobs and top_logprobs must be set.","type":"invalid_parameter","code":400}}`
- Cross-testing with the same configuration using the OpenAI API works correctly without any issues.

```json
"dependencies": {
    "@ai-sdk/openai": "^0.0.13",
    "@vercel/kv": "^1.0.1",
    "ai": "^3.2.22"
  }
```

### Code example

```typescript
import { env } from "@/lib/env";
import { createOpenAI } from "@ai-sdk/openai";
import { kv } from "@vercel/kv";
import { streamText } from "ai";

const perplexity = createOpenAI({
  apiKey: env.PERPLEXITY_API_KEY,
  baseURL: "https://api.perplexity.ai/",
});

export const runtime = "edge";

export async function POST(req: Request) {
  const { messages, key } = await req.json();
  const cached = await kv.get<string>(key);

  if (cached) {
    return new Response(cached);
  }

  const result = await streamText({
    model: perplexity("llama-3-sonar-large-32k-chat"),
    messages,
  });

  return result.toTextStreamResponse();
}
```

### Additional context

Parts of the error logs:

```bash
Translation API error:  [AI_APICallError: Bad Request] {
  name: 'AI_APICallError',
  url: 'https://api.perplexity.ai/chat/completions',
  requestBodyValues: {
  model: 'llama-3-sonar-large-32k-chat',
  logit_bias: undefined,
  logprobs: false,
  top_logprobs: undefined,
  user: undefined,
  max_tokens: undefined,
  temperature: 0,
  top_p: undefined,
  frequency_penalty: undefined,
  presence_penalty: undefined,
  seed: undefined,
  messages: [
  { role: 'system', content: 'You are a Bible-savvy pastor.' },
  {
  role: 'user',
  content: [
  {
  type: 'text',
  text: '...'
}
]
}
],
  tools: undefined,
  stream: true,
  stream_options: { include_usage: true }
},
  statusCode: 400,
  responseHeaders: {
  cf-cache-status: 'DYNAMIC',
  cf-ray: '8a3094bc7f1329e6-FUK',
  connection: 'keep-alive',
  content-length: '119',
  content-type: 'application/json',
  date: 'Sun, 14 Jul 2024 09:45:38 GMT',
  server: 'cloudflare'
},
  responseBody: '{"error":{"message":"Neither or both of logprobs and top_logprobs must be set.","type":"invalid_parameter","code":400}}',
  cause: undefined,
  isRetryable: false,
  data: undefined
}
 POST /api/translate 500 in 631ms
```

The full logs can be found here: https://app.warp.dev/block/qa7yOBBAsZeXfBh1VVloJr

**Comment by lgrammel** [comment]
I have tested this with the following versions: 

-`@ai-sdk/openai`: `0.0.36`
- `ai`: `3.2.23`

It works with this configuration. Can you try updating the openai provider package to the latest version?

**Comment by judewang** [comment]
@lgrammel It worked, thank you for helping.

**Comment by lgrammel** [comment]
@kulterryan please update your packages to the latest versions. We needed to update the language model spec when introducing image/file generation by LLMs, which required all providers to be updated.

**Comment by siddharthd0** [comment]
having the same issue with sources use]: Error: Unhandled chunk type: source

**Comment by lgrammel** [comment]
@siddharthd0 please update your packages to the latest versions.

**Comment by kulterryan** [comment]
hi @lgrammel @siddharthd0!
it's an issue from perplexity end, cloudflare is blocking the api calls made from `edge` runtime

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a resolved dependency-version/support issue, with no confirmed defect in the current AI SDK implementation.

### Evidence
- The reported 400 error occurred with an outdated `@ai-sdk/openai` version (`0.0.13`).
- A maintainer tested `@ai-sdk/openai` `0.0.36` successfully and advised updating.
- The reporter confirmed that updating resolved the issue.
- Later reports were addressed by package updates or attributed to Perplexity/Cloudflare blocking edge-runtime requests.
