### ISSUE TITLE
Object type for `content` is not allowed in `ai@3.x` - blocker for Vision API

### ISSUE THREAD

**Issue by enesozturk** [vercel/ai#2358]
### Description

Object type for the `content` is necessary to work with Vision API and OpenAI is still supporting that structure for their API, see: https://platform.openai.com/docs/guides/vision

`ai` v3 is not accepting object value for the `content` field of the message while v2 does. I'm getting the following error while pushing new message with object for `content`;

```sh
"err": {
    "name": "AI_InvalidPromptError",
    "source": "edge-server",
    "message": "Invalid prompt: system message content must be a string",
    "stack": "AI_InvalidPromptError: Invalid prompt: system message content must be a string.."
}
```

Here is my value for system message:
```sh
{
  role: "system",
  content: [{ type: "text", text: "..my system message.." }],
}
```

This was possible previously. If I switch to string for system message and keep object for other messages, this time it's warning me to use same type for other messages:

```sh
"err": {
    "name": "AI_APICallError",
    "source": "edge-server",
    "message": "Invalid type for 'messages[3].content': expected one of a string or array of objects, but got an object instead.",
    "stack": "AI_APICallError: Invalid type for 'messages[3].content': expected one of a string or array of objects, but got an object instead."
}
```

Why this feature is dropped? Is there any docs to work with Vision API?

### Code example

Here is how I'm using Vision API with v2:

```js
const result = await streamText({
  model: openai("gpt-4o-mini"),
  messages: [
    {
      role: "system",
      content: [{ type: "text", text: "..my system message.." }],
    },
    // ... other messages with object as content type as well
    {
      role: "user",
      content: [
        { type: "text", text: "what is there this picture?" },
        { type: "image_url", text: "IMAGE_URL" },
      ],
    },
  ],
  temperature: 0.5,
  // other params
})
```

### Additional context

Versions
```json
"ai": "3.2.32",
"@ai-sdk/openai": "^0.0.37"
```

**Comment by lgrammel** [comment]
Images / multi-modal messages are supported. Please check out the guide: https://sdk.vercel.ai/docs/foundations/prompts#multi-modal-messages

This could be a new limitation that is specific to `gpt-4o-mini` on the OpenAI side. I'll investigate.

**Comment by lgrammel** [comment]
Just verified that this is working with gpt-4o-mini. Please use this example as a guide: https://github.com/vercel/ai/blob/main/examples/ai-core/src/generate-text/openai-multimodal-url.ts

**Comment by enesozturk** [comment]
@lgrammel thanks for clarifying. Is `generateText` also have streaming feature? I cannot find any reference it's streaming. If I check `streamText`'s [parameters](https://sdk.vercel.ai/docs/reference/ai-sdk-core/stream-text#parameters), it seems it's accepting string for system message and object for others but it's actually not?

**Comment by lgrammel** [comment]
@enesozturk `streamText` and `generateText` have similar prompts. You can use images with both. If you need streaming, use `streamText`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The thread resolves the report as an API-usage/support question rather than a confirmed SDK failure or requested product change.

### Evidence
- Maintainer verified multimodal messages work with `gpt-4o-mini` and linked a working example.
- The reported system message uses an unsupported array value where system content is expected to be a string.
- The follow-up asks how streaming relates to `generateText`; the maintainer clarifies that images work with both APIs and recommends `streamText` for streaming.
