### ISSUE TITLE
sswr is a dependency not an optional dependency in core.

### ISSUE THREAD

**Issue by snikch** [vercel/ai#2393]
### Description

Currently the `sswr` package is a dependency rather than an optional `peerDependency` like `svelte` is. Since it's only used in files imported `svelte` I could imagine it should be an optional peer dependency.

For us with the latest Yarn berry, it's causing `svelte` to become a required peer dependency.

```
Package xxx@workspace:apps/xxx is requested to provide svelte by its descendants

xxx@workspace:apps/xxx
└─ ai@npm:3.2.16 [27343] (via ^3.0.0 || ^4.0.0)
   ├─ @ai-sdk/svelte@npm:0.0.12 [8cf46] (via ^3.0.0 || ^4.0.0)
   │  └─ sswr@npm:2.1.0 [aacbc] (via ^4.0.0 || ^5.0.0-next.0)
   └─ sswr@npm:2.1.0 [aacbc] (via ^4.0.0 || ^5.0.0-next.0)

✘ Package xxx@workspace:apps/xxx does not provide svelte.
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports incorrect package dependency configuration that causes an unintended peer-dependency requirement in existing installations.

### Evidence
- The `ai` package installs `sswr` as a regular dependency even though it is only used by Svelte-related imports.
- With Yarn Berry, this dependency chain incorrectly makes `svelte` a required peer dependency for projects not providing Svelte.
- A maintainer linked PR #2398 in response, indicating a concrete fix.
