### ISSUE TITLE
OpenAIStream should handle 'function_call' on the server side

### ISSUE THREAD

**Issue by onionhammer** [vercel/ai#244]
Currently it's very difficult to handle 'streaming' if any function calls are being invoked by openai

OpenAIStream should be able to handle streaming function call (ala https://platform.openai.com/docs/guides/gpt/function-calling ) by giving a promise-based callback for function calls to interrupt and run additional queries.

**Comment by MaxLeiter** [comment]
This will be implemented in https://github.com/vercel-labs/ai/pull/178

**Comment by onionhammer** [comment]
@MaxLeiter this only seems to handle client-side functions, right?

**Comment by onionhammer** [comment]
@MaxLeiter can we reopen this now since that PR doesn't address this? Or do you have another issue to track?

**Comment by MaxLeiter** [comment]
The (heavily work in progress) PR is here: #311

**Comment by onionhammer** [comment]
@MaxLeiter With this callback-based approach, it seems pretty unwieldy to loop and handle multiple requested function calls from OpenAI in a row; are there any samples?

**Comment by onionhammer** [comment]
@MaxLeiter Ahh thanks. What about if `get_weather` and `get_location` are only available if a function called `get_personal` is called, how would you 'scope' it? 

For example, your bot might have different  functions available to it if the user is asking about the weather than if they're asking about recipes.

**Comment by MaxLeiter** [comment]
You can pass a different `functions` argument to the openai call

**Comment by onionhammer** [comment]
> You can pass a different `functions` argument to the openai call

Got it, then you just have a single `experimental_onFunctionCall` to handle all possible calls in 1 place, like a grand central station of function calls..

**Comment by MaxLeiter** [comment]
> Got it, then you just have a single experimental_onFunctionCall to handle all possible calls in 1 place, like a grand central station of function calls..

Exactly, it's recursive. I'll try and make this more clear in the docs!

>Another issue I'm seeing is that it's not handling Azure OpenAI responses, which dont send a function_call in the first chunk of data streamed back, instead it sends back some information about obscenities/harrassment etc first.

Interesting, I didn't realize functions were treated differently. Thanks for the report, I'll take a look.

**Comment by olegkorol** [comment]
Hi @MaxLeiter,

I _used to_ achieve recursive function calls in a similar way to what you describe above:

```typescript
const stream = OpenAIStream(initialResponse, {
  async experimental_onFunctionCall({name, arguments: args}, createFunctionCallMessages) {
    console.log('function call needed:', name, args)

    const functionResult = await runFunction(name, args);
    console.log('function result:', functionResult)

    const newMessages = createFunctionCallMessages(functionResult);

    return openai.chat.completions.create({
      model: GPT_MODEL,
      stream: true,
      messages: [...messages, ...newMessages],
      functions,
      function_call: 'auto'
    })
  },
  
  // ...

})
```

Now I am testing the new `ai/rsc` with generative UI and wonder if/how I can achieve the same behaviour.

Thanks!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Although the issue began as a feature request, the comments identify a concrete failure in the implemented `OpenAIStream` function-call handling for Azure OpenAI responses. A concrete existing-behavior failure takes precedence.

### Evidence
- The original request sought server-side handling of streamed OpenAI function calls through a callback.
- After the callback API was implemented, the reporter identified a concrete failure: Azure OpenAI streams are not handled when moderation metadata precedes the `function_call` chunk.
- A maintainer acknowledged the Azure behavior as a report to investigate.
