### ISSUE TITLE
does @ai-sdk/google-vertex support claude 3.5?

### ISSUE THREAD

**Issue by lgrammel** [vercel/ai#2441]
### Discussed in https://github.com/vercel/ai/discussions/2440

<div type='discussions-op-text'>

<sup>Originally posted by **nalaso** July 28, 2024</sup>
I am using the @anthropic-ai/vertex-sdk, and it works fine with Claude 3.5. However, when I use the same region and project ID with @ai-sdk/google-vertex, it says:

"ClientError: [VertexAI.ClientError]: got status: 429 Too Many Requests. {"error":{"code":429,"message":"Quota exceeded for aiplatform.googleapis.com/generate_content_requests_per_minute_per_project_per_base_model with base model: anthropic-claude-3-5-sonnet. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.","status":"RESOURCE_EXHAUSTED"}"

Interestingly, the @anthropic-ai/vertex-sdk still works without any error, and I am on a pay-as-you-go plan. There is no way to increase the quota.

the error appers in both streamText and generateText

const vertex = createVertex({
  project: process.env.Vertex_Ai_ProjectID,
  location: process.env.Vertex_Ai_Location,
});

const { text } = await generateText({
  model: vertex('claude-3-5-sonnet@20240620'),
  prompt: content
})

    [https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex#model-capabilities](https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex#model-capabilities)
    
    And yeah gemini models works fine with @ai-sdk/google-vertex</div>

**Comment by nalaso** [comment]
I just found out @google-cloud/vertexai doesnt't support thrid party models like claude. [https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude#use_the_anthropic_sdk](https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude#use_the_anthropic_sdk)

[https://docs.anthropic.com/en/api/claude-on-vertex-ai](https://docs.anthropic.com/en/api/claude-on-vertex-ai) - @anthropic-ai/vertex-sdk and rest apis are the only ways to access claude from vertex ai.

**Comment by nalaso** [comment]
May I know if there is any workaround to use @anthropic-ai/vertex-sdk with generateText?

**Comment by HamedMP** [comment]
I'd love to do this too, the Anthropic server is too busy and I need to self-host it for performance.

**Comment by lgrammel** [comment]
Duplicate of #1813

**Comment by dielect** [comment]
I messed around for at least 2 hours. I always thought it was my configuration issue. Luckily, I searched for the relevant problem again.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support question and duplicate rather than a distinct report of broken documented behavior or a standalone feature proposal.

### Evidence
- The title and follow-up ask whether Claude 3.5 is supported and whether there is a workaround for using `@anthropic-ai/vertex-sdk` with `generateText`.
- The reporter later determined that `@google-cloud/vertexai` does not support third-party models such as Claude.
- A maintainer marked the issue as a duplicate of #1813.
