### ISSUE TITLE
LangchainAdapter/endpoint sends incorrect traces when deployed to vercel

### ISSUE THREAD

**Issue by yelouafi** [vercel/ai#2478]
### Description

I'm using LangchainAdapter as in the docs to convert langchain stream into ai stream. I've enabled langsmith tracing using the following env vars as per langsmith docs

```
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="..."
```

When I run locally the runs are correctly logged into langsmith, but on vercel the behavior is erratic: sometimes it's not logged at all, and somtimes it's logged with incorrect latency times

<img width="1031" alt="Screenshot 2024-07-30 at 14 01 11" src="https://github.com/user-attachments/assets/98f9df4e-757b-4cce-b247-b3ccaa3c4136">

### Code example

I'm using the following code in the api endpoint

```ts
const chain = await getQAChain();
const stream = await chain.stream(prompt);
const aiStream = LangChainAdapter.toDataStream(stream);
const response = new StreamingTextResponse(aiStream);
return response;
```

**Comment by lgrammel** [comment]
Is this issue related to the AI SDK, or does it happen when you deploy LangChain on Vercel (independent of the AI SDK)?

**Comment by yelouafi** [comment]
okk I think I found the fix. We need to call [`awaitAllCallbacks`](https://docs.smith.langchain.com/how_to_guides/tracing/trace_with_langchain#ensure-all-traces-are-submitted-before-exiting) 

```ts
import { awaitAllCallbacks } from "@langchain/core/callbacks/promises";
// ...

try {
  const stream = await chain.stream(prompt);
  const aiStream = LangChainAdapter.toDataStream(stream);
  const response = new StreamingTextResponse(aiStream);
  return response;
} finally {
   await await awaitAllCallbacks();
}
```

**Comment by yelouafi** [comment]
> Is this issue related to the AI SDK, or does it happen when you deploy LangChain on Vercel (independent of the AI SDK)?

I suppose it'll happen if we don't await the callbacks. Maybe the langchain adapter should await the callbacks by default, or just add mention to the docs

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete failure in an existing adapter workflow on Vercel. Although the underlying callback requirement may originate in LangChain and a documentation fix is suggested, the reported current behavior is broken, so bug is the best classification.

### Evidence
- LangChainAdapter-based streaming on Vercel intermittently omits LangSmith traces or records incorrect latency values, while local runs work.
- The reporter identified that pending LangChain tracing callbacks must be awaited before the serverless invocation exits.
- They suggest the adapter could await callbacks automatically, with documentation as an alternative.
