### ISSUE TITLE
fix: Fixing tools working with generative-ai (Google) and streamText

### ISSUE THREAD

**Issue by YBeletsky117** [vercel/ai#2487]
### My suggestion

```diff
diff --git a/node_modules/@ai-sdk/google/dist/index.js b/node_modules/@ai-sdk/google/dist/index.js
index 9f4b89b..444fe6a 100644
--- a/node_modules/@ai-sdk/google/dist/index.js
+++ b/node_modules/@ai-sdk/google/dist/index.js
@@ -390,6 +390,10 @@ var GoogleGenerativeAILanguageModel = class {
                   args: toolCall.args
                 });
                 hasToolCalls = true;
+                finishReason = mapGoogleGenerativeAIFinishReason({
+                  finishReason: candidate.finishReason,
+                  hasToolCalls
+                });
               }
             }
           },
```

**Comment by lgrammel** [comment]
The `hasToolCalls` flag is used earlier for any chunk candidate that has a finishReason.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This describes allegedly incorrect existing streaming behavior involving tool calls and finish reasons. Although the maintainer questions the suggested implementation change, the core report is a concrete behavioral failure.

### Evidence
- The report says Google Generative AI with `streamText` emits an end-of-stream status even though discovered tool calls mean processing should continue.
- The proposed patch recalculates `finishReason` after setting `hasToolCalls` to correct the stream status.
- A maintainer notes that `hasToolCalls` is already used when processing chunk candidates with a `finishReason`, casting doubt on the proposed fix but not fully resolving the reported failure.
