### ISSUE TITLE
onFinish callback for experimental_useObject

### ISSUE THREAD

**Issue by clasnake** [vercel/ai#2492]
### Feature Description

Is is possible to add an onFinish callback for experimental_useObject so that we can add custom logic at client side when the stream finishes? There is the onError callback on client side, onFinish callback on server side for streamObject, but I can't find onFinish on client side.

### Use Case

Perform custom actions when the stream completes, e.g., url redirecting, client logs, etc

**Comment by lgrammel** [comment]
Duplicates #2289

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for an API capability that is not currently available, so it is a feature request despite being marked as a duplicate.

### Evidence
- The issue requests a new client-side `onFinish` callback for `experimental_useObject`.
- The stated use cases are custom actions after stream completion, such as redirects and client logging.
- A maintainer notes that the request duplicates #2289; no broken existing behavior is described.
