### ISSUE TITLE
Support new llama models for perplexity AI

### ISSUE THREAD

**Issue by taylor-lindores-reeves** [vercel/ai#2498]
### Feature Description

New models released recently: https://docs.perplexity.ai/docs/model-cards

Latest version of OpenAI SDK package (v0.0.40) and Vercel AI (v3.2.41) do not support. Error message when attempting to use the new models:

`Invalid model 'llama-3.1-sonar-large-128k-online'. Permitted models can be found in the documentation at https://docs.perplexity.ai/docs/model-cards.`

**Comment by lgrammel** [comment]
You can pass any string. The message that you are receiving is from the perplexity backend.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
No AI SDK behavior change is required; the reported limitation is external to the repository and was resolved as a support clarification.

### Evidence
- The reporter requests support for a newly released Perplexity model after receiving an invalid-model error.
- A maintainer clarifies that the AI SDK accepts any model string and that the error originates from Perplexity's backend.
