### ISSUE TITLE
Back-to-back client-side function calling

### ISSUE THREAD

**Issue by odysseaspapadimas** [vercel/ai#257]
First of all I would like to thank all of the people that worked on implementing function calling with this package, this is an amazing update and really helpful for the app I'm developing

I got function calling to work just fine after copying the code from the example and one of the use cases I have is if the user asks to scan a barcode to redirect the user to another page(I'm using Next.js) which is simple enough. Just define the function on the server and check for it in the front-end and it works BUT I would first like to inform the user that they're about to be redirected in the form of a chat response so the workaround I thought would work would be to first call a function called `scan_barcode` that looks like this

```jsx
{
    name: "scan_barcode",
    description:
      "You might be a text based assistant but you have the capability to redirect the user and this will redirect the user to a barcode scanner. Inform the user that they will be redirected and then call the redirect_to_qr_scanner function",
    parameters: {
      type: "object",
      properties: {},
      required: [],
    },
  },
```

And then on the front-end I handle it like this
```jsx
else if (functionCall.name === "scan_barcode") {
      const functionResponse: ChatRequest = {
        messages: [
          ...chatMessages,
          {
            id: nanoid(),
            name: "scan_barcode",
            role: "function" as const,
            content: "",
          },
        ],
        functions: [
          {
            name: "redirect_to_qr_scanner",
            description: "Redirect to QR scanner",
            parameters: {
              type: "object",
              properties: {},
              required: [],
            },
          },
        ],
        // You can also (optionally) return a list of functions here that the model can call next
        // functions
      };
      return functionResponse;
    } else if (functionCall.name === "redirect_to_qr_scanner") {
      router.push("/qr");
    } 
```
I expected this to inform the user that they're about to be redirected and then call the redirect function, I tried to follow the comment's instructions and just pass a redirect function like so but then the chat responds like this

> Sure! Please use the barcode scanner on your device to scan the barcode.{"function_call": {"name": "redirect_to_qr_scanner", "arguments": "{}"}}

I'm probably just doing something wrong as this is pretty new and a bit confusing but any help would be greatly appreciated, thank you!

**Comment by Zakinator123** [comment]
I think this is the same [issue](https://github.com/vercel-labs/ai/pull/178#issuecomment-1611764727) @Archimagus was seeing, where the model would return text and a function call in the same response. I believe he added a fix to it in his svelte branch (though I'm not seeing it in #258 yet). Another thing you can try is forcing the model to use the redirect function. You'll notice that the `ChatRequest` type returned by the `FunctionCallHandler` can optionally take in `functions` as well as a `function_call` string, which by default is `'auto'`. `'auto'` means that its up to the model to choose which function to call, whereas if you pass in a specific function name, corresponding to one of the functions in the `functions` object, the model will be forced to use that function in its response. Here's the `ChatRequest` type for reference:
``` typescript
type ChatRequest = {
    messages: Message[];
    options?: RequestOptions;
    functions?: Array<ChatCompletionFunctions>;
    function_call?: CreateChatCompletionRequestFunctionCall;
};
```

**Comment by Archimagus** [comment]
The fix in the svelte branch is this.

```
    // Check to see if there is a function, so we don't bother parsing if there isn't one.
    const functionStart = streamedResponse.indexOf('{')
    if (functionStart !== -1) {
      const matches = /(.*?)(?:({"function_call".*?}})(.*))?$/gs.exec(
        streamedResponse
      )
      responseMessage.content = `${matches?.[1] ?? ''}${matches?.[3] ?? ''}`
      // While the function call is streaming, it will be a string.
      responseMessage.function_call = matches?.[2]
    } else {
      responseMessage.content = streamedResponse
    }
```

It's not exactaly where I'd like it to be, as it starts printing out the function call untill it is able to find the whole thing, then it splits it out to the funtion.  I would like to change it to detect that a funtion call stream has started, and redirect it all to the funtion_call part of the response, but also have the code clean.

But it works to split out calls that contain functions, you just see them in the response for a while.  This same code could be added to the React part.  But ideally all this logic should be abstracted out, so all the implemenetations work the same.

**Comment by odysseaspapadimas** [comment]
> The fix in the svelte branch is this.
> 
> ```ts
>     // Check to see if there is a function, so we don't bother parsing if there isn't one.
>     const functionStart = streamedResponse.indexOf('{')
>     if (functionStart !== -1) {
>       const matches = /(.*?)(?:({"function_call".*?}})(.*))?$/gs.exec(
>         streamedResponse
>       )
>       responseMessage.content = `${matches?.[1] ?? ''}${matches?.[3] ?? ''}`
>       // While the function call is streaming, it will be a string.
>       responseMessage.function_call = matches?.[2]
>     } else {
>       responseMessage.content = streamedResponse
>     }
> ```
> 
> It's not exactaly where I'd like it to be, as it starts printing out the function call untill it is able to find the whole thing, then it splits it out to the funtion. I would like to change it to detect that a funtion call stream has started, and redirect it all to the funtion_call part of the response, but also have the code clean.
> 
> But it works to split out calls that contain functions, you just see them in the response for a while. This same code could be added to the React part. But ideally all this logic should be abstracted out, so all the implemenetations work the same.

I'm sorry I don't quite understand where I need to use this code, could you or @Zakinator123 help me figure this out?

**Comment by Archimagus** [comment]
This code is in 
`packages/core/react/use-chat.ts`
in the verce-labs/ai repo (or rather, in this PR to add it to the vercel repo), That change will need to be either abstracted out, or coppied to the react and vue packages as well.

For now, you could try and do something similar in your chat hanlder to parse the incoming chat messages, but hopefully we can get this PR merges soon, and a similar (or better) fix pushed to the react code.

**Comment by odysseaspapadimas** [comment]
> This code is in `packages/core/react/use-chat.ts` in the verce-labs/ai repo (or rather, in [This PR](https://github.com/vercel-labs/ai/pull/258) to add it to the vercel repo), That change will need to be either abstracted out, or coppied to the react and vue packages as well.
> 
> For now, you could try and do something similar in your chat hanlder to parse the incoming chat messages, but hopefully we can get this PR merges soon, and a similar (or better) fix pushed to the react code.

Oh I see, well I won't be on this until monday again so I hope it's fixed by then, thank you so much!

**Comment by odysseaspapadimas** [comment]
Can someone help me with this by providing a complete example? I've went over the new changes and I just can't get it to work, I believe the flow should be something like this

User sends messages 'Scan a barcode' -> Server recognizes function call -> Sends response 'Opening QR Scanner' -> After response ends call openQr() in client code

What I tried doing was handle the scan_barcode function server-side like this
```tsx
       if (name === "scan_barcode") {
          const newMessages = createFunctionCallMessages(
            "Sure, opening QR Scanner shortly"
          );

          return openai.createChatCompletion({
            //@ts-ignore
            messages: [...messages, ...newMessages],
            stream: true,
            model: "gpt-3.5-turbo-0613",
            functions,
            function_call: {name: "open_qr_scanner"}
          });
        }
```
I thought this would produce the result I want but it just directly opens the QR scanner

Essentially what I want to understand how to do is: User wants to execute an action, chat responds and then performs the action

**Comment by odysseaspapadimas** [comment]
I see @MaxLeiter, well thank you for your wonderful work so far and I'll be waiting for these amazing changes

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a bug because mixed text-and-function-call responses are parsed incorrectly and expose the serialized function call to the user. The requested multi-step capability adds a feature aspect, but the concrete parsing failure takes precedence.

### Evidence
- The SDK renders the raw `{"function_call": ...}` payload as chat text when the model returns text and a function call in the same streamed response.
- Comments identify parsing in `use-chat.ts` as the cause and propose detecting function calls anywhere in the response stream.
- Although a maintainer notes that the broader multi-step workflow was still being implemented, the issue also contains a concrete failure in existing response parsing.
