### ISSUE TITLE
Add Structured Outputs (OpenAI)

### ISSUE THREAD

**Issue by arnau01** [vercel/ai#2573]
### Feature Description

Leverage new OpenAI new update on safe structured outputs.

https://openai.com/index/introducing-structured-outputs-in-the-api/

### Use Case

- Improvement to `generateObject`
- Additionally be able to use this at the same type as `generateText` with tool calling

**Comment by BrianHung** [comment]
https://github.com/vercel/ai/blob/0a2702eca9ec3cb6c690248abe51ff548b6afbc5/packages/openai/src/openai-chat-language-model.ts#L618 would be a good starting point, as strict is not copied over.

**Comment by lgrammel** [comment]
WIP: https://github.com/vercel/ai/pull/2582

**Comment by lgrammel** [comment]
Available in `ai@3.3.3` and `@ai-sdk/openai@0.0.43` with the `structuredOutputs` option for OpenAI chat models:

```ts
const {object} = await generateObject({
  model: openai('gpt-4o-2024-08-06', {
    structuredOutputs: true,
  }),
  schema: z.object({
    recipe: z.object({
      name: z.string(),
      ingredients: z.array(
        z.object({
          name: z.string(),
          amount: z.string(),
        }),
      ),
      steps: z.array(z.string()),
    }),
  }),
  prompt: 'Generate a lasagna recipe.',
});
```

**Comment by brc-dd** [comment]
Just a heads up for others, if you're getting errors like this with `structuredOutputs`, replace `.optional()` or `.nullish()` with `.nullable()`

```
AI_APICallError: Invalid schema for response_format 'response': In context=(), 'required' is required to be supplied and to be an array including every key in properties. Missing 'foo'
```

**Comment by bernaferrari** [comment]
Shouldn't vercel ai fix this? Change the zod destructuring to do this.

**Comment by BrianHung** [comment]
Official documentation on this:
https://platform.openai.com/docs/guides/structured-outputs/supported-schemas

**Comment by lgrammel** [comment]
@brc-dd @bernaferrari 

This is a limitation of the OpenAI implementation. Other providers will not have this. Therefore I don't want to put in any magic, it's imo on the user / OpenAI to solve this.

Potential solutions:
a) clear error messages
b) docs around this, e.g. tips & troubleshooting

**Comment by brc-dd** [comment]
Yeah. I also think this SDK's behavior is fine. Maybe just a note in `structuredOutputs` section suggesting that some schema's might not work should be sufficient.

**Comment by crivano** [comment]
Will `structuredOutputs` be implemented for the "streamText" method? I have an application that streams a long JSON to the client and it would be great if I could use the `structuredOutputs` constraint.

**Comment by lgrammel** [comment]
@crivano `structuredOutputs` are a flag on openai models in the AI SDK. You can use `streamObject` if you want to stream structured JSON.

**Comment by crivano** [comment]
@lgrammel , it worked perfectly! Thank you!

**Comment by pommedeterresautee** [comment]
@lgrammel is it possible to have structured output enabled with stream text? (aka when a tool is called by OpenAI last GPT model) So far it doesn't work in our code...


```ts
       const hasTools = Object.keys(tools).length > 0;
        const modelOptions = {
          structuredOutputs: true,
          ...(hasTools && { parallelToolCalls: false }),
        };

        const { textStream, text, toolCalls } = await streamText({
          model: openai(model, modelOptions),
          toolChoice:
            toolsChoice === null || !hasTools // when tools are empty, tool_choice must be undefined
              ? undefined
              : toolsChoice,
          messages,
          tools,
          ...
```

**Comment by lgrammel** [comment]
@pommedeterresautee it should work without any extra effort, just enable structured outputs on the model. are you on the latest version of `ai` and `@ai-sdk/openai`? if so, what are you observing that makes you think structured output for tool calling does not work?

**Comment by pommedeterresautee** [comment]
We got a crash from Zod telling us some enum has not been respected (a value not listed)

**Comment by lgrammel** [comment]
@pommedeterresautee enums are difficult for LLMs. The mapping means they'll produce strings. Have you tried adding a description? See also https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#prompt-engineering-with-tools

**Comment by pommedeterresautee** [comment]
We have a description.
If I am not wrong the schema is supposed to contain the authorized values 

https://openai.com/index/introducing-structured-outputs-in-the-api/

![image](https://github.com/user-attachments/assets/1480044f-5ce1-4591-9ee7-de1adcafccca)

What do you mean by your remark.

My understanding is that as they are using constrain generation OpenAI August version of GPT4O should not have the possibility to choose a token which doesn't match the authorized values.

**Comment by bernaferrari** [comment]
You should share the code you are doing

**Comment by pommedeterresautee** [comment]
Tks @bernaferrari and done :-)
@Igrammel -> repro code here https://github.com/vercel/ai/issues/2683

**Comment by crivano** [comment]
This question is more to StackOverflow than to this GitHub issue, but you
can use a partial JSON parser like this one:
https://github.com/promplate/partial-json-parser-js

Em qui., 29 de ago. de 2024 às 10:02, mattkauffman23 <
***@***.***> escreveu:

**Comment by bernaferrari** [comment]
This library does that automatically using streamObject AFAIK. No need for anything else.

**Comment by bernaferrari** [comment]
is structuredOutputs incompatible with `createOpenAI`?

**Comment by gutembergAtJelou** [comment]
Why generateObject does not have and option for toolCalling? Lets say I have a 5 tools that retrieve different values, and then i want to use a model that takes that information and return a structured output.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This issue primarily requests and tracks a new OpenAI provider capability, which was subsequently implemented and released. Later troubleshooting does not supersede the original feature request.

### Evidence
- The description requests support for OpenAI's newly introduced Structured Outputs capability.
- The requested enhancement targets `generateObject` and tool calling with text generation.
- A maintainer linked an implementation PR and announced release of the new `structuredOutputs` model option.
- A later reported enum failure was moved to a separate reproduction issue (#2683).
