### ISSUE TITLE
feat: add exponential backoff to avoid rate limits

### ISSUE THREAD

**Issue by benheckmann** [vercel/ai#2637]
### Feature Description

Currently running into rate limit errors (tokens per minute) using your sdk.

Here is an example:
` ⨯ AI_RetryError: Failed after 3 attempts. Last error: Rate limit reached for gpt-4o-mini in organization org-... on tokens per min (TPM): Limit 200000, Used 199821, Requested 2295. Please try again in 634ms. Visit https://platform.openai.com/account/rate-limits to learn more.`

Would be nice to have an option (with default set to true(?)) for retrying after the limit resets according to the error message or using exponential backoff.

**Comment by benheckmann** [comment]
Found the parameter maxRetries, which does this (and is set to 3 by default).

**Comment by nim442** [comment]
Does it retry with exponential backoff? It's not documented that it does

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
The requested capability already exists, and the thread primarily resolves a usage question. Although a documentation gap is mentioned, there is no explicit request to change the documentation.

### Evidence
- The reporter requested retry/backoff behavior after encountering a rate-limit error.
- The reporter later found the existing `maxRetries` option, which defaults to three retries.
- A later comment confirmed that retries already use exponential backoff; another only noted that this behavior is not documented.
