### ISSUE TITLE
generateObject in Vercel SDK AI does not properly catch JSONParseError in Next.js

### ISSUE THREAD

**Issue by AletzMan** [vercel/ai#2659]
### Description

I'm using the Vercel AI SDK in a Next.js project. When using the generateObject function, I expect a JSONParseError to be caught within a block that checks if the error is of that type. However, even though the console shows that the error is indeed a JSONParseError, the block of code doesn't detect it, and therefore, the error is not handled properly.

### Code example

```
try {
    const result = await generateObject(...);
} catch (error) {
    if (JSONParseError.isJSONParseError(error)) {
        // Handle the error
    } else {
        // Handle other errors
    }
}
```

### Additional context

**Expected Behavior:**

The code should recognize the error as a JSONParseError and execute the corresponding block within the if condition.

**Actual Behavior:**

The error is not recognized as a JSONParseError, even though the console shows that it is, so the block of code that should handle this type of error does not get executed.

Environment:

Next.js Version: 14.2.5
Vercel SDK AI Version: 3.3.0
Node.js Version: 20.9.0

Additional Information:

I've attached a screenshot that shows the error information in the console:
![Screenshot 2024-08-13 154800](https://github.com/user-attachments/assets/0c421847-ac29-4f20-8d40-eea6fc251264)

**Comment by lgrammel** [comment]
thanks for the report. i'll look into a fix.

@AletzMan in the meantime, you can update the ai library and all `@ai-sdk/*` packages to their latest versions and use `JSONParseError.isInstance`.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2661

**Comment by lgrammel** [comment]
fix landed in main

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure of existing SDK error identification behavior, and the maintainer treated it as requiring a code fix.

### Evidence
- `generateObject` throws an error displayed as `JSONParseError`, but `JSONParseError.isJSONParseError(error)` returns false.
- The reporter expected the SDK's error-type check to recognize and handle the thrown parse error.
- A maintainer acknowledged the report, linked PR #2661, and confirmed that a fix landed in main.
