### ISSUE TITLE
Server-managed state

### ISSUE THREAD

**Issue by igor9silva** [vercel/ai#2706]
I'm designing a system on top of the (incredible) AI SDK, and I'm having a hard time managing state on the server. After some ~~trial and~~ error, and a few hours spent reading and hacking with `useChat` (react) and `processChatStream` implementations, I'm leaning towards to think my use case should not be supported at all, but instead be a whole other hook. Or I may be doing something fundamentally wrong.

This issue aims to spark  a discussion, gather opinions, and potentially collaborate more actively with the SDK, instead of beginning a whole new project, which I’m currently considering.

Taking this opportunity to express my deep appreciation for the AI SDK, the people behind it, and all the efforts being made to keep it up with the crazy speed things are changing (Anthropic cache already?!)! Would love to help 😁 

## My use case
- Persistent and immutable chat history, so every message stored in a DB and searchable. Client not able to alter history.
- Dynamically built streamText/Object/UI calls, so what I send to provider is not just raw messages thread.

### Issues I have today
- The client is able to alter history, as every API call sends the whole `messages` object.
- Message IDs are generated client-side, which leads to a few odd behaviors like the latest assistant call being persisted without an ID (as I persist on `streamText`'s `onFinish()`).
- I'm unable to know why the API call was made (new user message? added tool result? retry?), which is very important for my dynamic prompting.

### What I envision
1. Client says to server "append that message: {}" or "fulfill that tool call with: {}"
2. Server builds a `Messages[]` with info from DB + the client-sent object.
3. Server calls provider (or not) and streams back to user (including server generated ID). Persist it `onFinish()`.

This would make the client unable to update history, natural support for server-generated IDs and also transfer way less data (similar idea to Anthropic's new cache).

**Comment by lgrammel** [comment]
This might already be possible:

1. you can fully control what `useChat` sends to the server using `experimental_prepareRequestBody`, e.g. to only send the last message, or to modify the messages: https://sdk.vercel.ai/docs/reference/ai-sdk-ui/use-chat#experimental_prepare-request-body
1. you can then implement custom logic on the server, e.g. loading from db, different prompts, etc

Let me know if that works for you. The reason why a call was made and the ids might still be an issue.

**Comment by igor9silva** [comment]
Hi @lgrammel, thanks for replying and for the support.

I did an attempt with `prepareRequestBody`, but as you predicted I was not able to achieve my goal.

After that I first tried adding a `reason` field on a modified `useChat` implementation. Something like:
```ts
await triggerRequest({ messages }, 'add-tool-result')
await triggerRequest(chatRequest, 'append')
```

But I still find myself constantly fighting against it's client-first design, so I decided to start a new hook "from scratch" (quoted as it heavily inspired by yours). Hope to have something shareable soon.

**Comment by igor9silva** [comment]
I'm looking for a hook that exposes 3-ish actions:

`Load/reload` -> Load state from server.
`Append` -> Append a user message.
`SetToolResult` -> Add a client-side tool result to an assistant message.

**Comment by igor9silva** [comment]
I ended up with a completed different architecture (async queue'd processing) so that doesn't make sense anymore.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a superseded design discussion/support request rather than an active bug, documentation change, example request, or feature proposal.

### Evidence
- The report primarily seeks discussion and guidance about implementing server-managed chat state rather than reporting a documented behavior failure.
- The maintainer suggested existing request customization, while the author clarified they wanted a different hook/API design.
- The author later stated they adopted a different architecture and that the proposal no longer made sense.
