### ISSUE TITLE
Incorrect Link for Google Vertex AI

### ISSUE THREAD

**Issue by TaigoKuriyama** [vercel/ai#2709]
### Description

The link for Google Vertex AI on the Vercel AI SDK providers documentation page (https://sdk.vercel.ai/providers/ai-sdk-providers) is incorrect. Currently, clicking the Google Vertex AI link redirects to `https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai`.

**Steps to Reproduce:**

1. Go to https://sdk.vercel.ai/providers/ai-sdk-providers.
2. Click the link for "Google Vertex AI".
3. Observe the redirection to the incorrect URL.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a documentation defect requiring correction of an incorrect provider-page hyperlink.

### Evidence
- The providers documentation page links “Google Vertex AI” to the Google Generative AI URL.
- The requested correction concerns a broken documentation link, not SDK runtime behavior.
