### ISSUE TITLE
Unknown name minItems - Google AI SDK and OpenAI SDK

### ISSUE THREAD

**Issue by BleedingDev** [vercel/ai#2762]
### Description

I updated to `"@ai-sdk/google": "^0.0.43",` and now I get error. It seems like this SDK tries to use feature that is not supported as stated in issues here:
https://github.com/google-gemini/generative-ai-js/issues/200
https://github.com/google/generative-ai-docs/issues/210

Edit: Seems like this is broken with OpenAI `"@ai-sdk/openai": "^0.0.51",` as well. But only when `structuredOutputs` is true.
```typescript
    model: openai('gpt-4o-mini', {
      structuredOutputs: true
    }),
```

# Error
`Invalid JSON payload received. Unknown name \\"minItems\\" at 'generation_config.response_schema.properties[1].value.items.properties[1].value': Cannot find field.\\nInvalid JSON payload received. Unknown name \\"minItems\\" at 'generation_config.response_schema.properties[1].value': Cannot find field.",\n`

### Code example
```typescript
'use server'
import { generateObject } from 'ai'
import { google } from '@ai-sdk/google'
import { z } from 'zod'
const getQuizSchema = (amountQuestions: number, amountAnswers: number) => {
  const answerSchema = z.object({
    text: z.string(),
    isCorrect: z.boolean(),
  })

  const taskSchema = z.object({
    question: z.string(),
    answers: z.array(answerSchema).length(amountAnswers),
  })

  const quizSchema = z.object({
    chapterName: z.string(),
    tasks: z.array(taskSchema).length(amountQuestions),
  })
  return quizSchema
}

export async function generateQuiz(
  content: string,
  {
    outputLang = 'English',
    amountQuestions = 5,
    amountAnswers = 4,
    allowMultiple = false,
  }: { outputLang?: string; amountQuestions?: number; amountAnswers?: number; allowMultiple?: boolean },
) {
  const schema = getQuizSchema(amountQuestions, amountAnswers)
  const { object } = await generateObject({
    model: google('models/gemini-1.5-flash-latest'),
    schema: schema,
    system: trim`
...
    `,
    prompt: trim`
...
    `,
  })

  return object
}
```

#### Google
Broken in both `tool` and `json` modes.
#### OpenAI
Broken when `structuredOutputs` is `true`.

**Comment by BleedingDev** [comment]
Exactly same schema was working on older version of `"ai": "^3.3.14",`. :(

**Comment by lgrammel** [comment]
The provider JSON specs don't fully support the OpenAPI 3.0 spec (Google) or, as it seems, JSON Schema 7 (OpenAI) fully.

In the OpenAI case, just disable structured outputs.

In the Google case, I'm working on a workaround: #2743

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a reproducible runtime failure in existing structured object generation caused by incompatible JSON Schema conversion, so it is a bug rather than a request for new functionality.

### Evidence
- Updating @ai-sdk/google to 0.0.43 causes generateObject to send unsupported minItems schema fields and fail with an invalid JSON payload error.
- The same schema fails with @ai-sdk/openai 0.0.51 when structuredOutputs is enabled.
- A maintainer confirmed incomplete provider schema support and noted that a Google workaround was in progress in #2743.
