### ISSUE TITLE
More Gemini safety categories

### ISSUE THREAD

**Issue by xl0** [vercel/ai#2767]
### Feature Description

Looks like Google expanded the list of "harmful categories": https://ai.google.dev/api/generate-content#harmcategory

Please add them to  GoogleGenerativeAISettings.

### Use Case

I want to allow unsafe content for all categories.

### Additional context

Yes, I think that having many categories is a bit silly.

**Comment by xl0** [comment]
Actually, Google does not accept the other categories for some reason, only the original 4.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
Although initially framed as a feature request, the follow-up indicates the upstream API does not support the requested categories, leaving no clear actionable SDK enhancement.

### Evidence
- The description requests adding newly listed Gemini harm categories to `GoogleGenerativeAISettings`.
- The author later clarifies that Google rejects those additional categories and accepts only the original four, undermining the requested SDK change.
