### ISSUE TITLE
convertToCoreMessages does not convert Message[] to CoreMessage[]

### ISSUE THREAD

**Issue by wiesenthal** [vercel/ai#2779]
### Description

`convertToCoreMessages` docstring states:
> Converts an array of messages from useChat into an array of CoreMessages that can be used
with the AI core functions (e.g. `streamText`).

The Message interface from useChat defines role as `role: 'system' | 'user' | 'assistant' | 'function' | 'data' | 'tool';`

`convertToCoreMessages` accepts  `role: 'user' | 'assistant' | 'system';`

### Code example

```ts
import { Message } from "@ai-sdk/react";
import { convertToCoreMessages } from "ai";

const messages: Array<Message> = [];
convertToCoreMessages(messages);
```
Error:
```ts
Argument of type 'Message[] | undefined' is not assignable to parameter of type '{ role: "system" | "user" | "assistant"; content: string; toolInvocations?: ToolResult<string, unknown, unknown>[] | undefined; experimental_attachments?: Attachment[] | undefined; }[]'.
  Type 'undefined' is not assignable to type '{ role: "system" | "user" | "assistant"; content: string; toolInvocations?: ToolResult<string, unknown, unknown>[] | undefined; experimental_attachments?: Attachment[] | undefined; }[]'.ts(2345)
  ```

### Additional context

```json
"dependencies": {
    "@ai-sdk/react": "^0.0.50",
    "ai": "^3.3.15"
 }
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2804

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The current API's types prevent the documented conversion of `useChat` messages, constituting a concrete mismatch between existing behavior and documented behavior.

### Evidence
- The documented purpose of `convertToCoreMessages` is to convert messages from `useChat`, but its accepted role union excludes valid `Message` roles such as `function`, `data`, and `tool`.
- Passing `Message[]` from `@ai-sdk/react` to `convertToCoreMessages` produces a TypeScript assignability error.
- A maintainer linked PR #2804 in response, indicating a code-level fix.
