### ISSUE TITLE
Tools call is triggered, but the new tools format does not execute the code.

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#2801]
### Description

When I use the new format for a tools call, it will not trigger the tool. 

If I use this ...

```
tools: {
          getWeather: tool({
            description: 'Get the weather in a location',
            parameters: z.object({
              location: z.string().describe('The location to get the weather for')
            }),
            execute: async ({ location }) => {
              return {
                 location,
                 temperature: 72 + Math.floor(Math.random() * 21) - 10
               }
            }
          })
        }
```

it triggers the 'tools-call' with the correct function to be called, but it never actually triggers. However, if I use

```
tools: {
          getWeather: {
            description: 'Get the weather in a location',
            parameters: z.object({
              location: z.string().describe('The location to get the weather for')
            }),
            generate: async function (args, tool) {
              const result = { temperature: 72 + Math.floor(Math.random() * 21) - 10 }

              return result.temperature
            }
          }
        },
```
it triggers the function call. I am using google vertex ai 

### Code example

      const result = streamUI({
        temperature: 1,
        model: setupVertex(false),
        system: system_prompt,
        messages: secureMessages,
        initial: <BotMessage isFinal={false} index={index}></BotMessage>,
        
        tools: {
          getWeather: tool({
            description: 'Get the weather in a location',
            parameters: z.object({
              location: z.string().describe('The location to get the weather for')
            }),
            execute: async ({ location }) => {
              console.log('hiiiiiiiiiiiiiiiiiiiiii')
              return 'hi'
              // return {
              //   location,
              //   temperature: 72 + Math.floor(Math.random() * 21) - 10
              // }
            }
          })
        },
        // tools: {
        //   getWeather: {
        //     description: 'Get the weather in a location',
        //     parameters: z.object({
        //       location: z.string().describe('The location to get the weather for')
        //     }),
        //     generate: async function (args, tool) {
        //       const result = { temperature: 72 + Math.floor(Math.random() * 21) - 10 }

        //       return result.temperature
        //     }
        //   }
        // }
      }).catch(async error => {
        let title = await titlePromise
        handleUnexpectedStreamingErrors(error, aiState, reply, true, title)
      })

**Comment by lgrammel** [comment]
You can't use `tool` in `streamUI`, since the interface is different.

**Comment by lgrammel** [comment]
> > You can't use `tool` in `streamUI`, since the interface is different.
> 
> Is there a plan to bring it under 1 interface to rule them all?

not at this point bc they are different (response values) and `streamUI` needs work / has limitations

**Comment by Godrules500** [comment]
It may be a big lift, but do you think it would be worth switching to useChat? I think the streamUI seems great, but It does feel that streamUI is falling behind, and useChat seems to be the focus.

Currently I'm only responding text which is why I'm curious.

**Comment by lgrammel** [comment]
Already mentioned in the other thread: `streamUI` currently has several limitations, and using `streamText` + `createStreamableUI` / `createStreambleValue` for RSC might be the better solution atm.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The reported behavior is an unsupported interface combination rather than a confirmed failure of promised behavior. The clarified request is effectively an API-unification and ergonomics enhancement for `streamUI`.

### Evidence
- The reporter attempted to use the `tool()`/`execute` interface with `streamUI`, while the existing `generate`-based interface works.
- A maintainer clarified that `tool()` cannot be used with `streamUI` because its tool interface and response values are different.
- The follow-up asks whether the APIs could be unified, and the maintainer states there is currently no plan due to `streamUI` limitations.
