### ISSUE TITLE
Get the traceId, (telematry data) sent back from function result.

### ISSUE THREAD

**Issue by AnzeKop** [vercel/ai#2835]
### Feature Description

Would it be possible to get the traceId and other telemetry data returned in the result object?

### Use Case

Would need to store this in a database for creating dynamic endpoints where I can get humans to do human evals on specific trace Ids.

**Comment by lgrammel** [comment]
WIP PR: https://github.com/vercel/ai/pull/2893

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for a new API capability to expose telemetry metadata in function results, not a failure of existing documented behavior.

### Evidence
- The issue explicitly requests returning the trace ID and other telemetry data in the function result object.
- The stated use case is storing trace IDs for later human evaluation workflows.
- A maintainer linked a work-in-progress implementation PR, supporting that this is a planned capability.
