### ISSUE TITLE
When providing image message to any groq model, it throws `message[0].content must be a string`

### ISSUE THREAD

**Issue by baptisteArno** [vercel/ai#2837]
### Description

When calling streamText on any groq model, with an image message, the function throws with this error message: `message[0].content must be a string`

I would expect it to gracefully handle image either adding the URL as a text message or even downloading the URL content and parse it.

### Code example

Providing this to `streamText`:

```json
 "messages": [
     {
       "role": "user",
       "content": [
         {
           "type": "text",
           "text": "What's this?"
         },
         {
           "type": "image",
           "image": "https://s3.eu-west-3.amazonaws.com/..."
         }
       ]
     }
   ]
```

When inspecting requestBodyValues here are the parsed messages:

```json
"messages": [
     {
       "role": "user",
       "content": [
         {
           "type": "text",
           "text": "What's this?"
         },
         {
           "type": "image_url",
           "image_url": {
             "url": "https://s3.eu-west-3.amazonaws.com/typebot-test/public/tmp/cm0f0q3mp0003xaaprbc72y9s/Typebot%20x%20Segment.png"
           }
         }
       ]
     }
   ]
```

### Additional context

ai v3.3.20
@ai-sdk/openai v0.0.54

**Comment by baptisteArno** [comment]
`model.supportsImageUrls` returns `undefined` so by default it won't download it:

https://github.com/vercel/ai/blob/9cba6cb046c4dc034f36567ae5d106978be27ca6/packages/ai/core/prompt/convert-to-language-model-prompt.ts#L18C3-L18C33

**Comment by lgrammel** [comment]
Which Groq model supports images?

**Comment by baptisteArno** [comment]
None, but I thought the SDK could know that and convert any image message to text or something. But I guess maybe not!

**Comment by lgrammel** [comment]
we don't keep a list of models and their capabilities since providers change them pretty often. and re converting, multi-modal models use a different architecture and are trained on multimodal data. converting the image is not sufficient.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support/expectation mismatch involving unsupported image input, not a failure of promised SDK behavior or a concrete actionable feature request after clarification.

### Evidence
- The error occurs when sending image content to Groq models that the reporter confirms do not support images.
- The requested automatic conversion of an image to text is not existing or documented SDK behavior.
- A maintainer explains that the SDK does not maintain model-capability lists and that image conversion would not make a text-only model multimodal.
