### ISSUE TITLE
add tool roundtrips to streamUI

### ISSUE THREAD

**Issue by AWKohler** [vercel/ai#2848]
### Feature Description

add tool roundtrips to streamUI. This would allow us to use agents alongside Generative UI

**Comment by Godrules500** [comment]
fyi It is currently being added to streamText. Also, I just switched from streamUI to streamText. It may be worth trying that. It's not too hard of a transition.

**Comment by AWKohler** [comment]
That doesn't appear to have generative UI support. "initial" is not supported

**Comment by Godrules500** [comment]
> That doesn't appear to have generative UI support. "initial" is not supported

 I'll post what I do later, but I make the stream UI, or stream text now, asynchronous and use reply = createStreamUi with my initial UI value.

I then use reply.update and .done to update the UI. 

I actually I found that to update the UI quicker than the initial UI piece from stream UI

**Comment by AWKohler** [comment]
> I'll post what I do later
That would be great!

**Comment by Godrules500** [comment]
Let me know if this helps!

```
     // Used for just updating the text instead of rendering the full html
      let textStream: undefined | ReturnType<typeof createStreamableValue<string>> = createStreamableValue('')
      const reply = createStreamableUI(<BotMessage content={textStream.value} isFinal={false} index={index} />)
      streamText({
        temperature: 1,
        // topP: 0.95,
        model: setupVertex(useGrounding),
        system: system_prompt,
        messages: secureMessages,

        onFinish: async finishResult => {
          let text = finishResult.text
          textStream!.done()

          // boring unrelated stuff was here.

          // Closes the UI stream.
          reply.done(
            <BotMessage isFinal={true} index={index}>
              {text}
            </BotMessage>
          )
        }
      })
        .then(async x => {
          let text = ''
          for await (const streamedText of x.textStream) {
            text += streamedText || ''
            // The textStream was set up with content={textStream.value} of createStreamableUI
            textStream?.update(streamedText)
          }
          return text
        })
        .catch(async error => {
          let title = await titlePromise
          handleUnexpectedStreamingErrors(error, aiState, reply, true, title)
        })

      return {
        id,
        display: reply.value
      }
```

**Comment by lgrammel** [comment]
Duplicates #1895

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API capability enhancement for `streamUI`, not a report that its current behavior violates documented expectations.

### Evidence
- The request explicitly asks to add tool roundtrips to `streamUI`.
- The stated goal is to enable agents alongside Generative UI, which is a new capability.
- A maintainer notes that the request duplicates #1895; no existing promised `streamUI` behavior is identified as broken.
