### ISSUE TITLE
Anthropic cache-control flag not passed to assistant messages

### ISSUE THREAD

**Issue by iliane5** [vercel/ai#2888]
### Description

The current implementation doesn't pass cache control flags to assistant messages: https://github.com/vercel/ai/blob/main/packages/anthropic/src/convert-to-anthropic-messages-prompt.ts#L180

Whereas anthropic allows assistant messages to be cached as well:
https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#:~:text=for%20both%20user%20and%20assistant%20turns

**Comment by lgrammel** [comment]
Fix: #2890

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports incorrect existing Anthropic provider behavior: supported cache-control metadata is not propagated for assistant messages. The linked fix further confirms it as a concrete implementation defect.

### Evidence
- The Anthropic prompt converter omits cache-control flags from assistant messages.
- Anthropic supports prompt caching for both user and assistant turns, so the current conversion fails to pass supported message metadata.
- A maintainer linked pull request #2890 as the fix.
