### ISSUE TITLE
Tool execution not awaited in `streamUI`

### ISSUE THREAD

**Issue by Saran33** [vercel/ai#2921]
### Description

- The [streamUI docs](https://sdk.vercel.ai/docs/reference/ai-sdk-rsc/stream-ui) state that the [onFinish]() callback "is called when the LLM response and all request tool executions (for tools that have a `generate` function) are finished." A [comment](https://github.com/vercel/ai/blob/a9de7e0a7c72aff1e376b83b7040bb1261fddbe3/packages/ai/rsc/stream-ui/stream-ui.tsx#L194-L197) in the source code also suggests that this is the intended behaviour.

- However, this is not the case. The `onFinish` cb is executed immediately after the final chunk ("finish" type) is [received](https://github.com/vercel/ai/blob/a9de7e0a7c72aff1e376b83b7040bb1261fddbe3/packages/ai/rsc/stream-ui/stream-ui.tsx#L194-L197).

- In the example [vercel-ai-chatbot](https://github.com/vercel/ai-chatbot) repo, the updating of `aiState` is tightly coupled with the tool generators, being inlined. The `onFinish` callback isn't used in that repo. However, if we need to ensure that the UI has updated before marking `aiState` as done, and we don't want to handle all of this state management within the generators, then we have no way to await the result of `streamUI`. 

- Personally, I am streaming both text content and tool call results from the same message via `streamUI`, so ideally would to be able to wait for the generate method to be completed before updating state and closing a text stream, rather than putting all of this state management into each tool's generator.

### Steps to reproduce:
- Clone the [vercel-ai-chatbot](https://github.com/vercel/ai-chatbot) repo.
- Add logging anywhere before the return statement of a tool's generator body. e.g. `console.log('tool_execution_done')`
- Add an `onFInish` callback.
```tsx
    onFinish: async event => {
      console.log('ON_FINISH', event.finishReason);
    },
 ```
I am using what is currently the latest version (3.3.28), and it is also occurring on the demo repo (3.2.16).

### Additional context

Something similar seems to have been recently fixed for `streamText` - https://github.com/vercel/ai/pull/2859

**Comment by Saran33** [comment]
I made a quick PR for it https://github.com/vercel/ai/pull/2923 .
I'm not sure if `streamUI` is still the preferred option for streaming UI, as it has other limitations like the inability to handle parallel tools calls. It also takes some hacking around to render a stream of text content along with tool results in the same message node. In my application I have adapters for both `streamUI` and `streamText`, so I will probably switch to using the latter. It's a shame because I prefer `streamUI`. Rebuilding the wheel to stream UI with `streamText` feels unnecessary, although does seem to have more flexibility.

**Comment by lgrammel** [comment]
Thanks for the PR. It's fixed in main.

Re `streamUI`, it has some limitations. You can also use `streamText` with the RSC helpers like `createStreamableUI` to have more control.

**Comment by Saran33** [comment]
Awesome, thanks @lgrammel!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete mismatch between documented and actual `streamUI` behavior, and the maintainer confirmed it was fixed.

### Evidence
- The documented contract says `onFinish` runs after the LLM response and all tool `generate` executions finish, but it instead ran immediately upon receiving the final stream chunk.
- The reporter provided reproduction steps showing `onFinish` logging before tool execution completes in versions 3.3.28 and 3.2.16.
- A maintainer confirmed the submitted fix was merged into main.
