### ISSUE TITLE
Receiving the error "Error: Cannot read properties of undefined (reading 'workers')" after upgrading to v3.3.30 using Next.js v14.2.9

### ISSUE THREAD

**Issue by WoetDev** [vercel/ai#2948]
### Description

After upgrading to v3.3.30, I receive the following error:
![image](https://github.com/user-attachments/assets/777c4f03-df2b-4ca2-8dfb-a9f800a94e78)

### Code example

You can find the reproduction of the bug in this repository: https://github.com/WoetDev/bug-next-ai-sdk

It's a reproduction of the official example for using AI assistants with the Next.js app router, so this example seems to be broken: https://sdk.vercel.ai/examples/next-app/assistants/stream-assistant-responses

You only need to add your OPENAI API key in the .env file:

```
OPENAI_API_KEY=xxxx
```

### Additional context

Noticed this issue when upgrading packages, this is affecting the AI functionality in my production app and blocking me from upgrading.

**Comment by RickRyan26** [comment]
When tying to deploy SvelteKit to Vercel I am getting...

`The requested module '@ai-sdk/provider-utils' does not provide an export named 'createIdGenerator'`

Im using:

```
    "@ai-sdk/openai": "^0.0.54",
    "@ai-sdk/svelte": "^0.0.46",
    "ai": "^3.3.30",
```

**Comment by lgrammel** [comment]
@RickRyan26 please trying updating openai to `0.0.58`.

**Comment by lgrammel** [comment]
@WoetDev can you share a stacktrace & the versions of the ai sdk packages that you are using?

**Comment by nicoalbanese** [comment]
@WoetDev can you try and remove the "use server" directive at the top of your actions file and instead move it to the specific actions you are calling (to line 24)?

https://github.com/WoetDev/bug-next-ai-sdk/blob/15f3604073997cc17d10c0268313f6746b88abe2/src/app/actions.tsx#L24

**Comment by nsenthilkumar** [comment]
Moving the "use server" directive fixed this issue for me. I should have come here sooner.

Can we get some insight on why that was the issue so that we can better understand behind the hood moving forward?

**Comment by doctorDAlvarez** [comment]
Same issue here. Fixed moving the directive too. Any insights on why is this happening?
Thanks!!

**Comment by WoetDev** [comment]
@nicoalbanese thanks a bunch! moving the "use server" directive and adding a default state seemed to do the trick on my production app. 

I'm all up-to-date with the latest versions now without an issue:

```
"next": "^14.2.11",
"ai": "^3.3.35",
"@ai-sdk/openai": "^0.0.59"
```

**Comment by nihirv** [comment]
I was also running into this issue, but moving the use server directive was not the fix for me.

I was passing message history into generateObject, but my message object had attributes which didn't follow the type definition (e.g. I had more than just "role" and "content" in it). Removing my attributes fixed the issue

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete runtime failure after upgrading the SDK, with a reproducible workaround confirmed by multiple users. Although documentation updates were also suggested, the primary report is broken existing behavior.

### Evidence
- Upgrading to AI SDK v3.3.30 caused an unhandled runtime error: "Cannot read properties of undefined (reading 'workers')" in a reproduction based on an official Next.js assistants example.
- Multiple users reproduced the failure and reported that moving the "use server" directive to the individual action resolved it.
- The reporter confirmed that moving the directive and supplying initial AI/UI state fixed the production application on newer package versions.
