### ISSUE TITLE
React: mutating stream data unnecessarily causes other functions being recreated even though they are enclosed by useCallback

### ISSUE THREAD

**Issue by tonyfarney** [vercel/ai#2950]
### Description

In use-chat.ts:
```typescript
...
onUpdate(merged, data) {
  mutate([...chatRequest.messages, ...merged], false);
  mutateStreamData([...(existingData || []), ...data], false);
},
...
```

`data` is an empty array in my use case and it is causing `streamData` being modified. As it is a dependency for `triggerRequest` and `triggerRequest` is a dependency for `append`, `reload` and `handleSubmit`, `useCallback` returns a new function every time an update occurs when reading from the stream.

A simple modification avoids this behavior (and consequently unnecessary re-renders):
```typescript
... 
onUpdate(merged, data) {
  mutate([...chatRequest.messages, ...merged], false);
  if (data?.length) {
    mutateStreamData([...(existingData || []), ...data], false);
  }
},
...
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3703

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue identifies an unintended current React hook behavior that causes unnecessary callback recreation and re-renders during streaming, with a concrete conditional-mutation fix.

### Evidence
- `useChat` calls `mutateStreamData` on every stream update even when `data` is empty.
- The resulting `streamData` identity change recreates dependent callbacks such as `triggerRequest`, `append`, `reload`, and `handleSubmit`, causing unnecessary re-renders.
- A maintainer linked pull request #3703 in response, indicating a code-level resolution.
