### ISSUE TITLE
Streaming breaks when using await in tool execution on express

### ISSUE THREAD

**Issue by philipodev** [vercel/ai#2973]
### Description

Using the latest versions of `ai` and `express`.
Node.js version `v20.12.1` 

Reproduction:
https://github.com/philipodev/vercel-ai-express-await-possible-bug

### Code example

```javascript
app.post('/chat', async (req, res) => {
  const { messages } = req.body

  const result = await streamText({
    system: 'You are a helpful assistant',
    model: openai('gpt-4o'),
    messages,
    tools: {
      weather: {
        description: 'Get the weather for a given city',
        parameters: z.object({
          city: z.string().describe('The city to get the weather for'),
        }),
        execute: async ({ city }) => {

          // ISSUE: any async operation will break the stream. Try comment out the await and it will work.
          await new Promise((resolve) => setTimeout(resolve, 1000))

          return `The weather in ${city} is extremely sunny and 1000 degrees`
        },
      },
    },
  })

  result.pipeDataStreamToResponse(res)
})
```

### Additional context

Seems to be somewhat related to #1512 

As title says, if awaiting something in the `execute` function of a tool it breaks the streaming in express.

My react code looks like this: 

```tsx
import { useChat } from 'ai/react'

export default function AIPage() {
  const { messages, input, handleInputChange, handleSubmit } = useChat({
    keepLastMessageOnError: true,
    maxToolRoundtrips: 6,
    api: 'http://localhost:3000/chat',
    fetch: async (input, init) => {
      const token = await getJwt()
      return fetch(input, {
        ...init,
        headers: {
          ...init?.headers,
          Authorization: `Bearer ${token}`,
        },
      })
    },
  })

  return (
    <div>
      <>
        {messages.map((message) => (
          <div key={message.id}>
            {message.role === 'user' ? 'User: ' : 'AI: '}
            {message.content}
          </div>
        ))}

        <form onSubmit={handleSubmit}>
          <input
            name="prompt"
            placeholder="Ask a question"
            value={input}
            onChange={handleInputChange}
          />
          <button type="submit">Submit</button>
        </form>
      </>
    </div>
  )
}

```

### With `await`

<img width="514" alt="Skärmavbild 2024-09-11 kl  19 13 12" src="https://github.com/user-attachments/assets/a0a57d49-d0d4-4b00-82e9-b5bbe76b233a">

### Without

<img width="504" alt="Skärmavbild 2024-09-11 kl  19 15 08" src="https://github.com/user-attachments/assets/dd17648b-ca53-464a-b6e6-69e9c16c444b">

**Comment by philipodev** [comment]
Same thing with fastify using `result.toDataStream`

**Comment by philipodev** [comment]
I'd be happy to help out with a fix by PR, but this repo is very new to me so if someone could point me in the direction to look i could do some more debugging.

**Comment by philipodev** [comment]
Oh im an idiot... My issue was that i was using an older version on my client `v3.33.20` vs `v3.33.33` on the server. Simply updating the client version helped and it works as expected now.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported failure was caused by mismatched package versions rather than a defect in current AI SDK behavior, so it is best classified as a resolved support/configuration issue.

### Evidence
- Reporter initially observed incomplete tool invocation streaming when an async tool execution was used.
- The reporter later identified mismatched client and server AI SDK versions (v3.33.20 vs v3.33.33).
- Updating the client version resolved the issue and behavior worked as expected.
