### ISSUE TITLE
Gemini not working with structured output and union

### ISSUE THREAD

**Issue by bernaferrari** [vercel/ai#2974]
### Description

I'm getting

```
 ⨯ AI_APICallError: * GenerateContentRequest.generation_config.response_schema.properties[child].type: must be specified

    at async $$ACTION_0 (...)
digest: "940861687"
```

with the following code

```ts
    await generateObject({
      model: google.chat("gemini-1.5-flash"),
      schema: z.object({
        child: z.union([
          z.object({
            type: z.literal("Text1"),
            content: z.string(),
          }),
          z.object({
            type: z.literal("Text2"),
            content: z.string(),
          }),
        ]),
      }),
      system: `Answer anything.`,
    });
```

I expect the model to choose between Text1 and Text2 component. GPT works fine.

**Comment by lgrammel** [comment]
Unfortunately this comes down to a limitation in what Gemini supports: https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai#troubleshooting-schema-limitations

**Comment by bernaferrari** [comment]
Oh. I searched the error message but couldn't find anything in the docs or elsewhere. Thanks.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support report resolved as an upstream Gemini schema limitation, not a defect in the AI SDK or an explicit request for a product or documentation change.

### Evidence
- The reported union schema fails when sent to Gemini, while GPT accepts it.
- A maintainer states this is a limitation of Gemini's supported response schemas and links existing troubleshooting documentation.
- The reporter acknowledges the explanation and does not request an SDK or documentation change.
