### ISSUE TITLE
topK option is not passed from provider

### ISSUE THREAD

**Issue by minpeter** [vercel/ai#2994]
### Description

If you give the topK option, you should get a warning that it is not supported when using @ai-sdk/openai.

```ts

    if (topK != null) {
      warnings.push({
        type: 'unsupported-setting',
        setting: 'topK',
      });
    }
```

In reality, this is not the case and the output of topK will be null.

```ts
  async doStream(
    options: Parameters<LanguageModelV1["doStream"]>[0]
  ): Promise<Awaited<ReturnType<LanguageModelV1["doStream"]>>> {
    console.log("doStream topK", options.topK);
```

### Code example

```ts
  const result = await streamObject({
    model:  openai('gpt-4o'),
    system:
      "You categorize expenses into one of the following categories: " +
      "TRAVEL, MEALS, ENTERTAINMENT, OFFICE SUPPLIES, OTHER." +
      // provide date (including day of week) for reference:
      "The current date is: " +
      new Date()
        .toLocaleDateString("en-US", {
          year: "numeric",
          month: "short",
          day: "2-digit",
          weekday: "short",
        })
        .replace(/(\w+), (\w+) (\d+), (\d+)/, "$4-$2-$3 ($1)") +
      ". When no date is supplied, use the current date.",
    prompt: `Please categorize the following expense: "${expense}"`,
    schema: expenseSchema,
    temperature: 0.4,
    topK: 1,
    onFinish({ object }) {
      // save object to database
    },
  });

````

### Additional context

I found this bug during provider update. If you can't reproduce it, please let me know.

**Comment by lgrammel** [comment]
The check happens at the provider level:

https://github.com/vercel/ai/blob/main/packages/openai/src/openai-chat-language-model.ts#L91

It is expected that `topK` is passed into the provider. It is just not forward to the API and you'll get a warning as part of the `warnings` object on the result.

**Comment by minpeter** [comment]
I know this is set in the provider. However, is there any code to test that the topK prop is passed to the provider correctly?

Even if it is set, I can see that it actually passes undefined.
Could you please take a moment to demonstrate this phenomenon..?

**Comment by minpeter** [comment]
@lgrammel  According to the code, the openai provider should add a warning to the response when the topK option is set. In my testing, setting topK returns an empty array.

**Comment by lgrammel** [comment]
ah I see. will investigate

**Comment by minpeter** [comment]
thank you :)

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/2998

**Comment by lgrammel** [comment]
Fixed in `main`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a confirmed defect in existing option forwarding and warning behavior, not a request for new functionality.

### Evidence
- Passing `topK: 1` to `streamObject` resulted in the provider receiving `undefined` and returning no unsupported-setting warning.
- The OpenAI provider was expected to receive `topK` and add a warning while omitting it from the API request.
- A maintainer investigated, linked PR #2998, and confirmed the issue was fixed in `main`.
