### ISSUE TITLE
SDK web is down (Times out) 

### ISSUE THREAD

**Issue by Emmaccen** [vercel/ai#3058]
### Description

Visit the official SDK Docs: https://sdk.vercel.ai/docs

**Result**: Times out every time

**Browsers used**:

- Brave (With and without shield)
- FireFox
- Chrome

**Locations**:

- France
- USA
- Nigeria

**PS**: I've been trying this for over 48 hours now

**Comment by lgrammel** [comment]
I've tried all 3 locations through VPN and it works for me. If it's been going on for that long it's most likely a configuration issue on your end.

**Comment by Emmaccen** [comment]
> I've tried all 3 locations through VPN and it works for me. If it's been going on for that long it's most likely a configuration issue on your end.

Good feedback 👍. I'll look into the config thing. 
Thanks, Lars.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an environment-specific access/support issue with no confirmed repository bug or requested documentation change.

### Evidence
- Reporter experienced repeated timeouts accessing the documentation site across browsers and locations.
- Maintainer could not reproduce the timeout from the listed locations and suggested a local configuration issue.
- Reporter accepted that explanation and planned to investigate their configuration.
