### ISSUE TITLE
Can't trigger function calls using LangChainStream

### ISSUE THREAD

**Issue by brerdem** [vercel/ai#306]
Hi,

I'm trying to call functions using function call handler but couldn't figure out how to use it with LangChainStream. I'm using an `openai-functions` agent like this:

```
  const executor = await initializeAgentExecutorWithOptions(tools, llm, {
    agentType: "openai-functions",
    returnIntermediateSteps: true,
    verbose: true,
  });

  const lastMessage: Message = (messages as Message[]).at(-1)!;
  executor.call({ input: lastMessage.content }, [handlers]);

  return new StreamingTextResponse(stream);
``` 

And on front-end, the function handler is as below:

```
const functionCallHandler: FunctionCallHandler = async (
  chatMessages,
  functionCall
) => {
  console.warn(functionCall);

  if (functionCall.name === "calculator") {
    if (functionCall.arguments) {
      const parsedFunctionCallArguments = JSON.parse(functionCall.arguments);
      // You now have access to the parsed arguments here (assuming the JSON was valid)
      // If JSON is invalid, return an appropriate message to the model so that it may retry?
      alert("ok");
    }

    // Generate a fake temperature

    const functionResponse: ChatRequest = {
      messages: [
        ...chatMessages,
      ],
    };
    return functionResponse;
  }
};
```

I'm prompting simple math equation, I can see on verbose output OpenAI calls `calculator` function, however func handler can't catch it. Any idea what may be wrong here?

**Comment by matannahmani** [comment]
any updates regarding this one?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily an unresolved usage/support question. The available context does not establish that existing AI SDK behavior is broken or explicitly request a new capability.

### Evidence
- Reporter says they "couldn't figure out" how to use a function-call handler with LangChainStream and asks what may be wrong.
- No documented behavioral promise, error, regression, or maintainer clarification is provided.
- The only comment requests an update and adds no technical evidence.
