### ISSUE TITLE
Streaming data comes back in the wrong order

### ISSUE THREAD

**Issue by StringTheory69** [vercel/ai#308]
Hello,

The data I stream to build a chatgpt type interface comes back in the wrong order. When I use the completion call back at the end the text body is correct but during the stream it's totally jumbled. Any help would be great - thanks!

**Comment by 0xJacobean** [comment]
![Screenshot 2023-07-09 at 11 15 00 PM](https://github.com/vercel-labs/ai/assets/24348787/74d4b3a8-2c65-4ad2-bdfd-4a7d986f5bdb)

**Comment by 0xJacobean** [comment]
`export const config = {
  runtime: "edge",
};

export async function PATCH(
  req: Request,
  context: z.infer<typeof routeContextSchema>
) {
  try {
    const configuration = new Configuration({
      apiKey: process.env.OPENAI_API_KEY,
    });

    const openai = new OpenAIApi(configuration);
    
    // Validate route params.
    const { params } = routeContextSchema.parse(context);

    // Check if the user has access to this Project.
    if (!(await verifyCurrentUserHasAccessToProject(params.projectId))) {
      return new Response(null, { status: 403 });
    }

    const json = await req.json();
    const body = projectCreateSchema.parse(json);

    const { messages, temperature, top_p, frequency_penalty, presence_penalty } = await generateDict[body.section](body);

    const response = await openai.createChatCompletion({
      model: 'gpt-4',
      stream: true,
      messages
    });

    const stream = OpenAIStream(response, {
      onCompletion: async () => {
        // Stream completion callback
        // Add your custom logic here
      }
    });

    // Return stream response (SSE)
    return new StreamingTextResponse(stream);
  } catch (error) {
    console.log("ERROR REGENERATE ROUTE", error);
    if (error instanceof z.ZodError) {
      return new Response(JSON.stringify(error.issues), { status: 422 });
    }
    return new Response(null, { status: 500 });
  }
}
`

**Comment by 0xJacobean** [comment]
CLIENT : 

`            const reader = data.getReader();
            const decoder = new TextDecoder();
            let done = false;
            while (!done) {

                const { value, done: doneReading } = await reader.read();
                done = doneReading;
                const chunkValue = decoder.decode(value);
                addToSection(section, chunkValue);
            }`

**Comment by brerdem** [comment]
May I ask why don't you use `useChat` on client?

**Comment by MaxLeiter** [comment]
@0xJacobean can you share a minimal reproduction so we can try the project ourselves? It's difficult to assist without seeing all of the code.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This reports a concrete failure in current streaming behavior rather than requesting a new capability, although the lack of a reproduction leaves the root cause uncertain.

### Evidence
- The reporter says streamed text is jumbled and arrives in the wrong order, while the final completion text is correct.
- They provided server-side OpenAIStream/StreamingTextResponse code, client stream-reading code, and a screenshot of malformed output.
- A maintainer requested a minimal reproduction because the available code was insufficient to diagnose the cause.
