### ISSUE TITLE
Extend Attachment Type to support custom attributes

### ISSUE THREAD

**Issue by aneequrrehman** [vercel/ai#3148]
### Feature Description

Related to Generic Messages #1180.

Currently, `Attachment`s are not easily extensible. For instance, images may require additional fields such as `height` and `width`, or attachments may need a `file_pointer` depending upon the storage mechanism. And so at the moment, it requires custom projections and types to tackle this.

### Additional context

While I understand that handling storage details is not the responsibility of the AI SDK itself, introducing such a field as `Record<string, unknown>` or some similar mechanism to allow the `Attachment` type extension would simplify integration for consumers.

**Comment by aneequrrehman** [comment]
I noticed that `FilePart` and `ImagePart` are already interfaces, and even if you extend those, the conversational APIs seem to work.

Example:

```
declare module 'ai' {
  interface ImagePart {
    filePointer: string
    width: number
    height: number
}
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API extensibility enhancement for custom attachment metadata, not a concrete failure of existing behavior.

### Evidence
- The issue requests making the `Attachment` type extensible with custom attributes such as image dimensions or storage file pointers.
- The proposed solution is a new `Record<string, unknown>`-style field or another extension mechanism.
- The comment notes that declaration merging already works for `FilePart` and `ImagePart`, but does not identify broken or undocumented promised behavior for `Attachment`.
