### ISSUE TITLE
Support OpenAI o1 with `streamText({stream: false})`

### ISSUE THREAD

**Issue by xl0** [vercel/ai#3153]
### Feature Description

The o1 models do not support streaming at the moment, making them an odd outlier. It would be awesome to still be able to use them with `streamText({stream: false})`, because this would allow keeping the rest of the front- and back-end code the same for all models. In this case stream in `streamText` would refer to the fact that the same data streaming protocol is used to send the data back to the front-end.

### Use Case

I'm working on (yes, one more) chatbot UI that supports all common models/providers (openai, anthropic, google) and tries to maintain a balance between flexibility/features and ease of use.

o1 models work fine through Open Router because it gives a common interface, and emulates streaming for o1, but supporting o1 through OpenAI would require some work, and it's unclear how long until they support streaming.

**Comment by lgrammel** [comment]
The AI SDK openai provider simulates streaming / has streaming interface compatibility for o1 models in version `0.0.63`. please update `@ai-sdk/openai` to `0.0.63` and the `ai` to `3.4.7` (and related `@ai-sdk/*` libs as well). See https://sdk.vercel.ai/providers/ai-sdk-providers/openai#reasoning-models

**Comment by xl0** [comment]
@lgrammel Ha wow thank you! And you even requested the reasoning token count! :heart:

**Comment by sheharyarIshfaq** [comment]
Hi @lgrammel 

I’m encountering an issue with streaming in my Next.js API. I’m using the Vercel AI UI SDK's useChat hook for this. When I use the o1 model, streaming doesn’t work, but it works perfectly fine with o1-preview and o1-mini.

Could you please guide me on how to resolve this?

Thanks in advance for your assistance!

Best regards,
Sheharyar

![image](https://github.com/user-attachments/assets/eabb1303-6bd8-47bc-9264-1edf95930464)

**Comment by lgrammel** [comment]
@sheharyarIshfaq which versions are you using? please try the latest `@ai-sdk/openai` provider, there have been related changes recently. Also pls not that streaming for o1 is simulated (all text comes at the end), because o1 itself does not support streaming.

**Comment by sheharyarIshfaq** [comment]
@lgrammel I updated to the latest versions, here is the screenshot of my package.json file, yes but all the text is coming at once, they is no simulation which is mentioned, I mean that does it loads all the response, and then simulates the streaming or shows the answer at once?

![image](https://github.com/user-attachments/assets/0c49450c-7d7b-4f12-b1c4-09e6f2f7d0eb)

**Comment by xl0** [comment]
@sheharyarIshfaq works as expected. If the model returns all at once, it would be silly to delay the response to simulate streaming. The point is you can use the same streaming API with o1 as you would with other chat models.

**Comment by lgrammel** [comment]
@sheharyarIshfaq simulating streaming here means making it compatible with the streamText api (so it works). If you want to simulate sending it out with many chunks so it looks streamed, please check out smoothStream: https://sdk.vercel.ai/docs/ai-sdk-core/generating-text#smoothing-streams

**Comment by sheharyarIshfaq** [comment]
@lgrammel @xl0 thanks for the guidance

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new model/API compatibility rather than a failure of previously promised behavior. The requested capability was subsequently implemented, so the issue is a feature request.

### Evidence
- The issue requests support for using OpenAI o1 through the existing `streamText` interface despite the model not supporting native streaming.
- A maintainer confirmed that simulated streaming/interface compatibility was added in `@ai-sdk/openai` 0.0.63 and `ai` 3.4.7.
- Later comments clarify that compatibility returns the model’s completed text at once, while `smoothStream` can create multiple output chunks.
