### ISSUE TITLE
@ai-sdk/google-vertex@0.0.39 breaks tool calling

### ISSUE THREAD

**Issue by Und3rf10w** [vercel/ai#3156]
### Description

1. Configure a tool and set up a google-vertex provider
2. Pass a tool to either `streamText` or `generateText`
3. Get a `TypeError: Error reading properties of undefined (reading 'AUTO')`, regardless of the `toolChoice` that is applied.

### Code example
```typescript
import { createVertex } from '@ai-sdk/google-vertex';
import { generateText } from 'ai';

const vertex = createVertex({
  project: 'my-project',
  location: 'us-central1',
});


const { text } = await generateText({
  model: vertex('gemini-1.5-pro'),
  prompt: 'What is the weather in San Fransico,
  maxSteps: 5,
  tools: {
    getWeather: {
      description: 'Get the weather for a location',
      parameters: z.object({
        city: z.string().describe('The city to get the weather for'),
        unit: z
          .enum(['C', 'F'])
          .describe('The unit to display the temperature in'),
      }),
      execute: async ({ city, unit }) => {
        const weather = {
          value: 24,
          description: 'Sunny',
        };

        return `It is currently ${weather.value}°${unit} and ${weather.description} in ${city}!`;
      },
    },
  },
});
```

### Additional context

Downgrading to `@ai-sdk/google-vertex@0.0.38` (e.g. `yarn add @ai-sdk/google-vertex@0.0.38`) fixes this.

My guess is 20ffa738cf330a1f03b3a782146437893a4c5529 is responsible in some way.

**Comment by lgrammel** [comment]
I just double checked and it works. Most likely this is a versioning issue. Have you upgraded `ai` to `3.4.7`? (other `@ai-sdk/*` libs might also need upgrades to the latest version)

**Comment by Und3rf10w** [comment]
Interesting, to be fair, that wasn't the actual tool I was using. All of my other packages were upgraded.

Here's relevant packages from my `package.json`:

```
    "@ai-sdk/amazon-bedrock": "^0.0.28",
    "@ai-sdk/azure": "^0.0.41",
    "@ai-sdk/google-vertex": "0.0.39",
    "@ai-sdk/openai": "^0.0.63",
    "@ai-sdk/provider": "^0.0.24",
    "@ai-sdk/react": "^0.0.62",
    "@ai-sdk/ui-utils": "^0.0.46",
    "ai": "^3.4.7",
    "@google-cloud/vertexai": "^1.3.1",
    "@google/generative-ai": "^0.12.0",
```

My real tool is:

```typescript
googlesearch: {
description: 'Search the web using Google. ',
  parameters: z.object({
    query: z.string().describe('The search query to use'),
  }),
  execute: async ({ query }: { query: string }) => {
    try {
      const res = await search.cse.list({
        cx: ...,
        q: query,
        auth: ...,
        num: 10,
      })
      return { results: JSON.stringify(res.data.items) }
    } catch (error) {
      console.error('Error executing Google search:', error)
      throw new Error('Failed to execute Google search')
    }
  },
}
```

When I upgrade that `ai-sdk/google-vertex` to 0.0.39, I get the following trying to use it:

```
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'AUTO')"
}
```

When I use 0.0.38, it works fine.

**Comment by Und3rf10w** [comment]
I just confirmed trying the same tool, `getWeather` is also causing this. I'm using `vertex` from a `Provider`, which will return a `GoogleVertexProvider.languageMode()`

Here is a more complete version of my code:

## Tool.ts
```typescript
const makeTool = {
  description: 'Get the weather for a location',
  parameters: z.object({
    city: z.string().describe('The city to get the weather for'),
    unit: z
      .enum(['C', 'F'])
      .describe('The unit to display the temperature in'),
  }),
  execute: async ({ city, unit }) => {
    const weather = {
      value: 24,
      description: 'Sunny',
    }

    return `It is currently ${weather.value}°${unit} and ${weather.description} in ${city}!`
  },
}

export async function getTool() {
  return makeTool
}
```


## streamVertex.ts
```typescript
const vertexClient = await getLanguageModel(reqData.modelName, reqData.modelOptions as GoogleVertexSettings)
const messages = reqData.messages

// just something I have the adjust the prompt properly
prompt = buildGeminiPrompt(messages as Message[], modelName)

if (stream) {
  const stream = await streamText({
    model: vertexClient,
    tools: getTool(),
    maxSteps: 5,
    messages: reqData.messages as CoreMessage[],
    async onStepFinish(event) {
      // callback stuff
    },
    async onFinish (event) {
      // Callback stuff
    },
  })
  
  return stream.toDataStreamResponse()
}
```

I'll play around some more and try to see what's causing this, but I'm really not 100% certain now.

**Comment by Und3rf10w** [comment]
Once I upgraded `@google-cloud/vertexai` from `1.3.1` to `1.8.1` resolved this. Sorry for any confusion and thank your for your patience.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported failure was ultimately attributed to an outdated dependency and resolved by upgrading it, so this is a dependency-version support issue rather than a confirmed AI SDK bug.

### Evidence
- The error occurred with `@google-cloud/vertexai` 1.3.1 while using `@ai-sdk/google-vertex` 0.0.39.
- The maintainer suggested a package-version mismatch rather than a reproducible SDK failure.
- The reporter confirmed that upgrading `@google-cloud/vertexai` to 1.8.1 resolved the problem.
