### ISSUE TITLE
`experimental_providerMetadata` inside `message` for mistral ignored.

### ISSUE THREAD

**Issue by DreamGenX** [vercel/ai#3183]
### Description

Mistral supports `prefix: true` on the last message, if it's an assistant message: https://docs.mistral.ai/guides/prefix/

### Code example

try adding this as a last message:

```ts
{
  role: 'assistant',
  content: 'Foo',
  experimental_providerMetadata: {
    mistral: {
      prefix: true
    }
  }
}
```

**Comment by lgrammel** [comment]
We handle this automatically now: https://github.com/vercel/ai/pull/3256

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes existing provider-specific message behavior failing to honor supported metadata, with a subsequent implementation fixing the behavior.

### Evidence
- The report states that Mistral's supported `prefix: true` metadata is ignored when supplied on the final assistant message.
- A maintainer says the behavior is now handled automatically and links to PR #3256, indicating a code-level resolution.
