### ISSUE TITLE
Allow the AI to continue the conversation after calling a tool

### ISSUE THREAD

**Issue by mrasoahaingo** [vercel/ai#3204]
### Feature Description

How do you manage the AI to continue the conversation when user doesn't need to respond after the tool response?

For example:

I want to make a tool which saves the user choice

```javascript
streamUI({
system: 'Ask the user to choose between A and B, save the choice. Then C and D, saved the choice'
...
tools: {
  save_user_choice: {
    ...
    generate: async function* ({ choice }) {
      yield "saving..."
      async saveChoice(choice)
      return "Your choice has been saved"
    }
  }
}
```

The chat :

```
assistant : choose between A and B
user : A
assistant : Your choice has been saved
```

Then I want the assisant to continue the conversation 
```
assistant : choose between A and B
user : A
assistant : Your choice has been saved

assistant: now choose between C and D
user : C
assistant : Your choice has been saved
assistant : Thank you!
```

**Comment by jeremyphilemon** [comment]
Hey @mrasoahaingo, thanks for opening an issue!

Based on your requirements, it sounds like this behavior can be achieved by switching over to [`useChat` and `streamText`](https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling) + using [`maxSteps`](https://sdk.vercel.ai/docs/reference/ai-sdk-ui/use-chat#max-steps) along with some prompt engineering. `streamUI` currently does not support multi-step tool calls.

I also imagine the system prompt to be:

> You are a friendly assistant. You need to save two choices by asking the user two questions. The first choice is between A and B, while the second choice is between C and D.

So the flow ends up being like:

```
assistant: choose between A and B
user: A
assistant: great thank you! no choose between C and D
user: C
assistant: awesome, I've saved your responses
```

Do note that you will have to write the system prompt in such a way that you assume the flow will have alternating `user` and `assistant` messages.

**Comment by mrasoahaingo** [comment]
Thanks, actually I want to use `streamUI` so I will deal with it :)

**Comment by lgrammel** [comment]
Please note that we are moving away from `streamUI` and putting it on pause for the near future. We recommend using ai sdk core + ui.

**Comment by mrasoahaingo** [comment]
Oh 🥲 ... It will be deprected? just asking if I should rewrite my code now 😄

**Comment by lgrammel** [comment]
@mrasoahaingo There are several long-standing limitations with AI SDK RSC that have been causing pain for our users, and there are no good solutions in the near term: https://sdk.vercel.ai/docs/getting-started/navigating-the-library#when-to-use-ai-sdk-rsc

To avoid people running into these issues, we recommend using AI SDK UI. We may resume work on AI SDK RSC once there are paths to resolving the underlying limitations.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This requests a capability that `streamUI` does not currently provide, rather than reporting a regression or contradiction of documented behavior.

### Evidence
- The requester wants `streamUI` to continue generating after a tool result so the assistant can perform additional conversational steps.
- A maintainer states that `streamUI` currently does not support multi-step tool calls and recommends `useChat`/`streamText` with `maxSteps` instead.
- The requester confirms they specifically want to use `streamUI`; maintainers describe AI SDK RSC as paused due to long-standing limitations.
