### ISSUE TITLE
NoSuchModelError thrown when using amazon-bedrock provider and `embed` function 

### ISSUE THREAD

**Issue by VaggelisKa** [vercel/ai#3211]
### Description

I am trying to generate text embeddings using the `@ai-sdk/amazon-bedrock` provider but whenever i try to pass any model id to `bedrock.textEmbeddingModel("...")` i get back an `AI_NoSuchModelError` error.

### Code example

```ts
import { createAmazonBedrock } from "@ai-sdk/amazon-bedrock";

export const bedrock = createAmazonBedrock({
  region: "eu-central-1",
  accessKeyId: "...",
  secretAccessKey: "...",
});

export const bedrockEmbeddingModel = bedrock.textEmbeddingModel(
  "amazon.titan-embed-text-v1" // Or any other model id,
);
```

I am then trying to use the generated model id through the `embed` function like so

```ts
    let { embedding } = await embed({
      model: bedrockEmbeddingModel,
      value: content.trim(),
    });
```

### Additional context

Notable library versions

```json
{
  "ai": "^3.4.9",
  "@ai-sdk/amazon-bedrock": "^0.0.29",
  "next": "14.2.14"
}
```

**Comment by gastonfartek** [comment]
I was looking to use titan as well but it seems it is not supported yet

https://github.com/vercel/ai/blob/main/packages/amazon-bedrock/src/bedrock-provider.ts#L109-L111

**Comment by VaggelisKa** [comment]
> I was looking to use titan as well but it seems it is not supported yet
> 
> https://github.com/vercel/ai/blob/main/packages/amazon-bedrock/src/bedrock-provider.ts#L109-L111

True i noticed that too after posting this issue, would be nice to have a more explanatory error message until support is added!

**Comment by gastonfartek** [comment]
depending on your use-case you might be able to do something like this

```typescript
type EmbeddingResponse = {
  embedding: number[];
  inputTextTokenCount: number;
};

type EmbedFn = (inputText: string) => Promise<EmbeddingResponse>;

const embed: EmbedFn = async (inputText) => {
  const client = new BedrockRuntimeClient({ region: "us-east-1" });

  const payload = {
    inputText,
  };

  const command = new InvokeModelCommand({
    contentType: "application/json",
    body: JSON.stringify(payload),
    modelId: "amazon.titan-embed-text-v1",
    // modelId: "amazon.titan-embed-text-v2:0",
  });
  const apiResponse = await client.send(command);

  const response = JSON.parse(
    new TextDecoder().decode(apiResponse.body),
  ) as EmbeddingResponse;

  return response;
};
```

**Comment by gastonfartek** [comment]
I create a PR for it here  https://github.com/vercel/ai/pull/3219

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3219

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
The reported error results from an unsupported provider capability rather than a failure of promised behavior. The issue effectively requests Amazon Bedrock embedding model support, with improved error messaging as a secondary concern.

### Evidence
- Amazon Bedrock text embedding models such as `amazon.titan-embed-text-v1` were not supported by the provider at the time.
- The reporter acknowledged the missing support and referred to support being added in the future.
- A follow-up pull request was created to implement the capability.
