### ISSUE TITLE
React Native (Expo) Support

### ISSUE THREAD

**Issue by aretrace** [vercel/ai#3217]
### Feature Description

I've been trying to get the AI SDK to work in Expo (React Native), both Core and UI. 
Repo showing my (limited) progress so far 👉 https://github.com/aretrace/expo-vercel-ai-sdk-debug

Could the `vercel/ai` team to take a look and hopefully add preliminary React Native support / documentation to the SDK? 
# 🥺🙏

> this feature request is separate from discussion issue https://github.com/vercel/ai/discussions/655, that particular issue has been solved by `unstable_enablePackageExports`

### Use Case

[4.3+ billion potential additional users](https://www.gsma.com/newsroom/press-release/smartphone-owners-are-now-the-global-majority-new-gsma-report-reveals/)

### Additional context

@codybrouwers @karaggeorge @jeremyphilemon @MaxLeiter @lgrammel @jaredpalmer @iteratetograceness

**Comment by lgrammel** [comment]
Expo 52 works with the AI SDK. Check out our guide: https://sdk.vercel.ai/docs/getting-started/expo

**Comment by nordwestt** [comment]
I'm using Expo 52 and have followed the guide, ensuring to import fetch from 'expo/fetch' and pass it to the constructor for createOllama. 
It works brilliantly on the web but on mobile (Expo Go), I get an error "First parameter has member 'readable' that is not a ReadableStream"

I've been bumping my head against the wall for several days on this issue. Any idea what might be the problem?

**Comment by longseespace** [comment]
> I'm using Expo 52 and have followed the guide, ensuring to import fetch from 'expo/fetch' and pass it to the constructor for createOllama. It works brilliantly on the web but on mobile (Expo Go), I get an error "First parameter has member 'readable' that is not a ReadableStream"
> 
> I've been bumping my head against the wall for several days on this issue. Any idea what might be the problem?

I run into the same issue. Did you ever figure out a solution?

**Comment by CatStudioApp** [comment]
> > I'm using Expo 52 and have followed the guide, ensuring to import fetch from 'expo/fetch' and pass it to the constructor for createOllama. It works brilliantly on the web but on mobile (Expo Go), I get an error "First parameter has member 'readable' that is not a ReadableStream"
> > I've been bumping my head against the wall for several days on this issue. Any idea what might be the problem?
> 
> I run into the same issue. Did you ever figure out a solution?



I think all folks above are focusing on client-server solution instead of pure client solution. Clearly the pure client solution does not work...

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Although originally opened as a support feature request, later comments describe a reproducible runtime failure in the now-documented Expo 52 support, making this a bug in current behavior.

### Evidence
- A maintainer stated that Expo 52 is supported and linked the official Expo guide.
- A user following that guidance reported that the SDK works on web but fails in Expo Go with: "First parameter has member 'readable' that is not a ReadableStream".
- Another user reproduced the same mobile failure, and a later comment stated that a pure-client solution does not work.
