### ISSUE TITLE
AIStream how to use toDataStreamResponse when fetching api response for useChat

### ISSUE THREAD

**Issue by QiaoLi1996** [vercel/ai#3241]
### Feature Description

env: nextjs 14.2.13 + ai sdk 3.3.43 + python api

Problem： I have a python api with stream return - `text/event-stream`, and I use fetch to call the api to get stream response.
and how can I use fetch api response in nextjs server side and toDataStreamResponse for client‘s useChat.

for client:
```javascript
  const useChatMethods = useChat({
    api: `${process.env.NEXT_PUBLIC_BASE_PATH}/api/test/json-stream-test`,
    streamProtocol: 'data',
    // streamProtocol: 'text',
    // headers: {
    //     Authorization: 'token',
    // },
    // credentials: 'same-origin',
    onResponse: (response: Response) => {
      console.log('chat-root --- Received response from server:', response)
    },
    onFinish: (message: Message) => {
      console.log('chat-root --- Finished streaming message:', message)
    },
    onError: (error: Error) => {
      console.error('chat-root --- An error occurred:', error)
    },
  });
```

for server
```javascript
  const response = await fetch(
    `http://127.0.0.1:5000/api/test/json-stream-test`,
    {
      method: "POST",
      headers: {
        // "Content-Type": "application/json",
        // "Cache-Control": "no-cache",
        // userName: "admin",
        // Authorization: `Bearer ${process.env.CREDIT_NOTE_TOKEN}`,
      },
      body: JSON.stringify({ 
        userName,
        conversationId: sessionId,
        messages
      }),
    }
  );

const stream = AIStream(response)

return new StreamingTextResponse(stream) 
```
I used to use Stream Text Response. If I want to use Steam Data Response, how to adjust?

### Additional context

by fetching python - `text/event-stream` api response, how can I use useChat with streamProtocol: 'data'

**Comment by QiaoLi1996** [comment]
Can anyone help? I’d be very grateful.

**Comment by lgrammel** [comment]
Please check out the data stream protocol and our FastAPI example:

- https://sdk.vercel.ai/docs/ai-sdk-ui/stream-protocol#data-stream-protocol
- https://github.com/vercel/ai/tree/main/examples/next-fastapi

**Comment by QiaoLi1996** [comment]
> Please check out the data stream protocol and our FastAPI example:请查看数据流协议和我们的 FastAPI 示例：
> 
> * https://sdk.vercel.ai/docs/ai-sdk-ui/stream-protocol#data-stream-protocol
> * https://github.com/vercel/ai/tree/main/examples/next-fastapi

I have solved this already, but still thanks.
```javascript
 // const stream = AIStream(response);
  const stream = AIStream(response, parser, {
    onStart() {
    },
    onText(text: string){
      console.log('onText text---', text);
      data.append({
        text: 'onText text---' + text,
      });
    },
    onCompletion(completion: string) {
      console.log('onCompletion completion---', completion);
    },
    onFinal(completion: string) {
      console.log('onFinal completion---', completion);
      data.close();
    },
    // experimental_streamData: true
  })
  
return new StreamingTextResponse(stream.pipeThrough(createStreamDataTransformer()), {}, data) 
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question about integrating an external Python stream, rather than a report of broken behavior or a request to change the SDK, documentation, or examples.

### Evidence
- The issue asks how to adapt a fetched Python SSE response for useChat with the data stream protocol.
- A maintainer directed the reporter to the data stream protocol documentation and FastAPI example.
- The reporter confirmed the problem was solved and shared working integration code; no SDK failure was identified.
