### ISSUE TITLE
Support abortion of tool execution

### ISSUE THREAD

**Issue by wong2** [vercel/ai#3272]
### Feature Description

Let's say I have a web search tool, it sends out an HTTP request to do a web search when it's executed.

```
const tools = {
  web_search: tool({
    .......
  }),
}

streamText({
  model: openai('gpt-4o'),
  prompt: '...',
  tools,
  abortSignal: req.signal,
})
```

Now I really wish I had a way to stop search requests in `web_search` when an abort happens, but it seems like there's no way to do it right now.

**Comment by lgrammel** [comment]
Would you want to use the same abort signal that we use for the main request? we could add it as an optional parameter to the tools, then you could use it in the tool implementation. alternatively you can use the abort signal from the closure when you create the tool

**Comment by wong2** [comment]
I think using the same abort signal I passed to `streamText` is enough.

**Comment by wong2** [comment]
Yeah, something like this would be cool :

```
execute: async ({ query }, abortSignal) => {
   ...  
}
```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3277

**Comment by wong2** [comment]
Thanks, good job as always!

**Comment by wong2** [comment]
I've gave it a try, and get the following type error:

```
execute: async ({ query }, { abortSignal }) => {
  const searchResults = await searchWeb(query, numResults, abortSignal)
  return { searchResults }    
}
```

```
    Type '({ query }: { query: string; }, { abortSignal }: { abortSignal?: AbortSignal | undefined; }) => Promise<SpecificErrorInstance<[], { query: string; }, CustomClass, AggregateErrors, unknown> | { ...; }>' is not assignable to type '((args: { query: string; }, options: { abortSignal?: AbortSignal | undefined; }) => PromiseLike<SpecificErrorInstance<[], { query: string; }, CustomClass, AggregateErrors, unknown> | { ...; }>) & ((args: { ...; }) => PromiseLike<...>)'.
      Type '({ query }: { query: string; }, { abortSignal }: { abortSignal?: AbortSignal | undefined; }) => Promise<SpecificErrorInstance<[], { query: string; }, CustomClass, AggregateErrors, unknown> | { ...; }>' is not assignable to type '(args: { query: string; }) => PromiseLike<SpecificErrorInstance<[], { query: string; }, CustomClass, AggregateErrors, unknown> | { searchResults: WebSearchResult[]; }>'.
        Target signature provides too few arguments. Expected 2 or more, but got 1.
  Overload 2 of 2, '(tool: CoreTool<ZodObject<{ query: ZodString; }, "strip", ZodTypeAny, { query: string; }, { query: string; }>, SpecificErrorInstance<[], { query: string; }, CustomClass, AggregateErrors, unknown> | { ...; }> & { ...; }): CoreTool<...> & { ...; }', gave the following error.
    Type '({ query }: { query: string; }, { abortSignal }: { abortSignal?: AbortSignal | undefined; }) => Promise<SpecificErrorInstance<[], { query: string; }, CustomClass, AggregateErrors, unknown> | { ...; }>' is not assignable to type 'undefined'.ts(2769)

```

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3285

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Although opened as a feature request, the comments identify a concrete type failure in the implemented behavior. Per the classification rules, the concrete failure takes precedence.

### Evidence
- The original request asks for passing the `streamText` abort signal into tool execution.
- After PR #3277 implemented this, the reporter received a TypeScript overload error when defining `execute` with the new second `{ abortSignal }` parameter.
- The maintainer responded with follow-up PR #3285, indicating the initial implementation required a fix.
