### ISSUE TITLE
Bedrock + createObject + Claude 3.5 + CoT | sometimes wraps json in <thinking> tags

### ISSUE THREAD

**Issue by pr1ntr** [vercel/ai#3283]
### Description

See the code below as its self explanatory. If I tell Claude to use the CoT technique and place its output into `<thinking>` tags. 
see [these](https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/chain-of-thought#example-writing-donor-emails-structured-guided-cot) docs

It will sometimes try to output:
```
<thinking>
{...json}
</thinking>
```

and then it breaks 

### Code example

```
export const getSegmentAnalysisPrompt = (start: number, end: number, distance: number) => `
**Input Parameters:**
  
  **Start Point:**
  <startPoint>${start}</startPoint>
  
  **End Point:**
  <endPoint>${end}</endPoint>
    
  **Distance of Segment:**
  <segmentDistance>${distance}km</segmentDistance>

Think before you create this anaylsis in <thinking> tags.

1. Choose a range within the <startPoint> and <endPoint> that can be described by the <description> from the <trackFeaturesDictionary>
Consider the <segmentDistance> of the range in choosing what type of feature it is.
The middle point of that range must be the most important point in the segment.
It must not be the entirity of the input range
Start must always be less than end.
place values into <id>, <start> and <end> tags


2. generate a list of 5-10 titles for the segment.
Try to be irrelevant and fun with the titles.
place the titles into <titles> tags


Review the data and make sure it adheres to the instructions. If it does not start over.
`

export async function analyzeTrackSegment({ startIndex, endIndex, image, distance }: AnalyzeTrackSegmentInput) {
  const imagePart: ImagePart = {
    type: 'image',
    image: image.imageData,
    mimeType: image.contentType,
  }
  console.log('start and end in:', startIndex, endIndex)
  const system = getSegmentAnalysisSysPrompt()
  const text = getSegmentAnalysisPrompt(startIndex, endIndex, distance)
  const messages: CoreMessage[] = [
    {
      role: 'user',
      content: [
        imagePart,
        {
          type: 'text',
          text,
        },
      ],
    },
  ]
  const now = Date.now()
  const result = await generateObject({
    model: bedrock(AWS_BEDROCK_MODEL_ID as string),
    schema: analyzeSegmentSchema,
    system,
    messages,
    temperature: 1,
    maxTokens: 2000,
  })
  console.log('Receive Text', Date.now() - now)

  console.log('start and end, out:', result.object.analyses[0].start, result.object.analyses[0].end)

  return result.object
}


```

### Additional context

I also tried to prefill an assistant `{` message but the SDK says that is not supported. Assuming the createObject method already does that.

**Comment by lgrammel** [comment]
This is an issue with the LLM output. The technique from Anthropic is not intended for structured outputs. To achieve something similar with structured outputs, you want to give the LLM a field in the structure that it can write to, e.g. "reasoning: string". This field has to come first, so the model can reason by outputting tokens and then complete the structure afterwards.

**Comment by pr1ntr** [comment]
i think i understand.. so don't use XML but make it reason inside of json fields?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support issue caused by combining incompatible prompting instructions with structured output, not a demonstrated AI SDK defect or a concrete request for new functionality.

### Evidence
- The prompt explicitly asks Claude to emit chain-of-thought in XML `<thinking>` tags while `generateObject` expects structured JSON output.
- The maintainer states that this is an LLM-output issue and that Anthropic's XML technique is not intended for structured outputs.
- The suggested resolution is to add a leading `reasoning: string` field to the schema rather than change SDK behavior.
