### ISSUE TITLE
Unnecessary serialization of inputs and outputs when telemetry is disabled

### ISSUE THREAD

**Issue by V3RON** [vercel/ai#3311]
### Description

We're encountering a performance issue with the SDK related to the telemetry functionality. Even though we don’t use telemetry at all (we don’t provide any value for the telemetry parameter), the SDK still serializes the inputs and outputs. This serialization seems unnecessary, as it isn't used for anything without telemetry being enabled, and it negatively impacts performance.

This becomes a significant problem when dealing with large binary data like images. The SDK uses `JSON.stringify`, which also attempts to serialize ArrayBuffer objects. This causes memory spikes during request processing. For instance, when sending a 1MB image, we observed memory usage increasing from 30MB to around 120MB temporarily, which can lead to out-of-memory exceptions in some environments. Whether the serialization logic should include binary data is another topic for discussion.

We’ve confirmed that a workaround for this issue is to provide parameters `recordInputs` and `recordOutputs` to explicitly prevent the serialization of inputs and outputs. However, there is no reason for the SDK to serialize inputs and outputs in the first place if telemetry isn't being used. Ideally, the SDK should skip this serialization entirely when telemetry is disabled.

### Additional context

**Steps to reproduce**
1. Do not provide a value for the telemetry parameter in the SDK configuration (i.e., no telemetry settings are specified).
2. Send a request with a large binary payload, such as an image (ArrayBuffer).
3. Monitor memory usage during the request processing.

**Cause**
It appears that the following piece of code is responsible for the issue:

```javascript
if (telemetry?.recordInputs === false) {
  return attributes;
}
```

The problem arises because when the telemetry parameter is not provided, the condition `telemetry?.recordInputs === false` evaluates to false.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3314

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete performance and memory failure in existing SDK behavior: telemetry data is unnecessarily serialized when telemetry is not enabled.

### Evidence
- Inputs and outputs are serialized even when no telemetry configuration is provided.
- Serialization of large binary payloads causes substantial temporary memory spikes and can trigger out-of-memory errors.
- Explicitly setting recordInputs and recordOutputs prevents the behavior, indicating telemetry-related work is occurring despite telemetry being disabled.
- A maintainer linked PR #3314 in response, suggesting a code-level correction.
