### ISSUE TITLE
Update peerDeps for Svelte 5

### ISSUE THREAD

**Issue by Pascaltib** [vercel/ai#3345]
### Description

After upgrading to Svelte 5 and running `npm install` I get: 

```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: navar@0.0.1
npm ERR! Found: svelte@5.0.5
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^4.0.0" from @uploadthing/svelte@7.0.3
npm ERR! node_modules/@uploadthing/svelte
npm ERR!   @uploadthing/svelte@"^7.0.3" from the root project
npm ERR!
```

Although I can do `npm install --legacy-peer-deps`

Just need to update the peerDependencies as I can see that ^5.0.0-next.0 was already supported.

**Comment by Pascaltib** [comment]
woops! wrong repo!!!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a misfiled issue about another repository and does not describe a vercel/ai bug or requested change.

### Evidence
- The reported dependency conflict concerns `@uploadthing/svelte`, not a package in `vercel/ai`.
- The author explicitly states, “wrong repo.”
