### ISSUE TITLE
async onFinish not reporting message annotations

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#3358]
### Description

In the onFinish callback I am trying to send to the UI that an error has occured (I'd prefer to just update the message & properties send back to the UI), but the data annotations are not being sent to the top in this situation.

If I comment out the await titlePromise call, it'll display the annotations on the client. However, as soon as I add that line back in, it fails to send the annotations to the client, even though the stream is was open. FYI if I don't' close the stream, it stays in a loading state, so I know it still sees the dataStream.

Also, if I add a .then(results => results.toDataStreamResponse({data}) that works, but I don't want to put it there.

```
const result = await streamText({
      temperature: 1,
      tools,
      model: setupVertex({ useSearchGrounding: useGrounding }),
      system: system_prompt,
      messages: convertToCoreMessages(secureMessages),
      maxSteps: 10,
      frequencyPenalty: 0.15,
      onFinish: async finishResult => {
          let title = await titlePromise
		  console.log(title)
		  await data.appendMessageAnnotation({
			content: `I'm an annotation`,
			name: `error`
		  })
		  await data.append('call completed')
		  await data.close()
        }
      }
    })
    return result.toDataStreamResponse({ data })
```

**Comment by lgrammel** [comment]
Can it be that the `titlePromise` never resolves and thus the code after it does not get executed?

**Comment by Godrules500** [comment]
> Can it be that the `titlePromise` never resolves and thus the code after it does not get executed?

Sorry, I should of put that in there. I had checked first and it does resolve.

**Comment by lgrammel** [comment]
Also, this should not affect anything, but the `await` statements for data.append etc are not necessary.

**Comment by Godrules500** [comment]
> Also, this should not affect anything, but the `await` statements for data.append etc are not necessary.

Haha I realized that, but I was desparately awaiting everything I could.

**Comment by lgrammel** [comment]
> Also, if I add a .then(results => results.toDataStreamResponse({data}) that works, but I don't want to put it there.

This is very strange. However, would this be good enough as a workaround for the time being?

**Comment by Godrules500** [comment]
> > Also, if I add a .then(results => results.toDataStreamResponse({data}) that works, but I don't want to put it there.
> 
> This is very strange. However, would this be good enough as a workaround for the time being?

After further looking into it, I think it runs a little deeper. Anytime I have an async call in the onFinish, it isn't sending the annotations back to the client.

**Comment by Godrules500** [comment]
@lgrammel Another interesting thing is if I remove dataStream.close, it leaves the UI in a loading state. So the dataStream.close gets to the client, but the dataStream.appendMessageAnnotation does not get to the client.

**Comment by lgrammel** [comment]
I'll see if I can find the time to debug this today/tomorrow, it's important that async stuff works in onFinish

**Comment by mdluo** [comment]
## Case 1

Calling `data.appendMessageAnnotation` after an async task (e.g. inserting into db and return the id), the data chunk comes after the `finishReason` chunks:

```ts
await streamText({
  onFinish: async (message) => {
    try {
      const newId = await insertIntoDatabase(message);
      data.appendMessageAnnotation({ id: newId });
    } finally {
      await data.close();
    }
  },
});
```

![Google Chrome 2024-10-26 16 21 50](https://github.com/user-attachments/assets/40bb40a6-481f-4abb-9556-c683241805a9)

Outcome: **`onFinish` was not triggered**

## Case 2

Calling `data.appendMessageAnnotation` after `await Promise.resolve()`, the data chunk comes between the `finishReason` chunks:

```ts
await streamText({
  onFinish: async (message) => {
    try {
      await Promise.resolve();
      data.appendMessageAnnotation({ id: nanoid() });
    } finally {
      await data.close();
    }
  },
});
```

![CleanShot 2024-10-26 at 16 26 49@2x](https://github.com/user-attachments/assets/009640a5-47c8-4751-9983-cad699c530b5)

Outcome: **`onFinish` was not triggered**

## Case 3

Calling `data.appendMessageAnnotation` without prior async tasks, the data chunk comes before the `finishReason` chunks:

```ts
await streamText({
  onFinish: async (message) => {
    data.appendMessageAnnotation({ id: nanoid() });
    await data.close();
  },
});
```

![Google Chrome 2024-10-26 16 21 08](https://github.com/user-attachments/assets/9dcd7a2a-3d24-4c15-9954-8eb5818cd9a1)

Outcome: **`onFinish` was triggered**

**Comment by mdluo** [comment]
## Case 1

Calling `data.appendMessageAnnotation` after an async task (e.g. inserting into db and return the id), the data chunk comes after the `finishReason` chunks:

```ts
await streamText({
  onFinish: async (message) => {
    try {
      const newId = await insertIntoDatabase(message);
      data.appendMessageAnnotation({ id: newId });
    } finally {
      await data.close();
    }
  },
});
```

![Google Chrome 2024-10-26 16 21 50](https://github.com/user-attachments/assets/40bb40a6-481f-4abb-9556-c683241805a9)

Outcome: **`onFinish` was not triggered**

## Case 2

Calling `data.appendMessageAnnotation` after `await Promise.resolve()`, the data chunk comes between the `finishReason` chunks:

```ts
await streamText({
  onFinish: async (message) => {
    try {
      await Promise.resolve();
      data.appendMessageAnnotation({ id: nanoid() });
    } finally {
      await data.close();
    }
  },
});
```

![CleanShot 2024-10-26 at 16 26 49@2x](https://github.com/user-attachments/assets/009640a5-47c8-4751-9983-cad699c530b5)

Outcome: **`onFinish` was not triggered**

## Case 3

Calling `data.appendMessageAnnotation` without prior async tasks, the data chunk comes before the `finishReason` chunks:

```ts
await streamText({
  onFinish: async (message) => {
    data.appendMessageAnnotation({ id: nanoid() });
    await data.close();
  },
});
```

![Google Chrome 2024-10-26 16 21 08](https://github.com/user-attachments/assets/9dcd7a2a-3d24-4c15-9954-8eb5818cd9a1)

Outcome: **`onFinish` was triggered**

**Comment by lgrammel** [comment]
Reproduced for message annotations (`data` works though):

```
export async function POST(req: Request) {
  const { messages } = await req.json();

  // use stream data
  const data = new StreamData();
  data.append('initialized call');

  const result = await streamText({
    model: openai('gpt-4o'),
    messages: convertToCoreMessages(messages),
    async onFinish() {
      // this introduces the bug, potentially because of the delay
      await new Promise(resolve => setTimeout(resolve, 1000));

      // message annotation:
      data.appendMessageAnnotation({
        id: generateId(), // e.g. id from saved DB record
        other: 'information',
      });

      // call annotation:
      data.append('call completed');

      data.close();
    },
  });

  return result.toDataStreamResponse({ data });
}
```

**Comment by lgrammel** [comment]
Potential cause: the message was already updated, and the changes in the message annotation do not trigger an update on the frontend.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3367

**Comment by lgrammel** [comment]
pls update all ai-sdk ui packages and ai to latest.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing streaming behavior: asynchronous work in `onFinish` caused message annotations to be missed by the frontend. It was reproduced and fixed upstream.

### Evidence
- Message annotations appended after any asynchronous work in `streamText.onFinish` were not reflected by the client, while synchronous annotations worked.
- A second reporter provided reproducible cases showing late annotation chunks and `useChat.onFinish` not firing.
- A maintainer reproduced the failure, identified it as a bug, linked PR #3367, and the reporter confirmed the updated packages fixed it.
