### ISSUE TITLE
ai-sdk/google-vertex Tool call with double answers

### ISSUE THREAD

**Issue by Alaboudi1** [vercel/ai#3366]
### Description

I’m using a basic streamText call that includes two tool calls. I’ve observed an unusual behavior: the LLM executes the tool call and responds to the question before retrieving the data. Then, after receiving the data, it responds again. This behavior only occurs with @ai-sdk/google-vertex and not with @ai-sdk/openai, based on my testing.

Correct Tool call
<img width="896" alt="image" src="https://github.com/user-attachments/assets/68459690-2727-4419-b337-60c6c27f05e2">
You can see above the the tool call is initiated, finished and then answer start streaming.

However, here is the incorrect behavior 
<img width="871" alt="image" src="https://github.com/user-attachments/assets/d0bc99eb-9b6d-426d-bec6-0e499bd94ae7">

Here the tool call is initiated, then some response in text based on message history and then the tool call is finished and then the correct response is streamed.

Is this a bug? if not, how can I prevent this behavior? Thanks 

### Code example
```
import {
  streamText,
  tool,
} from "ai";
import { geminiProModel, geminiFlashModel, openAiModel } from "@/ai";
import { z } from "zod";
import { getFilteredCSVData, getStraegyData } from "../tools";

export const POST = async (request: Request) => {
  const requestData = await request.json();

  const response = await streamText({
    messages: requestData.messages,
    model: geminiProModel,
    system: `xxxx`,
    tools: {
      fetchAhadProjectStatisticsAndOpportunities: tool({
        description: `xxxxxx`,
        parameters: z.object({
          columns: z.array(z.string()).describe(`xxxxxx`),
        }),
        execute: async ({ columns }: { columns: string[] }): Promise<any> => {
          try {
           xxxxxxxx

            return {
              data: data.map((row) => JSON.stringify(row)).join("\n"),
            };
          } catch (error) {
            console.error("Error in getProjectSimpleData:", error);
            throw new Error("Failed to retrieve project data");
          }
        },
      }),
      answerCompanyStrategyQueries: tool({
        description: `xxxxx`,
        parameters: z.object({
          question: z
            .string()
            .describe(
              `xxxxxx`
            ),
          type: z.string().describe(`xxxx`),
        }),
        execute: async ({
          question,
          type,
        }: {
          question: string;
          type: string;
        }) => {
          xxxxx
          return {
            userRefinedQuery: question,
            supportingDocument: doc,
          };
        },
      }),
    },
    maxSteps: 5,
    temperature: 0,
  });

  return response.toDataStreamResponse({
    headers: {
      "Cache-Control": "no-cache",
      "Content-Type": "text/event-stream",
    },
  });
};
```

**Comment by lgrammel** [comment]
@Alaboudi1 does the bug still occur with the latest AI SDK versions? We fixed a related issue: https://github.com/vercel/ai/issues/3953

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete, provider-specific incorrect streaming behavior in which an answer is produced twice around tool execution. This is a failure of existing behavior rather than a request for a new capability.

### Evidence
- With @ai-sdk/google-vertex, streamText emits an answer during the tool-call step and then emits another answer after receiving the tool result.
- The same setup reportedly behaves correctly with @ai-sdk/openai, and the attached stream output demonstrates the duplicate response.
- A maintainer explicitly referred to the behavior as a bug and linked a related fix, asking whether it still occurs in the latest SDK.
