### ISSUE TITLE
Returning an image from the computer tool in the Anthropic provider sends the content as a string

### ISSUE THREAD

**Issue by carloslfu** [vercel/ai#3370]
### Description

I put together https://github.com/carloslfu/aven to test Claude's computer use capabilities using the AI SDK. At first, I hacked my way to it, but the behavior seems to continue even after updating to the latest release.

The problem is when you return an image from the computer tool to return the screenshot. Here is the diff of the updated version: https://github.com/carloslfu/aven/commit/ce71f88561b0be899f3412898a5156ce08202790#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R306

![Screenshot 2024-10-27 at 9 43 40 AM](https://github.com/user-attachments/assets/fb93bfe7-0cd8-465c-bdcd-66c84cfd2134)

Here is the full file: https://github.com/carloslfu/aven/blob/remove-tool-response-workaround/src/App.tsx#L306

I inspected the outgoing request, and the problem is that the `tool_result` content is being sent as a string, not as an array. Here is the request body:

```json
{
  "model": "claude-3-5-sonnet-20241022",
  "max_tokens": 8192,
  "temperature": 0,
  "system": [
    {
      "type": "text",
      "text": "You are a helpful assistant that can control the computer.\n\n<SYSTEM_CAPABILITY>\n ..."
    }
  ],
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "type hello world in textedit"
        }
      ]
    },
    {
      "role": "assistant", 
      "content": [
        {
          "type": "text",
          "text": "I'll help you type \"hello world\" in TextEdit. Let me break this down into steps:\n\n1. First, I need to take a screenshot to see the current state of the desktop\n2. Find and click on TextEdit\n3. Wait for it to open\n4. Type \"hello world\"\n\nLet's start:"
        },
        {
          "type": "tool_use",
          "id": "toolu_01791VbzhLRZBfycSKSrgMVd",
          "name": "computer",
          "input": {
            "action": "screenshot"
          }
        }
      ]
    },
    {
      "role": "user",
      "content": [
        {
          "type": "tool_result",
          "tool_use_id": "toolu_01791VbzhLRZBfycSKSrgMVd",
          "content": "[{\"type\":\"image\",\"data\":\"iVBORw0KGgoAAA...\",\"mimeType\":\"image/png\"}]"
        }
      ]
    }
  ],
  "tools": [
    {
      "name": "computer",
      "type": "computer_20241022",
      "display_width_px": 1920,
      "display_height_px": 1080
    }
  ],
  "tool_choice": {
    "type": "auto"
  },
  "stream": true
}
```

**Comment by lgrammel** [comment]
https://sdk.vercel.ai/providers/ai-sdk-providers/anthropic#computer-tool

You need to implement a separate method on your tool for the correct conversion to multi part tool results.

**Comment by carloslfu** [comment]
Yes, I tried using `experimental_toToolResultContent`, but it didn't help, although I could see that it was being used because the logs fired. This is the code: https://github.com/carloslfu/aven/blob/remove-tool-response-workaround/src/App.tsx#L320.

![Screenshot 2024-10-27 at 11 05 45 AM](https://github.com/user-attachments/assets/f7b7c287-e95d-47b7-b62c-6b49f320b3ef)

I removed and reinstalled the modules just to be sure and the error continues. The versions are `@ai-sdk/anthropic` v0.0.53 and `ai` v3.4.20.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in the Anthropic provider’s existing image tool-result serialization, including when the documented conversion method is used.

### Evidence
- Anthropic `tool_result.content` is serialized as a JSON string instead of the required multipart content array for an image result.
- The reporter reproduced the problem on `@ai-sdk/anthropic` 0.0.53 and `ai` 3.4.20.
- After the maintainer recommended `experimental_toToolResultContent`, the reporter confirmed that the callback ran and returned image content, but the incorrect serialization persisted.
