### ISSUE TITLE
Empty parameter's not passing through for tools - Google Gemini 1.5 Flash

### ISSUE THREAD

**Issue by ajaykrupalk** [vercel/ai#3371]
### Description

I am using streamText and the model `Google Gemini 1.5 Flash 002`, and getting this error `GenerateContentRequest.tools[0].function_declarations[5].parameters.properties: should be non-empty for OBJECT type`

### Code example

```js
const result = await streamText({
        model: google("gemini-1.5-flash-002"),
        system: `\
            - you are a friendly home automation assistant
            - reply in lower case
            - do not add more lights until you are asked to
        `,
        messages: convertToCoreMessages(messages),
        maxSteps: 5,
        tools: {
           viewCameras: {
                description: "view all available cameras",
                parameters: z.object({}),
                execute: async () => {
                    return { };
                }
            },
```

**Comment by lgrammel** [comment]
Reproduced.

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3392/files

**Comment by faev999** [comment]
I got the same error using all the new gemini2.0 models (lite,  pro ,flash). I am on windows using litellm 1.60.8:


```
Lib\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 1206, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: VertexAIException BadRequestError - {    
  "error": {
    "code": 400,
    "message": "* GenerateContentRequest.tools[0].function_declarations[0].parameters.properties: should be non-empty for OBJECT type\n* GenerateContentRequest.tools[0].function_declarations[2].parameters.properties: should be non-empty for OBJECT type\n* GenerateContentRequest.tools[0].function_declarations[3].parameters.properties: should be non-empty for OBJECT type\n* GenerateContentRequest.tools[0].function_declarations[4].parameters.properties: should be non-empty for OBJECT type\n",
    "status": "INVALID_ARGUMENT"
  }
}
```
I think this not a litellm problem, but it is rather on Gemini side:
https://discuss.ai.google.dev/t/gemini-doesnt-accept-parameterless-functions/56501/12

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a reproducible failure in existing tool-calling behavior for valid parameterless tool definitions, rather than a request for a new capability.

### Evidence
- Using `streamText` with Gemini 1.5 Flash and a parameterless tool defined as `z.object({})` returns a 400 error requiring non-empty object properties.
- A maintainer confirmed the issue was reproduced and linked pull request #3392.
- A later comment reports the same failure with Gemini 2.0 models.
