### ISSUE TITLE
Tool Result Content Incorrectly Serialized as String Instead of Array

### ISSUE THREAD

**Issue by qunash** [vercel/ai#3379]
### Description

When using tools with the Anthropic client, the tool result content is being incorrectly serialized as a JSON string instead of being passed as a proper array. This affects the handling of tool results, particularly when working with image data.

## Current Behavior
The tool result content is being sent as a stringified JSON array:

```json
{
  "role": "user",
  "content": [
    {
      "type": "tool_result",
      "tool_use_id": "toolu_01S7EwkaZG1prpL9Z83tuDFX",
      "content": "[{\"type\":\"image\",\"data\":\"XYZ==\",\"mimeType\":\"image/png\"}]"
    }
  ]
}
```

## Expected Behavior
The tool result content should be sent as a proper array:
```json
{
  "role": "user",
  "content": [
    {
      "type": "tool_result",
      "tool_use_id": "toolu_01S7EwkaZG1prpL9Z83tuDFX",
      "content": [{"type": "base64", "data": "XYZ==", "media_type": "image/png"}]
    }
  ]
}
```

### Code example

```Typescript
import { streamText, type CoreMessage, tool } from 'ai';
import { createAnthropic } from '@ai-sdk/anthropic';
import { z } from 'zod';

const screenshotTool = {
  take_screenshot: tool({
    description: 'Takes a screenshot of the current tab and returns it as a base64 encoded image',
    parameters: z.object({}),
    execute: async (_, { abortSignal } = {}): Promise<{ data: string }> => {
      return {
        data: "XYZ=="
      };
    },
    experimental_toToolResultContent(result) {
      return [{ type: 'image', data: result.data, mimeType: 'image/png' }];
    }
  })
};

const anthropicClient = createAnthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!
});

const model = anthropicClient('claude-3-5-sonnet-20241022');

async function main() {
  const messages: CoreMessage[] = [{
    role: 'user',
    content: 'Can you take a screenshot of the page and describe what you see?'
  }];

  const result = await streamText({
    model,
    messages,
    system: 'You are an AI assistant that can take and analyze screenshots.',
    tools: screenshotTool,
    maxSteps: 3,
    experimental_toolCallStreaming: true
  });

  return result.toDataStreamResponse();
}
```
The official [computer use example](https://github.com/vercel/ai/blob/main/examples/ai-core/src/generate-text/anthropic-computer-use-computer.ts) from this repo does not work for the same reason.

### Additional context

```
@ai-sdk/anthropic version: 0.0.53
ai package version: 3.4.20
```

**Comment by lgrammel** [comment]
can you try ai 3.4.21

**Comment by qunash** [comment]
> can you try ai 3.4.21

Thanks for the quick update. But there's still a problem: when there are multiple tool result contents with images in the message history, older ones are still sent as a string, not a JSON list. So the bug is not quite fixed yet

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete serialization failure in existing tool-result handling that produces an incorrect Anthropic request payload and breaks image tool results.

### Evidence
- Anthropic tool result content containing image data is serialized as a JSON string rather than the required content array.
- The reporter confirmed that version 3.4.21 still stringifies older image tool results when multiple results are present in message history.
- A maintainer linked PR #3403 as a first solution, confirming a product-level fix.
