### ISSUE TITLE
[google-vertex] gs:// for file parts not working

### ISSUE THREAD

**Issue by rovnyart** [vercel/ai#3391]
### Description

"ai": "3.4.18",
"@ai-sdk/google-vertex": "0.0.40",

I'm trying to move my code to vercel/ai from @google-cloud/vertexai. I need to pass audio files to the model, and I found  out from doco, that (I think) there is a possibility to pass gs:// links to google storage objects. At least I understood the [documentation](https://sdk.vercel.ai/providers/ai-sdk-providers/google-vertex#file-inputs) that way:) But it seems like not working now - I get a validation error: Base64 decoding failed for gs://xxx.mp3. Am I missing something?

### Code example

```
 const model = this.vertex('gemini-1.5-flash-002', {
      structuredOutputs: true,
    });

    const { object } = await generateObject({
      model,
      schema: callAnalysisSchema,
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: callReportPrompt },
            {
              type: 'file',
              data: `gs://${config.googleStorage.buckets.audioCalls}/${objectId}`,
              mimeType: 'audio/mpeg',
            },
          ],
        },
      ],
      experimental_telemetry: {
        isEnabled: true,
        metadata: {
          objectId,
        },
      },
    });
```

**Comment by lgrammel** [comment]
can you try

```
data: new URL(`gs://${config.googleStorage.buckets.audioCalls}/${objectId}`)
```

**Comment by rovnyart** [comment]
Getting new error:
```
AI_DownloadError: Failed to download gs://kespa-calls-mp3/69dc8bb5-2adb-4a7b-9b0e-c742ac5ebedf.mp3: TypeError: protocol must be http: or https:
 url: "gs://kespa-calls-mp3/69dc8bb5-2adb-4a7b-9b0e-c742ac5ebedf.mp3"
 ```

**Comment by lgrammel** [comment]
You need `"@ai-sdk/google-vertex": "0.0.42",`

**Comment by rovnyart** [comment]
thanks, it's working on 0.0.42

**Comment by vishalsaugat** [comment]
@lgrammel Its is not working if the file has spaces. Working fine if file doesnt have space

**Comment by lgrammel** [comment]
@vishalsaugat spaces are unsafe in URLs (as are some other characters), you need to replace them with `%20`

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported failure was resolved by using the supported input form and package version, with no remaining SDK defect identified. This is primarily a resolved usage/version support question.

### Evidence
- The reporter used @ai-sdk/google-vertex 0.0.40 and received a base64 validation error for a gs:// file reference.
- A maintainer instructed them to pass the value as a URL and upgrade to @ai-sdk/google-vertex 0.0.42.
- The reporter confirmed that it worked after upgrading to 0.0.42.
