### ISSUE TITLE
FinishReason is tool-calls but returns an error in useChat and text is empty

### ISSUE THREAD

**Issue by ajaykrupalk** [vercel/ai#3433]
### Description

What I have tried already?
- set maxSteps to 25
- my ai SDK is on version 3.4.9
- my google provider SDK is on version 0.0.55

I am using streamText, the exact issue is that when there is a message from the user, and error is enabled in useChat, there is an error, which is not clear. See Attached  image below.

ThefinishReason in onStepFinish is tool-calls and the text is empty, but there is an error message (Below attached image)
```json
{"stepType":"initial","text":"","toolCalls":[],"toolResults":[],"finishReason":"tool-calls","usage":{"promptTokens":722,"completionTokens":4,"totalTokens":726},"warnings":[],"response":{"id":"aitxt-kdi1VZL53dzCHiQfaUAQHw6W","timestamp":"2024-10-31T14:07:18.552Z","modelId":"gemini-1.5-flash-002"},"rawResponse":{"headers":{"alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","content-disposition":"attachment","content-type":"text/event-stream","date":"Thu, 31 Oct 2024 14:07:18 GMT","server":"scaffolding on HTTPServer2","server-timing":"gfet4t7; dur=1522","transfer-encoding":"chunked","vary":"Origin, X-Origin, Referer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"0"}},"isContinued":false}
```

The response from the model:
```json
{"warnings":[],"rawResponse":{"headers":{"alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","content-disposition":"attachment","content-type":"text/event-stream","date":"Thu, 31 Oct 2024 14:07:18 GMT","server":"scaffolding on HTTPServer2","server-timing":"gfet4t7; dur=1522","transfer-encoding":"chunked","vary":"Origin, X-Origin, Referer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"0"}},"usage":{},"finishReason":{},"text":{},"toolCalls":{},"toolResults":{},"steps":{},"experimental_providerMetadata":{},"response":{},"responseMessages":{},"originalStream":{}}
```

Error from the console from useChat
```js
const { messages, handleSubmit, input, handleInputChange, append, isLoading, stop, error, reload } = useChat({
    body: { id },
    initialMessages,
    maxSteps: 5,
    keepLastMessageOnError: true,
  })
console.log("error", error, error?.message)
```
![image](https://github.com/user-attachments/assets/af07f02d-6ebe-481f-a26c-672858e5de99)

### Code example

```js
const result = await streamText({
        model: google("gemini-1.5-flash-002"),
        messages: convertToCoreMessages(messages),
        maxSteps: 5,
        tools: {
            updateHub: {
                description: "update the hub with new values",
                parameters: z.object({
                    hub: z.object({
                        climate: z.object({
                            low: z.number(),
                            high: z.number(),
                        }),
                        lights: z.array(
                            z.object({ name: z.string(), status: z.boolean() }),
                        ),
                        locks: z.array(
                            z.object({ name: z.string(), isLocked: z.boolean() }),
                        ),
                    }),
                }),
                execute: async ({ hub: newHub })=> {
                    console.log("update hub with")
                    hub = newHub;
                    return hub;
                }
            },
       },
        onStepFinish: async (result) => {
            console.log(JSON.stringify(result));
        }
    });

    console.log("Result from model", JSON.stringify(result))
    return result.toDataStreamResponse({});
```

### Additional context

Any workaround or fix is appreciated

**Comment by lgrammel** [comment]
Error messages are suppressed by default for security reasons. Please check out https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot#error-messages for information on how to forward them to the frontend.

**Comment by lgrammel** [comment]
This looks like a prompt engineering issue to me. Gemini seems to call the function with data that does not match the schema. I suggest 2 things:

- write a good system prompt that instructs the model what to do
- give it an outlet to opt out of the hub update (here it tried entering 'unknown', maybe make that possible)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The SDK is correctly rejecting invalid tool arguments, and the unclear frontend error is documented security behavior. The issue is therefore a support/prompt-engineering question rather than an SDK bug or requested product change.

### Evidence
- Forwarding the suppressed error revealed that Gemini called `updateHub` with `{"hub":"unknown"}`, which violates the declared object schema.
- The maintainer explained that frontend error messages are suppressed by default for security and linked the documented forwarding mechanism.
- The maintainer characterized the failure as a prompt-engineering/model-output issue and suggested improving the system prompt or allowing an opt-out value.
