### ISSUE TITLE
Possible regression? The `useChat` `onFinish` callback started getting called _before_ the tools have executed for streamText

### ISSUE THREAD

**Issue by jstjoe** [vercel/ai#3437]
### Description

Have not isolated reproduction steps yet, a bit stuck. Seeing a new problem with existing code.
The behavior does not occur in my local dev environment, only when I push to a Vercel preview / staging environment.
Seeking clarification of the intended behavior and suggestions of possible issues to investigate.

Using `useChat()` on the front end with `"@ai-sdk/svelte": "^0.0.57"`.
Using `streamText()` on the back end, with `maxToolRoundtrips: 8`. Every tool has an `execute` function.

In my local development environment the bug behavior does not occur. Same code in a Vercel preview environment causes the `useChat` `onFinish` to be called as soon as there are `tool-calls`. For example, here is the response from /api/chat before onFinish is called and the stream stops: `9:{"toolCallId":"call_yDuIAGiEN64q1yI6AX6gKEKs","toolName":"web_search","args":{"query":"recent news articles on global trade October 2024"}}`

But in my local environment `onFinish` is only being called by `useChat` when the tool-results are returned. For example, this is the end of the streaming response:

```
e:{"finishReason":"stop","usage":{"promptTokens":3430,"completionTokens":440},"isContinued":false}
d:{"finishReason":"stop","usage":{"promptTokens":5749,"completionTokens":463}}
```

This is blocking me from making changes to my app. I hope this is user error but could really use some help and an answer to the question: is the `useChat` `onFinish` callback supposed to be called before the tool-results are returned? What could cause that?

### Code example

Server code sample:

```
const result = await streamText({
		model: provider,
		messages: [
			{
				role: 'system',
				content: getPrompt(agent),
				experimental_providerMetadata
			},
			...documentsMessages,
			...messages
		],
		maxRetries: 2,
		temperature,
		tools: toolsObjects,
		maxToolRoundtrips: 8,
		experimental_telemetry: {
			isEnabled: true,
			functionId: 'tt-chat-api',
			metadata: {
				version: 'v0.2.2',
				model: modelName,
			},
		},
		onFinish(event) {
			try {
				console.log('TT > /api/chat > onFinish event: ', event);
				console.log('TT > /api/chat > onFinish event.messages: ', event.responseMessages);
			} catch (error) {
				console.error('TT > /tt/api/chat > conversation save error: ', error);
			}
		},
	}).catch((error) => {
		return error(500, {"message": `Call to the model failed.`, error});
	});
	return result.toDataStreamResponse();
```

Client Code Sample:

```
const { messages, append, stop, isLoading, input } = useChat({ 
		initialMessages,
		api: '/tt/api/chat',
		id,
		body: {
			id,
			previewToken,
		},
		sendExtraMessageFields: true,
		onResponse(response) {
			console.log('Chat.svelte > onResponse() > response: ', response);
		},
		onError(error) {
			console.error('Chat.svelte > onError() > error: ', error);
		},
		onFinish(message, options) {
		        // HERE is where I see the problem manifest. 
		        // In dev, this gets called after the tool results are streamed. 
		        // In preview, this suddenly started getting called after the tool call is streamed. Help!
			console.log('Chat.svelte > onFinish() > message: ', { message, options });
		},
	});
```

**Comment by jstjoe** [comment]
Well, it's working now 🫤 😅.
Disregard, will re-open with more detail if this re-occurs.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The issue was withdrawn after a transient, unreproduced problem resolved, so it does not establish a current SDK bug or request a concrete change.

### Evidence
- The reported behavior occurred only in a Vercel preview environment and had no isolated reproduction steps.
- The author later stated that it was working again and asked readers to disregard the report unless it recurred.
