### ISSUE TITLE
Support sending the messages array to a tool's `execute` function

### ISSUE THREAD

**Issue by mauricekleine** [vercel/ai#3468]
### Feature Description

I'm using LLMs as tools for a generic task agent that delegates tasks to tools. In order for each LLM tool to have access to the context of the agent execution chain, it would be great if each tool has access to the messages array _so far_. So let's say I set `maxSteps` to 5, then the initial call to my `streamText` method would contain the original messages array send by `useChat`. It would then determine which tool to use (`toolChoice` is set to `true`) and execute that tool - which in my case is another LLM call with it's own prompt:

```js
export const myTool = tool({
    description: '',
    execute: async ({ description, title }) => {
        const result = await generateText({
            description, '',
	    messages , // <== this is currently missing
	    model: vertex,
	    system: '',
        });

         return { text: result.text };
    },
    parameters: z.object({ ... })
});
```

But the context of the message history between tools gets lost since the tools don't have access to the messages array, including the results of previous tool executions.

**Comment by Slyracoon23** [comment]
This would be extremely useful +1

**Comment by lgrammel** [comment]
https://github.com/vercel/ai/pull/3774

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API capability enhancement allowing tools to access conversation context, not a failure of documented existing behavior.

### Evidence
- The issue explicitly requests that a tool's `execute` function receive the accumulated messages array.
- Current tool execution lacks access to the agent's message and prior tool-result context.
- A maintainer linked PR #3774, indicating work toward the requested capability.
