### ISSUE TITLE
Can't intercept rate limit response to send to client

### ISSUE THREAD

**Issue by bonnie** [vercel/ai#358]
I am using the client flow with the `OpenAIApi`(https://sdk.vercel.ai/docs/guides/openai#create-a-route-handler) and `useChat`. 

I am having trouble figuring out how to intercept the rate limit message from OpenAI to communicate that to the client. When I come up against a rate limit, I get the following error on the server (on the client, the `useChat` error value is `undefined` and the `message` in the `onFinish` callback is blank).

```
- error unhandledRejection: Error: Response error: {
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-yM6kVmwe3p9nzGEcIxJaKT1g on requests per day. Limit: 200 / day. Please try again in 7m12s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": "rate_limit_exceeded"
    }
}

    at Object.eval (webpack-internal:///(sc_server)/./node_modules/ai/dist/index.mjs:129:46)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///(sc_server)/./node_modules/ai/dist/index.mjs:43:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
}
```

The traceback points to the internal AI SDK code. The error not handled when I wrap the handler contents in a `try` block: 

```js
import { Configuration, OpenAIApi } from 'openai-edge'
import { OpenAIStream, StreamingTextResponse } from 'ai'
 
// Create an OpenAI API client (that's edge friendly!)
const config = new Configuration({
  apiKey: process.env.OPENAI_API_KEY
})
const openai = new OpenAIApi(config)
 
// IMPORTANT! Set the runtime to edge
export const runtime = 'edge'
 
export async function POST(req: Request) {
  try {
    // Extract the `messages` from the body of the request
    const { messages } = await req.json()
 
    // Ask OpenAI for a streaming chat completion given the prompt
    const response = await openai.createChatCompletion({
      model: 'gpt-3.5-turbo',
      stream: true,
      messages
    })
    // Convert the response into a friendly text-stream
    const stream = OpenAIStream(response)
    // Respond with the stream
    return new StreamingTextResponse(stream)
  } catch (error) {
      return NextResponse.json(
        { message: error?.toString() ?? "Server error" },
        { status: 500 },
      );
  }
}
```

Is there a way to intercept the 429 response and prevent this error that I'm not seeing? Thanks!

**Comment by MaxLeiter** [comment]
Are you using the latest version of `ai`? It should throw an error you can handle in `onError` or `onResponse`.

**Comment by bonnie** [comment]
Thanks for the response! I am using ai@2.1.26 . Unfortunately... 

- `onError` does not get triggered (as indicated by the `console.log` within not getting called). 
- the `response` arg to `onResponse` is this when the server throws the "unhandledRejection: Error": 

```
{
  type: 'basic',
  url: 'http://localhost:3000/api/chat',
  redirected: false,
  status: 200,
  ok: true, 
  body: (...)
  bodyUsed: true
  headers:  Headers {}
}
```

Thanks again,
Bonnie

**Comment by MaxLeiter** [comment]
> onError does not get triggered (as indicated by the console.log within not getting called).
Can you share all of your code? That makes it easier for me to reproduce. On a basic test it seems to be working as expected for me.

**Comment by bonnie** [comment]
Thanks for taking the time to reproduce, @MaxLeiter!

**Comment by baptisteArno** [comment]
I have the same issue with the quota is exceeded. I'm getting this on the server:

```ts
Error: Response error: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
```

I need a way to notify my user on the client

**Comment by MaxLeiter** [comment]
As we investigate the error handling, you can work around this in the API route by checking the response status from OpenAI:


```
if (!response.ok) { ... }
```

**Comment by tuffstuff9** [comment]
> As we investigate the error handling, you can work around this in the API route by checking the response status from OpenAI:
> 
> ```
> if (!response.ok) { ... }
> ```

I am dealing with the same issue. The try/catch is not catching the error either. Checking response.ok returns false, but I have no way of passing the error back to the user. Would appreciate any solutions / work arounds if possible. Thank you!

**Comment by MaxLeiter** [comment]
Yeah, there are new recommendations using the OpenAI SDK because it doesn't return a `Response`.

**Comment by baptisteArno** [comment]
Here is what I do:

backend:
```ts
const streamOrResponse = await getChatCompletionStream(conn)(
  state,
  block.options,
  messages
);

if (!streamOrResponse)
  return new Response("Could not create stream", { status: 400 });

if ("ok" in streamOrResponse)
  return new Response(streamOrResponse.body, {
    status: streamOrResponse.status,
    headers: {
      "Access-Control-Allow-Origin": "*",
    },
  });

return new StreamingTextResponse(streamOrResponse, {
  headers: {
    "Access-Control-Allow-Origin": "*",
  },
});

```

Frontend:

```ts
const res = await fetch(`...`);

if (!res.ok) {
  if (
    (context.retryAttempt ?? 0) < maxRetryAttempts &&
    (res.status === 403 || res.status === 500 || res.status === 503)
  ) {
    await new Promise((resolve) =>
      setTimeout(resolve, secondsToWaitBeforeRetries * 1000)
    );
    return streamChat({
      ...context,
      retryAttempt: (context.retryAttempt ?? 0) + 1,
    })(messages, { onMessageStream });
  }
  return {
    error: (await res.json()) || "Failed to fetch the chat response.",
  };
}

```

**Comment by baptisteArno** [comment]
> Yeah, there are new recommendations using the OpenAI SDK because it doesn't return a `Response`.

But wait it shouldn't be compatible with Edge runtime, right?

**Comment by MaxLeiter** [comment]
@baptisteArno The OpenAI SDK version 4 is edge/streaming compatible! There is no longer a need for openai-edge as of 2.2: https://twitter.com/vercel/status/1691908159705596076

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a reproducible failure in existing error handling: provider errors are not propagated through the documented server or client mechanisms. Later workarounds and SDK recommendations do not change the original report from a concrete bug.

### Evidence
- OpenAI 429/quota failures produce an unhandled server rejection while `useChat` receives no error and a blank finished message.
- The route-level `try/catch` and client `onError` callback do not catch or report the failure.
- A maintainer confirmed they were able to reproduce the behavior and described error handling as under investigation.
