### ISSUE TITLE
Issue for Claude models when streaming the responses in non-English

### ISSUE THREAD

**Issue by olefirenko** [vercel/ai#362]
It can be reproduced here https://sdk.vercel.ai/. So far noticed issues with the Japanese and Russian languages. 
Some letters are doubled and there are some encoding issues.

<img width="637" alt="Screenshot 2023-07-21 at 3 19 31 PM" src="https://github.com/vercel-labs/ai/assets/5434459/adada78a-0592-4c10-80da-e15b59086a44">

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes concrete incorrect output when using an existing streaming capability with non-English text, so it is a bug.

### Evidence
- Streaming Claude responses in Japanese and Russian reportedly doubles some letters and introduces encoding corruption.
- The attached screenshot shows malformed replacement characters and duplicated or incorrectly joined Cyrillic text in the streamed output.
- The failure is reproducible on the AI SDK website.
