### ISSUE TITLE
UseChat() > append() started failing after update to 3.4.33 with `Cannot read properties of null (reading 'concat')`

### ISSUE THREAD

**Issue by jstjoe** [vercel/ai#3650]
### Description

Looking for some guidance here. Upgraded my project to 3.4.33 and now append() is failing on the front end. The error suggests that `messages` is null. The surrounding code has not changed, is there somewhere you could point me to troubleshoot? I've logged the `messages` store and it exists.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'concat')
    at append (@ai-sdk_svelte.js?v=e967a945:357:42)
```

I'm using SvelteKit but did not upgrade to 5, still using "svelte": "^4.2.19".

What can I do to investigate this further? I'm a relative novice maintaining an app solo and could really use some direction.

Thank you.

### Code example

```
export let append: UseChatHelpers['append'];
```

```
await append({
		content: event.detail.text,
		role: 'user',
	}, {
		options: {
			body: {
				
				agent,
				documents,
				instructions,
				model,
				newConversation,
				tools,
			},
		}
	}
)}}
```

### AI provider

"@ai-sdk/anthropic": "^0.0.56",     "@ai-sdk/openai": "^0.0.58",     "@ai-sdk/svelte": "^0.0.57",

### Additional context

"ai": "^3.4.33",

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete regression in existing `append()` behavior after an SDK update, resulting in an unexpected runtime exception.

### Evidence
- After upgrading to AI SDK 3.4.33, Svelte `useChat().append()` throws `TypeError: Cannot read properties of null (reading 'concat')`.
- The reporter states the surrounding application code did not change and the messages store exists.
- The failure occurs with Svelte 4.2.19 and `@ai-sdk/svelte` 0.0.57.
