### ISSUE TITLE
Expo SDK52 fetch compatibility

### ISSUE THREAD

**Issue by matthiasbayer** [vercel/ai#3705]
### Description

The recent [Expo SDK 52](https://expo.dev/changelog/2024/11-12-sdk-52) release includes [expo/fetch API](https://docs.expo.dev/versions/latest/sdk/expo/#expofetch-api), which _finally_ adds support for streaming responses using fetch(). 

This means we can now pass that `fetch` implementation to the `useChat` hook and use the AI SDK inside of React Native! Super awesome.

I got everything working with a straight forward implementation in this repository: https://github.com/matthiasbayer/expo-ai-sdk 

But there seems to be an issue with how the AI SDK is handling the streaming response:
<img width="675" alt="Screenshot 2024-11-15 at 4 10 01 PM" src="https://github.com/user-attachments/assets/b2d56260-93e2-40c7-9978-d3dd4d006019">

This error comes from the [web-streams-polyfill](https://www.npmjs.com/package/web-streams-polyfill) package that expo/fetch uses under the hood. I suspect the error gets triggered by an incorrect or somewhat incompatible use of the streams inside the AI SDK, causing an invalid stream state.

This error pops up every time the SDK makes a network call. Strangely enough, it doesn't impact the functionality. The streaming response appears on the screen. React Native buffers the first few hundred characters for some reason instead of rendering the message instantly, not sure if that's a related bug or not.

### Code example

https://github.com/matthiasbayer/expo-ai-sdk

### AI provider

ai@^3.4.33, @ai-sdk/openai^0.0.72, @ai-sdk/react^0.0.70

### Additional context

It's hard for me to identify the exact root cause of this problem. It might be incorrect usage of the Streams API, but it could also be a bug in the `web-streams-polyfill` or the `expo/fetch` implementation. Not sure where to start.

**Comment by lgrammel** [comment]
Please try with the latest ai sdk (`4.0.x-canary`). It's unlikely that the issue is on the AI SDK side, because the stream usage in `useChat` is pretty straight forward. See https://github.com/vercel/ai/blob/main/packages/ui-utils/src/process-data-stream.ts for where the consumption happens.

**Comment by matthiasbayer** [comment]
Quickly tested the canary version of the `ai` and `@ai-sdk/*` packages. Issue is still present, but I agree that the stream usage looks pretty unsuspicious. I'll try to dig through the dependency stack to find the root cause. Thanks for pointing me to the right file to start at.

**Comment by lgrammel** [comment]
Actually it could be buggy because we don't check for `done` on read.

**Comment by lgrammel** [comment]
Can you hack the `processDataStream` function in you local `node_modules` folder to include the following change (prob in the mjs and in the cjs file for `@ai-sdk/ui-utils`): 

```
    const { value, done } = await reader.read();

    if (done) {
      break;
    }
 ```

**Comment by matthiasbayer** [comment]
Good catch. Seems like `value` was `undefined` in all cases always, but good idea to add that `done` check.

```
{"done": true, "value": undefined}
```

I think the issue (still not sure which library is getting it wrong) is on the server side. I can provoke the error by reading the stream directly with a fetch request, skipping the ai/ui altogether:


```ts
      const response = await fetch('http://localhost:3000/api/chat', {
        method: 'POST',
        body: JSON.stringify({ messages: [] }),
        headers: {
          Accept: 'text/event-stream',
          'Content-Type': 'application/json',
        },
      });
```

reading from a different stream works fine, for example:

```ts
      const response = await fetch('https://httpbin.org/drip?numbytes=512&duration=2&delay=0', {
        headers: { Accept: 'text/event-stream' },
      });
```


So it looks to me that either the server is sending something out of order, or there is a bug in the expo/fetch library or its dependencies.

**Comment by lgrammel** [comment]
we want to add a reactive native guide once this works!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The reported failure was traced to Expo's fetch/stream implementation rather than vercel/ai. The remaining discussion is support follow-up and a possible future guide, not a concrete AI SDK documentation request.

### Evidence
- The reporter reproduced the stream errors without AI SDK UI code by directly consuming streams.
- The reporter ultimately reproduced the same failure with httpbin.org and concluded it was unrelated to the AI SDK.
- The final documentation-guide remarks are aspirational and contingent on Expo compatibility being resolved.
