### ISSUE TITLE
Is it possible to implement an ANTHROPIC_API_HOST capability?

### ISSUE THREAD

**Issue by mk-qi** [vercel/ai#3762]
### Feature Description

I am unable to directly access http://api.anthropic.com/ for certain reasons, I  implement a relay mechanism. so it  need to customize the base URL of the API 

### Use Cases

self deploy bolt.new

**Comment by lgrammel** [comment]
You can set the baseURL on the Anthropic provider: https://sdk.vercel.ai/providers/ai-sdk-providers/anthropic#provider-instance

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support question about an existing configuration capability, not a request requiring a product or documentation change.

### Evidence
- The reporter asks whether Anthropic's API base URL can be customized for use with a relay.
- A maintainer explains that the existing Anthropic provider already supports setting `baseURL` and links to the relevant documentation.
