### ISSUE TITLE
Expose the LLM provider response in AISDKError

### ISSUE THREAD

**Issue by williamlmao** [vercel/ai#3779]
### Feature Description

I have two other feature requests (#3451, #3208) that I've opened, both of which I will be closing in favor of this one as I believe this suggestion is the best way to handle this.

Currently when you use generateObject or generateText with a function call and the LLM responds with data that does not match your provided schema, the behavior is that the vercel AI SDK will throw a InvalidToolArgumentsError or AISDKError, which just returns the zod parsing error.

The issue here is that now the entire generateText or generateObject call is throwing a zod error, and the response from the provider is no longer accessible at all, even though that was technically a successful response. This is a problem for a few reasons

1. We lose access to what the LLM actually generated. Sometimes the response is recoverable / fixable, but we do not have an opportunity to handle those error cases.
2. Usage data is now lost (I know we could still save it with fetch intercepts, but this means we have to work with the data outside of the calling function scope)

I think of the vercel AI SDK as an extension of calling these providers, so it feels weird to me that a successful response from the LLM provider is completely inaccessible due to a zod parse error. I do agree that a generateText/generateObject should throw this error, but it should include the full LLM provider response. 

In the case of #3208 when Groq throws an error directly from their API, the error that groq throws should be passed through the AISDKError. 

If the error was thrown like this, that would be a huge, huge help.
```
try {
  const {result} = await generateText({
    ...
  });
} catch (e: InvalidToolArgumentsError) {
  e.response
  // Do something with the e.response
 // Log usage data still
}

```

**Comment by lgrammel** [comment]
You can already do this: check if the error with `InvalidToolArguments.isInstance` and then access `toolArgs` (which are the incorrect args)

**Comment by williamlmao** [comment]
Thanks @lgrammel! I opened #3869 to point people to this on the Error Handling page. 

That being said though, is there any way to access some of the other data we'd expect on a successful LLM response, such as `usage` or `experimental_providerMetadata`?

**Comment by williamlmao** [comment]
Hi @lgrammel - ran into this again with generateObject. I looked through the error types in the docs, but I didn't see any equivalent error helper to access the incorrect object generation. 

Ultimately, we still think the Vercel AI SDK should expose more at the request/response level. Right now we have this feeling that we're fighting the framework due to over abstraction. If we're able to access the full request/response regardless of ai sdk errors, then that would solve everything and anything the sdk did not already provide, we'd be able to build around ourselves. 

We're happy to try put in a PR ourselves, but before we spend the time working on it we just want to make sure that the AI SDK team would be receptive of this change. If you give us the green light, we'll try to get this in next week. 

The PR we would make would just expose the full provider response all of the AI SDK error types.

**Comment by lgrammel** [comment]
You cannot access the full provider response, because it may not even exist at the point where the tool call fails (e.g. in the streaming case). The error messages contain all parts of the response that are required to fix the error.

**Comment by williamlmao** [comment]
Hi @lgrammel, I understand that there are some additional complications with tool calling + streaming, but let me give a simpler example with generateObject.

Here is a simple text classification example. Sometimes, the provider will return a value that falls outside of the specified enum (we see this happen occasionally even when using structured outputs). Let's say that if the LLM returns anything outside of the enum, we just want to replace whatever it gave us with 'neutral'. 

```
async function classifyText(text: string) {
  try {
    return await generateObject({
      model: openai('gpt-4-turbo'),
      schema: z.object({
        category: z.enum(['exciting', 'boring', 'neutral']),
        reasoning: z.string(),
      }),
      prompt: `Classify the following text into one of the following categories: exciting, boring, or neutral: ${text}`,
    });
  } catch (error) {
    if (TypeValidationError.isInstance(error)) {
      const generatedValue = error.value;
      generatedValue.category = 'neutral';
      
      // At this point, we want to treat this as a successful response and return type GenerateObjectResult, but all we have from the TypeValidationError is .value. The rest of the data from the response is completely missing.
      
      return generatedValue;
    }
    throw error;
  }
}

async function main(requestId: string) {
  const text = getText();
  const aiSdkResult = await classifyText(text);
  await customAIRequestLogger({
    function: 'text-classifier',
    requestId,
    input: text,
    output: aiSdkResult.object,
    usage: aiSdkResult.usage,
    // assume we are logging other data, such as `system_fingerprint` or `cached_tokens` 
  });
  await saveResult({
    requestId,
    result: aiSdkResult.object,
  });
}
```

Right now, this will throw a `AI_TypeValidationError`, which only has `value` and `message`, even though the inference provider sent back a 200, with all of the other metadata/usage information we would expect if we called the provider directly. 

The core problem that I'm trying to point out is that by using the Vercel AI SDK, we can no longer access that 200 response because the SDK is throwing a type validation error.

In the example above, if we get a AI_TypeValidationError, we can repair it and want to be able to treat this as a successful response. We _could_ try to reconstruct a successful `GenerateObjectResult` in the `catch` block, but we'd only be able to estimate the usage tokens with our own tokenizer and pass the result back, and we'd be missing other fields on the response. 

At the end of the day, the AI SDK is an abstraction on top of making requests to inference providers, so I'd expect to be able to access all of the data returned from those requests, especially the successful ones.

I hope this helps clarify the issue I'm trying to point out, and that it doesn't come off as complaining! I love the AI SDK and all of the work you are doing on it, and I'm just trying to give feedback to help make it better. I understand getting the full response from the provider may not be possible in tool calling / streaming situations, but I do think there should be a better solution here.

**Comment by lgrammel** [comment]
I plan to add a repair abstraction similar to the tool call repair for invalid structured outputs. You can use that to repair the result. `generateText` would then respond with all information (instead of throwing an error).

**Comment by williamlmao** [comment]
@lgrammel okay that would be great! I think ultimately as long as we're able to treat a successful response from the provider as a successful response and access all of the data, that's the main thing we need. 

That being said, what if we don't want to repair it, and we do want to throw the error, but we still want to record/do work on some of the data returned by the provider (i.e custom logging functions for usage data)? Would we still be able to access that data?

**Comment by williamlmao** [comment]
To add to this, we recently started seeing a lot of `AI_NoObjectGeneratedError` when using llama 3.3 on groq/together. The AI_NoObjectGeneratedError only shows the [`message` field](https://sdk.vercel.ai/docs/reference/ai-sdk-errors/ai-no-object-generated-error), and no other information from the LLM provider response. 

```
AI_NoObjectGeneratedError: No object generated.
      at new _AISDKError (/Users/wl/personalprojects/friends-and-fables/packages/ai-suite/node_modules/ai/node_modules/@ai-sdk/provider/dist/index.mjs:19:9)
      at new NoObjectGeneratedError (/Users/wl/personalprojects/friends-and-fables/packages/ai-suite/node_modules/ai/dist/index.mjs:3100:7)
      at /Users/wl/personalprojects/friends-and-fables/packages/ai-suite/node_modules/ai/dist/index.mjs:3846:4
```

Just adding another example - this is a pretty clear example where the AI SDK is obscuring the provider response/returned data. Even if it is an error, I would love to be able to see what was actually generated.

**Comment by lgrammel** [comment]
The `AI_NoObjectGeneratedError` is thrown when there is no output.

**Comment by williamlmao** [comment]
@lgrammel this in itself is actually a very good example of why it's problematic that the AI SDK obscures the provider response. 

The [documentation](https://sdk.vercel.ai/docs/reference/ai-sdk-errors/ai-no-object-generated-error) says: This error occurs when the AI provider fails to generate a parsable object.

When I read the docs, it sounds to me like the response could have generated something, just not a parseable object. 

But what this points out is that **without seeing the response from the provider, I cannot know what is actually happening**. 

Additionally, this is problematic because now I don't have anything I can go back to Groq with. I cannot show them the response their API sent, which could potentially help them solve the issue.

I feel really strongly that _when possible_, the AI SDK should include a `provider_response` on the error object, which could just look like this: 

```
import { NoObjectGeneratedError } from 'ai';

if (NoObjectGeneratedError.isInstance(error)) {
 error.provider_response
}
```

I understand there may be some complications during streaming/tool calls, but in the case of a simple generateObject I don't see why the response should not be exposed.

**Comment by colemccracken** [comment]
> is thrown when there is no output.

As I understand in this case the response is a 200 but `response.data.choices[0].message.content` is empty, but we pass a lot of useful debug info that would be good to have access to. The most useful would be `response.data.x_groq.id`, but if theres an easy way to pass up the whole thing that would be great

**Comment by lgrammel** [comment]
With AI SDK `4.0.18`, I have reworked how `generateObject`, `streamObject`, and `output` (for `generateText`) report errors.

Now `NoObjectGeneratedError` errors are thrown when the generation fails for some reason related to structure parsing or validation.

This error occurs when the AI provider fails to generate a parsable object that conforms to the schema. It can arise due to the following reasons:

- The model failed to generate a response.
- The model generated a response that could not be parsed.
- The model generated a response that could not be validated against the schema.

The error preserves the following information to help you log the issue:

- text: The text that was generated by the model. This can be the raw text or the tool call text, depending on the object generation mode.
- response: Metadata about the language model response, including response id, timestamp, model, and headers (to e.g. extract the Groq request id header).
- usage: Request token usage.
- cause: The cause of the error (e.g. a JSON parsing error). You can use this for more detailed error handling.

More information: https://sdk.vercel.ai/docs/ai-sdk-core/generating-structured-data#error-handling

**Comment by williamlmao** [comment]
@lgrammel, you are the man!!! This was really the only thing seriously getting in the way of the AI SDK for us - very happy we were able to get this one through and think it is a really important update. Appreciate all of your hard work! 🙏

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API capability expansion that makes provider response information available during structured-output failures, rather than a failure of previously promised behavior.

### Evidence
- The issue requests exposing provider response metadata, generated text, and usage data on AI SDK errors.
- Existing errors only exposed limited parsing details, and no documented behavior promised access to the complete provider response.
- The maintainer implemented expanded `NoObjectGeneratedError` fields in AI SDK 4.0.18, including `text`, `response`, `usage`, and `cause`.
