### ISSUE TITLE
Add toolCall/toolCallId to `tool.execute` options or Introduce Built-in Progress Streaming

### ISSUE THREAD

**Issue by KABBOUCHI** [vercel/ai#3842]
### Feature Description

Currently, when implementing a tool's execute function, there is no direct access to the toolCall/toolCallId, which makes it challenging to send progress updates or associate execution state with a specific call.

```ts
const data = new StreamData();
  
const myTool = tool({
    execute: async ({ }, { toolCall }) => {
        data.append({
           ...toolCall,  // currently toolCall is not available here
           type: "tool_execute_progress", 
           data: {} 
        }) 
        data.append({...toolCall, type: "tool_execute_progress", ... })
        data.append({...toolCall, type: "tool_execute_progress", ... })
        
        return {}
    },
});
```

Adding toolCall/toolCallId to the options passed into `tool.execute` would enable us to associate progress updates more effectively and enhance communication with the frontend.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This asks for an API expansion and new progress-streaming capability, not a failure of documented existing behavior.

### Evidence
- The current `tool.execute` options do not expose the `toolCall` or `toolCallId`.
- The request proposes adding this information so callers can associate streamed progress updates with a specific tool invocation.
