### ISSUE TITLE
'File content parts in user messages' functionality not supported

### ISSUE THREAD

**Issue by whydna** [vercel/ai#3844]
### Description

Trying to attach a PDF file to content message - but getting this error. Is it not supported?

### Code example

{
  type: 'file',
  mimeType: 'application/pdf',
  data: fs.readFileSync(file),
} as FilePart

### AI provider

@ai-sdk/openai

**Comment by rockywangxiaolei** [comment]
this is subject to the model provider ,you may check your model config to make sure the model support PDF input.

**Comment by lgrammel** [comment]
OpenAI does not support PDF input (Gemini, Vertex, Anthropic (certain models) do).

**Comment by juzarantri** [comment]
@lgrammel @rockywangxiaolei  I am getting the same issue with openai. It works fine with images but fails with application/pdf. 

And the model I am using is gpt-4o which is able to parse the pdf

my code:
` return createDataStreamResponse({
    execute: (dataStream) => {
      const result = streamText({
        model: myProvider.languageModel(selectedChatModel),
        system: systemPrompt({ selectedChatModel }),
        messages,
        maxSteps: 5,
        experimental_activeTools:
          selectedChatModel === "chat-model-reasoning"
            ? []
            : [
                "getWeather",
                "createDocument",
                "updateDocument",
                "requestSuggestions",
              ],
        experimental_transform: smoothStream({ chunking: "word" }),
        experimental_generateMessageId: generateUUID,
        tools: {
          getWeather,
          createDocument: createDocument({ session, dataStream }),
          updateDocument: updateDocument({ session, dataStream }),
          requestSuggestions: requestSuggestions({
            session,
            dataStream,
          }),
        },
        onFinish: async ({ response, reasoning }) => {
          if (session.user?.id) {
            try {
              const sanitizedResponseMessages = sanitizeResponseMessages({
                messages: response.messages,
                reasoning,
              });

              await saveMessages({
                messages: sanitizedResponseMessages.map((message) => {
                  return {
                    id: message.id,
                    chatId: id,
                    role: message.role,
                    content: message.content,
                    createdAt: new Date(),
                  };
                }),
              });
            } catch (error) {
              console.error("Failed to save chat");
            }
          }
        },
        experimental_telemetry: {
          isEnabled: true,
          functionId: "stream-text",
        },
      });

      result.mergeIntoDataStream(dataStream, {
        sendReasoning: true,
      });
    },
    onError: (e) => {
      console.log(e, "Error>>>>>>>>>>>>>>");

      return "Oops, an error occured!";
    },
  });
}`

**Comment by eric-burel** [comment]
For some provides it seems that an actual URL is needed, [data URLs](https://developer.mozilla.org/fr/docs/Web/URI/Reference/Schemes/data) with a `base64` encoding doesn't work where an absolute URL works.

```
// doesn't work
data: "data:application/pdf;base64," +
            fs.readFileSync("./scan-ocr.pdf", "base64")
```

**Comment by vacuitas-explicat** [comment]
I was running into the same error, and updating the dependencies fixed it for me
Bumping `@ai-sdk/openai` to `1.3.24` and `ai` to `4.3.19` resolved the issue

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a provider-capability/support question rather than a demonstrated failure of promised AI SDK behavior or an explicit feature request.

### Evidence
- The reporter asks whether attaching a PDF through an OpenAI file content part is supported, without explicitly requesting a product change.
- A maintainer states that OpenAI did not support PDF input at the time, while other providers did.
- A later commenter reports resolving the behavior by updating `@ai-sdk/openai` and `ai` dependencies.
