### ISSUE TITLE
onError callback in useChat hook is not working. 

### ISSUE THREAD

**Issue by Praneeth-Pike** [vercel/ai#3875]
### Description

Error message is not being passed to onError callback in useChat hook. I'm using a custom express server for the /chat endpoint.

### Code example

// useChat hook
``` 
const { messages, input, setInput, handleSubmit, isLoading, stop, error } =
		useChat({
			id,
			api:  `${EXPRESS_API_URL}/chat`,
			initialMessages: data.messages,
			onError: (error) => {
				console.error('error on chat', error)
			},
			onFinish: async (message, { finishReason, usage }) => {
				console.log(`onFinish message id: ${message.id}`, finishReason)
				console.log('usage', usage)
			},
		})
```

/chat endpoint
```
expressApp.post('/chat', async (req: Request, res: Response) => {
	try {
		const { messages, context } = req.body

		const model = openai("gpt-4o")

		const payload = {
			model,
			messages: convertToCoreMessages([
				{
					role: 'system',
					content: context
						? `<MetaPrompt>${ChatSystemPrompt}</MetaPrompt>\n<PreviousContext>${context}</PreviousContext>`
						: `<MetaPrompt>${ChatSystemPrompt}</MetaPrompt>`,
				},
				...messages,
			]),
		}

		const result = streamText({
			...payload,
		})

		return result.pipeDataStreamToResponse(res, {
			sendUsage: true,
			getErrorMessage: (error) => {
				if (error == null) {
					return 'unknown error'
				}

				if (typeof error === 'string') {
					return error
				}

				if (error instanceof Error) {
					return error.message
				}

				return JSON.stringify(error)
			},
		})
	} catch (error: any) {
		log.error('Error in /chat:', error)
		res.status(500).json({
			error: error.message ?? 'Internal server error',
		})
	}
})
```

### Additional context

onError works with the same code for v3.4, but when I upgrade to v4 and remove the await from streamText, onError is not being passed to the client hook

**Comment by oalexdoda** [comment]
Same issue over here. Sometimes useChat errors out (server-side) and it doesn't return any error. Maybe it's missing something here?

![image](https://github.com/user-attachments/assets/2269e9d4-83bb-4435-861f-b1680b347d19)

**Comment by lgrammel** [comment]
Related backend errors have been fixed. Can you try again with the latest AI SDK versions?

**Comment by Praneeth-Pike** [comment]
They're fixed! thanks @lgrammel !!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This was a regression or defect in existing error propagation behavior, later fixed in the backend and confirmed resolved.

### Evidence
- After upgrading from AI SDK v3.4 to v4, server-side stream errors were not passed to the useChat onError callback.
- Another user reproduced missing errors from useChat.
- A maintainer stated that related backend errors had been fixed, and the reporter confirmed the latest versions resolved the issue.
