### ISSUE TITLE
createDataStreamResponse's onError needs to handle async operations.

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#3977]
### Feature Description

createDataStreamResponse's onError needs to handle async operations. I need to be able to handle async operations in the onError of createDataStreamResponse (Unless I'm using the wrong thing)

### Use Cases

My use case is that if there is an AI error (servers down), I want to capture that error, add it to the message conversation, and then display that to the user on the front end.

In this example with needing onError to be asynchronous, I am needing to do this to handle displaying an error link.

```
    const ReactDOMServer = await import('react-dom/server')
    displayMessage = createShowReportIssueError(message, reportIssueUrl, error)
    message = ReactDOMServer.renderToString(displayMessage)
```

**Comment by lgrammel** [comment]
The intention of `onError` is very different. It is intended to be similar to `getErrorMessage` on the streamText result. I'll consider renaming it. The error part would then get send to the frontend.

I believe you're trying to work around a current limitation of the AI SDK by trying to modify the messages here. I'm wondering if there needs to be a better way to process error parts on the client instead.

**Comment by Godrules500** [comment]
So how do I currently handle something like a network error or the AI service being down? 

I don't want to toast an error message and just leave it with a user prompt with no AI message below it. 

What I'm needing to do is handle the error and save that error to the messages so that the user sees 
User: "Hey, what is 2 plus 3?" 
AI: An unexpected error has happened. Please report an issue here ... 

Vertex AI throws these types of error frequently enough that I have to handle it. (Yay unexpected and informative "unexpected_error" lol)

**Comment by lgrammel** [comment]
This was a separate bug. Should be resolved once the next version goes out, see https://github.com/vercel/ai/pull/3987

**Comment by lgrammel** [comment]
Closing this issue under the assumption that #3987 solves it. Please re-open if it doesn't.

**Comment by Godrules500** [comment]
I think I could make this work by calling setMessages in the onError call from useChat. That said, can we make getErrorMessage asynchronous.

```
result.mergeIntoDataStream(streamingData)
          result.toDataStreamResponse({
            getErrorMessage: async error => {
              let title = await titlePromise
              const messageError:CoreMessage = await handleUnexpectedStreamingErrors(error, chat, true, title)
              console.error(error)
              return messageError
            }
          })
```
Also, you mentioned that it returns the error in the parts. Where do I read those at? onError seems to be capturing the actual error even if I return "You have errored. Self destructing in 5 seconds" it still returns the vertexai client error.

**Comment by Godrules500** [comment]
I wonder if it has more to do with I'm not returning the toDataStreamResponse correctly since it is wrapped with createDataStreamResponse. Is there an example of how to use the toDataStream with createDataStreamResponse?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
Although framed partly as an async-callback enhancement, the reported missing error message is concrete broken behavior and was explicitly characterized by a maintainer as a bug.

### Evidence
- The reporter describes `createDataStreamResponse`’s server-side `onError` return value not reaching the client; the client handler receives an empty message.
- A maintainer identified the behavior as a separate bug and linked PR #3987 as the expected fix.
- The issue also requests async callbacks, but it includes a concrete failure in current error propagation.
