### ISSUE TITLE
How to pass the user needed by litellm using openai, and charge the user separately for litellm.

### ISSUE THREAD

**Issue by HECHONG999** [vercel/ai#4025]
### Feature Description

How to pass the user needed by litellm using openai, and charge the user separately for litellm. 
I hope openai can deliver user

### Use Cases

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/8bd2e948-873e-4417-84f6-2e5899111e6f">

**Comment by lgrammel** [comment]
This is supported via model options (`user`): https://sdk.vercel.ai/providers/ai-sdk-providers/openai#chat-models

**Comment by HECHONG999** [comment]
> This is supported via model options (`user`): https://sdk.vercel.ai/providers/ai-sdk-providers/openai#chat-models

I am using StreamUI and it seems that this function does not support passing in a user key.

**Comment by HECHONG999** [comment]
> it is a model option and not related to streamUI in particular



> it is a model option and not related to streamUI in particular

Thank you very much for your reply, I carefully checked the document and found it. Thank you.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a resolved usage/support question about an existing documented capability, not a product defect or request for a change.

### Evidence
- The reporter asks how to pass LiteLLM's `user` field through the OpenAI provider while using StreamUI.
- A maintainer explains that `user` is already supported as an OpenAI model option and is unrelated to StreamUI.
- The reporter confirms they found the documented option and thanks the maintainer.
