### ISSUE TITLE
Add Gemini 2.0 model to google vertex.

### ISSUE THREAD

**Issue by Godrules500** [vercel/ai#4089]
### Feature Description

I know that google and google vertex can function differently (Still don't understand why google does this), so if it is possible, I wanted to request that gemini 2.0 be added to the google vertex like it was with google.

Thanks! Y'all are awesome!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new model support in an existing provider, which is a product capability enhancement.

### Evidence
- The issue explicitly requests adding Gemini 2.0 support to the Google Vertex provider.
- The maintainer acknowledges the request and says they are working to put the support in place.
- No broken or contradictory existing behavior is reported.
