### ISSUE TITLE
Support `reasoning_effort` for OpenAI `o1` model

### ISSUE THREAD

**Issue by wong2** [vercel/ai#4137]
### Feature Description

> A new `reasoning_effort` API parameter allows you to control how long the model thinks before answering.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API capability expansion to expose a provider parameter, so it is a feature request.

### Evidence
- The issue requests support for a new OpenAI API parameter, `reasoning_effort`, for the `o1` model.
- It does not describe a failure or regression in existing AI SDK behavior.
