### ISSUE TITLE
Error [AI_APICallError]: messages.12.content.1.image.source.base64.data: The image specified was not valid

### ISSUE THREAD

**Issue by Tian-Hun** [vercel/ai#4152]
### Description

When using `experimental_attachments` some images with a `.jpg` extension give an error:

Error [AI_APICallError]: messages.12.content.1.image.source.base64.data: The image specified was not valid
    at <unknown> (node_modules/@ai-sdk/anthropic/node_modules/@ai-sdk/provider-utils/src/response-handler.ts:58:15)
    at async postToApi (node_modules/@ai-sdk/anthropic/node_modules/@ai-sdk/provider-utils/src/post-to-api.ts:81:27)
    at async AnthropicMessagesLanguageModel.doStream (node_modules/@ai-sdk/anthropic/src/anthropic-messages-language-model.ts:282:49)
    at async fn (node_modules/ai/core/generate-text/stream-text.ts:506:24)
    at async (node_modules/ai/core/telemetry/record-span.ts:18:21)
    at async _retryWithExponentialBackoff (node_modules/ai/util/retry-with-exponential-backoff.ts:37:11)
    at async streamStep (node_modules/ai/core/generate-text/stream-text.ts:461:14)
    at async fn (node_modules/ai/core/generate-text/stream-text.ts:965:8)
    at async (node_modules/ai/core/telemetry/record-span.ts:18:21)
  56 |       return {
  57 |         responseHeaders,
> 58 |         value: new APICallError({
     |               ^
  59 |           message: errorToMessage(parsedError),
  60 |           url,
  61 |           requestBodyValues, {
  cause: undefined,
  url: 'https://api.anthropic.com/v1/messages',
  requestBodyValues: [Object],
  statusCode: 400,
  responseHeaders: [Object],
  responseBody: '{"type":"error","error":{"type":"invalid_request_error","message":"messages.12.content.1.image.source.base64.data: The image specified was not valid"}}',
  isRetryable: false,
  data: [Object]
}

### Code example

```json
{
    "role": "user",
    "content": "test",
    "experimental_attachments": [
        {
            "url": "https://7cvq9ppwadyagnal.public.blob.vercel-storage.com/WechatIMG159-yKOSwrshWCckNkCKauHpvQwazHqVMo.jpg",
            "name": "WechatIMG159.jpg",
            "contentType": "image/jpeg"
        }
    ]
}
```

### AI provider

@ai-sdk/anthropic 1.0.5

**Comment by lgrammel** [comment]
Can you attach the image? I tried Anthropic with jpeg images and it worked:

```
  const result = streamText({
    model: anthropic('claude-3-5-sonnet-20240620'),
    messages: [
      {
        role: 'user',
        content: [
          { type: 'text', text: 'Describe the image in detail.' },
          { type: 'image', image: fs.readFileSync('./data/rome.jpg') },
        ],
      },
    ],
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }
  ```

**Comment by lgrammel** [comment]
Investigating. Using the image directly works:

```
  const result = streamText({
    model: anthropic('claude-3-5-sonnet-20240620'),
    messages: [
      {
        role: 'user',
        content: [
          { type: 'text', text: 'Describe the image in detail.' },
          { type: 'image', image: fs.readFileSync('./data/img.jpg') },
        ],
      },
    ],
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }
  ```

**Comment by lgrammel** [comment]
Weirdly it seems that Anthropic process the jpeg image if you set the backend mimetype to `image/png`, but not when it is set to `image/jpeg` (independent of the type in attachments since we auto-detect)

**Comment by lgrammel** [comment]
The file in question is in fact a PNG: 
![CleanShot 2024-12-20 at 16 26 13](https://github.com/user-attachments/assets/ca1401b4-4f6a-4f78-bfe6-0d6d36640213)

**Comment by demattosanthony** [comment]
seems like sending back only the actual file content and not a file url works. Am i wrong here?

**Comment by bholbein** [comment]
Hi there. there seems to be a regression somewhere between 4.3.3 and 4.3.10

**Comment by samdenty** [comment]
thanks for the call out @bholbein, it looks like the thing changed was this PR:

https://github.com/vercel/ai/pull/5470

**Comment by samdenty** [comment]
@bholbein would you be able to provide the same image, you're using?

**Comment by bholbein** [comment]
![Image](https://github.com/user-attachments/assets/8c885add-226f-4f08-b10b-ce02b558ea4b) @samdenty I think this was the one.

**Comment by samdenty** [comment]
can you provide the code you're using along with the actual error message?

**Comment by bholbein** [comment]
> can you provide the code you're using along with the actual error message? Does it mention base64, or in the request does it have a URL?

Is there any particular part you're interested in @samdenty

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete failure in existing image attachment handling, with follow-up evidence suggesting MIME detection problems and a version regression.

### Evidence
- A URL-based image attachment causes Anthropic to return a 400 error stating that the base64 image is invalid.
- The image has a .jpg name and JPEG metadata but its actual bytes are PNG; a maintainer noted that direct file input works and MIME auto-detection may be involved.
- A later commenter reported a regression between AI SDK 4.3.3 and 4.3.10, and another contributor linked the behavior change to PR #5470.
