### ISSUE TITLE
Feedback for “Getting Started”

### ISSUE THREAD

**Issue by rogadev** [vercel/ai#421]
It would appear that something has broken, either in the package or in the way the demonstration was implemented, because the response is cut of and does not stream past a certain point.

![image](https://github.com/vercel-labs/ai/assets/61405141/b3de3a84-ccf4-4644-a920-44c936875086)

I assure you I have followed the instructions to the letter. Perhaps something has changed since the document was written that requires me to do something differently today?

**Comment by rogadev** [comment]
Here's a link to the repo if you'd like to double check for yourself:
https://github.com/rogadev/viu-ai-lab

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This reports a concrete failure in current SDK or documented demonstration behavior: streaming terminates before the response is complete.

### Evidence
- The response generated by the Getting Started implementation is cut off and stops streaming prematurely.
- The reporter states they followed the documented instructions exactly and provides both the relevant documentation link and a reproduction repository.
