### ISSUE TITLE
EDGE_FUNCTION_INVOCATION_FAILED with Sveltekit API route

### ISSUE THREAD

**Issue by yehiaabdelm** [vercel/ai#426]
I'm encountering a EDGE_FUNCTION_INVOCATION_FAILED with the following API route in my sveltekit app. Any suggestions? I'm not using anything that doesn't run on the edge. It works fine when using serverless functions.

```js
import { Configuration, OpenAIApi } from 'openai-edge'
import { OPENAI_API_KEY } from '$env/static/private'
import { OpenAIStream, StreamingTextResponse } from 'ai'
import * as create from '$lib/utils/createDbChat'

/** @type {import('@sveltejs/adapter-vercel').Config}*/
export const config = {
    runtime: 'edge'
}

const configuration = new Configuration({
    apiKey: OPENAI_API_KEY,
})
const openai = new OpenAIApi(configuration)
const provider = 'openai'

/** @type {import('@sveltejs/kit').RequestHandler}*/
export async function POST({ request, locals, fetch }) {

    let completionTokenCount = 0

    const { userId } = locals.user
    const requestBody = await request.json()


    const { model, messages, state, chatId } = requestBody
    const prompt = messages[messages.length - 1].content

    const response = await openai.createChatCompletion({
        model,
        messages,
        stream: true
    })

    const stream = new OpenAIStream(response, {
        onCompletion: async (completion) => {
            if (state === 'new') {
                const { promptId, parentId, completionId } = requestBody
                const [user, assistant] = create.newMessage({ promptId, prompt, completionId, parentId, completion, provider, model })
                const res = await fetch(`/api/chat/${chatId}`, {
                    method: 'POST',
                    body: JSON.stringify({
                        user,
                        assistant,
                        state,
                        parentId
                    })
                })
            }
            else if (state === 'regenerate') {
                const { promptId, completionId } = requestBody
                const assistant = create.regenerate({ promptId, completionId, completion, provider, model })
                const res = await fetch(`/api/chat/${chatId}`, {
                    method: 'POST',
                    body: JSON.stringify({
                        assistant,
                        state,
                    })
                })
            }
        },
        onToken: (t) => {
            completionTokenCount++
        }
    })
    return new StreamingTextResponse(stream)
}

```

**Comment by yehiaabdelm** [comment]
Similar issue for reference: https://stackoverflow.com/questions/76008395/sveltekit-vercel-deployment-edge-function-error-500-typeerror-l-is-not-a-fun

Here are the logs on vercel:

[POST] /api/openai/completion reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true

TypeError: Cannot read properties of undefined (reading 'auth_user')
    at (../../../../.svelte-kit/output/server/chunks/models.js:160:23)
    at (../../../../.svelte-kit/vercel-tmp/fn-1/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/lucia.js:3:0)
    at (../../../../.svelte-kit/vercel-tmp/fn-1/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/hooks.server.js:1:0)
    at (../../../../.svelte-kit/vercel-tmp/fn-1/edge.js:13:7)
    at (../../../../.svelte-kit/output/server/chunks/internal.js:198:9)
    at (../../../../.svelte-kit/output/server/index.js:2689:23)
    at (../../../../.svelte-kit/vercel-tmp/fn-1/edge.js:14:1)

**Comment by MaxLeiter** [comment]
This seems unrelated to `ai`, I don't know what `auth_user` is but it's not from us.

**Comment by albertorg** [comment]
getting th same issue

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a support request about an application-specific SvelteKit edge runtime error, with no demonstrated defect in the AI SDK.

### Evidence
- The failure stack trace points to an undefined `auth_user` in application/SvelteKit model and authentication code.
- A maintainer states that `auth_user` is not from the AI SDK and the error appears unrelated to `ai`.
- The report asks for troubleshooting suggestions rather than identifying a concrete AI SDK failure.
