### ISSUE TITLE
Adding a contribution guide

### ISSUE THREAD

**Issue by EmilioJD** [vercel/ai#435]
Hello,

I would love to make a contribution to the docs or the code. There just seems to be not much context for how to do so. I don't understand how the docs are generated and there is no contribution guide. Would love if a more seasoned contributor provided some context.

**Comment by MaxLeiter** [comment]
A guide should be written, you're right. I'll leave this open until it's done 👍 

In the meantime:

The library code exists in `packages/core`. `examples/` contains the templates demonstrating how to use the library with various providers. 

The docs are in `docs/pages/docs` and are copied to an internal repository  that hosts the playground (at https://sdk.vercel.ai) because the docs are heavily intertwined with some of its features/codebase. That's definitely not ideal for external docs contributors, but you can still render the markdown files in an online renderer (I use the [vscode preview feature](https://code.visualstudio.com/docs/languages/markdown)). I'll double-check the docs on the playground before merging your code to make sure it looks good when rendered.

**Comment by ahmetson** [comment]
@MaxLeiter also, would be nice if you add the wish-list or a roadmap, so people can collaborate on them to add new features.

**Comment by kundan05** [comment]
Contact the Community:
Reach out to the community through the project's communication channels. This could be a mailing list, forum, or chat platform. Introduce yourself and express your interest in contributing to the documentation or code. Ask if there's a specific process or if someone could guide you.
Explore the Repository:
Look through the project's repository on the hosting platform (e.g., GitHub, GitLab). Check for any existing documentation on how to contribute. Sometimes, projects have a CONTRIBUTING.md file or a dedicated section in the README.
Analyze Existing Documentation:
Examine the existing documentation to understand the structure and format. Identify areas where you think improvements or clarifications could be made. This could include fixing typos, adding examples, or providing more in-depth explanations.
Look for Code Contributions:
If you're interested in contributing to the code, examine the codebase. Check for existing issues related to code contributions and see if there are any ongoing discussions about code changes. This will give you insights into the current development focus.
Check for Build Instructions:
Even if there isn't a dedicated contribution guide, there might be information on how to build and test the project. Look for files like README, INSTALL, or BUILD. Understanding how to set up the project locally is crucial for making meaningful contributions.
Submit Inquiries on Communication Channels:
If you're still unsure, don't hesitate to ask questions on the community channels. You could inquire about the contribution process, ask for clarification on specific aspects, or request guidance from more experienced contributors.
Propose Improvements:
If you couldn't find an existing issue related to your planned contribution, consider opening one. Describe the improvement you'd like to make and ask for feedback. This can be a helpful step to ensure alignment with the project's goals.
Provide Feedback:
If you encounter issues or challenges during the contribution process, provide constructive feedback to the maintainers. This helps improve the overall contribution experience for yourself and future contributors.
Document Your Process:
As you navigate through the contribution process, take notes on the steps you followed. This can be useful for creating a draft contribution guide that you might propose to the community or the maintainers.
Share Your Experience:
After successfully making a contribution, consider sharing your experience with the community. This could include insights into the contribution process, challenges you faced, and how you overcame them. Such information can be valuable for other newcomers.

**Comment by MaxLeiter** [comment]
We have a basic contributing file here, but will keep improving it: https://github.com/vercel/ai/blob/main/CONTRIBUTING.md

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The requested change is written contributor documentation, not a change to SDK behavior or runnable examples.

### Evidence
- The reporter asks for a contribution guide explaining how to contribute to the code and documentation.
- A maintainer agreed that a guide should be written and later linked the new CONTRIBUTING.md file.
