### ISSUE TITLE
error No HTTP methods exported

### ISSUE THREAD

**Issue by aimagination-dev** [vercel/ai#461]
When using the examples in AI SDK docs, I am always getting "error No HTTP methods exported in ...Export a named export for each HTTP method." However, when using the examples in https://github.com/vercel/ai/tree/main/examples/next-langchain that is slightly different then code is working fine. Any hints why example in the doc page are throwing such an error?
https://sdk.vercel.ai/docs/guides/providers/langchain

**Comment by MaxLeiter** [comment]
Hi, please provide your exact code and file name / path for your route handler

**Comment by aimagination-dev** [comment]
I mainly copied the example from the documentation below
https://sdk.vercel.ai/docs/guides/providers/langchain
File path is app/api/chat/route.ts

import { NextRequest } from 'next/server'
import { Message as VercelChatMessage, StreamingTextResponse } from 'ai'
 
import { ChatOpenAI } from 'langchain/chat_models/openai'
import { BytesOutputParser } from 'langchain/schema/output_parser'
import { PromptTemplate } from 'langchain/prompts'
 
export const runtime = 'edge'
 
/**
 * Basic memory formatter that stringifies and passes
 * message history directly into the model.
 */
const formatMessage = (message: VercelChatMessage) => {
  return `${message.role}: ${message.content}`
}
 
const TEMPLATE = `You are a pirate named Patchy. All responses must be extremely verbose and in pirate dialect.
 
Current conversation:
{chat_history}
 
User: {input}
AI:`
 
/*
 * This handler initializes and calls a simple chain with a prompt,
 * chat model, and output parser. See the docs for more information:
 *
 * https://js.langchain.com/docs/guides/expression_language/cookbook#prompttemplate--llm--outputparser
 */
export async function POST(req: NextRequest) {
  const body = await req.json()
  const messages = body.messages ?? []
  const formattedPreviousMessages = messages.slice(0, -1).map(formatMessage)
  const currentMessageContent = messages[messages.length - 1].content
 
  const prompt = PromptTemplate.fromTemplate(TEMPLATE)
  /**
   * See a full list of supported models at:
   * https://js.langchain.com/docs/modules/model_io/models/
   */
  const model = new ChatOpenAI({
    temperature: 0.8
  })
 
  /**
   * Chat models stream message chunks rather than bytes, so this
   * output parser handles serialization and encoding.
   */
  const outputParser = new BytesOutputParser()
 
  /*
   * Can also initialize as:
   *
   * import { RunnableSequence } from "langchain/schema/runnable";
   * const chain = RunnableSequence.from([prompt, model, outputParser]);
   */
  const chain = prompt.pipe(model).pipe(outputParser)
 
  const stream = await chain.stream({
    chat_history: formattedPreviousMessages.join('\n'),
    input: currentMessageContent
  })
 
  return new StreamingTextResponse(stream)
}

**Comment by MaxLeiter** [comment]
can you try bumping your version of langchain? it seems functional for me with `0.0.129`

**Comment by aimagination-dev** [comment]
I am also on langchain v0.0.129 but still hit the issue

**Comment by MaxLeiter** [comment]
can you create a full repository so I can try a full reproduction? feel free to make it private and invite my github if you can't make it public. I and other team members cannot reproduce.

**Comment by aimagination-dev** [comment]
My page.tsx is also copied from the doc

`'use client'
 
import { useChat } from 'ai/react'
 
export default function Chat() {
  const { messages, input, handleInputChange, handleSubmit } = useChat()
 
  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      {messages.map(m => (
        <div key={m.id}>
          {m.role === 'user' ? 'User: ' : 'AI: '}
          {m.content}
        </div>
      ))}
 
      <form onSubmit={handleSubmit}>
        <label>
          Say something...
          <input
            className="fixed w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
            value={input}
            onChange={handleInputChange}
          />
        </label>
        <button type="submit">Send</button>
      </form>
    </div>
  )
}`

**Comment by aimagination-dev** [comment]
sent you an invite - thanks

**Comment by MaxLeiter** [comment]
@aimagination-dev it works fine for me 🤔 

![CleanShot 2023-08-17 at 13 32 55@2x](https://github.com/vercel/ai/assets/8675906/7673c92b-ed24-4d68-9583-ae7c86c3a03c)

**Comment by MaxLeiter** [comment]
Going to close as it seems unique, but feel free to reply back here and I'll try and assist @aimagination-dev

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an environment-specific support request with no reproducible AI SDK or documentation defect established.

### Evidence
- Reporter receives “No HTTP methods exported” after copying the documented LangChain route handler.
- Maintainer tested the provided reproduction and confirmed it worked correctly.
- Issue was closed as unique to the reporter’s environment, with an offer for further assistance.
