### ISSUE TITLE
[vue] "name" parameter get's removed from function calls

### ISSUE THREAD

**Issue by cosbgn** [vercel/ai#469]
Look at this screenshot:
![2023-08-18_14 25 07@2x](https://github.com/vercel/ai/assets/17546283/22344a08-4a95-400f-b2c7-fa47f735884a)
The function call is executed correctly, but when I then ask another question the name is removed, and openAi throws an error as it's required.

I add messages as: `setMessages([...messages.value, msg])` using `useChat` with vue.js and send prompts with `handleSubmit`

**Comment by MaxLeiter** [comment]
Thanks for the report, this should be fixed

**Comment by cosbgn** [comment]
@MaxLeiter It's still happening on `ai/vue`

**Comment by cosbgn** [comment]
> Can you confirm that 2.2.2 introduced this?

Not sure, I just started using this library now. But I can try downgrading a few version. I'll let you know in a sec.

**Comment by cosbgn** [comment]
Seems to happen also with earlier versions like 2.1 etc

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete failure in existing Vue chat behavior: message state is serialized without a required field, causing a downstream API error.

### Evidence
- Vue `useChat` removes the required `name` field from a message with role `function` when submitting a subsequent question.
- The malformed message causes OpenAI to return an error that function-role messages must have a `name`.
- The reporter confirms the failure also occurs in earlier 2.1-era versions.
