### ISSUE TITLE
Dynamic body / Way to update useChat options

### ISSUE THREAD

**Issue by cosbgn** [vercel/ai#471]
Currently options are fixed. However I need a way to change the body. My code looks like this (with vue.js but I think the idea is the same with react or any other library):

```js
<template>
	<div>
	  <button @click="n++; input = Math.random(); ">Increase to {{n+1}}</button>
	  <br /> <br/>
	  <button @click="handleSubmit">Submit</button>
	</div>
</template>

<script setup>
import { useChat } from 'ai/vue'

onMounted(() => input.value = Math.random()) // Otherwise req is not sent

const n = ref(0)
	const optio = computed(() => {

	})
	const { handleSubmit, input } = useChat({
		api:"/404",
		body: { n: n.value },
		onError: (e => alert("Callback works"))
	})
</script>
```

The body will allways be 0 (the inital value) no matter what n is. Ideally body would accept a function, like `getBody` or we would have a way to update the useChat options.

**Comment by MaxLeiter** [comment]
Can you not create a `getBody()` function or some equivalent?

```
useChat({ 
    body: getBody()
}) 

```

**Comment by cosbgn** [comment]
I tried, it doesn't work, it gets called on creation and never again.

**Comment by MaxLeiter** [comment]
Ah yeah I wasn't thinking very clearly -- body can be adapted to accept a function. Would you like to submit a PR?

**Comment by cosbgn** [comment]
> Would you like to submit a PR?

I really wouldn't know from where to start! But I agree a function for body would be great.

**Comment by MaxLeiter** [comment]
In each of the `use-chat` files (so for react, solid, vue, svelte) there's this line https://github.com/vercel/ai/blob/d6b8948dafdd06eb170ac4cdd8b72d3e8f7f410f/packages/core/vue/use-chat.ts#L123C16-L123C16

```
          ...body,
          ...options?.body
```

If you adjust the types of `body` (in `shared/types.ts`)  to also accept a `() => Request.BodyInit` these lines can become

```
	...(body instanceof Function ? body() : body)
````

**Comment by cosbgn** [comment]
Ok I'll give it a try

**Comment by cosbgn** [comment]
@MaxLeiter currently there are 2 bodies, options.body and body. I should replace both right? Like this:

```js
    //   ...extraMetadata.body, // Remove this
    //   ...chatRequest.options?.body, // Remove this
	  ...(extraMetadata?.body instanceof Function ? extraMetadata.body() : extraMetadata.body),
	  ...(chatRequest?.options?.body instanceof Function ? chatRequest.options.body() : chatRequest?.options?.body),
```

**Comment by cosbgn** [comment]
Let me know: https://github.com/vercel/ai/pull/477

**Comment by shuding** [comment]
Not sure if this is a bug but when you do `n++` the internal ref of body should be updated. That’s how it works in the React version if `n` is a state, and the Vue version should do the same.

**Comment by dosstx** [comment]
This discussion in this thread then explains why I'm having the same issue ? https://github.com/vercel/ai/discussions/508

**Comment by dosstx** [comment]
I believe I may have fixed this issue for my case. I submitted a PR here: https://github.com/vercel/ai/pull/511

 In Vue 3, refs should be unwrapped inside the composable to make them reactive. By using the ref pattern, you allow the composable to react to changes in the value. The missing piece here is that the useChat utility should use unref(body) instead of directly accessing the .value property.

**Comment by dosstx** [comment]
OK I am not sure if this fixed the issue, sorry:( Can someone else check? This was my first PR ever so I am not sure if I tested it optimally. For some reason I thought it was working. Can any other Vue gurus check it out?

**Comment by arunavo4** [comment]
Currently I do this using a state variable. 
```
const {
    messages,
    setMessages,
    input,
    reload,
    stop,
    isLoading,
    handleInputChange,
    handleSubmit,
  } = useChat({
    api: "/api/chat",
    body: {
      ...state.model_config,
    },
  });
  ```

**Comment by jamesneal** [comment]
While we wait for that to be merged, here's a workaround for us Svelte folks:

```	let options = { model: 'gpt-3.5-turbo', temperature: 0.3 };
	let chat = useChat({ body: { options } });
	let { input, handleSubmit, messages, isLoading } = chat;
	$: {
	     chat = useChat({ body: { options } });
	     input = chat.input;
	     handleSubmit = chat.handleSubmit;
	     messages = chat.messages;
	     isLoading = chat.isLoading;
	   }
```

**Comment by 0xinhua** [comment]
Hi, I wonder if this problem has been completely solved? Same problem here, useChat is used in vue code but the body parameter is not updated, Or how to change the code?

```js
const chatId = ref('')
const { messages, input, handleSubmit, isLoading, stop, reload } = useChat({
  initialMessages,
  body: {
    id: chatId.value,
  },
})

```

**Comment by gwhitelaw** [comment]
@cosbgn this is now possible using the ChatRequestOptions. The docs currently are inconsistent with the api (I have an issue to fix mentioned above, but I wanted to let you know incase other people come across this issue.

[Docs](https://sdk.vercel.ai/docs/api-reference/use-chat):

```
      await chat.handleSubmit(e, {
        options: {
          body: {
            ...
          },
          headers: {
           ...
          },
        },
```

**Comment by jakob-fiegerl** [comment]
For anyone still facing this issue. I found another way:

form calls my `onSubmit` which calls VercelAI `handleSubmit`

```svelte
const { handleSubmit } = useChat({});

const onSubmit = (e: any, chatRequestOptions?: ChatRequestOptions) => {
    handleSubmit(e, {
        ...chatRequestOptions,
        options: {
            ...chatRequestOptions?.options,
            body: {
                ...chatRequestOptions?.options?.body,
                metadata: {
                    // your additional props here
                },
            },
        },
    });
};

<form on:submit={onSubmit}>
  <!-- chat logic -->
</form>
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
Although the initial proposal suggests accepting a function as an enhancement, the comments clarify a concrete Vue reactivity failure: request body values do not update as maintainers expect them to.

### Evidence
- In Vue, the `body` passed to `useChat` remains at its initial value after the underlying ref changes.
- A maintainer stated that the internal body reference should update and that Vue should behave like the React implementation.
- Later commenters reproduced the same stale-body behavior in Vue/Nuxt and proposed unwrapping reactive refs inside the composable.
