### ISSUE TITLE
Premature abort of stream when not running on the edge

### ISSUE THREAD

**Issue by bonnie** [vercel/ai#497]
## The issue
I have a server route that calls `openai.createChatCompletion`. When runtime is **not** set to edge in the route, the stream prematurely aborts and does not run the `onCompletion` function. In this case, the `onCompletion` callback saves to the database (similar to the documentation: https://sdk.vercel.ai/docs/guides/openai#guide-save-to-database-after-completion)

Since the `onCompletion` saves to the database, I **can't** run on the edge -- if I try, I get this error on the server: 

```
- error Error: PrismaClient is unable to be run in the browser.
```

## What this looks like on the client
The stream ends mid-sentence, and the output is not saved to the database. 

## My workaround
- set the runtime to "edge" in the server route
- create a new route to save to the database
- call the route that saves to the db from the client, in the `onFinish` callback to `useCompletion`. 

I don't have time to create a minimally reproducible test case, but I might be able to in a week or two. Please let me know if I can answer any questions!

**Comment by MaxLeiter** [comment]
Thanks for the report @bonnie. I believe this is a vercel or Next.js issue, not one with the SDK, but I want to leave this open to track it here.
 
Can you confirm you're using Next.js and/or Vercel, and if so, what Next.js version are you using?

**Comment by MaxLeiter** [comment]
Aha, I think you could be running into timeout limits and we should surface that better (in the SDK)

From the [Vercel docs on limits](https://vercel.com/docs/limits/overview):

<img width="801" alt="CleanShot 2023-08-22 at 15 10 08@2x" src="https://github.com/vercel/ai/assets/8675906/ead2a280-c677-4bd1-beea-ce0951ff1c17">

Edge Functions have no limit on execution time, as long as they start responding within 30 seconds. Serverless functions have a hard time limit of 10 seconds on hobby and 60 seconds on pro.

**Comment by bonnie** [comment]
Aha, I see. So when I run on the edge, everything's fine because the stream starts within 30 seconds. But when I run as a serverless function it gets cut off after 10 seconds because I'm ~cheap~ on the hobby plan. 

That makes perfect sense -- thank you! We can close this out. 😊

**Comment by bonnie** [comment]
Aha, I see. So when I run on the edge, everything's fine because the stream starts within 30 seconds. But when I run as a serverless function it gets cut off after 10 seconds because I'm ~cheap~ on the hobby plan.

That makes perfect sense -- thank you! We can close this out. 😊

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This was resolved as a deployment-platform limit/support explanation, not a failure or requested change in the AI SDK.

### Evidence
- The stream ended after roughly 30 seconds when deployed as a non-edge Vercel Serverless Function on the Hobby plan.
- The maintainer identified Vercel's 10-second Hobby serverless execution timeout as the likely cause, rather than an AI SDK defect.
- The reporter agreed the platform timeout explained the behavior and requested that the issue be closed.
