### ISSUE TITLE
docs(guides): fix error handling code for openAI completion

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/ai#499]
In [Use the Completion API](https://sdk.vercel.ai/docs/guides/providers/openai#use-the-completion-api), the code with error handling:

```ts
// ...

  // Ask OpenAI for a streaming completion given the prompt
  const response = await openai.completions.create({
    model: 'text-davinci-003',
    stream: true,
    prompt
  })
 
  // Check for errors -----> here
  if (!response.ok) {
    return new Response(await response.text(), {
      status: response.status
    })
  }

// ...
```

The `response` does not return a type of `Response`, therefore the code is not valid.

### Suggestion

```ts
// ...

  // Ask OpenAI for a streaming completion given the prompt
  const completions = await openai.completions.create({
    model: 'text-davinci-003',
    stream: true,
    prompt
  })

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(completions)

  // Respond with the stream
  const response = new StreamingTextResponse(stream)

  // Check for errors
  if (!response.ok) {
    return new Response(await response.text(), {
      status: response.status
    })
  }

  return response

// ...
```

### Reference

- [Use the Completion API](https://sdk.vercel.ai/docs/guides/providers/openai#use-the-completion-api)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This requests a correction to invalid code in the documentation guide, without reporting a defect in the SDK's runtime behavior.

### Evidence
- The linked OpenAI completion guide checks `response.ok`, `response.text()`, and `response.status` on the value returned by `openai.completions.create`.
- The reporter states that this value is not a web `Response`, making the documented code invalid, and proposes corrected guide code.
