### ISSUE TITLE
docs(guides): following the guide renders awkward UI on Next.js(v.13.4.19)

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/ai#509]
In [Providers - OpenAI](https://sdk.vercel.ai/docs/guides/providers/openai), the `Wire Up the UI` example `page.tsx` code:

```ts
'use client'
 
import { useChat } from 'ai/react'
 
export default function Chat() {
  const { messages, input, handleInputChange, handleSubmit } = useChat()
 
  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      {messages.map(m => (
        <div key={m.id}>
          {m.role === 'user' ? 'User: ' : 'AI: '}
          {m.content}
        </div>
      ))}
 
      <form onSubmit={handleSubmit}>
        <label>
          Say something...
          <input
            className="fixed w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
            value={input}
            onChange={handleInputChange}
          />
        </label>
        <button type="submit">Send</button>
      </form>
    </div>
  )
}
```

Renders:

![Screenshot 2023-08-24 at 9 34 06 PM](https://github.com/vercel/ai/assets/120007119/c96843c9-b2c6-4e4a-92ce-5f798ec5d1d2)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This reports a problem with a documentation guide's UI code example. Correcting the guide would address the issue without changing product behavior.

### Evidence
- The issue points to the OpenAI provider guide's `page.tsx` example and shows that following it produces an awkward layout.
- The screenshot highlights that the Send button is misplaced and the input value is not visible.
- The requested correction concerns code published in a documentation guide, not the SDK's runtime behavior.
