### ISSUE TITLE
Composable makes arbitrary requests to a `completion-loading` endpoint.

### ISSUE THREAD

**Issue by genu** [vercel/ai#515]
There is an issue in vue where there are constant requests made to the end point `completion-loading`. I'm not sure what is causing this. I'm using vue. It could be simmilar to issue #395 

It happens if I just call the `useCompletion()` composable in the setup function. 

```vue
<script lang="ts" setup>
import { useCompletion } from 'ai/vue'

const test = useCompletion()
</script>

<template>
  <div>hello</div>
</template>

```
<img width="1334" alt="CleanShot 2023-08-24 at 23 20 44@2x" src="https://github.com/vercel/ai/assets/928780/c4532404-0bdd-4cc2-b16f-93889189fb05">

I'm wondering if its realted to how this `useSWRV` instance is configured here:

https://github.com/vercel/ai/blob/56f9c4b178315d6189b00c714827395f66c76462/packages/core/vue/use-completion.ts#L71-L74

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete, unintended runtime behavior in the existing Vue composable: merely initializing `useCompletion()` causes continuous arbitrary network requests and 404 errors.

### Evidence
- Calling `useCompletion()` in a Vue setup function triggers repeated requests without any completion action.
- The requests target generated `completion-*-loading` endpoints and return 404 responses, as shown in the network log.
- The reporter points to the composable's `useSWRV` configuration as a possible cause.
