### ISSUE TITLE
useChat  isLoading never resets to false

### ISSUE THREAD

**Issue by fullStackDataSolutions** [vercel/ai#518]
I'm using the following code:

```ts
const {  isLoading, messages, input, handleInputChange, handleSubmit } = useChat()  

...

<fieldset disabled={isLoading}>
                <textarea
                  value={input}
                  onChange={handleInputChange}
                  placeholder="Send a message..."
                />
                <button className="btn" type="submit">
                  Send
                </button>
              </fieldset>
```

When a stream starts, isLoading is never resets to false. This is obviously a bug.

**Comment by MaxLeiter** [comment]
Which framework are you using?

**Comment by blazestudios23** [comment]
Nest.js

**Comment by MaxLeiter** [comment]
```
'use client'

import { Message } from 'ai/react'
import { useChat } from 'ai/react'
import { ChatRequest, FunctionCallHandler, nanoid } from 'ai'

export default function Chat() {
  const functionCallHandler: FunctionCallHandler = async (
    chatMessages,
    functionCall
  ) => {
    if (functionCall.name === 'eval_code_in_browser') {
      if (functionCall.arguments) {
        // Parsing here does not always work since it seems that some characters in generated code aren't escaped properly.
        const parsedFunctionCallArguments: { code: string } = JSON.parse(
          functionCall.arguments
        )
        // WARNING: Do NOT do this in real-world applications!
        eval(parsedFunctionCallArguments.code)
        const functionResponse = {
          messages: [
            ...chatMessages,
            {
              id: nanoid(),
              name: 'eval_code_in_browser',
              role: 'function' as const,
              content: parsedFunctionCallArguments.code
            }
          ]
        }
        return functionResponse
      }
    }
  }

  const { isLoading, messages, input, handleInputChange, handleSubmit } =
    useChat()

  // Generate a map of message role to text color
  const roleToColorMap: Record<Message['role'], string> = {
    system: 'red',
    user: 'black',
    function: 'blue',
    assistant: 'green'
  }

  return (
    <form onSubmit={handleSubmit}>
      <fieldset disabled={isLoading}>
        <textarea
          value={input}
          onChange={handleInputChange}
          placeholder="Send a message..."
        />
        <button className="btn" type="submit">
          Send
        </button>
      </fieldset>
      <div className="messages">
        {messages.map(message => (
          <div key={message.id} style={{ color: roleToColorMap[message.role] }}>
            {message.content}
          </div>
        ))}
      </div>
    </form>
  )
}

```
works fine for me

**Comment by smndtrl** [comment]
@MaxLeiter I have the same issue as @blazestudios23 on my system. I tried your code and the problem remains the same.  I used `2.2.9` and `2.2.10` of the package.

In the `route.ts`, I use langchains `ChatOllama` with a `StringOutputParser`. I currently have no way to test with `ChatOpenAI` and the `BytesOutputParser` to see if it makes a difference.

**Comment by blazestudios23** [comment]
Mine actually does go back to true, but it takes about 30 seconds after the chat response ends. So some kind of issue with it not registering that the chat is done.

**Comment by Jasonkoolman** [comment]
I experience the same issue with `useCompletion` after awaiting `complete(prompt)`

**Comment by altechzilla** [comment]
Experiencing something similar here when the stream is interrupted before it starts sending data. 

1. Start a completion
2. Switch to a different chat id before it sends data through
3. The hook gets stuck with isLoading set to true for that chat id

**Comment by dosstx** [comment]
Experiencing same issue with Vue. Anyone got it resolved?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete incorrect lifecycle-state behavior in existing hooks: `isLoading` does not promptly reset when streaming finishes or is interrupted. Despite possible integration-specific causes, this is presented as a failure of current behavior.

### Evidence
- The reporter states that `useChat().isLoading` remains true after the response stream ends, leaving the form disabled.
- A later clarification reports that it resets only after roughly 30 seconds, suggesting delayed recognition of stream completion.
- Other users report similar behavior with `useCompletion`, Vue, and interrupted streams, although one LangChain case was resolved by using `BytesOutputParser`.
