### ISSUE TITLE
Weird client-side function handling

### ISSUE THREAD

**Issue by odysseaspapadimas** [vercel/ai#523]
I have a bunch of functions on the client-side that I would like to first respond to the user before executing the rest of the function, this was part of my other issue that I was basically told this wasn't supported [yet](https://github.com/vercel/ai/issues/257#issuecomment-1640902774), however I came up with a kind of solution
```jsx
    //inside the client functionCallHandler
    if (functionCall.name === "call_number") {
      if (functionCall.arguments) {
        const args: { number: string } = JSON.parse(functionCall.arguments);
        const functionResponse: ChatRequest = {
          messages: [
            ...chatMessages,
            {
              id: nanoid(),
              name: "call_number",
              role: "function" as const,
              content: "",
            },
          ],
        };

        const synth = window.speechSynthesis;
        const utterance = new SpeechSynthesisUtterance("Redirecting to phone");
        synth.speak(utterance);

        //open phone app
        setTimeout(() => {
          open(`tel:${args.number}`);
        }, 3000);

        return functionResponse;
      }
    }
```
The `call_number` function
```jsx
  {
    name: "call_number",
    description: "Call a number",
    parameters: {
      type: "object",
      properties: {
        number: {
          type: "string",
          description: "The number to call",
        },
      },
      required: ["number"],
    },
  },
```

This simply returned a response from the server say `Calling <number>` then 1-2 seconds later it opened the tel protocol or whatever else I wanted to do. This at some point used to work but as of the 2.2(I think) version doesn't work. I included new functionality and updated to 2.2 without testing these functions and at some version they stopped working, I have not been able to find which version.

Now comes the weird part, it's not that this doesn't work it's that the function gets called multiple times, like a lot, it goes like this: Send a message that triggers the function and then the client function gets run anywhere from 3 to 7 times opening a new tab in this example for each one.
The returned message sometimes is `Sure, calling <number>` but sometimes it includes the arguments as well like so
```
{
"number": <number>
}
Sure calling <number>
```

These examples were run with gpt-3.5-turbo

I'm assuming the problem is somewhere with the functionResponse and how the server-side function handling has been changed quite a bit in the last few versions, and I've tried changing the message content inside the functionResponse to different values but have not found something that works better than just leaving it empty
```jsx
{
   id: nanoid(),
   name: "call_number",
   role: "function" as const,
   content: "", //this one
}
```

**Comment by odysseaspapadimas** [comment]
[Here](https://github.com/odysseaspapadimas/ai-chat-functions) you go @MaxLeiter, here's a screenshot as well
![image](https://github.com/vercel/ai/assets/19214233/b7224561-2c32-42ec-8290-d898682ed4ab)

**Comment by MaxLeiter** [comment]
Interestingly, it only seems to happen with the phone number function. Weather seems to work okay for me:

<img width="632" alt="CleanShot 2023-08-30 at 20 53 19@2x" src="https://github.com/vercel/ai/assets/8675906/b9d4ef2f-ce66-43a8-b70f-2cc19e09d269">

**Comment by lgrammel** [comment]
Please check out our new tool calling with AI SDK Core and useChat: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling#example-server-side-tool-execution-with-roundtrips

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete regression in existing function-calling behavior: one function call is processed multiple times and produces malformed output.

### Evidence
- After upgrading to AI SDK 2.2, a client-side `functionCallHandler` that previously worked began executing the same function 3–7 times for one request.
- The repeated executions open multiple tabs and sometimes leak function arguments into the assistant response.
- The reporter supplied a reproduction repository and screenshot, and a maintainer attempted to reproduce and investigate the version that introduced the change.
