### ISSUE TITLE
Allow sending additional data in Message, apart from role and content

### ISSUE THREAD

**Issue by ExLineP** [vercel/ai#526]
Hi! I have an app where every message has unique id, task_id of the message etc.
When sending data to api `const { messages } = request;` only role and content gets to api. Sending the same messages in the body doesn't seem like a good solution and in my situation i couldn't have it to work anyway. Is there a solution to this problem?

**Comment by dosstx** [comment]
Isn't this what the `body` option is for in `useChat`?

Example (Vue syntax):

```
const body = {
    foo: 'bar', name: 'John' 
}

const { messages, input, handleSubmit } = useChat({
    api: '/api/chat',
    headers: { 'Content-Type': 'application/json' },
    body: body //<----- send custom messages here
})
```

**Comment by ExLineP** [comment]
> Isn't this what the `body` option is for in `useChat`?
> 
> Example (Vue syntax):
> 
> ```
> const body = {
>     foo: 'bar', name: 'John' 
> }
> 
> const { messages, input, handleSubmit } = useChat({
>     api: '/api/chat',
>     headers: { 'Content-Type': 'application/json' },
>     body: body //<----- send custom messages here
> })
> ```

But why do i need to send the same messages twice? The best solution, in my opinion, is to allow additional fields in Message type.

**Comment by ExLineP** [comment]
@MaxLeiter can you provide some clarification on this, please?

**Comment by MaxLeiter** [comment]
OpenAI will throw an error if you pass invalid data inside a message

**Comment by ExLineP** [comment]
> OpenAI will throw an error if you pass invalid data inside a message

but we are mapping in the API the data which is gonna go to the OpenAI anyway ` messages: messages.map((message: any) => ({
      content: message.content,
      role: message.role,
    })).` 
The data which is coming to the API from the UI doesn't need to be touched.

**Comment by dosstx** [comment]
> > Isn't this what the `body` option is for in `useChat`?
> > Example (Vue syntax):
> > ```
> > const body = {
> >     foo: 'bar', name: 'John' 
> > }
> > 
> > const { messages, input, handleSubmit } = useChat({
> >     api: '/api/chat',
> >     headers: { 'Content-Type': 'application/json' },
> >     body: body //<----- send custom messages here
> > })
> > ```
> 
> But why do i need to send the same messages twice? The best solution, in my opinion, is to allow additional fields in Message type.

Btw "send the same message twice", do you mean the `role` and `content` data that is being sent to the API? You would want that twice becasue the chat needs to know the previous messages in order for it to understand message context for its responses. Maybe I don't understand what you are asking?

**Comment by MaxLeiter** [comment]
Ah, we forgot to document `sendExtraMessageFields` (and I forgot it exists 😅). 

This will work for you, right @ExLineP? https://github.com/vercel/ai/blob/44265c3f956ccd974ddf1afd4c30f1fcb41dc1b5/packages/core/svelte/use-chat.ts#L78-L89

**Comment by ExLineP** [comment]
Yes! Thank you!

**Comment by MaxLeiter** [comment]
Documented in ec4bfa09c90a20338eee289c462639087a5dbc35. Thanks for the issue!

**Comment by felipetodev** [comment]
Is there any way to add that extra field but in the assistant's response?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The problem was missing documentation for an existing capability, not a required product behavior change.

### Evidence
- The requested behavior already existed through the `sendExtraMessageFields` option.
- A maintainer stated the option had been omitted from the documentation.
- The maintainer resolved the issue by documenting the option in commit `ec4bfa09c90a20338eee289c462639087a5dbc35`.
