### ISSUE TITLE
Messages Metadata

### ISSUE THREAD

**Issue by Yoha485** [vercel/ai#542]
It's not really an issue, just want to know your opinion

Did someone try to add metadata to chat messages?
For example. Let's say I have a weather chat bot. I want my main data structure in chat to be like:
```
[
  {
    message: 'What's the weather?',
    type: MessageTypes.WEATHER_MESSAGE,
    from: 'user'
  },
  {
    message: '43 F Today',
    type: MessageTypes.WEATHER_MESSAGE,
    from: 'bot'
  },
]
```

Not just `string`

---

The main idea is that I want a different UI for different message types. For example when user will obtain answer about the weather I would also put a button to this message that will redirect you to website for more information.

I understand that you can easily do that but the main thing is that I'm trying to save message streaming. Cause when I just operate this data structure between client and server I won't have a message streaming.

My only thought was to include all metadata to message string itself and conditionaly hide it from user on the client, but at the same time have the information that I need. But it's not the best way to do that I'm sure

If someone have any suggestions, I'll be glad to read them. Thanks!

**Comment by MaxLeiter** [comment]
You can enable `sendExtraMessageFields` in the useChat/useCompletion options and then we will leave your `messages` intact on the server.

**Comment by Yoha485** [comment]
@MaxLeiter 
Thanks man, should've read documentation better

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support question about using existing APIs, not a report of broken behavior or a request to change the product, documentation, or examples.

### Evidence
- The author explicitly frames the issue as a request for opinions and suggestions about attaching metadata to streamed chat messages.
- A maintainer points to existing `sendExtraMessageFields` and `experimental_StreamData` functionality.
- The author acknowledges that the solution was already documented.
