### ISSUE TITLE
Unify experimental client and server function calling

### ISSUE THREAD

**Issue by MaxLeiter** [vercel/ai#547]
The client-side API should be changed to match the server-side.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API consistency and ergonomics enhancement requesting a behavior/API change, so it is a feature request.

### Evidence
- The issue requests changing the client-side API to match the server-side API.
- No concrete malfunction or contradiction of documented behavior is reported.
