### ISSUE TITLE
useChat's `messages` does not trigger an update as a dependency in a useCallback, which is called inside of onFinish(...)

### ISSUE THREAD

**Issue by davit-b** [vercel/ai#548]
Simply put
```ts
const {
    messages,
    setMessages,
    input,
    setInput,
    append
  } = useChat({
    onFinish: (message) => {
      pushToLocalStateAndReset()
    }
  })
```

```ts
  const pushToLocalStateAndReset = useCallback(() => {
    console.log({
      msg: 'pushToLocalStateAndReset',
      messages: messages,
    })
  }, [messages])
  ```

On the first chat will output
![Screenshot 2023-09-07 at 12 56 49 PM](https://github.com/vercel/ai/assets/12516060/f2ea70fb-42ef-4432-bce4-3cb911a16bee)

Even though there is data within the messages[] array as it's render on the screen.

### The problem
It's likely one of two things
1. I'm using useCallback incorrectly because of my lack of experience with React.
2. Something about the way that SWR implements `messages` and it's `mutate(...)` function doesn't work like if messages was simply stored inside of `useState` for warning dependency that an update has occured.

See [https://github.com/vercel/ai/blob/f81de390e142520e1d9fe64f4c3adb9dcf493102/packages/core/react/use-chat.ts#L352](https://github.com/vercel/ai/blob/f81de390e142520e1d9fe64f4c3adb9dcf493102/packages/core/react/use-chat.ts#L352)
```ts
  // Store the chat state in SWR, using the chatId as the key to share states.
  const { data: messages, mutate } = useSWR<Message[]>([api, chatId], null, {
    fallbackData: initialMessages,
  });
```

**Comment by davit-b** [comment]
Or maybe, it has to do entirely with the `onFinish` helper being instantiated once as an input into `const {...} = useChat({...})` and therefore that callback doesn't update?

**Comment by davit-b** [comment]
I discovered a work around to get `onFinish` to trigger a side effect. 
```ts
const [triggerCopyToLocalState, setTriggerCopyToLocalState] = useState(false)

const {
    messages,
    ...
  } = useChat({
    onFinish: (message) => {
      // ~~pushToLocalStateAndReset()~~
      // Cannot call a callback from here, have to update some local state and have that useEffect to call a callback.
      setTriggerCopyToLocalState(true)
    },
  })
```

```ts
  const pushToLocalStateAndReset = useCallback(() => {
    ...
  }, [tempMessages, messagesToRender])

  useEffect(() => {
    if (triggerCopyToLocalState) {
      pushToLocalStateAndReset()
      setTriggerCopyToLocalState(false)
    }
  }, [triggerCopyToLocalState, pushToLocalStateAndReset])
  ```

This actually works.

But it would save a lot of headache to be able to call a up-to-date callback from the useFinish(...) handler.

**Comment by davit-b** [comment]
A helpful todo would be 
[ ] - Add documentation to the `onFinish` callback is memoized at the time of initialization of the `useChat(...)` and it doesn't update as a user may expect it to update.

**Comment by MaxLeiter** [comment]
`onFinish` provides the `message`:  `onFinish: (message) => {}`. The next render pass will have an updated `messages`. A PR calling this out in the docs would be great!

**Comment by qieman** [comment]
> const pushToLocalStateAndReset = useCallback(() => {
>     ...
>   }, [tempMessages, messagesToRender])

```
  const pushToLocalStateAndReset = useCallback(() => {
    ...
  }, [tempMessages, messagesToRender])
```
thie useCallback did not work, tempMessages and messagesToRender still old state

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The maintainer characterized the behavior as expected render timing rather than a product failure, with the requested resolution being clearer documentation.

### Evidence
- The reporter found that `messages` is stale when accessed from a callback invoked inside `onFinish`.
- The reporter explicitly requested documentation clarifying when `onFinish` and message updates occur.
- A maintainer explained that `onFinish` supplies the completed `message`, while the updated `messages` value is available on the next render, and invited a documentation PR.
