### ISSUE TITLE
useChat hook call to `/api/chat` doesn't pass the full `Message` object. 

### ISSUE THREAD

**Issue by davit-b** [vercel/ai#551]
https://github.com/vercel/ai/blob/f81de390e142520e1d9fe64f4c3adb9dcf493102/packages/core/react/use-chat.ts#L93

If you want to use the `onStart` or `onCompletion` callbacks to save to a database, you do not have access to the additional fields of the `Message` type. Important fields such as `id` or `createdAt` which leads one to generating new guids for the messages on the server-side 

```ts
// Convert the response into a friendly text-stream
    const stream = OpenAIStream(response, {
      onStart: async () => {
        // This callback is called when the stream starts
        // You can use this to save the prompt to your database
        // await savePromptToDatabase(prompt)
      },
      onToken: async (token: string) => {
        // This callback is called for each token in the stream
        // You can use this to debug the stream or save the tokens to your database
        logger.debug(token)
      },
      onCompletion: async (completion: string) => {
        // This callback is called when the stream completes
        // You can use this to save the final completion to your database
        // await saveCompletionToDatabase(completion)

        // 6. Save messageSequence to DDB
        await saveInputAndCompletionToDDB(messages, completion)
      }
    })
```

The `Message` type is defined by the SDK itself
```ts
/**
 * Shared types between the API and UI packages.
 */
type Message = {
    id: string;
    createdAt?: Date;
    content: string;
    role: 'system' | 'user' | 'assistant' | 'function';
    /**
     * If the message has a role of `function`, the `name` field is the name of the function.
     * Otherwise, the name field should not be set.
     */
    name?: string;
    /**
     * If the assistant role makes a function call, the `function_call` field
     * contains the function call name and arguments. Otherwise, the field should
     * not be set.
     */
    function_call?: string | ChatCompletionMessage.FunctionCall;
};
```

but only the `content` and `role` are passed to the `/api/chat` route handler. If you think through the flow on client-side it goes like this 
1. (client) take inputs, generates ids for them, and put them into the `messages` object
2. (client) calls server for completion
3. (server) returns stream completion && saves the input, or completion to a database
4. (client) reads the stream, generates an id for the read string, and stores in the `messages` object

So in step # 3, if one stores to the database using different id keys - and then generates ids keys on the client-side as well - how can you reconcile them later without a pull from the server and rewriting id keys on messages?

**Comment by ctate** [comment]
As @venables mentioned, `sendExtraMessageFields` will pass extra fields (`id` and `createdAt`) to `/api/chat` but keep in mind that OpenAI doesn't accept these params, so you'll need to omit them when using `openai.chat.completions.create()`:

```ts
const { messages } = (await req.json()) as {
  messages: Array<{
    id: string
    createdAt: string
    content: string | null
    role: 'system' | 'user' | 'assistant' | 'function'
    function_call?: {
      arguments: string
      name: string
    }
    name?: string
  }>
}

const response = await openai.chat.completions.create({
  model: 'gpt-3.5-turbo',
  stream: true,
  messages: messages.map((message) => ({
    role: message.role,
    content: message.content,
    function_call: message.function_call,
    name: message.name,
  })),
})
```

**Comment by davit-b** [comment]
Yes `sendExtraMessageFields` works for the case of sending the `id` and `createdAt`.

However `messages` is typed as `Message[]` and you include add extra fields. I don't know if there is a way to create a type that extends `Message` like you would `extend` a class in Java. 

```ts
/**
 * Shared types between the API and UI packages.
 */
type Message = {
    id: string;
    createdAt?: Date;
    content: string;
    role: 'system' | 'user' | 'assistant' | 'function';
    /**
     * If the message has a role of `function`, the `name` field is the name of the function.
     * Otherwise, the name field should not be set.
     */
    name?: string;
    /**
     * If the assistant role makes a function call, the `function_call` field
     * contains the function call name and arguments. Otherwise, the field should
     * not be set.
     */
    function_call?: string | ChatCompletionMessage.FunctionCall;
};
```

<img width="506" alt="Screenshot 2023-10-03 at 8 01 38 AM" src="https://github.com/vercel/ai/assets/12516060/30d6cdbb-bf41-4924-883a-87bc0f8dd2a9">


If there is a way to do this with TS, I'd happily learn if anyone can point the way.

**Comment by MaxLeiter** [comment]
Fixed by #619.  See the PR for an example. Thanks @venables!

**Comment by davit-b** [comment]
@venables Very cool thing to learn! Thank you!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The existing extra-message-fields capability worked at runtime but its typing rejected custom fields, creating a concrete mismatch in supported behavior that required a code fix.

### Evidence
- `sendExtraMessageFields` already sends `id` and `createdAt`, resolving the original server-side field omission.
- The reporter then demonstrated a TypeScript error when adding custom fields because `messages` was constrained to `Message[]`, despite the option supporting extra fields.
- A maintainer stated that PR #619 fixed the issue and provided an example.
