### ISSUE TITLE
Question: How to send extra data like temperature with useChat?

### ISSUE THREAD

**Issue by hyqshr** [vercel/ai#558]
HI! I'm trying to send some extra data (like temperature)to API using useChat.There is a data and metadata field in useChat, but not sure how to use them.

**Comment by ctate** [comment]
Hey @hyqshr - here is a basic example below. The data can be any type (string, number, object, etc.).

**API**

```ts
export async function POST(req: Request) {
  // Extract the `prompt` from the body of the request
  const { messages } = await req.json();

  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages: messages,
  });

  // Instantiate the data
  const data = new experimental_StreamData();

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response, {
    onFinal: message => {
      setTimeout(() => {
        data.append('moreData'); // Send some more data to client
        data.close(); // Make sure you close the data stream
      }, 2000);
    },
    experimental_streamData: true, // Enables streaming data
  });

  data.append('someData'); // Send some extra data to client

  // Respond with the stream
  return new StreamingTextResponse(stream, {}, data);
}
```

**UI**

```ts
const { messages, input, handleInputChange, handleSubmit, data } = useChat();

console.log(data); // the extra data
```

**Comment by hyqshr** [comment]
Thanks! By the way, is there any way to send data from the client to the server? :)

**Comment by holdenmatt** [comment]
Yes, look at the `body` param of `useChat`

**Comment by about-hector** [comment]
> Yes, look at the `body` param of `useChat`

it doesn't currently work as supposed, whatever you pass in the body is the initialization valye for useChat, if you change a value later on it doesn't reflect in the useChat body

nobody seems to have found workarounds yet

**Comment by ctate** [comment]
> Thanks! By the way, is there any way to send data from the client to the server using `useChat`? :)

I made this PR which might be a potential solution via `handleSubmit`: https://github.com/vercel/ai/pull/595

**Comment by zoahmed-xyz** [comment]
I'm using this to append the sources of retrieval augmented generation to my messages. Does anyone have a good solution for how to do this on the client/UI?

**Comment by 0x-Legend** [comment]
> > Yes, look at the `body` param of `useChat`
> 
> it doesn't currently work as supposed, whatever you pass in the body is the initialization valye for useChat, if you change a value later on it doesn't reflect in the useChat body
> 
> nobody seems to have found workarounds yet

I was able to change the values after initialization just by using useState and changing the value that way.

**Comment by coelhomultimedia** [comment]
I don't know if this is you need!

Client:
```javascript
append(
        id: uuidv4(),
        role: role,
        content: content,
        createdAt: new Date(),
        hidden: hidden,
        assistantName: assistantName,
        assistantAvatar: assistantAvatar,
        assistantRole: assistantRole,);
```
API:
```javascript
import OpenAI from "openai";
import {
    OpenAIStream,
    StreamingTextResponse,
    experimental_StreamData,
} from "ai";

// Initialize OpenAI instance with the API key from environment variables
const openai = new OpenAI({
    apiKey: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
});

// Specify the runtime environment
export const runtime = "edge";

export default async function POST(req) {
    const { messages } = await req.json();

    // Clean up the messages to only include role and content
    const allowedMessages = messages.map((message) => ({
        role: message.role,
        content: message.content,
    }));

    const response = await openai.chat.completions.create({
        model: "gpt-4",
        stream: true,
        messages: allowedMessages,
        temperature: 0.2,
        top_p: 1.0,
        n: 1,
        presence_penalty: 0.0,
        frequency_penalty: 0.0,
        logit_bias: {},
    });

    // Instantiate the data
    const data = new experimental_StreamData();

    // Convert the response into a friendly text-stream
    const stream = OpenAIStream(response, {
        experimental_streamData: true, // Enables streaming data
    });

    // Append only the last message
    const lastMessage = messages[messages.length - 1];
    data.append(lastMessage);

    data.close();

    // Respond with the stream
    return new StreamingTextResponse(stream, {}, data);
}
```

Client:
```javascript
    const chatOptions = useChat({sendExtraMessageFields:true}); // Send extra fields true
    console.log(chatOptions.data);
```
[#688](url)

**Comment by JayeshYadav99** [comment]
Thanks For Sharing

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a usage question resolved through the existing `useChat` body parameter, rather than a confirmed product defect or request for a new capability.

### Evidence
- The issue asks how to pass extra client data such as temperature through `useChat`.
- Comments identify the existing `body` option and provide a complete client/server example.
- One commenter reports that later body changes are not reflected, but another reports successfully updating values with React state; no maintainer confirms a defect.
