### ISSUE TITLE
Help with debug/logging

### ISSUE THREAD

**Issue by markNZed** [vercel/ai#565]
Is there a way to see the raw messages being sent/received with the OpenAI API ? It would be nice to be able to do a sanity check that all the parameters etc are being set as expected. Thanks.

**Comment by peterdresslar** [comment]
[Yes](https://sdk.vercel.ai/docs/api-reference/ai-stream).

// route.ts
const stream = OpenAIStream(response, {
            // log tokens to the console
            onToken: (token) => console.log(token)
        });

**Comment by peterdresslar** [comment]
On the client? You could [use React useEffect](https://github.com/peterdresslar/ai-edge-example-anthropic).

```typescript
//page.tsx
//imports
import { useEffect } from 'react';

export default function Chat() {
  const { messages, input, handleInputChange, handleSubmit, isLoading, error } = useChat();

//log messages, if and when they arrive at client
  useEffect(() => {
    if (messages.length === 0) {
      console.log('no messages');
    } else {
      for (let i = 0; i < messages.length; i++) {
        console.log(messages[i].role, messages[i].content);
      }
    }
  }, [messages]);
 //...   
 ```
 Please note that I am declaring a couple of other useful helpers from UseChat for debugging.

**Comment by markNZed** [comment]
> On the server? [Yes](https://sdk.vercel.ai/docs/api-reference/ai-stream).
> 
> ```ts
> // route.ts
> const stream = OpenAIStream(response, {
>             // log tokens to the console
>             onToken: (token) => console.log(token)
>         });
> ```

Yes on the server. It is good to see the tokens but I want to see all the data that is sent to OpenAI e.g. all the parameters, the conversation, etc

**Comment by shuding** [comment]
> I want to see all the data that is sent to OpenAI e.g. all the parameters, the conversation, etc

That is out of the scope of the SDK, as all the params are passed to OpenAI's lib, not the AI SDK. You can log all the information there:

```js
// add your logs before this
const response = await openai.completions.create({
  model: 'text-davinci-003',
  stream: true,
  prompt,
})
```

And then, the SDK takes over the repsonse:

```js
const stream = OpenAIStream(response)
```

So the AI SDK only knows about the tokens from the response, but it isn't aware of the AI parameters.

**Comment by markNZed** [comment]
Ah I see, thanks for the explanation. I am swapping out a library that was wrapping OpenAI. It seems OpenAI may improve debug support as per https://github.com/openai/openai-node/issues/302

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is a support question about logging data handled by the OpenAI client library, not a report of broken AI SDK behavior or a request for a specific SDK change.

### Evidence
- The reporter asks how to inspect raw OpenAI request and response data for debugging.
- A maintainer explains that request parameters are passed directly to OpenAI's library and can be logged before calling it; the AI SDK only handles the response stream.
- The reporter accepts the explanation and points to possible debugging improvements in the OpenAI library.
