### ISSUE TITLE
[feature] Multi-field Forms for Completion

### ISSUE THREAD

**Issue by bagedaddy** [vercel/ai#579]
Not sure this is available, but is there a way to use the ai SDK to stream ai results from a multi-field form. Seems like the useCompletion only works with a single input.

For instance, let's say we're building a character designer. User can type in the genre, gender, the personality, the job the character has. When the form submits, we send a request to openai with a prompt like "Describe a character in {genre}, who has the following traits {personality}, {job}, {gender}".

**Comment by about-hector** [comment]
this is something you should implement on your own using a system prompt

**Comment by about-hector** [comment]
handleSubmit is nothing fancy, it's just a helper hook that appends a message and resets the input field.

append, in turn, calls the triggerRequest function that is the one actually fetching your response, streaming it etc. 

when you submit a form, you can manipulate the formEvent object and do what you will with it. 

If you have multiple things you'd like to input you can 

-add them to the body of the request using the "body" param offered by useCompletion
-manipulate the formData, generate a prompt with it with a custom helper and send that to the server as a message.

**Comment by MaxLeiter** [comment]
Thanks for the issue @bagedaddy, and thanks @about-hector for explaining how to work around it!

@bagedaddy @thewebalchemist see here: https://sdk.vercel.ai/docs/api-reference/use-completion#usecompletionhelpers

**Comment by thewebalchemist** [comment]
Thanks for the quick reply, so how do i go about here, since I have tried using useState:

'use client'

import { useState } from 'react';
import { useCompletion } from 'ai/react';

export default function ProductNameGenerator() {
  const { completion, input, handleInputChange, handleSubmit } = useCompletion();

  const [adjective, setAdjective] = useState('');
  const [noun, setNoun] = useState('');
  const [verb, setVerb] = useState('');

  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      <form className='flex flex-col space-y-2 ' onSubmit={(e) => handleSubmit}>
        <input
          className="text-gray-800 w-full max-w-md border border-gray-300 rounded shadow-xl p-2"
          value={adjective}
          placeholder="Enter an Adjective..."
          onChange={(e) => setAdjective(e.target.value)}
        />
        <input
          className="text-gray-800 w-full max-w-md border border-gray-300 rounded shadow-xl p-2"
          value={noun}
          placeholder="Enter a Noun..."
          onChange={(e) => setNoun(e.target.value)}
        />
        <input
          className="text-gray-800 w-full max-w-md border border-gray-300 rounded shadow-xl p-2"
          value={verb}
          placeholder="Enter a Verb..."
          onChange={(e) => setVerb(e.target.value)}
        />
        <button type="submit" className="bg-blue-500 text-white p-2 rounded">
          Generate Product Names
        </button>
      </form>
      <div className="whitespace-pre-wrap my-6">{completion}</div>
    </div>
  );
}

**Comment by bagedaddy** [comment]
@MaxLeiter @about-hector Thanks for the suggestions, though I'm not sure that solves it. I'm asking what if you want to have two or three separate inputs for the user that you want to combine into a single prompt for text completion or chat.

I've been playing around with a workaround that I think works: basically creating a custom handleFormSubmit hook to create a concatenatedInput, calling handleInputChange on a Synthetic Event to change the input to the concatenated input, then handling the submit. 

It feels a little unintuitive and there is probably room to make it better, but it was the best I could manage without understanding how useCompletion works under the hood. Would appreciate any of your thoughts! @thewebalchemist, let me know if something like this works for you!

```
 const { completion, input, handleInputChange, handleSubmit } = useCompletion();

  const [businessDescription, setBusinessDescription] = useState("");
  const [businessIndustry, setBusinessIndustry] = useState("");
  const [businessName, setBusinessName] = useState("");

  const handleFormSubmit = (e: React.FormEvent<HTMLFormElement>) => {
  
    // Combine the three inputs into one prompt
    const concatenatedInput = `Prompt: ${prompt}, Essay: ${businessIndustry}, Business Name: ${businessName}`;
  
    // Create a synthetic ChangeEvent object
    const syntheticEvent = {
      target: {
        value: concatenatedInput,
      },
    } as ChangeEvent<HTMLInputElement>;
  
    // Update the input using the SDK's handleInputChange and the synthetic event
    handleInputChange(syntheticEvent);
  
    // Submit the form using the SDK's handleSubmit
    handleSubmit(e);
  };

  return (
      <form onSubmit={handleFormSubmit}>
        <input
          value={businessDescription}
          placeholder="Describe your business..."
          onChange={(e) => setBusinessDescription(e.target.value)}
        />
        <input
          value={businessIndustry}
          placeholder="Business Industry..."
          onChange={(e) => setBusinessIndustry(e.target.value)}
        />
        <input
          value={businessName}
          placeholder="Name your business..."
          onChange={(e) => setBusinessName(e.target.value)}
        />
        <button type="submit">Submit</button>
      </form>
  );


```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question about implementing multi-field input with existing SDK capabilities, not a confirmed bug or a request requiring a new feature.

### Evidence
- The description asks whether multi-field form streaming is already possible rather than reporting a concrete SDK failure.
- Comments explain that additional fields can be passed through useCompletion's `body` parameter or combined into a prompt before submission.
- A maintainer links the existing `useCompletion` helper documentation.
- The final comment is an implementation-support question about wiring multiple React state values into `handleSubmit`.
