### ISSUE TITLE
Dark Theme Styling Issue with Text Input in Next.js Getting Started Guide

### ISSUE THREAD

**Issue by lucas-wa** [vercel/ai#580]
I started reading the documentation and tried to follow the 'Getting Started' guide using Next.js. I had difficulty in knowing if the text in the input (located in the root's page.jsx) was being typed initially until I realized that my app, by default, applied Tailwind styling in dark theme. As a result, the text colors turned white, but the input for submitting the prompt remained white along with the text within it, making it impossible to perceive the text and causing me to question if I had done something wrong. I suggest applying a 'text-black' class or any other darker color by default to the input.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
This is a correction to sample code embedded in the documentation, not a failure of AI SDK runtime behavior.

### Evidence
- The Next.js Getting Started guide's input remains white while inherited dark-theme text is also white, making typed text invisible.
- The requested change is to add a dark text color class such as `text-black` to the guide's input code.
