### ISSUE TITLE
I want to use multiple inputs to get the data.

### ISSUE THREAD

**Issue by thewebalchemist** [vercel/ai#584]
I would like to use multiple input, here is an example:

'use client'

import { useState } from 'react';
import { useCompletion } from 'ai/react';

export default function ProductNameGenerator() {
  const { completion, input, handleInputChange, handleSubmit } = useCompletion();

  const [adjective, setAdjective] = useState('');
  const [noun, setNoun] = useState('');
  const [verb, setVerb] = useState('');

  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      <form className='flex flex-col space-y-2 ' onSubmit={(e) => handleSubmit}>
        <input
          className="text-gray-800 w-full max-w-md border border-gray-300 rounded shadow-xl p-2"
          value={adjective}
          placeholder="Enter an Adjective..."
          onChange={(e) => setAdjective(e.target.value)}
        />
        <input
          className="text-gray-800 w-full max-w-md border border-gray-300 rounded shadow-xl p-2"
          value={noun}
          placeholder="Enter a Noun..."
          onChange={(e) => setNoun(e.target.value)}
        />
        <input
          className="text-gray-800 w-full max-w-md border border-gray-300 rounded shadow-xl p-2"
          value={verb}
          placeholder="Enter a Verb..."
          onChange={(e) => setVerb(e.target.value)}
        />
        <button type="submit" className="bg-blue-500 text-white p-2 rounded">
          Generate Product Names
        </button>
      </form>
      <div className="whitespace-pre-wrap my-6">{completion}</div>
    </div>
  );
}

Below is the api/completion:

import OpenAI from 'openai';
import { OpenAIStream, StreamingTextResponse } from 'ai';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export const runtime = 'edge';
export async function POST(req: Request) {
  const { adjective, noun, verb } = await req.json();
  const response = await openai.completions.create({
    model: 'text-davinci-003',
    stream: true,
    temperature: 0.6,
    max_tokens: 300,
    prompt: `Generate 10 product names using the following inputs:\n\nAdjective: ${adjective}\nNoun: ${noun}\nVerb: ${verb}\n\nProduct Names:`,
  });
  const stream = OpenAIStream(response);
  return new StreamingTextResponse(stream);
}

**Comment by MaxLeiter** [comment]
You can manually call `setMessages` with `reload` or use `append` to construct your own message to send from the client. https://sdk.vercel.ai/docs/api-reference/use-chat

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily an implementation/support question that can be addressed using existing APIs, rather than a bug or a request for a new SDK capability.

### Evidence
- The report asks how to submit multiple client-side input values to construct a prompt.
- No broken or contradictory SDK behavior is identified.
- A maintainer points to existing `useChat` methods (`setMessages` with `reload`, or `append`) as the solution.
