### ISSUE TITLE
Connecting with OpenSource LLM

### ISSUE THREAD

**Issue by mahimairaja** [vercel/ai#587]
Is it possible to connect with fine-tuned LLM models like LLaMa-2?

**Comment by matthoffner** [comment]
Hello I've built a simple example demonstrating how you can use the Llama.cpp server with `useChat`: https://github.com/matthoffner/llama-use-chat

**Comment by MaxLeiter** [comment]
You have to connect to them through a provider, or run them locally with e.g. Ollama and connect with the OpenAIProvider: 

https://ollama.com/blog/openai-compatibility

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question that was answered with existing integration options, so it does not constitute a bug, documentation request, examples request, or feature request.

### Evidence
- The description asks whether fine-tuned open-source models such as LLaMA 2 can be connected.
- Comments provide support guidance and examples for connecting through a provider, llama.cpp, or Ollama's OpenAI-compatible API.
- No broken behavior, documentation change, example repository change, or explicit new capability is requested.
