### ISSUE TITLE
I want to use multiple inputs to get the data.

### ISSUE THREAD

**Issue by thewebalchemist** [vercel/ai#596]
Can someone please help me with the following, really confused:

`'use client'

import { useState } from 'react';
import { useCompletion } from 'ai/react';

export default function ProductNameGenerator() {
  const { completion, input, handleInputChange, handleSubmit } = useCompletion();

  const [adjective, setAdjective] = useState('');
  const [noun, setNoun] = useState('');
  const [verb, setVerb] = useState('');

  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      <form>
        <input
          className=" text-gray-800 w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
          placeholder="Enter an Adjective..."
          value={input}
          onChange={handleInputChange}
        />
        <input
          className=" text-gray-800 w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
          value={noun}
          placeholder="Enter a Noun..."
          onChange={(e) => setNoun(e.target.value)}
        />
        <input
          className=" text-gray-800 w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
          value={verb}
          placeholder="Enter a Verb..."
          onChange={(e) => setVerb(e.target.value)}
        />
        <button type="submit" className="bg-blue-500 text-white p-2 rounded">
          Generate Product Names
        </button>
      </form>
      <div className="whitespace-pre-wrap my-6">{completion}</div>
    </div>
  );
}

`

**Comment by thewebalchemist** [comment]
> Can someone please help me with the following, really confused:
> 
> `'use client'
> 
> import { useState } from 'react'; import { useCompletion } from 'ai/react';
> 
> export default function ProductNameGenerator() { const { completion, input, handleInputChange, handleSubmit } = useCompletion();
> 
> const [adjective, setAdjective] = useState(''); const [noun, setNoun] = useState(''); const [verb, setVerb] = useState('');
> 
> return (
> 
> 
> 
> 
> <input
> className=" text-gray-800 w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
> value={noun}
> placeholder="Enter a Noun..."
> onChange={(e) => setNoun(e.target.value)}
> />
> <input
> className=" text-gray-800 w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
> value={verb}
> placeholder="Enter a Verb..."
> onChange={(e) => setVerb(e.target.value)}
> />
> 
> Generate Product Names
> 
> 
> {completion}
> 
> 
> );
> }
> `

@MaxLeiter

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/support question resolved through an existing API, not a request to change SDK behavior, documentation, or examples.

### Evidence
- The reporter asks for help using multiple form inputs with `useCompletion` and does not describe an SDK failure.
- A maintainer explains that the existing `complete` helper supports this use case and provides working sample code plus documentation links.
