### ISSUE TITLE
useChat infinitely call api when use function call of openai

### ISSUE THREAD

**Issue by Crayon-ShinChan** [vercel/ai#609]
### Description

I use `useChat` in client side. when I didn't use function call, everything was fine. but when I used function call, it called the api again and again in a infinite loop.

### Code example

```ts
import OpenAI from "openai";
import { OpenAIStream, StreamingTextResponse } from "ai";
import type { ChatCompletionCreateParams } from "openai/resources/chat/completions";

// Optional, but recommended: run on the edge runtime.
// See https://vercel.com/docs/concepts/functions/edge-functions
export const runtime = "edge";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

const functions: ChatCompletionCreateParams.Function[] = [
  {
    name: "student_info",
    description: "Generate student information",
    parameters: {
      type: "object",
      properties: {
        name: {
          type: "string",
          description: "The name of the student",
        },
        GPA: {
          type: "integer",
          description: "The GPA of the student",
        },
      },
      required: ["name", "GPA"],
    },
  },
];

export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json();

  // Request the OpenAI API for the response based on the prompt
  const response = await openai.chat.completions.create({
    model: "gpt-3.5-turbo",
    stream: true,
    messages: messages,
    functions: functions,
    function_call: "auto",
  });

  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response);

  // Respond with the stream
  return new StreamingTextResponse(stream);
}
```

```ts
// client component
import { useChat } from 'ai/react';
 
export default function MyComponent() {
  const { messages, input, handleInputChange, handleSubmit } = useChat({
    api: '/api/chat',
  });
 
  return (
    <div>
      <ul>
        {messages.map((m, index) => (
          <li key={index}>
            {m.role === 'user' ? 'User: ' : 'AI: '}
            {m.function_call?.arguments}
          </li>
        ))}
      </ul>
 
      <form onSubmit={handleSubmit}>
        <label>
          Say something...
          <input value={input} onChange={handleInputChange} />
        </label>
        <button type="submit">Send</button>
      </form>
    </div>
  );
}
```

**Comment by odysseaspapadimas** [comment]
I would suggest going through the [docs](https://sdk.vercel.ai/docs/guides/providers/openai-functions) and properly setting up function calling

**Comment by aniravi24** [comment]
I'm noticing the same behavior when using the [vercel openai chatbot template](https://github.com/vercel-labs/ai-chatbot) and adding a `experimental_onFunctionCall` handler to the `useChat` hook.

When the handler returns a `ChatRequest`, it doesn't loop infinitely. If I don't return anything, it keeps looping.

**Comment by Crayon-ShinChan** [comment]
> I would suggest going through the [docs](https://sdk.vercel.ai/docs/guides/providers/openai-functions) and properly setting up function calling

Hi, do you mean add `experimental_onFunctionCall`? But I don't need the `experimental_onFunctionCall`, because I just want to extract the student name and gpa in the input message.

For example, if the `input` is "I'm a student named Joe with 3.7 GPA", then the `message` from useChat hook already returns the right answer

```
{
    "name": "Joe",
    "GPA": 3.7,
}
```

But it just infinite loop the process and message was streamed this json string again and again.

**Comment by Crayon-ShinChan** [comment]
I create functionCallHandler 
```
const functionCallHandler: FunctionCallHandler = async (
  chatMessages,
  functionCall
) => {
  if (functionCall.name === "student_info") {
    console.log("chatMessages: ", chatMessages);
    console.log("functionCall: ", functionCall);
  }
};
```
then this infinite loop problem solved. However, I think in my situation, I don't really need such a functionCallHandler because I don't call external API or something.

**Comment by ireneeromero** [comment]
Try using [experimental_onFunctionCall](https://sdk.vercel.ai/docs/guides/providers/openai-functions#handling-function-calls-on-the-server)

```
const stream = OpenAIStream(response, {
  experimental_onFunctionCall: async (
    { name, arguments: args },
    createFunctionCallMessages,
  ) => {
    // if you skip the function call and return nothing, the `function_call`
    // message will be sent to the client for it to handle
    if (name === 'get_current_weather') {
      // Call a weather API here
      const weatherData = {
        temperature: 20,
        unit: args.format === 'celsius' ? 'C' : 'F',
      };
 
      // `createFunctionCallMessages` constructs the relevant "assistant" and "function" messages for you
      const newMessages = createFunctionCallMessages(weatherData);
      return openai.chat.completions.create({
        messages: [...messages, ...newMessages],
        stream: true,
        model: 'gpt-3.5-turbo-0613',
        // see "Recursive Function Calls" below
        functions,
      });
    }
  },
});

**Comment by 0x-Legend** [comment]
Use the functionCallHandler (client side) and process your logic from the functionCall message inside it, But don't return a functionResponse like the docs tells you to. Typescript will throw errors, but you can ignore them considering your use case.

**Comment by lgrammel** [comment]
Please check out our new tool calling with AI SDK Core and useChat: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling#example-server-side-tool-execution-with-roundtrips

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **Medium**

### Rationale
The clarified request is for a new function-calling workflow that exposes extracted arguments without requiring a handler, rather than a confirmed failure of the documented setup.

### Evidence
- The loop occurs when OpenAI function calling is used without configuring a function-call handler.
- The reporter confirms that adding a client-side FunctionCallHandler stops the loop.
- The clarified request asks whether function calls can be supported without a handler when only extracting structured arguments.
- Comments direct the reporter to documented handler-based workflows and later tool-calling support.
