### ISSUE TITLE
For `OpenAIStream` > `onCompletion` or `onFinish` include OpenAI's metadata

### ISSUE THREAD

**Issue by davit-b** [vercel/ai#616]
### Feature Description

Not sure if https://github.com/vercel/ai/pull/425 covers this case or forsee's it.

In a non-stream API call to OpenAI's chat completion we receive two very important pieces of information
1. https://platform.openai.com/docs/api-reference/chat/object#choices-finish_reason
which when tracked can indicate abuse by user, or it can indicate mismanagement of tokens when value is either `length` or `content_filter`

2. https://platform.openai.com/docs/api-reference/chat/object#usage 
usage tells you if you're internal estimates of the token sizes (most likely calculated with tiktoken) are the same as what OpenAI receives

This information exists on the API calls, yet then signature for the `onCompletion` callback is `onCompletion: async (completion: string) => {...}` which only returns the completion string value.

**Comment by davit-b** [comment]
any thoughts? How do we detect if the stream's stop reason was "length". all I want is to offer to my users the ability to _continue_ a stream in event of a cutoff. 

I've implemented this feature as a hack by detecting if the stream doesn't end in punctuations `\.\\n\?\!` but it's janky. Would be easier to just have the dang "stop_reason" returned by the Stream to the client...

**Comment by gtokman** [comment]
I'm also trying to find a way to get the full response 
```
"{\"id\":\"chatcmpl-8CC61E5Jto5axQyjArXSVYyxxCNib\",\"object\":\"chat.completion.chunk\",\"created\":1697917125,\"model\":\"gpt-3.5-turbo-0613\",\"choices\":[{\"index\":0,\"delta\":{\"role\":\"assistant\",\"content\":\"\"},\"finish_reason\":null}]}"
```

Why is only the text part stripped out?

```
  const stream = OpenAIStream(response);
```

**Comment by peterdresslar** [comment]
Hello! The response from calling the upstream OpenAI library with `openai.chat.completions.create`, when called with `stream: true`, just contains text chunks (or, more specifically, `ChatCompletionChunk`s). 

The response does not contain completion data such as usage and finish_reason. See for instance [this closed issue from the OpenAI typescript library](https://github.com/openai/openai-node/issues/257) which describes this very question.

An possibly enlightening way to see the difference in return objects between streaming and not streaming: create a function that looks like:

```
export async function POST(req: Request) {
  const { messages } = await req.json();
  
  const isStreaming = false;
  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo-0613',
    stream: isStreaming,
    messages,
  });

  console.log(JSON.stringify(response));
  
  // do other stuff
  }
  ```
  
If you toggle `isStreaming` back and forth and view responses, you'll quickly see the difference. In fact, note that depending on the value of `isStreaming`, intellisense in your IDE will return different overloads from the Completion API when you request a definition of `openai.chat.completions.create`.

There are some interesting workaround approaches to consider, or you could consider a feature request or even a PR for the OpenAI typescript code.

**Comment by peterdresslar** [comment]
In case it helps, there is an example workaround to access the chunk data in the discussions here: https://github.com/vercel/ai/discussions/663

**Comment by davit-b** [comment]
@peterdresslar That's interesting. I didn't learn about `tee` until your example. I'm debating whether I should implement the same hack our wait until AIStream offers a more elegant solution. I have a production apps, I have to experiment with it first.

Right now I'm using the `message.content.match(/(\?|\.|\!)$/g)` to prompt to the user to ask the llm the "continue" the response. It's dumb but works for 90%+ of the cases. I notice that the LLM doesn't respect response_tokens well when playing with sizes below 400 tokens. Still it only happens 10% of the time.

Hmm...actually I may just implement the `tee` solution server-side just to emit metrics based on the `finish_reason` rather than returning it to the client.

**Comment by jonasb** [comment]
Digging into the underlaying OpenAI APi, they appear to not include `usage` for streaming completions. You need to count the tokens yourself, unfortunately.

**Comment by SamStenner** [comment]
> Digging into the underlaying OpenAI APi, they appear to not include `usage` for streaming completions. You need to count the tokens yourself, unfortunately.

I believe that using `openai.beta.chat.completions.stream` returns an object with a `totalUsage` property on it now. [Source](https://github.com/openai/openai-node/blob/a048174c0e53269a01993a573a10f96c4c9ec79e/src/lib/AbstractChatCompletionRunner.ts#L300).

**Comment by marclelamy** [comment]
> Digging into the underlaying OpenAI APi, they appear to not include `usage` for streaming completions. You need to count the tokens yourself, unfortunately.

Yes but other like Perplexity do. Many API providers use the OpenAI package as it's easy to use and only requires a change in the base URL.

**Comment by dion-blutui** [comment]
OpenAI provides usage metadata on streaming now https://github.com/openai/openai-node/compare/v4.41.1...v4.42.0

**Comment by lgrammel** [comment]
The AI SDK 3.1 API provides token usage and finish reason.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is an API capability expansion to expose provider metadata, not a failure of documented existing behavior.

### Evidence
- The request asks for `OpenAIStream` callbacks to expose finish reason and token usage metadata in addition to completion text.
- Users describe workarounds for accessing `finish_reason`, indicating the requested metadata was not part of the existing callback API.
- A maintainer states that AI SDK 3.1 later added token usage and finish reason support.
