### ISSUE TITLE
onFinal only contains completion if onCompletion is defined

### ISSUE THREAD

**Issue by jpulec** [vercel/ai#621]
### Description

Best I can tell, if the `onFinal()` callback handler will only actually have the aggregated completion if you've also defined `onCompletion()`. Otherwise, messages don't get aggregated in `createCallbackTransformer` and the empty string is passed to `onFinal()`.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This describes incorrect callback behavior: `onFinal()` should receive the aggregated completion independently, but currently depends on another optional callback being defined.

### Evidence
- The report states that `onFinal()` receives an empty string unless `onCompletion()` is also defined.
- It attributes the failure to `createCallbackTransformer` not aggregating messages when `onCompletion()` is absent.
