### ISSUE TITLE
replicate-stream interface mismatch from latest Replicate SDK

### ISSUE THREAD

**Issue by peterdresslar** [vercel/ai#630]
### Description

Calls to create ReplicateStream from a Prediction generated using a [Replicate create method]() no longer pass type safety--at least using the latest Replicate library. At some point in the past several weeks, `updated_at` became optional on the Replicate interface (which, sure, makes sense.) The copy of the interface in `streams/replicate-stream` is thus out of sync.

### Additional context

`replicate` 0.20.1 or later

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete compatibility regression in existing behavior: current Replicate SDK prediction objects fail the AI SDK's expected type interface.

### Evidence
- `ReplicateStream` no longer accepts a `Prediction` from Replicate SDK 0.20.1 or later under TypeScript type checking.
- The issue identifies an interface mismatch: Replicate made `updated_at` optional, while the copied interface in `streams/replicate-stream` remains out of sync.
