### ISSUE TITLE
Allow OpenAI function call without following reponse

### ISSUE THREAD

**Issue by dnsosebee** [vercel/ai#645]
### Feature Description

For my React application I need to use OpenAI's function calling feature to produce structured output that will then stream to the frontend as generative UI (and this seems like a use case that's getting more and more popular).

It seems that this is not supported: currently, every function call is assumed to be followed by an additional response from the chat completion. So I get stuck in an infinite loop where the function call is neither handled on the frontend nor backend and gets passed back and forth, because of this line here: https://github.com/vercel/ai/blob/703e9ec55832c6da6fd5f253ee8331f4b5510188/packages/core/react/use-chat.ts#L432

I wonder if we could add the ability to terminate the request loop on the frontend?

### Use Case

For streaming structured output to the frontend.

**Comment by 0x-Legend** [comment]
Are you handling function calls from the client or the server?

Based on your use case, I'm assuming client. In the functionCallHandler, just don't return a functionResponse and you should be good to go. Typescript will throw an error since it expects a functionResponse to be returned, but you can ignore that considering your use case.

**Comment by dnsosebee** [comment]
I'm handling on client.

Here's my client-side code, which is the same as the example repo except I removed the content from the functionCallHandler and replaced with some log statements:

```typescript
"use client";

import { FunctionCallHandler } from "ai";
import { Message, useChat } from "ai/react";

export default function Chat() {
  const functionCallHandler: FunctionCallHandler = async (chatMessages, functionCall) => {
    console.log("\n\n\n");
    console.log("functionCall", functionCall);
    console.log("chatMessages", chatMessages);
  };

  const { messages, input, handleInputChange, handleSubmit, data } = useChat({
    api: "/api/chat-with-functions",
    experimental_onFunctionCall: functionCallHandler,
  });

  // Generate a map of message role to text color
  const roleToColorMap: Record<Message["role"], string> = {
    system: "red",
    user: "black",
    function: "blue",
    assistant: "green",
  };

  console.log("\n\n\n");
  console.log("data", data);
  console.log("messages", messages);

  return (
    <div className="flex flex-col w-full max-w-md py-24 mx-auto stretch">
      {messages.length > 0
        ? messages.map((m: Message) => (
            <div
              key={m.id}
              className="whitespace-pre-wrap"
              style={{ color: roleToColorMap[m.role] }}
            >
              <strong>{`${m.role}: `}</strong>
              {m.content || JSON.stringify(m.function_call)}
              <br />
              <br />
            </div>
          ))
        : null}
      <div id="chart-goes-here"></div>
      <form onSubmit={handleSubmit}>
        <input
          className="fixed bottom-0 w-full max-w-md p-2 mb-8 border border-gray-300 rounded shadow-xl"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  );
}
```

When I run this, the handler eventually gets called and logs, but that ends up triggering another call to the API, and so on and so on (the handler keeps being called without my intervention, and the UI never updates from the original asked question).

And from poking around, my guess is that the line I referenced above is the culprit -- as long as there is a functionCallHandler on the client, it assumes that there will be a further chat completion done from the server, regardless whether a functionResponse was returned. Let me know if I'm mistaken and thanks so much for the help.

**Comment by dnsosebee** [comment]
I think we posted our comments at the same time :) Please see my latest comment on that line of code.

Blank return statement is equivalent to what I have since the function returns `undefined` regardless.

**Comment by 0x-Legend** [comment]
Oh, now I see what you mean! 

I'm not sure how my implementation didn't send a follow up response.

But thanks to your merge, I can now remove a custom type lol.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
This is a concrete control-flow defect: the SDK fails to terminate the request loop when no function response is returned, causing an infinite sequence of follow-up calls.

### Evidence
- Returning undefined from the client-side function call handler still triggers repeated API requests instead of terminating processing.
- The reported `break` exits only the message iteration `for` loop, despite the code comment indicating that the request loop should stop.
- A later comment indicates the reporter's merged change resolved the behavior.
