### ISSUE TITLE
Expand ai/prompts to Support Multiple Providers and Prompt Engineering

### ISSUE THREAD

**Issue by peterdresslar** [vercel/ai#654]
### Feature Description

Make it possible to build and manipulate prompts in a fashion that matches the otherwise clean, concise routes, with an approach that understands and uses the `Message` structure that connects the server and client. Something like:

```typescript
const { messages } = await req.json();
prompt = buildPrompt(messages); 
const response = await myprovider.chat.create(prompt.toPrompt());
```

### Use Case

Any situation where the `{messages}` and other prompting needs to be manipulated could use some helper functionality. Note especially programmatic prompting.

**Comment by MaxLeiter** [comment]
Thanks @peterdresslar. We've had a busy week with next conf but @shuding and I will review this next week!

**Comment by lgrammel** [comment]
`ai/prompts` is deprecated with the new architecture introduced in 3.1

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new prompt-building and provider-agnostic capabilities. The later deprecation makes the proposal obsolete but does not change its nature as a feature request.

### Evidence
- The issue requests helper functionality to build and manipulate prompts using the SDK's Message structure and multiple providers.
- No existing documented behavior is reported as broken.
- A maintainer later notes that ai/prompts was deprecated in the architecture introduced in version 3.1.
