### ISSUE TITLE
experimental_StreamingReactResponse documentation + example

### ISSUE THREAD

**Issue by odysseaspapadimas** [vercel/ai#700]
### Feature Description

Documentation and an example for the new feature introduced in Next.js Conf

### Use Case

There's currently no documentation other than the code shown on Jarded's keynote which appears to be different from what the SDK seems to actually use

**Comment by clodal** [comment]
For anyone looking to get an idea of how this might look, the docs on [`experimental_StreamData`](https://sdk.vercel.ai/docs/api-reference/stream-data) would probably be the next best thing for now.

**Comment by carloslfu** [comment]
@odysseaspapadimas @clodal. By looking through the code, I found some API docs here, they are not yet public but can help: https://github.com/vercel/ai/blob/a1767613140525b02fab889355d4d0f21ac52ec7/docs/pages/docs/api-reference/streaming-react-response.md.

**Comment by MaxLeiter** [comment]
We have some documentation here, and will be improving it in the near future: https://sdk.vercel.ai/docs/api-reference/streaming-react-response

**Comment by odysseaspapadimas** [comment]
Also this [example](https://github.com/vercel/ai/tree/main/examples/next-openai/app/stream-react-response)

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The primary request is to document a newly introduced API; although it also requests an example, no product behavior change or failure is described.

### Evidence
- The request explicitly asks for documentation and an example for `experimental_StreamingReactResponse`.
- The reported gap is a lack of public guidance, not broken SDK behavior.
- Comments link to the API reference documentation and an existing `stream-react-response` example.
