### ISSUE TITLE
Type Error related to new openAI announcement

### ISSUE THREAD

**Issue by nabilfatih** [vercel/ai#713]
### Description

I use this onFunctionCall API a lot and it was working fine, but when I deploy it again on Vercel, it goes error (without any changes in API). I think it is because the new openAI released? https://openai.com/blog/new-models-and-developer-products-announced-at-devday

### Code example

```
Type error: Argument of type 'Stream<ChatCompletionChunk>' is not assignable to parameter of type 'Response \| AsyncIterableOpenAIStreamReturnTypes'.
Type 'Stream<ChatCompletionChunk>' is not assignable to type 'AsyncIterable<Completion>'.
The types returned by '[Symbol.asyncIterator]().next(...)' are incompatible between these types.
Type 'Promise<IteratorResult<ChatCompletionChunk, any>>' is not assignable to type 'Promise<IteratorResult<Completion, any>>'.
Type 'IteratorResult<ChatCompletionChunk, any>' is not assignable to type 'IteratorResult<Completion, any>'.
Type 'IteratorYieldResult<ChatCompletionChunk>' is not assignable to type 'IteratorResult<Completion, any>'.
Type 'IteratorYieldResult<ChatCompletionChunk>' is not assignable to type 'IteratorYieldResult<Completion>'.
Type 'ChatCompletionChunk' is not assignable to type 'Completion'.

const stream = OpenAIStream(response, {
experimental_onFunctionCall: async (
{ name, arguments: args },
createFunctionCallMessages
```

**Comment by tmyracle** [comment]
I also just ran into this with a fresh install of openai (4.16.1) and ai (2.2.20) trying to follow the docs:

`  const response = await openai.chat.completions.create({
    model: "gpt-3.5-turbo-16k",
    stream: true,
    temperature: 0.0,
    messages: [
      {role: "system", "content": ""},
      {role: "user", "content": prompt}
    ]
  });

  const stream = OpenAIStream(response);`

Same type error as above with response.

**Comment by lhr0909** [comment]
I was able to get it compiled by forcing the response type to `AsyncIterable<any>`. It works for me as-is. I haven't gone in to change our `function_call` into `tool_call` yet, that is a bit too much of a change.

```typescript
  const response = await openai.chat.completions.create({
    model: "gpt-3.5-turbo-16k",
    stream: true,
    temperature: 0.0,
    messages: [
      {role: "system", "content": "You are a helpful yada yada"},
      {role: "user", "content": prompt}
    ]
  });

  const stream = OpenAIStream(response as AsyncIterable<any>);
```

**Comment by nabilfatih** [comment]
yeah, this SDK really needs changes to support the new OpenAI released (not only this type error)

**Comment by xeladotbe** [comment]
you can simply call `.asResponse()` on the return value of openai.chat.completions.create

```
  const chatCompletion = await openai.chat.completions
    .create({ ... })
    .asResponse()

  const stream = OpenAIStream(chatCompletion)
```

**Comment by ChristopherTrimboli** [comment]
> you can simply call `.asResponse()` on the return value of openai.chat.completions.create
> 
> ```
>   const chatCompletion = await openai.chat.completions
>     .create({ ... })
>     .asResponse()
> 
>   const stream = OpenAIStream(chatCompletion)
> ```

this worked for me as good fix without `any` hacks, not sure if need new docs, or supposed to do on own now.

**Comment by sachinsom93** [comment]
> you can simply call `.asResponse()` on the return value of openai.chat.completions.create
> 
> ```
>   const chatCompletion = await openai.chat.completions
>     .create({ ... })
>     .asResponse()
> 
>   const stream = OpenAIStream(chatCompletion)
> ```

I tried the same thing but got the below error.
![image](https://github.com/vercel/ai/assets/64790109/3d4699fa-f42a-433f-ad57-6d8eac4c1661)

**Comment by nabilfatih** [comment]
> you can simply call `.asResponse()` on the return value of openai.chat.completions.create
> 
> ```
>   const chatCompletion = await openai.chat.completions
>     .create({ ... })
>     .asResponse()
> 
>   const stream = OpenAIStream(chatCompletion)
> ```

thanks for the advice!.. yeah it is working fine, but for `experimental_onFunctionCall` still get the type error

**Comment by xeladotbe** [comment]
> > you can simply call `.asResponse()` on the return value of openai.chat.completions.create
> > ```
> >   const chatCompletion = await openai.chat.completions
> >     .create({ ... })
> >     .asResponse()
> > 
> >   const stream = OpenAIStream(chatCompletion)
> > ```
> 
> I tried the same thing but got the below error. ![image](https://user-images.githubusercontent.com/64790109/281017804-3d4699fa-f42a-433f-ad57-6d8eac4c1661.png)
> 
> Error:
> 
> ```
> CHAT ERROR:  TypeError: responseBodyStream.pipeThrough is not a function
>     at AIStream (webpack-internal:///(sc_server)/./node_modules/ai/dist/index.mjs:113:31)
>     at OpenAIStream (webpack-internal:///(sc_server)/./node_modules/ai/dist/index.mjs:317:18)
>     at POST (webpack-internal:///(sc_server)/./app/api/chat/route.ts:37:78)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:242:37)
> ```
> 
> Here is my code:
> 
> ```
>  const response = await openai.chat.completions.create({
>       messages: messages,
>       model: "gpt-3.5-turbo-0301",
>       max_tokens: 50,
>       stream: true,
>       temperature: 0.2,
>     }).asResponse();
>     const openAIStream = OpenAIStream(response);
>     return new StreamingTextResponse(openAIStream);
> ```

I only get this error message when I use the rewrites within the Next.js config

**Comment by sachinsom93** [comment]
> > > you can simply call `.asResponse()` on the return value of openai.chat.completions.create
> > > ```
> > >   const chatCompletion = await openai.chat.completions
> > >     .create({ ... })
> > >     .asResponse()
> > > 
> > >   const stream = OpenAIStream(chatCompletion)
> > > ```
> > 
> > 
> > I tried the same thing but got the below error. ![image](https://user-images.githubusercontent.com/64790109/281017804-3d4699fa-f42a-433f-ad57-6d8eac4c1661.png)
> > Error:
> > ```
> > CHAT ERROR:  TypeError: responseBodyStream.pipeThrough is not a function
> >     at AIStream (webpack-internal:///(sc_server)/./node_modules/ai/dist/index.mjs:113:31)
> >     at OpenAIStream (webpack-internal:///(sc_server)/./node_modules/ai/dist/index.mjs:317:18)
> >     at POST (webpack-internal:///(sc_server)/./app/api/chat/route.ts:37:78)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:242:37)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is my code:
> > ```
> >  const response = await openai.chat.completions.create({
> >       messages: messages,
> >       model: "gpt-3.5-turbo-0301",
> >       max_tokens: 50,
> >       stream: true,
> >       temperature: 0.2,
> >     }).asResponse();
> >     const openAIStream = OpenAIStream(response);
> >     return new StreamingTextResponse(openAIStream);
> > ```
> 
> @sachinsom93 I only get this error message when I use the rewrites within the Next.js configuration.
> 
> Update: I also get this error message when I use node-fetch

@xeladotbe Thanks for your response.

Yes, I am using rewrites within the Next.js configuration.

After changing the runtime to `edge`, I am no longer getting the error.
```
export const runtime = "edge";
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports concrete type incompatibilities and a runtime exception in existing AI SDK streaming behavior after an OpenAI SDK change, rather than merely requesting new support or documentation.

### Evidence
- Previously working OpenAIStream usage no longer type-checks with OpenAI SDK 4.16.1 and AI SDK 2.2.20 because Stream<ChatCompletionChunk> is rejected.
- Another user reproduced the same type error while following the documented usage.
- Casting to AsyncIterable<any> or converting with .asResponse() was reported as a workaround, but experimental_onFunctionCall still produced a type error.
- A related runtime path also threw `responseBodyStream.pipeThrough is not a function` in a Node/Next.js configuration.
