### ISSUE TITLE
Support for OpenAI Assistants

### ISSUE THREAD

**Issue by edouard-blocktool** [vercel/ai#721]
### Feature Description

The new Assistants API from OpenAI unlocks the following:
1. Not having to manage the thread history busting the context window
2. Access to Code Interpreter & document embedding

It'd be great for Vercel AI client to leverage this API through Vercel AI and still benefit from the React useChat, useCompletion constructs.

### Additional context

See https://platform.openai.com/docs/assistants/overview

**Comment by edouard-blocktool** [comment]
It's worth noting that OpenAI Assitants API does not support streaming yet. But they're planning to add it.

**Comment by SamiHK** [comment]
With or without streaming, we need it. 
@jw-vercel @aaronbrown-vercel please expedite this.

**Comment by dosstx** [comment]
I saw on X that the CEO of Vercel mentioned they are working on this.

**Comment by MaxLeiter** [comment]
We'll likely formally request comments and feedback on our work soon, but for now you can follow @lgrammel's great work here: #728. If anything jumps out to you as a problem (or a great addition!) please reply there so we can track it.

**Comment by MaxLeiter** [comment]
We've just released 2.2.24 with the first release of our experimental assistant APIs. Please give it a try and provide feedback! Proper documentation will be coming soon, but in the meantime you can refer to this doc and the example in the repo: https://github.com/vercel/ai/blob/main/examples/next-openai/app/api/assistant/assistant-setup.md

**Comment by harrywang** [comment]
@MaxLeiter any pointer on how to upload a file to the assistant?

**Comment by taylor-lindores-reeves** [comment]
> @MaxLeiter any pointer on how to upload a file to the assistant?

I did it here; https://youtu.be/ATf2GmkMPLk?si=-rouWrn8sruC2W1v

Although this is somewhat outdated now, but the concept of file upload using this API applies.

**Comment by ekimcem** [comment]
Can we also get the images generated by code_int. tool ?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for new OpenAI Assistants support and related API capabilities. The only apparent body-handling problem was retracted as incorrect usage, so it does not establish a bug.

### Evidence
- The issue requests integration with OpenAI's Assistants API while retaining React hooks such as useChat and useCompletion.
- A maintainer announced an initial experimental Assistants API release in version 2.2.24.
- Follow-up comments request additional capabilities such as file uploads, streaming, and access to Code Interpreter-generated images; no confirmed existing behavior failure is reported.
