### ISSUE TITLE
React: `onFinish` callback called before `experimental_StreamData` is defined

### ISSUE THREAD

**Issue by thomas-tosch** [vercel/ai#745]
### Description

How to reproduce: 
```
const { messages, data } = useChat({
        api: aiAssistantUrl,
        initialMessages: [],
        onFinish: (message) => {
        	console.log(data);
        }
    });
```
When the onFinish hook is called it outputs
`undefined`

Second call will output the data from the previous message.

Expected behaviour:
IMO it should trigger onFinish once the stream data was defined as well as this is more consistant.
At the moment I made a workaround using useEffect with data and isLoading as deps.

### Additional context

Library current version: 2.2.20
React: 18.2

**Comment by lgrammel** [comment]
@thomas-tosch what are you using to send the data (route)? I've tried reproducing it with the `next-openai` example on main, but for both normal mode and experimental streaming `onFinish` was called as expected.

**Comment by thomas-tosch** [comment]
Hi @lgrammel, thanks for answering to my issue.

To add a bit of context, I'm using `LangchainStream` from `ai` in order to get a `stream`.

I've been setting my data values after the chain call was fufilled.
`sourceDocument` is not returned in the onFinish hook of the `LangchainStream` parameters, that's why I went this way to set it.
`chain
        .call(
            {
                question: messages[messages.length - 1].content,
                chat_history: chatHistory,
            },
            {
                callbacks: [handler, handlers],
            },
        )
        .then((result) => {
            const metadata = result['sourceDocuments']?.map((item) => item.metadata);
            extraFieldData.append(metadata);
            extraFieldData.close();
        })`

**Comment by lgrammel** [comment]
With this code, it worked for me:

Server:
```ts
export async function POST(req: Request) {
  const data = new experimental_StreamData();

  const model = new ChatOpenAI({ streaming: true });

  const stream = await PromptTemplate.fromTemplate('{input}')
    .pipe(model)
    .pipe(new BytesOutputParser())
    .stream(
      { input: 'Hello' },
      {
        callbacks: [
          {
            handleChainEnd(outputs, runId, parentRunId) {
              // check that main chain (without parent) is finished:
              if (parentRunId == null) {
                data.append({ t1: 'v1' });
                data.close();
              }
            },
          },
        ],
      },
    );

  return new StreamingTextResponse(
    stream.pipeThrough(createStreamDataTransformer(true)),
    {},
    data,
  );
}
```

Client:
```ts
export default function Chat() {
  const { messages, input, handleInputChange, handleSubmit } = useChat({
    api: 'http://localhost:3000/api/stream-data',
    onFinish: data => {
      console.log('Chat finished with data:', data);
    },
  });

  return (
    <div className="mx-auto w-full max-w-md py-24 flex flex-col stretch">
      {messages.length > 0
        ? messages.map(m => (
            <div key={m.id} className="whitespace-pre-wrap">
              {m.role === 'user' ? 'User: ' : 'AI: '}
              {m.content}
            </div>
          ))
        : null}

      <form onSubmit={handleSubmit}>
        <input
          className="fixed w-full max-w-md bottom-0 border border-gray-300 rounded mb-8 shadow-xl p-2"
          value={input}
          placeholder="Say something..."
          onChange={handleInputChange}
        />
      </form>
    </div>
  );
}
```

You can find the full example code here: https://github.com/lgrammel/vercel-ai/tree/lg/issue-745/examples/next-langchain/app/stream-data

Example console log in browser:
![image](https://github.com/vercel/ai/assets/205036/f88a7d02-a227-456c-8266-4bbe2e26a08f)

**Comment by thomas-tosch** [comment]
Thanks for your help there.

Here's part of our server implementation:
```
      streamingLLM =  new ChatOpenAI({
                  modelName: 'gpt-3.5-turbo',
                  streaming,
                  openAIApiKey: this.apiKey,
                  callbacks,
      });

    const chain = ConversationalRetrievalQAChain.fromLLM(
        streamingLLM,
        new FrontifyAppServerRetrieverFactory(config).build(),
        {
            returnSourceDocuments: true,
            verbose: false,
            qaChainOptions: {
                type: 'stuff',
                prompt: CHAT_PROMPT,
            },
            questionGeneratorChainOptions: {
                llm: nonStreamingLLM,
                template: QUESTION_GENERATOR_PROMPT_LITERAL,
            },
        },
    );
```

I tried doing the following:

```
chain
        .call(
            {
                question: messages[messages.length - 1].content,
                chat_history: chatHistory,
            },
            {
                callbacks: [
                    handler,
                    handlers,
                    {
                        handleChainEnd(outputs: ChainValues) {
                            console.log(outputs);
                            const metadata = outputs.sourceDocuments?.map((item) => item.metadata);
                            extraFieldData.append(metadata);
						   extraFieldData.close();
                        },
                    },
                ],
            },
        )
```

Without success.

Your implementation involves using `fromTemplate` which we didn't do.

**Comment by lgrammel** [comment]
@thomas-tosch I found that `handleChainEnd` is called for sub-chains as well. That could explain why you see several calls. Here is the part of my solution that's relevant:

```ts
handleChainEnd(outputs, runId, parentRunId) {
  // check that main chain (without parent) is finished:
  if (parentRunId == null) {
    data.append({ t1: 'v1' });
    data.close();
  }
},
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete timing/stale-data failure in existing `useChat` behavior. Although the discussion suggests the server-side LangChain stream lifecycle may contribute and no minimal reproduction confirmed an SDK defect, the reported symptom is framed as broken current behavior.

### Evidence
- `useChat`'s `onFinish` callback observes `data` as `undefined` on the first request and as the previous request's data on the next call.
- The reporter expects `onFinish` to run only after `experimental_StreamData` has been received and currently uses a `useEffect` workaround.
- A maintainer could not reproduce the behavior with the standard example and suggested changing the LangChain stream-closing logic, but the reporter said the proposed implementation did not resolve it.
