### ISSUE TITLE
"Promise<ReadableStream<any>>" is not a valid POST return type

### ISSUE THREAD

**Issue by suzushi-tw** [vercel/ai#839]
### Description

Hi, I am new to this. So everything works on local, and I can get response from chatgpt as well, however it fails to compile.  My code in route.ts are the same as in example. And the following is the error in vercel log:

<html>
<body>

src/app/chat/route.ts
--
11:28:56.324 | Type error: Route "src/app/chat/route.ts" has an invalid export:
11:28:56.324 | "Promise<ReadableStream<any>>" is not a valid POST return type:
11:28:56.325 | Expected "void \| Response \| Promise<void \| Response>", got "Promise<ReadableStream<any>>".
11:28:56.325 | Expected "Promise<void \| Response>", got "Promise<ReadableStream<any>>".
11:28:56.325 | Expected "void \| Response", got "ReadableStream<any>".
11:28:56.325 |  
11:28:56.450 | Error: Command "npm run build" exited with 1

</body>
</html>

### Code example

import OpenAI from 'openai';
import { OpenAIStream, StreamingTextResponse } from 'ai';
 
// Create an OpenAI API client (that's edge friendly!)
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});
 
// IMPORTANT! Set the runtime to edge
export const runtime = 'edge';
 
export async function POST(req: Request) {
  const { messages } = await req.json();
 
  // Ask OpenAI for a streaming chat completion given the prompt
  const response = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    stream: true,
    messages,
  });
 
  // Convert the response into a friendly text-stream
  const stream = OpenAIStream(response);
  // Respond with the stream
  return new StreamingTextResponse(stream);
}

### Additional context

While running npm run build on local, it returns the following: 
.next/types/app/chat/route.ts:176:7
Type error: Type '{ __tag__: "POST"; __return_type__: Promise<ReadableStream<any>>; }' does not satisfy the constraint '{ __tag__: "POST"; __return_type__: void | Response | Promise<void | Response>; }'.
  Types of property '__return_type__' are incompatible.
    Type 'Promise<ReadableStream<any>>' is not assignable to type 'void | Response | Promise<void | Response>'.
      Type 'Promise<ReadableStream<any>>' is not assignable to type 'Promise<void | Response>'.
        Type 'ReadableStream<any>' is not assignable to type 'void | Response'.

  174 |         __return_type__: Response | void | never | Promise<Response | void | never>
  175 |       },
> 176 |       {
      |       ^
  177 |         __tag__: 'POST',
  178 |         __return_type__: ReturnType<MaybeField<TEntry, 'POST'>>
  179 |       },
   Linting and checking validity of types  .

**Comment by suzushi-tw** [comment]
> What versions of Next.js, `ai` and node.js are you using?

Hi, its latest, 2.2.14, and v18.17 for nodejs

**Comment by cnoori** [comment]
Having the same issue..I'm on 

"typescript": "5.2.2",
"next": "^14.0.3",

**Comment by cnoori** [comment]
Was able to resolve it by updating my return statements 

from:  return  { message: 'Failed to create' };

To: return NextResponse.json({ error: 'Failed to create' }, { status: 400 });

Im able to compile my code now
https://nextjs.org/docs/app/api-reference/functions/next-response

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This reports a concrete build-time type failure when using the AI SDK streaming response API, so it is best classified as a bug. The precise cause is not fully established, and one commenter resolved a related case by fixing a separate non-Response return path.

### Evidence
- The documented-style route returning `new StreamingTextResponse(stream)` works locally but fails during `npm run build`.
- Next.js reports the POST handler as returning `Promise<ReadableStream<any>>` instead of the required `Response` type.
- Another user reproduced a similar compilation failure with Next.js 14.0.3 and TypeScript 5.2.2.
