### ISSUE TITLE
Vercel production: "Error: Chroma getOrCreateCollection error: Error: Unexpected token 'D', \"Direct IP \"... is not valid JSON"

### ISSUE THREAD

**Issue by moreno1123** [vercel/ai#843]
### Description

"chromadb": "1.6.1",
"langchain": "0.0.200",
"next": "13.5.4",

When I'm querying Chroma on localhost there is no issue, everything works like a charm but on production build on Vercel it does not work. Chroma is hosted on aws ec2 in both scenarios.
I'm getting following error only on Vercel (with the same code on localhost and production):

```json
"error": "Error: Chroma getOrCreateCollection error: Error: Unexpected token 'D', \"Direct IP \"... is not valid JSON"
```

It's edge runtime what's causing the error.
Locally everything seems to work fine but on production build it's not working with already mentioned error.

I've built a recreation of the bug -> https://github.com/moreno1123/chat_bug
Actual prod build -> https://chat-bug.vercel.app/

Maybe this is Vercel AI SDK issues, idk, I will open the issue there also.

### Code example

Following code is from the project, not from the bug recreation repo.

Code for querying (working only on localhost):
```typescript
export const runtime = 'edge';

export async function POST(req: Request){
  try {
    const body = await req.json()
    const messages = body.messages ?? [];
    const question = messages[messages.length - 1].content
    const { history, collectionId } = body
    console.log(collectionId)

    const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

    const { stream, handlers } = LangChainStream();
    
    const vectorStore = await Chroma.fromExistingCollection(
      new OpenAIEmbeddings(),
      {
        url: env.CHROMA_DB_SERVER,
        collectionName: collectionId,
      },
    );

    const chain = makeChain(vectorStore);

    chain.call({
      question: sanitizedQuestion,
      chat_history: history
    }, [handlers]);

    return new StreamingTextResponse(stream);
  } catch (error) {
    return NextResponse.json({message: "Internal error", error: error.toString()}, {status: 500})
  }
}
```

Code for creating the collection (working both on localhost and prod):
```typescript

export async function POST(req: Request){
  try {
    const body = await req.formData()
    const file:any = body.get('file')
    const fileName:string = file.name
    const userId:any = body.get('userId')

    const collectionName = await prisma.collection.create({
      data: {
        fileName: fileName,
        userId: userId,
      }
    })

    const loader = new WebPDFLoader(file);
    const docs = await loader.load();

    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 2000,
      chunkOverlap: 500,
    });

    const documents = await splitter.splitDocuments(docs);
    
    const vectorStore = await Chroma.fromDocuments(
      documents,
      new OpenAIEmbeddings(),
      { 
        url: env.CHROMA_DB_SERVER,
        collectionName: collectionName.id
      }
    );

    return NextResponse.json({message: "Embbed successfull!", collectionName: collectionName.id}, {status:200})
  } catch (error) {
    return NextResponse.json({message: "Internal error"}, {status: 500})
  }
}
```

Also I can confirm that the creation of collection is working on Vercel. As seen in the following example:
```json
{
    "message": "Embbed successfull!",
    "collectionName": "bc40a3bb-86c6-4a89-804d-df5c58b51062"
}
```
![image](https://github.com/vercel/ai/assets/83433432/9c994fae-28b8-4969-a538-1c9cd50c8588)

### Additional context

I've also opened an issue on langchain repo but I guess this is Vercel issue...
https://github.com/langchain-ai/langchainjs/issues/3521

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is an integration/support report involving Chroma and LangChain rather than a demonstrated defect or requested change in the Vercel AI SDK.

### Evidence
- The error occurs during `Chroma.fromExistingCollection`, before the AI SDK constructs or returns `StreamingTextResponse`.
- The maintainer states that the failing behavior is between Chroma and LangChain and does not appear related to the AI SDK.
- The reporter also opened the issue with LangChain and was unsure which project was responsible.
