### ISSUE TITLE
useChat body payload invalid

### ISSUE THREAD

**Issue by Haiananan** [vercel/ai#882]
### Description

useChat body payload cant pass the object into api's body

### Code example

```js 
const {
    messages,
    isLoading,
    error,
  } = useChat({
    initialMessages: [
      {
        role: 'assistant',
        content: 'Hi, I am your personal assistant. How can I help you?',
        id: nanoid(),
      },
    ],
    id,
    body: {
      model: 'gpt-3.5-turbo-1106',
      test: 'ok',
    },
  })
```
Here is my api
```ts
import OpenAI from 'openai'
import { OpenAIStream, StreamingTextResponse } from 'ai'
import { NextResponse } from 'next/server'

// Optional, but recommended: run on the edge runtime.
// See https://vercel.com/docs/concepts/functions/edge-functions
export const runtime = 'edge'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
  baseURL: process.env.OPENAI_BASE_URL!,
})

export async function POST(req: Request) {
  try {
    const body = await req.json()

    console.log(body)
    // { messages: [ { role: 'user', content: 'xxx' } ] }

    const { messages, model, memoryMessagesNumber = 4 } = body

    const messagesToSend = [
      {
        role: 'system',
        content: `You are ${model}, an OPENAI AI assistant, reply in markdown.Today is ${new Date().toLocaleDateString()}.`,
      },
      ...messages.splice(-memoryMessagesNumber),
    ]

    if (process.env.NODE_ENV === 'development')
      console.log({ model, memoryMessagesNumber, messagesToSend })
    // model is undefined

    // Request the OpenAI API for the response based on the prompt
    const response = await openai.chat.completions.create({
      model,
      stream: true,
      messages: messagesToSend,
    })

    // Convert the response into a friendly text-stream
    const stream = OpenAIStream(response)

    // Respond with the stream
    return new StreamingTextResponse(stream)
  }
  catch (error) {
    // Check if the error is an APIError
    if (error instanceof OpenAI.APIError) {
      const { name, status, headers, message } = error

      return NextResponse.json({ name, status, headers, message }, { status })
    }
    else {
      throw error
    }
  }
}
```
理论上来讲 我可以在body中获取到model字段，但我打印之后始终是undefined，仅有messages和最新一条消息

### Additional context

{
  "name": "aice",
  "type": "module",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "node": "18.x",
    "yarn": "1.x",
    "pnpm": "8.x"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "prisma generate",
    "format": "prettier --check --ignore-path .gitignore .",
    "format:fix": "prettier --write --ignore-path .gitignore ."
  },
  "dependencies": {
    "@chakra-ui/color-mode": "^2.2.0",
    "@chakra-ui/next-js": "^2.1.4",
    "@chakra-ui/react": "^2.7.1",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@headlessui/react": "^1.7.15",
    "@headlessui/tailwindcss": "^0.1.3",
    "@prisma/client": "5.7.1",
    "@rvxlab/tailwind-plugin-ios-full-height": "^1.1.0",
    "@splidejs/react-splide": "^0.7.12",
    "@tailwindcss/typography": "^0.5.10",
    "@tanstack/react-query": "^5.14.2",
    "@types/node": "20.3.0",
    "@types/react": "18.2.11",
    "@types/react-copy-to-clipboard": "^5.0.4",
    "@types/react-datepicker": "^4.11.2",
    "@types/react-dom": "18.2.4",
    "@types/react-input-mask": "^3.0.2",
    "@types/react-syntax-highlighter": "^15.5.7",
    "add": "^2.0.6",
    "ai": "^2.2.30",
    "autoprefixer": "10.4.14",
    "eslint-config-next": "13.4.5",
    "framer-motion": "^10.16.4",
    "i": "^0.3.7",
    "millify": "^6.1.0",
    "next": "14",
    "next-auth": "^4.24.5",
    "npm": "^9.8.0",
    "openai": "^4.24.1",
    "postcss": "8.4.24",
    "rc-slider": "^10.2.1",
    "react": "18.2.0",
    "react-copy-to-clipboard": "^5.1.0",
    "react-datepicker": "^4.14.1",
    "react-dom": "18.2.0",
    "react-hot-toast": "^2.4.1",
    "react-input-mask": "^2.0.4",
    "react-markdown": "^9.0.1",
    "react-responsive": "^9.0.2",
    "react-syntax-highlighter": "^15.5.0",
    "react-textarea-autosize": "^8.4.1",
    "react-tooltip": "^5.14.0",
    "recharts": "^2.7.2",
    "remark-gfm": "^4.0.0",
    "sonner": "^1.2.4",
    "tailwind-merge": "^1.13.1",
    "tailwind-scrollbar": "^3.0.4",
    "tailwindcss": "3.3.2",
    "typescript": "5.1.3",
    "yarn": "^1.22.19"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^2.4.6",
    "eslint": "8.42.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "prettier": "^3.1.1",
    "prettier-plugin-tailwindcss": "^0.5.9",
    "prisma": "^5.7.1"
  }
}

**Comment by Haiananan** [comment]
In theory, I should be able to access the model field in the body, but after printing it, it is always undefined. Only messages and the latest message are available.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The report describes a concrete failure of the existing `useChat` body-payload behavior: configured custom fields are not sent to the API.

### Evidence
- `useChat` is configured with a `body` containing `model` and `test`, but the API request only receives `messages`.
- The server consistently observes `model` as `undefined` despite it being supplied in the hook configuration.
