### ISSUE TITLE
OpenAI function calling returns invalid JSON when streaming

### ISSUE THREAD

**Issue by jameschetwood** [vercel/ai#890]
### Description

I'm using OpenAI with Function Calling. I'm not calling multiple functions, I just need to ensure the response is of a certain JSON structure. 

If I don't stream the response it works as expected.

Route handler: 
```
import OpenAI from "openai";
import schema from "./schema.json";

export const runtime = "edge";

export async function POST(request: Request) {
    try {
        const openai = new OpenAI({
            apiKey: process.env["OPENAI_API_KEY"],
        });
        const response = await openai.chat.completions.create({
            model: "gpt-4",
            // stream: true,
            messages: [
                {
                    role: "user",
                    content: "Give me 5 questions and answers for a pub quiz",
                },
            ],
            tools: [
                {
                    type: "function",
                    function: {
                        name: "get_questions_and_answers",
                        description: "Get questions and answers",
                        parameters: schema,
                    },
                },
            ],
            tool_choice: {
                type: "function",
                function: { name: "get_questions_and_answers" },
            },
        });
        return Response.json(
            JSON.parse(
                response.choices[0].message.tool_calls?.[0].function.arguments || "",
            ),
        );
    } catch (error) {
        console.error({ error });
        throw new Error("Server error");
    }
}
```
Response:
```
{
    "getQuestions": [
        {
            "Question": "What is the capital of Australia?",
            "Answer": "Canberra"
        },
        {
            "Question": "Who wrote 'To Kill a Mockingbird'?",
            "Answer": "Harper Lee"
        },
        {
            "Question": "Who invented the telephone?",
            "Answer": "Alexander Graham Bell"
        },
        {
            "Question": "What is the name of the first manned mission to land on the Moon?",
            "Answer": "Apollo 11"
        },
        {
            "Question": "What is the chemical symbol for Sodium?",
            "Answer": "Na"
        }
    ]
}
```

I understand that streaming is required to prevent the serverless function from sometimes timing out. When I try to add streaming the response is invalid JSON: 
```
import OpenAI from "openai";
import { OpenAIStream, StreamingTextResponse } from "ai";
import schema from "./schema.json";

export const runtime = "edge";

export async function POST(request: Request) {
    try {
        const openai = new OpenAI({
            apiKey: process.env["OPENAI_API_KEY"],
        });
        const response = await openai.chat.completions.create({
            model: "gpt-4",
            stream: true,
            messages: [
                {
                    role: "user",
                    content: "Give me 5 questions and answers for a pub quiz",
                },
            ],
            tools: [
                {
                    type: "function",
                    function: {
                        name: "get_questions_and_answers",
                        description: "Get questions and answers",
                        parameters: schema,
                    },
                },
            ],
            tool_choice: {
                type: "function",
                function: { name: "get_questions_and_answers" },
            },
        });
        const stream = OpenAIStream(response);
        return new StreamingTextResponse(stream);
    } catch (error) {
        console.error({ error });
        throw new Error("Server error");
    }
}
```

Response:
```
{"tool_calls":[ {"id": "call_zyzM9nL9j4x2uojmERkmvcMJ", "type": "function", "function": {"name": "get_questions_and_answers", "arguments": "{\n  \"getQuestions\": [\n    {\n      \"Question\": \"What is the capital of France?\",\n      \"Answer\": \"Paris\"\n    },\n    {\n      \"Question\": \"Who wrote the novel '1984'?\",\n      \"Answer\": \"George Orwell\"\n    },\n    {\n      \"Question\": \"What is the chemical symbol for gold?\",\n      \"Answer\": \"Au\"\n    },\n    {\n      \"Question\": \"Who painted the Mona Lisa?\",\n      \"Answer\": \"Leonardo da Vinci\"\n    },\n    {\n      \"Question\": \"What is the largest planet in our solar system?\",\n      \"Answer\": \"Jupiter\"\n    }\n  ]\n}"}}
```

I've have a repo which demonstrates the issue: 
https://github.com/jameschetwood/openai-function-calling

**Comment by ozzyonfire** [comment]
I think the issue here is that you are trying to parse the accumulated text, but since the text is coming in as chunks, it is not a valid JSON object yet. So the error you are getting is expected. 

You can view how the package parses a streamed response by checkout out this file: https://github.com/vercel/ai/blob/main/packages/core/shared/process-chat-stream.ts

**Comment by jameschetwood** [comment]
> I think the issue here is that you are trying to parse the accumulated text, but since the text is coming in as chunks, it is not a valid JSON object yet. So the error you are getting is expected.
> 
> You can view how the package parses a streamed response by checkout out this file: https://github.com/vercel/ai/blob/main/packages/core/shared/process-chat-stream.ts

I don't think that's it. If I use a tool like Postman to hit the API (so it's not my code parsing it) I can see the JSON is invalid.

**Comment by baptisteArno** [comment]
I have the exact same issue but it's only happening on production when deploying on Vercel. 😨

I'm super confused and I don't know how I can debug that...

**Comment by AaronFriel** [comment]
Give the [fn-stream](https://github.com/AaronFriel/fn-stream) library a try. It includes a streaming, incremental JSON parser that returns nodes of the response incrementally.

**Comment by suryasanchez** [comment]
Same issue here after migrating from function_call to tool_choice. The JSON is always missing "]}" at the end.

The fix I did is simply adding the `]}` after getting all the stream 😅

**Comment by lgrammel** [comment]
In `v3.0.14`, we added 2 experimental functions for the object generation use case:

- `experimental_generateObject`
- `experimental_streamObject`

You can find examples here: https://github.com/vercel/ai/tree/main/examples/ai-core/src

**Comment by suryasanchez** [comment]
> In `v3.0.14`, we added 2 experimental functions for the object generation use case:
> 
> * `experimental_generateObject`
> * `experimental_streamObject`
> 
> You can find examples here: https://github.com/vercel/ai/tree/main/examples/ai-core/src

Thank @lgrammel that worked great!

The only thing is that `OpenAIStream` doesn't work with `experimental_streamObject` in api route (app router) so I wrote my own stream like

```javascript
const stream = new ReadableStream({
    async start(controller) {
      for await (const partialObject of result.partialObjectStream) {
        const chunk = JSON.stringify(partialObject) + "\n"; // Format each chunk
        controller.enqueue(new TextEncoder().encode(chunk));
      }
      controller.close();
    },
  });

  return new StreamingTextResponse(stream, {
    headers: { "Content-Type": "application/json" },
  });
```

And then in the UI I do something like below. Note that I don't use chat, simply call the AI via API route.

```javascript
let buffer = ""; // String buffer to accumulate incoming data

const response = await fetch(`/api/chat/`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({ message }),
});

  const reader = response.body.getReader();

const readStream = async () => {
  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      return; // Resolve the promise when the stream is finished
    }

    const chunk = new TextDecoder().decode(value);
    buffer += chunk; // Accumulate the chunk into the buffer

    let boundary;
    while ((boundary = buffer.indexOf("\n")) !== -1) {
      const json = buffer.substring(0, boundary);
      buffer = buffer.substring(boundary + 1);

      try {
        const data = JSON.parse(json);
        console.log(data);

      } catch (error) {
        console.error("Error parsing JSON object", error);
      }
    }
  }
};

await readStream();
```

I'm pretty sure there is a better way but hope this will help someone.

**Comment by lgrammel** [comment]
@suryasanchez great example! I'll think about how we can integrate something along those lines. 

Here is an example of using `streamObject` with RSCs for incremental rendering:

https://github.com/vercel/ai/tree/main/examples/next-ai-rsc/app/stream-object

**Comment by lgrammel** [comment]
Please check out our new tool calling with AI SDK Core and useChat: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a reproducible failure in existing streaming tool-call handling that produces invalid output, so it is a bug despite later workarounds and newer object-streaming APIs.

### Evidence
- With `stream: true`, `OpenAIStream(response)` emits malformed JSON for forced tool calls, while the equivalent non-streaming request succeeds.
- Multiple commenters reproduced malformed output, including missing closing `]}` and improperly escaped function arguments.
- A commenter isolated the failure to explicit `tool_choice: { type: "function", ... }`; using `tool_choice: "auto"` avoided it, potentially due to the differing `finish_reason`.
