### ISSUE TITLE
Documentation basic example for Mistral does not work

### ISSUE THREAD

**Issue by amorphius** [vercel/ai#897]
### Description

I was trying to launch example from this page https://sdk.vercel.ai/docs/guides/providers/mistral
But it didn't work for me. The API key is correct but it seems that my POST handler does not respond. Even if I put some console.log at the very beginning of route handler - it won't be executed. 
It seems that the problem is in client. When I remove Mistral client creation at least route starts to respond.

### Code example

import { OpenAIStream, StreamingTextResponse } from 'ai';
 
// Note: There are no types for the Mistral API client yet.
// @ts-ignore
import MistralClient from '@mistralai/mistralai';
 
const client = new MistralClient(process.env.MISTRAL_API_KEY || '');
 
export async function POST(req: Request) {
  console.log('~~~ START POST HANDLER');
  // Extract the `messages` from the body of the request
  const { messages } = await req.json();
 
  const response = await client.chatStream({
    model: 'mistral-tiny',
    stream: true,
    max_tokens: 1000,
    messages,
  });
 
  // Convert the response into a friendly text-stream. The Mistral client responses are
  // compatible with the Vercel AI SDK OpenAIStream adapter.
  const stream = OpenAIStream(response);
 
  // Respond with the stream
  return new StreamingTextResponse(stream);
}

**Comment by ChristopherTrimboli** [comment]
same, broken using `edge` runtime in backend API route: `Error [TypeError]: edgeFunction is not a function` 

switch to `nodejs` runtime and does not error, but just stalls, no response, no console logs, very odd.

**Comment by chanmathew** [comment]
Same issue here. I don't think the JS client is returning anything, see bug I opened here: https://github.com/mistralai/client-js/issues/50

**Comment by lgrammel** [comment]
We have a new provider architecture since v3.1 - please checkout this page: https://sdk.vercel.ai/providers/ai-sdk-providers/mistral

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **High**

### Rationale
The issue reports a concrete failure when running an existing documented integration example. Although the integration was later replaced by a new provider architecture, the reported behavior was that the current example did not function as presented.

### Evidence
- The documented Mistral provider example fails to invoke the POST handler or return a response despite a valid API key.
- Another reporter reproduced runtime errors on Edge and indefinite stalling on Node.js.
- A maintainer noted that AI SDK v3.1 introduced a new provider architecture and directed users to the newer Mistral provider page.
