### ISSUE TITLE
experimental_useAssistant has been blocked by CORS policy

### ISSUE THREAD

**Issue by marcolivierbouch** [vercel/ai#902]
### Description

Hello team,

I have an issue with the experimental_useAssistant running not on the same host as my backend. I always get "Blocked by CORS policy" even if my CORS policy accepts everything.

I have created a chat in my nextjs that is working very great app using this code:
```
  const { status, messages, input, submitMessage, handleInputChange } =
    useAssistant({ api: `/api/chatbots/${window.chatbotConfig.chatbotId}/chat` });
```
Find the full code here https://github.com/marcolivierbouch/OpenAssistantGPT/blob/update-chatbotjs/components/chat.tsx and everything is working great.

But when I use the useAssistant in a "external" website I always get the error. I don't know if putting the full url in useAssistant creates the issue?
```
  const { status, messages, input, submitMessage, handleInputChange } =
    useAssistant({ api: `https://openassistantgpt.io/api/chatbots/${window.chatbotConfig.chatbotId}/chat` });
```
The full code of where I have the issue is here https://github.com/marcolivierbouch/OpenAssistantGPT/blob/update-chatbotjs/chatbotjs/src/Chat.tsx. This is a project built using esbuild and React component.

Thank you for your help in advance. Let me know if you need more information.

Full error:
```
 Access to fetch at 'https://www.openassistantgpt.io/api/chatbots/clq5598dc000hrrwh5zvt6s1m/chat' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

NEXT CORS policy:
```
  async headers() {
    return [
      {
        // matching all API routes
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Credentials", value: "true" },
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "*" },
          { key: "Access-Control-Allow-Headers", value: "Sec-WebSocket-Accept, X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" },
        ]
      }
    ]
  }
  ```

![error](https://github.com/vercel/ai/assets/29548847/5a07a2d2-fd4b-4392-a1f7-cb89d91a5252)

### Code example

1. Create a npm project
2. Create file component using vercel/ai
3. Build using esbuild
4. Import the js script in index.html file (example here: https://github.com/marcolivierbouch/OpenAssistantGPT/blob/update-chatbotjs/chatbotjs/tests/index.html)
5. Test the chat

All my code is here: https://github.com/marcolivierbouch/OpenAssistantGPT/tree/update-chatbotjs/chatbotjs

**Comment by marcolivierbouch** [comment]
I found the issue I needed to add this right after the POST in my implementation:

```
export async function OPTIONS(req: Request) {
    return new Response('Ok', { status: 200 })
}
```

Maybe we could at this to the main documentation to save people time! :)

**Comment by marcolivierbouch** [comment]
Closing this!

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Documentation**  
Confidence: **High**

### Rationale
The SDK was not shown to be malfunctioning; the resolved issue was backend CORS configuration, followed by a request to document the necessary OPTIONS handler.

### Evidence
- The CORS preflight failed because the backend did not handle OPTIONS requests.
- The reporter resolved the problem by adding an OPTIONS route returning HTTP 200.
- The reporter then suggested adding this requirement to the main documentation and closed the issue.
