### ISSUE TITLE
ChatRequestOptions for handleSubmit does documentation and code are different

### ISSUE THREAD

**Issue by gwhitelaw** [vercel/ai#938]
### Description

The documentation for useChat ChatHelpers [here](https://sdk.vercel.ai/docs/api-reference/use-chat) says this is how to send dynamic body and headers to the handleSubmit function:

handleSubmit | (e: React.FormEvent<HTMLFormElement>, options: ChatRequestOptions) => void | Form submission handler that automatically resets the input field and appends a user message.**The chat request options can have a `data` property that you can use to send an extra body object to the API endpoint in addition to the `messages` array**.
-- | -- | --

Which claims `data` should be in ChatRequestOptions, or in the child property within `options`. However, neither of these is correct and this is the only way to pass dynamic body and headers via the api:

```
      await chat.handleSubmit(e, {
        options: {
          body: {
            ...
          },
          headers: {
           ...
          },
        },
```

I believe this is just a documentation fix, but wanted to highlight it here as I've seen other people asking about sending dynamic content (#471).

### Code example

```
      await chat.handleSubmit(e, {
        options: {
          data: {
            ...
          },
        },
```

**Comment by lgrammel** [comment]
You do not need to add `options` as a property, it is the name of the whole object.

```ts
await chat.handleSubmit(e, { data: ... });
```

https://github.com/vercel/ai/blob/main/packages/core/react/use-chat.ts#L67

**Comment by aakashg00** [comment]
how am i supposed to access the data/headers in the POST endpoint?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
The alleged documentation mismatch was based on a usage misunderstanding and was corrected by the maintainer; no confirmed SDK or documentation defect remains. The thread is primarily support-related.

### Evidence
- The reporter believed `ChatRequestOptions` required a nested `options` property and requested a documentation fix.
- A maintainer clarified that `options` names the entire second argument and the documented usage is `handleSubmit(e, { data: ... })`.
- The remaining comment is a support question about accessing data or headers in the POST endpoint.
