### ISSUE TITLE
useChat append message limit

### ISSUE THREAD

**Issue by gzhou2142** [vercel/ai#941]
### Feature Description

Have a way to set the maximum number of messages to include when calling the append function of useChat

### Use Case

Having all the messages sent in the api call can become inefficient.

**Comment by MaxLeiter** [comment]
You can manually control this with `setMessages` and an effect. I don't believe this is something we'll support in the core library.

**Comment by gzhou2142** [comment]
I'm using the messages state provided by useChat to render my ui for showing historical messages. Resetting the messages state will affect the UI. Currently I'm moving the data in messages to another state, and ressetting the messages state, but this causes weird UI issues. Any ideas on how to go about this?

```
onFinish() {
      setHistoricalMessages((prev) => [...prev, ...messages]);
      setMessages([]);
      setResponseId(nanoid());
    },
```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Feature**  
Confidence: **High**

### Rationale
This is a request for a new `useChat` configuration capability. The reported UI difficulties with a manual workaround do not establish a concrete SDK defect.

### Evidence
- The issue requests a new option to limit how many messages `useChat.append` includes in an API call.
- The motivation is reducing inefficiency from sending the full message history, not a failure of documented behavior.
- A maintainer states this can be controlled manually and is not currently supported by the core library.
