### ISSUE TITLE
Perhaps I'm missing something? `experimental_StreamData`

### ISSUE THREAD

**Issue by dremnik** [vercel/ai#956]
### Description

It seems to me that there is only a method to append new data to the stream -- not one for removing it. I realize this may be technically challenging, but how are you supposed to use the reload function to regenerate a message if the data stream can only ever grow? 

I know you guys already have it in the roadmap to have a message.data which makes a lot more sense, then you can easily just remove the message with whatever annotation you might have added.

Am I missing something or is the reload issue a genuine bug?

### Code example

  append(value: JSONValue): void {
    if (this.isClosed) {
      throw new Error('Data Stream has already been closed.');
    }

    this.data.push(value);
  }

  appendMessageAnnotation(value: JSONValue): void {
    if (this.isClosed) {
      throw new Error('Data Stream has already been closed.');
    }

    this.messageAnnotations.push(value);
  }

**Comment by lgrammel** [comment]
It's a stream that is being sent to the client. You cannot remove information, because has already been sent.

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **High**

### Rationale
This is primarily a usage/design question about expected streaming behavior, not a demonstrated defect or a concrete request to change the SDK.

### Evidence
- The reporter asks whether stream data can be removed to support message regeneration with reload.
- The maintainer explains that already-sent stream information cannot be removed from the client.
