### ISSUE TITLE
Serverless stream exception

### ISSUE THREAD

**Issue by zandko** [vercel/ai#960]
### Description

I have no problem running and deploying to the server locally. When I used Tencent Cloud serverless, I found that the flow was abnormal, and all the text responded at the same time.

### Code example

 return new StreamingTextResponse(stream, {
      headers: { ...ResponseHeaders }
    }, data);

**Comment by lgrammel** [comment]
Having the text returned at the same time might indicate a lack of support for streaming on the provider side (Tencent). 
 Does Tencent Cloud serverless support streaming? When you e.g. deploy your example to Vercel, does streaming work there?

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily a deployment-provider support question about Tencent Cloud Serverless streaming capabilities, not a confirmed SDK bug or request for a product change.

### Evidence
- Streaming works locally but responses are buffered when deployed to Tencent Cloud Serverless.
- The maintainer suggested Tencent may not support streaming and asked whether the same deployment streams correctly on Vercel.
- No AI SDK defect or documented behavior violation was established.
