### ISSUE TITLE
Request body is not sent with useChat after upgrading to >=2.2.26

### ISSUE THREAD

**Issue by zachtball** [vercel/ai#965]
### Description

Install version >2.2.25
Use useChat hook and point the `api` at a lambda url (haven't tested another backend service)
Try to log the request body, it is undefined
Install version 2.2.25
Works fine

### Code example

```
  const { messages, input, handleInputChange, append, isLoading, setMessages } = useChat({
    api: process.env.NEXT_PUBLIC_CHAT_LAMBDA_URL,
    body: {
      functions,
      idToken,
      ...settings,
    },
  });
```

in my backend (lambda) I do
```
console.log('body', event.body);
// INFO	body undefined
```

Change version to "ai": "2.2.25", and it works fine
```
INFO	body 
{
    "messages": [
...
```

**Comment by rollsrobby** [comment]
try setting `sendExtraMessageFields` to `true`. works for us with `v2.2.35`
```js
  const { messages, input, handleInputChange, append, isLoading, setMessages } = useChat({
    api: process.env.NEXT_PUBLIC_CHAT_LAMBDA_URL,
    sendExtraMessagesFields: true    
    body: {
      functions,
      idToken,
      ...settings,
    },
  });
```

**Comment by zachtball** [comment]
> try setting `sendExtraMessageFields` to `true`. works for us with `v2.2.35`

Hey thanks for the reply, sadly that did not work for me.

**Comment by jakepgoldman** [comment]
This is an issue for me in `3.0.23`. Any resolution? `body` is not dynamic.

**Comment by jakepgoldman** [comment]
This is an issue for me in `3.0.23`. Any resolution? `body` is not dynamic.

**Comment by lgrammel** [comment]
You can send in the body in `handleSubmit` if it's dynamic: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot#setting-custom-body-fields-per-request

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
The issue reports a concrete regression in existing `useChat` request behavior across versions. Although the maintainer clarified the supported approach for dynamic body fields, that does not fully account for the original report that `event.body` is entirely undefined.

### Evidence
- The reporter says `useChat` sends no request body with versions newer than 2.2.25, while downgrading to 2.2.25 restores it.
- Setting `sendExtraMessageFields: true` did not resolve the reported failure.
- Another user reported related non-dynamic `body` behavior in 3.0.23; a maintainer noted dynamic fields can instead be passed through `handleSubmit`.
