### ISSUE TITLE
experimental_StreamData not working with AIStream HELP ME!

### ISSUE THREAD

**Issue by Turbo1337GS** [vercel/ai#970]
### Description

Hey everyone, I'm starting to play with the 'AI' module! The problem is that experimental_StreamData does not support operations during its own parsing using AIStreamParser and with the AIStream stream!

However, when using, for example, an OpenAIStream type stream, everything works correctly!

The problem is that I have my own NLP model, and I would like to parse these data after my NLP model streams text, and extract data and add elements such as which websites it analyzes, my model is connected to the network! So, since experimental_StreamData does not support AiStream, can someone suggest a sensible way I can return this data from raw JSON?

### Code example

```ts
export const runtime = "edge";
import {
  OpenAIStream,
  StreamingTextResponse,
  experimental_StreamData,
  streamToResponse,
} from "ai";
import {
  AIStream,
  type AIStreamParser,
  type AIStreamParserOptions,
  AIStreamCallbacksAndOptions,
} from "ai";
import { ChatCompletionChunk } from "./interface";

export interface ChatCompletion {
  data: ChatCompletionChunk;
}
const api_key = process.env.API_KEY;
function TestParser(): AIStreamParser {
  let previous = "";
  return (chunk) => {
    try {
      const json: ChatCompletionChunk = JSON.parse(chunk);
      const text = json.choices[0].delta.content;
      console.log(json);
      previous = text;
      return text;
    } catch (error) {
      console.error("Error parsing chunk:", error); // Logujemy błąd parsowania
      return; // W przypadku błędu nie zwracamy nic
    }
  };
}
export async function POST(req: Request) {
  const { messages } = await req.json();
  const parser = TestParser();//function TestParser(): AIStreamParser
  const response = await CustomFetch(messages); // function CustomFetch(messages: any): Promise<Response>

  const data = new experimental_StreamData();

  const stream = AIStream(response,parser, {
    onStart() {
      data.append({
        text: 'Hello from experimental_StreamData',
      });
    },
    onCompletion(completion) {
      console.log('completion', completion);

    },
    onFinal(completion) {
      data.close();
    },
    experimental_streamData: true,
  });
  return new StreamingTextResponse(stream, {}, data);
}```

### Additional context

When change the AiStream to OpenAIStream, the experimental_StreamData start work!

P.S.: The problem is that the front-end is missing data from the 'data' variable and the message[].content.

**Comment by lgrammel** [comment]
This seems outdated. Please check out our updated guide on `StreamData`: https://sdk.vercel.ai/docs/ai-sdk-ui/streaming-data

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **None**  
Confidence: **Medium**

### Rationale
This is primarily an outdated usage/support question rather than a confirmed defect or a request to change documentation, examples, or product behavior.

### Evidence
- Reporter asks for help combining the experimental `StreamData` API with a custom `AIStream` parser after frontend data is missing.
- The API discussed was experimental, and no documented compatibility guarantee with `AIStream` is identified.
- A maintainer states that the report is outdated and directs the reporter to the updated `StreamData` guide.
