### ISSUE TITLE
onToolCall payload is null

### ISSUE THREAD

**Issue by SanteJ731** [vercel/ai#981]
### Description

When I call the openai api and trigger onToolCall, if the api returns the arguments as a one-time complete json like: `{"location":"corgi,solo,cutest dog,brown fur,black eyes"}`, then the payload in onToolCall will be null. This should be related to the steps of parsing the stream.

**Comment by lgrammel** [comment]
The old tool calling mechanism is now deprecated. Check out our new tool calling with 
- AI SDK Core: https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling
- Chatbots with Tools: https://sdk.vercel.ai/docs/ai-sdk-ui/chatbot-with-tool-calling

**Comment by iranzithierry** [comment]
hey @lgrammel it's possible to return client data back to ai so can handle it like
```tsx
         onToolCall: async ({ toolCall }) => {
            const { toolName, toolCallId } = toolCall;
            const args = toolCall.args as any;
            let result: { success: boolean; data?: any; message: string };

            try {
               switch (toolName) {
                  case "READ_DATA":
                     const data = getFilledData();
                     result = { success: true, data, message: `Read ${data.length} rows` };
                     break;
                  case "SET_CELL_VALUE":
                     setCellValue(args.cell, args.value);
                     result = { success: true, message: `Updated ${args.cell} → "${args.value}"` };
                     break;
                  default:
                     throw new Error(`Unknown tool: ${toolName}`);
               }
            } catch (err: any) {
               result = { success: false, message: err.message };
            }
            return result
         },```

**Comment by lgrammel** [comment]
## Identify issue type

Identified as **Bug**  
Confidence: **Medium**

### Rationale
This describes a concrete failure in an existing API: valid tool-call arguments produce a null callback payload. Deprecation does not change the report from a bug into a feature request.

### Evidence
- The reporter states that `onToolCall` receives a null payload when OpenAI streams tool arguments as one complete JSON object.
- The reported result is attributed to incorrect stream parsing behavior.
- A maintainer notes that this tool-calling mechanism is deprecated and recommends the newer APIs, but does not dispute the reported failure.
